:slug: rules/226/
:category: authentication
:description: This requirement establishes the importance of preventing denial of service attacks by avoiding account lockouts.
:keywords: Account, Authentication, Attempt, Lockout, ASVS, CWE, Rules, Ethical Hacking, Pentesting
:rules: yes

= R226. Avoid account lockouts

== Requirement

The system must never block a user account
given one or several failed authentication attempts.

== Findings

* [inner]#link:/web/findings/087/[F087. Account lockout]#

== References

. [[r1]] link:https://cwe.mitre.org/data/definitions/645.html[CWE-645: Overly Restrictive Account Lockout Mechanism]
The software contains an account lockout protection mechanism,
but the mechanism is too restrictive and can be triggered too easily,
which allows attackers to deny service to legitimate users by causing their
accounts to be locked out.

. [[r2]] link:https://owasp.org/www-project-top-ten/OWASP_Top_Ten_2017/Top_10-2017_A2-Broken_Authentication[OWASP Top 10 A2:2017-Broken Authentication].
Application functions related to authentication and session management are
often implemented incorrectly,
allowing attackers to compromise passwords, keys, or session tokens,
or to exploit other implementation flaws to assume other users’ identities
temporarily or permanently.

. [[r3]] link:https://www.owasp.org/index.php/ASVS_V2_Authentication[OWASP-ASVS v3.1-2.20]
Verify that anti-automation is in place
to prevent breached credential testing, brute forcing,
and account lockout attacks.
