:slug: events/burn-the-datacenter/
:subtitle: From pets to cattle
:category: events
:description: This page aims to inform the customer about the different talks offered by Fluid Attacks. The Burn the datacenter conference seeks to socialize our belief in the future for technologies and software development for the next 10 years, according to the opinion of our experts.
:keywords: Fluid Attacks, Burn the datacenter, Technology, Continuous Integration, Infrastructure, Code

= Burn the Datacenter

== 1. Objective

In this space we seek to socialize our beliefs
about the future of technologies, software development
and management of development lifecycle for the next +10+ years
and hence, how to adapt the complete ecosystem,
including our area of interest: security testing.

== 2. Content

The fields of software development and infrastructure management
have been typically separated into different and antagonistic worlds.
There is a dichotomy between the flexibility to changes
during the development phase
and the stability in the infrastructure.
We have recently found misapplied concepts such as +DevOps+, +DevOps+ profiles
and companies that create +DevOps+ transformation areas,
but apart from the management area (roles, responsibilities, and processes)
how can these concepts be translated into a simple technical approach
in additional spaces to the applications?

In this methodological universe,
we are losing sight of a critical need for programming languages
scoped to infrastructure and networks,
which has been around for more than +20+ years.
These languages would allow programming practices
that have been developed for half a century
to also apply to infrastructure development.

* Can we compile a server?
* Can we perform infrastructure linting?
* Can we perform network static analysis?
* Can we perform continuous integration over infrastructure?
* Can we perform continuous deployment over infrastructure?
* Can infrastructure be immutable and hence, disposable?

In this conference, we will talk about
how the world belongs to the programmers
and how the environments can be infinite.

== 3. Experience

We have given this free academic conference for a year, in:

* *Large Companies:*
link:https://www.avianca.com/co/es/[Avianca],
link:https://www.grupobancolombia.com/wps/portal/personas[Bancolombia],
link:https://www.bcp.com.bo/[Banco de Credito del Peru],
link:https://www.banistmo.com/[Banistmo],
link:http://www.celsia.com/[Celsia-EPSA],
link:https://www.comfama.com/webinicio/default.asp[Comfama],
link:https://www.velez.com.co/[Cueros Velez],
link:https://www.gnbsudameris.com.co/[GNB Sudameris],
link:https://www.grupoexito.com.co/es/[Grupo Éxito],
link:http://www.homecenter.com.co/homecenter-co/[Homecenter],
link:https://www.stgeorgesbank.com/[St. Georges Bank],
link:https://www.segurossura.com.co/Paginas/default.aspx[Sura],
link:https://www.tigoune.com.co/[Tigo Une].

* *Universities:* link:http://www.eafit.edu.co/[EAFIT],
link:https://www.udem.edu.co/[UdeM],
link:https://www.udea.edu.co/[UdeA],
link:https://medellin.unal.edu.co/[UNALMed],
link:http://www.politecnicojic.edu.co/[Politécnico Jaime Isaza Cadavid],
link:https://www.upb.edu.co/es/home[UPB],
link:http://www.uniminuto.edu/[Uniminuto Bogotá]

* *IT Vendor Enterprises*
link:https://www.arus.com.co/[ARUS],
link:http://www.cadena.com.co/es/home.aspx[Cadena],
link:https://www.choucairtesting.com/[Choucair Testing],
link:https://outsourcing.cidenet.com.co/home/[Cidenet],
link:http://www.cognox.co/sitios/Cognox/default.aspx[Cognox],
link:http://flypass.com.co/[Flypass],
link:http://gluky.co/[Gluky],
link:http://www.internexa.com/Paginas/Home.aspx[Internexa],
link:https://www.kometsales.com/[Komet Sales],
link:http://perceptio.co/[Perceptio],
link:http://www.mareigua.com/[Mareigua],
link:http://novit.pe/[NovitIT Peru],
link:http://www.seti.com.co/sitios/seti/Paginas/HomePageSeti.aspx[SETI],
link:https://www.todo1services.com/[Todo1].

* *Open spaces* link:https://www.rutanmedellin.org/es/[RutaN],
link:https://www.meetup.com/es/mde-devops[MeetUp-Medellin-DevOps].

We have given more than *35 conferences* with *878 assistants*
and *an overall satisfaction of 165%*.

== 4. Where?

The presentation can be hosted
at your company's facilities or an external venue.

The event can be held in Medellín with a minimum public of +20+ assistants,
one of them with at least +10+ dependants.
For other cities in Colombia, Central America, Ecuador, and Perú,
there must be one assistant with at least +20+ dependants.

== 5. Duration

The conference has a duration of +2+ hours
(duration cannot be reduced).

== 6. When?

[button]#link:../#when[When]#

== 7. Public

The conference is suitable for both technical and managerial personnel,
and the satisfaction rate for both profiles is equally high.
However, if you wish to promote new changes
and experimentation inside your company,
considering people with power of decision is important.

The number of attendants is set according to the limits of the workspace.
The conference has been given in groups of +20+ people
and in auditoriums with over +80+ people

== 8. Requirements

[button]#link:../#requirements[Requirements]#

== 9. Speaker

[button]#link:../../people/ralvarez/[Rafael Alvarez]#

== 10. Videos

++++
<iframe width="560" height="315" src="https://www.youtube.com/embed/qKsz-nvgMrU" frameborder="0" allowfullscreen></iframe>
++++
