:slug: empleos/evaluacion-conocimientos/
:category: careers
:eth: no

= Evaluación de conocimientos

El siguiente paso para continuar con tu proceso de selección es realizar nuestro examen de conocimientos. Este examen contiene diversas áreas de conocimientos, unas que aplican a tu perfil, y otras que no, sin embargo debes presentarlas todas a conciencia pues con esto podremos validar si el examen es efectivo determinando que los que saben - saben y los que no - no.

 NOTA: Este examen es totalmente en inglés y no es posible cambiar el idioma

Los pasos para realizar el examen son los siguientes:

== Crear una cuenta

. Ingresar a la dirección web: https://fluid.la/courses/login/index.php[Click aquí].
. Dar click en el botón “CREATE NEW ACCOUNT” y llena el formulario con tu información. Por favor tenga en cuenta que el nombre de usuario solo admite letras en minúsculas, y la contraseña debe ser mayor a 8 caracteres, tener una letra en mayúscula y al menos un carácter no alfanumérico (*,-, o #).
. Confirmar su dirección de correo siguiendo las instrucciones. Revise su buzón de correo y su carpeta SPAM en caso tal de que no llegue a su bandeja principal.

== Instalar SafeExamBrowser

. Descarga el siguiente software de seguridad para presentar el examen: link:../../files/fluidexams.zip[Click aquí].

 IMPORTANTE: Por favor termina de leer los demás pasos antes de ejecutar el aplicativo
 
. Descomprimir el archivo .ZIP descargado y luego instalar en Windows el archivo con nombre "SafeExamBrowserInstaller.exe". El teclado puede cambiar su configuracion, y quedar en ingles, por lo que debe validar si es necesario volverlo a configurar para que quede en español.
. Verifica que estas conectado a Internet y que tengas una conexión estable.
. En cualquier momento puedes salir del aplicativo con el botón que está situado en la parte inferior derecha de la pantalla.
. Para presentar el examen, debes ir a la carpeta y ejecutar el archivo 'fluidexams'. Desde este momento el único programa activo será el examen.

== Realizar el examen

. Deberás iniciar sesión con tus credenciales, las cuales registraste anteriormente.
. Al tener éxito de ingresar, debes ir a la barra de navegación izquierda y buscar la pestaña "Sites home", dar clic en el.
. Bajas al final de la página y seleccionas “General Knowlegde Exam”.
. Dar clic en el botón "Enroll me", luego, en la siguiente página, da click en el botón que dice "ATTEMPT QUIZ NOW" para comenzar.

 IMPORTANTE: Por favor ten en cuenta que una vez respondas o saltes una pregunta, no podrás volver a ella, por lo que no podrás modificar la respuesta

. Al finalizar el examen, buscar en la parte inferior de la aplicativo y dar click "FINISH ATTEMPT" para validar que respondió todas las preguntas
. Luego, en la parte inferior de la pagina dar click en “Submit all and finish”.
. Para salir del aplicativo debe hacerlo con el botón que está situado en la parte inferior derecha de la pantalla.
. Envíanos un correo notificandonos que finalizaste el examen.

Desde el momento del registro en la plataforma del examen, usted tiene 24 horas para presentarlo y sólo un (1) intento. En caso de no poder presentar el examen en el tiempo indicado por favor escribir un correo proponiendo un nuevo compromiso para la presentación del mismo. El examen tiene una duración máxima de 3 horas y 20 minutos, por lo que debes disponer de tiempo suficiente para realizarlo sin interrupciones.

¡Que te diviertas!  ... y buena suerte, aunque no la necesitas.
