:slug: empleos/
:description: FLUID siempre está en busca de jóvenes talentos apasionados por la programación y la informática. La siguiente página tiene como objetivo informar a los interesados en ser parte del equipo de trabajo de FLUID sobre el proceso de selección realizado y las etapas que lo componen.
:keywords: FLUID, Empleo, Proceso, Selección, Etapas, Contratación.
:translate: careers/

= Empleos

A continuación te explicaremos cómo puedes hacer parte de nuestro equipo:

[role="etapa_c"]
== 1. Condiciones

El objetivo de esta etapa
es que conozcas y aceptes los términos y condiciones del proceso de selección,
Esto es obligatorio y requiere un esfuerzo estimado de 4 a 6 min.
Para comenzar,
solo debes seguir las instrucciones detalladas [button]#link:terminos/[aquí]#

== 2. Razones

El objetivo de esta etapa
es que conozcas qué hace a FLUID un gran lugar para trabajar.
Esto es obligatorio y requiere un esfuerzo estimado de 3 a 5 min.
Para comenzar,
solo debes hacer click [button]#link:razones/[aquí]#

== 3. Vacantes

El objetivo de esta etapa
es que conozcas los roles que puedes desempeñar en FLUID,
o en vacantes que se tienen por parte de AUTONOMIC,
una empresa Spin Off de FLUID encargada del proceso de reclutamiento.
Esto es obligatorio y requiere un esfuerzo estimado de 3 a 5 min.
Para comenzar,
solo debes hacer click [button]#link:vacantes/[aquí]#

== 4. Portafolio

El objetivo de esta etapa
es evidenciar su capacidad de expresarse,
sintetizar ideas y llamar la atención mediante la elaboración de un portafolio.
Esto es obligatorio y requiere un esfuerzo estimado de 1 a 2 horas según tu habilidad.
Para iniciar,
solo debes seguir las instrucciones detalladas [button]#link:portafolio/[aquí]#

[role="etapa_a"]
== 5. Aplicación

El objetivo de esta etapa
es que registres tu hoja de vida y tus expectativas laborales.
Esto es obligatorio y requiere un esfuerzo estimado de 5 a 10 min según tu perfil.
Para hacerla requieres haber finalizado la etapa anterior.

[role="a_formLink"]
Para iniciar,
solo debes seguir las instrucciones detalladas [button]#link:https://fluidattacks.com/forms/aplicacion[aquí]#

[role="etapa_h"]
== 6. Historia

El objetivo de esta etapa es registrar tus periodos laborales.
Es opcional *sólo si no tienes experiencia laboral* y requiere un esfuerzo estimado de 3 a 5 min por periodo.
Para hacerla requieres haber finalizado la etapa anterior.

[role="h_formLink"]
Para iniciar,
solo debes seguir las instrucciones detalladas [button]#link:https://fluidattacks.com/forms/periodo[aquí]#

++++
<script>document.getElementsByClassName("h_formLink")[0].style.display="none",document.getElementsByClassName("a_formLink")[0].style.display="none";var r=window.location.href.split("?")[1];"398453"==r?(document.getElementsByClassName("a_formLink")[0].style.display="block",document.getElementsByClassName("etapa_a")[0].style.backgroundColor="#ffffa6"):"987343"==r?(document.getElementsByClassName("h_formLink")[0].style.display="block",document.getElementsByClassName("etapa_h")[0].style.backgroundColor="#ffffa6"):"0062"==r&&(document.getElementsByClassName("etapa_c")[0].style.backgroundColor="#ffffa6");</script>
++++
== 7. Evaluaciones

. *Temperamento:* El objetivo de esta etapa
es determinar los rasgos preponderantes de tu temperamento y su equilibrio.
Esto es obligatorio y requiere un esfuerzo estimado de 8 a 10 min.
Para hacerla no requieres haber finalizado la etapa anterior.
Para iniciar,
solo debes seguir las instrucciones detalladas [button]#link:evaluacion-temperamento/[aquí]#

. *Conocimientos:* El objetivo de esta etapa
es evidenciar sus aptitudes y habilidades en distintas áreas.
Esto es obligatorio y requiere un esfuerzo estimado de 2 a 3 horas según tu conocimiento.
Para hacerla requieres haber finalizado la evaluación anterior.
Para iniciar,
solo debes seguir las instrucciones detalladas [button]#link:evaluacion-conocimientos/[aquí]#

. *Fortalezas:* El objetivo de esta etapa
es evidenciar sus fortalezas mediante el test Clifton StrengthsFinder.
Esto es obligatorio y requiere un esfuerzo estimado de 40 a 45 min.
Para hacerla requieres haber finalizado la evaluación anterior.
Para comenzar,
debes notificarnos vía e-mail a careers@autonomicmind.co

== 8. Retos

. *Retos Técnicos*: El objetivo de esta etapa
es evidenciar en la práctica tu potencial para aprender,
investigar y resolver diferentes tipos de problemas a los que nos enfrentamos diariamente.
Nuestros talentos actuales están en el link:https://www.wechall.net/country_ranking/for/31/Colombia[TOP10 de Colombia],
e incluso,
algunos de ellos están en el link:https://www.wechall.net/ranking[TOP100 Mundial].
Esto es obligatorio para perfiles técnicos y requiere un esfuerzo estimado de 4 a 16 horas según tu conocimiento.
Para hacerla requieres haber finalizado la etapa anterior.
Para iniciar,
solo debes seguir las instrucciones detalladas [button]#link:retos-tecnicos/[aquí]#

. *Retos No Técnicos*: El objetivo de esta etapa
es evidenciar sus habilidades para dar solución a retos que aplican a perfiles analíticos y estadísticos.
Esto es obligatorio para perfiles no técnicos y requiere un esfuerzo estimado de 4 a 16 horas según tu conocimiento.
Para hacerla requieres haber finalizado la etapa anterior.
Para iniciar,
solo debes seguir las instrucciones detalladas [button]#link:retos-no-tecnicos/[aquí]#

== 9. Entrevistas

. *Entrevista en Video:* El objetivo de esta etapa
es demostrar su interés por pertenecer a FLUID mediante una entrevista virtual.
Requiere un esfuerzo estimado de 25 a 30 min.
Para hacerla requieres haber finalizado la etapa anterior.
Para iniciar,
notifícanos vía e-mail a careers@autonomicmind.co
. *Entrevista Presencial:* El objetivo de esta etapa
es acordar un encuentro en donde podremos conocerlo personalmente.
Requiere un esfuerzo estimado de 25 a 30 min.
Para hacerla requieres haber finalizado la etapa anterior.
Para iniciar,
notifícanos vía e-mail a careers@autonomicmind.co

== 10. Inmersión

El objetivo de esta etapa
es participar en un auto-entrenamiento intensivo en retos de programación y de hacking,
financiado por FLUID.
Esto es obligatorio y el esfuerzo requerido es determinado según tu conocimiento.
Para iniciar,
notifícanos vía e-mail a careers@autonomicmind.co y leer las instrucciones detalladas  [button]#link:inmersion/[aquí]#

== 11. Referencias

El objetivo de esta etapa es validar las referencias de sus empleos anteriores.
Esto es obligatorio y requiere un esfuerzo estimado de 15 min por llamada.
Para hacerla requieres haber finalizado la etapa anterior.
Para iniciar,
solo debes seguir las instrucciones detalladas [button]#link:referencias-inversas/[aquí]#

== 12. Polígrafo

El objetivo de esta etapa
es presentar una prueba de polígrafo.
Nuestro negocio principal es la seguridad de la información,
por lo cuál puede que en el proceso o su relación laboral sea necesario presentar este tipo de pruebas.
Esto es opcional y el esfuerzo requerido estimado es de 2 horas.
Para hacerla requieres haber finalizado la etapa anterior.
Para iniciar,
notifícanos vía e-mail a careers@autonomicmind.co

== 13. Audición

El objetivo de esta etapa
es demostrar su capacidad expresarse, exponiendo un tema indicado a una audiencia de mínimo de tres y máximo 30 personas.
Esto es opcional y el esfuerzo requerido estimado es de 4 horas para prepararse y 20 min para la presentación.
Para hacerla no requieres haber finalizado la etapa anterior.
Para iniciar,
notifícanos vía e-mail a careers@autonomicmind.co

== 14. Oferta

Si has llegado hasta este punto te enviaremos vía e-mail los términos de la oferta laboral que tenemos para ti.
Si tienes dudas, debes expresarlas en el mismo hilo de correo.

== 15. Vinculación

Ya habiendo llegado a un acuerdo con lo ofertado,
debes enviarnos vía e-mail los documentos que detallamos [button]#link:vinculacion/[aquí]#

Al finalizar, te notificaremos del resultado del proceso.
Aunque es un proceso largo,
se puede hacer muy rápido.
En algunos casos se hace en menos de dos semanas.

== Preguntas frecuentes

* *¿Tienes dudas?*, puedes leer nuestra sección de preguntas frecuentes [button]#link:faq/[aquí]#
