:slug: empleos/terminos/
:category: careers
:description: TODO
:keywords: TODO

= Términos

A continuación se especifican los términos del proceso de selección, 
por favor leerlos en detalle. 

Si tienes dudas, contáctanos vía e-mail a careers@autonomicmind.co.

Para participar en el proceso, diligencia el siguiente [read-more]#link:https://fluid.la/forms/seleccion/[formulario >>]#

== La empresa

A continuación, nos presentamos como empresa con el fin de que luego puedas tomar una decisión informada sobre donde potencialmente continuarás tu carrera laboral.

=== Contexto 

* Somos una empresa:

** De origen Colombiano,
** Dedicada a la seguridad de la información,
** Fundada en el 2001,
** Con menos de 40 personas,
** Ventas anuales cercanas a 1.5MM USD,
** Con sedes en Medellín, Bogotá (Colombia) y en Clayton (North Carolina, U.S.A.).
++++
</br>
++++
* En FLUID todos los sistemas están sujetos a monitoreo mediante link:https://www.timedoctor.com/[sistemas de control automáticos de actividad y tiempo]. Con lo cual buscamos:
** Mantener la seguridad de la información de nuestros clientes, 
** Ser objetivos, precisos y justos en la evaluación del desempeño.

== El proceso de selección

. Mediante este proceso, se busca encontrar y contratar el 10% más alto de la población para cada rol y rango salarial requerido. 
. Con este proceso, FLUID desea seleccionar sólo a los mejores para construir un equipo:
** Élite,
** Duradero, 
** Disciplinado, 
** Responsable,
** Ético.

. Hemos automatizado gran parte del proceso de selección para que optimices tu tiempo y así, puedas aspirar a hacer parte de nuestro equipo de forma más ágil y sencilla. 

. La gran mayoría del proceso se realiza por Internet y depende de tu disponibilidad y dedicación, por ende, la duración del proceso se encuentra en un 90% en tus manos.

. Dado que el proceso de selección es detallado y algo diferente a lo que realizan las demás empresas, queremos que hayas leído detenidamente todo el proceso que se encuentra detallado link:../../empleos/[aquí].  

. Si continuas y aceptas estos términos estas indicando que entiendes el esfuerzo y dedicación que esto implica y aceptas ser parte de él.

=== Fin del proceso 
++++
</br>
++++
. Si durante el proceso no se te notifica de forma explícita del fin del mismo, 
significa que aún te encuentras en él y por tanto, estás sujeto a análisis para alguna vacante actual o potencial.

== El candidato

. Al aceptar estos términos y condiciones, declaras que tu contrato actual o anteriores no contienen cláusulas (o éstas han vencido) que te inhabiliten para trabajar en cualquier función en una empresa de seguridad de la información.

. Al aceptar estos términos y condiciones, entiendes que de firmar un contrato entre las partes:
** Contendrá cláusulas de:
*** Exclusividad, 
*** No competencia, 
*** No solicitación,
*** Confidencialidad.
** Las anteriores cláusulas tendrán aplicación durante la relación laboral y 6 meses posteriores a la finalización del mismo.

. En la etapa de vinculación, después de que aceptes nuestra oferta de trabajo, deberás proveer la siguiente link:../vinculacion/[información].

. Al aceptar estos términos y condiciones, entiendes que existe la posibilidad de que nuestra oferta sea inferior a tu expectativa salarial inicial. 
Esto se debe a que: 
** Para nosotros es una de mayor prioridad la equidad de los salarios de las personas de nuestro equipo actual y la coherencia de esta remuneración con su desempeño. 
** Es posible que nuestra percepción de tu desempeño potencial no concuerde con tu expectativa salarial inicial.

. Al aceptar estos términos y condiciones, aceptas ser recomendado para vacantes no solo de FLUID sino también para vacantes en nuestros aliados de negocio.

. Por defecto tus registros permanecerán en nuestra base de datos para futuras ofertas. 
** Si deseas que se eliminen los datos recolectados, debes indicarlo vía e-mail a careers@autonomicmind.co.
