:slug: empleos/test-personalidad
:category: careers
:eth: no

= Test de Personalidad

Cordial saludo,

Por favor, siga las instrucciones debajo para realizar la evaluación de Clifton StrengthsFinder y descubrir sus fortalezas. Por favor en respuesta a este correo enviar adjunto el resultado de las pruebas.

1. Envíenos un correo indicando que ha llegado a esta etapa y solicitenos un código de acceso al test.
2. Una vez le asignemos un código, visite https://www.gallupstrengthscenter.com/Register/es-AR/Index
3. Copie y pegue el código de acceso en el campo disponible y luego haga clic en Continuar.
4. Siga las instrucciones en pantalla para crear una cuenta en Gallup Strengths Center.
5. Una vez registrado, podrá realizar la evaluación de Clifton StrengthsFinder. Por favor, tómese 45 minutos sin interrupciones para completarla. 

Una vez completada la evaluación, por favor enviarnos por correo los PDF correspondientes a sus resultados de la prueba.

Si tiene problemas con su código de acceso, por favor comuníquese con nosotros vía e-mail. Para todos los demás problemas, por favor visite la página de Ayuda del Centro Fortalezas de Gallup.
