:slug: empleos/vinculacion/
:category: careers
:description: TODO
:keywords: TODO
:eth: no

= Vinculación

En este paso, requerimos que nos envíes vía e-mail (careers@autonomicmind.co) en un archivo .ZIP, meticulosamente organizado con un PDF por cada uno de los siguientes documentos:

. Foto digital, a color, en fondo blanco, con traje y corbata (hombres),
. Fotocopia de la cédula -en 1 página las 2 caras-,
. Fotocopia de la libreta militar -en 1 página las 2 caras- (si eres hombre),
. Fotocopia de la Tarjeta Profesional -en 1 página las 2 caras- (si tienes pregrado),
. Fotocopia del diploma de universidad (si tienes pregrado),
. Fotocopia del diploma de bachiller (si no tienes pregrado),
. Certificado de estudios actuales (si estás estudiando actualmente),
. Fotocopia de certificaciones obtenidas,
. Fotocopia de cursos realizados,
. Fotocopia del RUT actualizado,
. Nombre de la EPS donde quieres afiliarte o de estar ya afiliado a alguna debes incluir el certificado de afiliación,
. Nombres completos y cédulas de los beneficiarios para EPS,
. Nombre de fondo de pensión obligatoria de tu preferencia o de estar ya afiliado debes incluir el certificado de afiliación,
. Evidencia de asistencia al examen médico de Ingreso,
. Certificación bancaria (Bancolombia),
. Estado civil, indicando si tiene hijos
. Dirección completa de su residencia (Nomenclatura con N°. de apto y nombre de la unidad, Barrio, Municipio, Teléfono fijo y Celular)


Si tienes alguna duda no dudes en escribir a careers@autonomicmind.co
