:slug: rules/251/
:category: networks
:description: This requirement establishes the importance of avoiding leaving the access points with the factory-set IP address.
:keywords: Network, IP, Access Point, Wireless, Address, ASVS, PCI DSS, Requirement, Rules, Ethical Hacking, Pentesting
:rules: yes

= R251. Change access point IP

== Requirement

Access points must not use the factory-set `IP` address.

== References

. [[r1]] link:https://owasp.org/www-project-application-security-verification-standard/[OWASP-ASVS v4.0.1
V2.5 Credential Recovery Requirements.(2.5.4)]
Verify shared or default accounts are not present
(e.g. "root", "admin", or "sa").

. [[r2]] link:https://owasp.org/www-project-application-security-verification-standard/[OWASP-ASVS v4.0.1
V2.10 Service Authentication Requirements.(2.10.2)]
Verify that if passwords are required,
the credentials are not a default account.

. [[r3]] link:https://owasp.org/www-project-application-security-verification-standard/[OWASP-ASVS v4.0.1
V14.2 Dependency.(14.2.2)]
Verify that all unneeded features, documentation, samples, configurations are
removed,
such as sample applications, platform documentation, and default or example
users.

. [[r4]] link:https://www.pcisecuritystandards.org/documents/PCI_DSS_v3-2-1.pdf[PCI DSS v3.2.1 - Requirement 2.1.1]
For wireless environments connected to the cardholder data environment or
transmitting cardholder data,
change ALL wireless vendor defaults at installation,
including but not limited to default wireless encryption keys, passwords,
and *SNMP* community strings.
