:slug: servicios/hacking-continuo/
:category: servicios
:description: Nuestro servicio de Hacking Continuo busca encontrar todas las vulnerabilidades y reportarlas lo antes posible. A través de la participación en el ciclo de vida de desarrollo, estamos en la capacidad de encontrar vulnerabilidades de forma paralela al desarrollo.
:keywords: Fluid Attacks, Servicios, Hacking, Continuo, Vulnerabilidad, Seguridad.

= Hacking Continuo

El hacking continuo busca detectar y reportar todas las vulnerabilidades
y problemas de seguridad de un sistema
durante todo el ciclo de desarrollo del mismo,
nuestra participación durante este ciclo
nos permite detectar vulnerabilidades de seguridad de forma continua
en múltiples versiones del sistema que se está desarrollando
sin reportar falsos positivos,
así como verificar su corrección efectiva
antes de la salida a producción del sistema.

[role="tb-alt"]
[cols=3, frame="topbot"]
|====

2+a|== Hacking antes que exista ambiente

Se puede iniciar con las revisiones de seguridad
desde el inicio del desarrollo,
incluso antes de contar con un ambiente funcional.
Ya que se revisa el código fuente directamente
en el repositorio de código del proyecto.

a|image::hacking-antes-ambiente.svg[alt="Planos de una aplicación"]

a|image::tipos-hacking.svg[alt="Símbolo de código fuente"]

2+a|== Tipos de hacking

* *Hacking Continuo Integral:*
Se realiza hacking de aplicación (ambiente de integración),
infraestructura (si esta como código)
y análisis de código fuente (repositorio en +GIT+).

* *Hacking Continuo Limitado:* Se realiza hacking de aplicación
o análisis de código fuente
cuando se tiene acceso solo al ambiente de integración
o al código fuente.

2+a|== Healthcheck

Si al iniciar una suscripción ya hay desarrollos previos
es necesario hacer un desatraso o +healthcheck+.
Esto se realiza con el fin de revisar la totalidad de las líneas
o entradas desarrolladas hasta el momento de la toma de la suscripción.
En los primeros +3+ meses se realiza el desatraso
y en los meses siguientes se continúa con el Ethical Hacking
de forma paralela al desarrollo
(El +healthcheck+ tendrá un costo adicional a la suscripción).

a|image::healthchecks.svg[alt="Símbolo de código fuente con verificaciones exitosas"]

a|image::rigurosidad.svg[alt="Lista de revisiones"]

2+a|== Rigurosidad

Es posible que el cliente decida cuáles requisitos de seguridad se revisarán
en el hacking (perfilamiento) a través de nuestro producto
[button]#link:../../productos/rules/[Rules]#.

Además sabrá la rigurosidad exacta del hackeo
(lo revisado y lo no revisado).

2+a|== Duración

La suscripción se contrata por espacio mínimo de un año

a|image::duracion.svg[alt="Calendario"]

a|image::ciclos-ataque.svg[alt="Engranaje"]

2+a|== Ciclos de Ataque
Durante el tiempo de la suscripción se realizan múltiples ciclos de ataque
a las diferentes versiones del código y/o aplicación
que se generan durante el desarrollo del sistema,
nuestro equipo de hacking revisará constantemente
las funcionalidades del sistema
incluso cuando ya han sido probadas en versiones anteriores.

2+a|== Comunicación directa y ágil

Toda la comunicación del proyecto se hace a través de
[button]#link:../../productos/integrates/[Integrates]#,
mediante las funcionalidades de Chat y de comentarios.

a|image::comunicacion-agil.svg[alt="Dos personas teniendo una conversación"]

a|image::ambientes-hacking.svg[alt="Código fuente dentro de una mira"]

2+a|== Ambientes de hacking

Es posible elegir un único ambiente de hacking entre producción,
pruebas e integración con el servicio básico.
También es posible adicionar ambientes
para verificación de cierre de vulnerabilidades por un cargo adicional.

2+a|== Equipo de hacking altamente calificado

Personal con certificaciones prácticas
y estudios relacionados en temas de seguridad,
realiza hacking manual y con herramientas
para garantizar el reporte de vulnerabilidades
de impacto específicos del negocio,
prácticas inseguras de programación,
alineación a estándares y regulaciones de seguridad sin falsos positivos,
posibilitando la detección de vulnerabilidades +Zero Day+.

a|image::equipo-calificado.svg[alt="Equipo"]

a|image::explotacion.svg[alt="Computador con un candado abierto"]

2+a|== Explotación de vulnerabilidades

Siempre que se tenga acceso a la aplicación desplegada
y se cuente con autorización por parte del cliente
para la afectación de ambientes
usando nuestro motor de explotación propio
[button]#link:../../productos/asserts/[Asserts]#.

2+a|== Extracción de información crítica

En las vulnerabilidades donde sea posible se extraen
todos los registros comprometidos
con el fin de maximizar el impacto generado
y comprometer información sensible.
[button]#link:../../productos/integrates/#registros-comprometidos[Ejemplo]#.

a|image::info-critica.svg[alt="Flechas saliendo de un candado cerrado"]

a|image::seguimiento.svg[alt="Gráfica de barras con una línea continua encima"]

2+a|== Seguimiento de vulnerabilidades a través de Integrates

Durante la ejecución del proyecto es posible verificar
las vulnerabilidades reportados en nuestra plataforma [button]#link:../../productos/integrates/[Integrates]#,
así como visualizar en tiempo real estadísticas del proyecto,
del estado de remediación de las vulnerabilidades,
clasificar las vulnerabilidades por edad, entre otros.

2+a|== Verificación de cierre

Se realizan múltiples ciclos de verificación
para actualizar el estado de una vulnerabilidad
durante la vigencia de la suscripción.
Se pueden hacer tantos ciclos de cierre como sean necesarios
para garantizar que el hallazgo sea solucionado efectivamente.

a|image::verificacion-cierre.svg[alt="Lista de pendientes"]

a|image::soporte-remediacion.svg[alt="Símbolos de pregunta y respuesta"]

2+a|== Soporte de Remediación.

Durante el proyecto es posible solicitar aclaraciones
directamente a los hackers
mediante [button]#link:../../productos/integrates/[Integrates]#.

Es posible utilizar nuestras guias detalladas de remediación
mediante [button]#link:../../productos/defends/[Defends]#.

2+a|== Generar Informes Técnicos y ejecutivos desde Integrates

En el informe técnico se encuentra
la información detallada de cada vulnerabilidad.
Es de gran utilidad para el personal técnico
a la hora de darle una solución a las fallas de seguridad reportadas.

En el informe ejecutivo se encuentra la información resumida y organizada.
De tal manera que pueda ser de utilidad
para todas las personas en la cadena de valor del proyecto.

a|image::reportes.svg[alt="Gráfico de barras en una presentación"]

a|image::borrado-seguro.svg[alt="Caneca de basura con una nube detrás"]

2+a|== Borrado seguro de información

+7+ días hábiles luego de la aprobación final de los informes
se borra toda la información de nuestros sistemas.

|====

* Si desea conocer las diferencias entre nuestros servicios
y otros proveedores puede conocer nuestros diferenciadores
[button]#link:../diferenciadores/[aquí]#.

* Si desea conocer las diferencias entre nuestros servicios
puede ver nuestra tabla comparativa
[button]#link:../comparativo/[aquí]#.
