:slug: rules/300/
:category: data
:description: This document contains the details of the security requirements related to the definition and management of data access in the organization. This requirement establishes the importance of masking sensitive personal and business data to avoid information leakages.
:keywords: Requirement, Security, Data, Information, Business, Mask
:rules: yes

= REQ.300 Mask sensitive data

== Requirement

Bussiness sensitive data
(credit card numbers, *CVV*, etc) must be masked.

== Description

Applications usually handle personal information such as credit card numbers,
*CVV*, personal identifications, social security numbers, etc.
The exposure of this data could severely affect their owners and so they must
be considered sensitive and specifically protected.
Masking is a mechanism that contributes to this protection.

== Findings

* [inner]#link:/web/findings/038/[F038. Business information leak]#

== References

. [[r1]] link:https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:02002L0058-20091219[Directive 2002/58/EC (amended by E-privacy Directive 2009/136/EC).
Art. 4: Security of processing.(1a)]
The measures referred to in paragraph 1 shall at least protect personal data
stored or transmitted against accidental or unlawful destruction,
accidental loss or alteration,
and unauthorized or unlawful storage, processing, access or disclosure.

. [[r2]] link:https://gdpr-info.eu/recitals/no-51/[GDPR. Recital 51: Protecting sensitive personal data]
Personal data which are, by their nature, particularly sensitive in relation
to fundamental rights and freedoms merit specific protection as the context of
their processing could create significant risks to the fundamental rights
and freedoms.
