:slug: kb/java/establecer-control-acceso-url
:eth: no
:category: java
:kb: yes

=  Establecer Control de Acceso a URL

== Necesidad

Establecer control de acceso a URL mediante servidor de aplicaciones (Java)

== Contexto

A continuación se describen las circunstancias bajo las cuales la siguiente 
solución tiene sentido

. Se dispone a un servidor de aplicaciones conforme con las especificaciones 
empresariales de Java.
. Se ha configurado los roles de seguridad necesarios por la aplicación en el 
servidor de aplicaciones.
* Para Tomcat: Tomcat Roles
. Se ha configurado la interfaz de autenticación para la aplicación web
* Ver Authentication web form (Java)

== Solución

. Dentro del archivo WEB-INF\web.xml de la aplicación web se deben configurar 
los roles requeridos en la aplicación
[source, xml, linenums]
 <security-role>
  <role-name>rol1</role-name>
</security-role>
<security-role>
  <role-name>rol2</role-name>
</security-role>
 
[start=2]
. Posteriormente se deben definir la restricción de seguridad para la dirección 
URL que se quiere proteger, y que por ende solo pueden ser accedidas por 
determinados roles
[source, xml, linenums]
 <security-constraint>
  <display-name>Restricción de Seguridad 1</display-name>
  <web-resource-collection>
    <web-resource-name>Direcciones Protegidas</web-resource-name>
    <url-pattern>/restringido/*</url-pattern>
  </web-resource-collection>
  <auth-constraint>
    <role-name>rol1</role-name>
  </auth-constraint>
</security-constraint>
 
[start=3]
. De esta forma el acceso a todos los archivos contenidos en /restringido 
estará disponible solo a las personas que hayan sido autenticadas 
satisfactoriamente con los roles correspondientes, en este caso, rol1.

== Referencias
. Aplicación web de ejemplo de Tomcat 5.5. (archivo web.xml).
