:slug: rules/068/
:category: rules
:description: En el presente documento se detallan los requerimientos de seguridad relacionados a la gestion segura de los componentes definidos para un determinado sistema. Por lo tanto, dichos componentes probados deben estar identificados luego de realizar las pruebas de caja blanca.
:keywords: Componente, Identificar, Probar, Caja Blanca, Definir, Seguridad.
:rules: yes

= REQ.068 Identificar componentes probados

== Requisito

Los componentes efectivamente probados
(pruebas de caja blanca) deben haber sido identificados.

== Descripción

Durante la prueba pueden existir condiciones
que no permitan probar alguno de los componentes del sistema,
en la documentación se la prueba debe quedar clarificado
cuales componentes fueron efectivamente probados.

== Implementación

. En el proceso de Ethical Hacking se debe verificar los componentes
que se hayan establecido en el alcance para la prueba,
en caso de existir inconvenientes
y que el alcance no pueda cubrirse por completo,
en la documentación realizada deben quedar establecidos
los componentes que fueron efectivamente probados.

== Ataques

. Se identificaron vulnerabilidades en producción,
en la documentación de las pruebas realizadas no se evidencia
si efectivamente este componente fue probado.

== Atributos

* Capa: Negocio
* Activo: Arquitectura de seguridad
* Alcance: Adherencia
* Fase: Pruebas
* Tipo de Control: Recomendación
