:slug: rules/999/
:category: rules
:description: En el presente documento se detallan los requerimientos de seguridad relacionados al manejo adecuado de información sensible dentro de un programa. La información confidencial no debe permanecer ni en memoria ni en variables u objetos después de haber sido utilizada.
:keywords: memoria, búfer, tiempo de vida, datos sensibles, información sensible, atacante.
:rules: yes

= REQ.999 Limitar tiempo de vida de datos sensibles

== Nombre

La aplicación debe limpiar/eliminar datos, recursos y/o objetos 
creados por la misma cuando ya no estén en uso.

== Descripción

El presente criterio de seguridad 
trata sobre la protección inadecuada de datos sensibles, 
los cuales, pueden conducir a vulnerabilidades 
que podrían afectar tanto la confidencialidad, la disponibilidad 
e integridad de la información 
durante todo su ciclo de vida.<<r1,^[1]^>> 
Esta fuga de información confidencial 
es más probable si la memoria que contiene los datos 
no es borrada después de usar dicha información.

== Implementación

Por lo anterior, para el presente criterio de seguridad, 
se recomienda seguir las siguientes pautas:<<r2,^[2]^>>

. Si un programa hace uso de un recurso 
como por ejemplo un archivo de texto plano, una imagen, etc., 
después de usar dicho recurso, 
se debe cerrar el acceso al mismo lo antes posible.

. Cuando un programa haga uso de una conexión 
a una base de datos por ejemplo, 
después de usar dicha conexión, 
esta debe ser cerrada tan pronto sea posible.

. Si existen variables en el búfer de memoria, 
estas deben ser sobrescritas antes de ser liberadas.

. Si en memoria existen objetos creados dentro de la aplicación, 
estos deben ser destruidos por esta una vez no sean necesarios.

. En general, cualquier recurso, variable, objeto, conexión, etc., 
debe ser destruido sin esperar a que el recolector de basura los elimine.

De acuerdo a lo anterior, para limitar el riesgo 
de exposición de información confidencial, 
los programas deben minimizar la vida útil de dichos datos sensibles.

== Soluciones

. *+COBOL+* link:../../defends/cobol/liberar-recursos/[Liberar Recursos].
. *+JAVA+* link:../../defends/java/limitar-vida-datos-sensibles/[Limitar el tiempo de vida de datos sensibles].
. *+SCALA+* link:../../defends/scala/limitar-tiempo-vida/[Limitar el tiempo de vida de datos sensibles].

== Casos de abuso

A continuación se describen dos casos de abuso, 
los cuales, son aplicables para el presente criterio de seguridad:

. Un atacante que logre entrar 
y pueda ejecutar código malicioso en el mismo sistema, 
podría acceder a información confidencial 
si esta se encuentra disponible en memoria.

. Cuando se produce un volcado de memoria (+core dump+),^<<r3,[3]>>,<<r4,[4]>>^ 
se generan archivos que podrían contener información confidencial 
como contraseñas, si estos se encontraban en memoria 
al momento de producirse el fallo.

== Referencias

. [[r1]] link:https://www.owasp.org/index.php/Category:Sensitive_Data_Protection_Vulnerability[Category:Sensitive Data Protection Vulnerability].
. [[r2]] link:https://wiki.sei.cmu.edu/confluence/display/java/MSC59-J.+Limit+the+lifetime+of+sensitive+data[MSC59-J. Limit the lifetime of sensitive data].
. [[r3]] link:https://en.wikipedia.org/wiki/Core_dump[Core dump].
. [[r4]] link:http://www.unixguide.net/linux/faq/07.13.shtml[What Is a "core" File?].
