:slug: rules/999/
:category: rules
:description: En el presente documento se detallan los requerimientos de seguridad relacionados al manejo adecuado de información sensible vinculada a un recurso utilizado dentro de un programa. La información confidencial no debe permanecer en memoria después de haber utilizado dicho recurso.
:keywords: memoria, búfer, tiempo de vida, datos sensibles, información sensible, atacante.
:rules: yes

= REQ.999 Limitar tiempo de vida de recursos

== Nombre

La aplicación debe liberar recursos una vez no estén en uso.

== Descripción

El presente criterio de seguridad
trata sobre la protección inadecuada de datos sensibles
asociados a un recurso almacenado en un computador.
Los cuales, pueden conducir a vulnerabilidades
que podrían afectar tanto la confidencialidad, la disponibilidad
e integridad de la información
durante todo su ciclo de vida.<<r1,^[1]^>>
Esta fuga de información confidencial
es más probable si la memoria que contiene los datos
no es borrada después de usar dicho recurso.

== Implementación

Por lo anterior, para el presente criterio de seguridad,
se recomienda seguir las siguientes pautas:<<r2,^[2]^>>

. Si un programa hace uso de un recurso
como por ejemplo un archivo de texto plano, una imagen, etc.,
después de usar dicho recurso,
se debe cerrar el acceso al mismo lo antes posible.

. Si existen datos en el búfer de memoria asociados a un recurso,
estos deben ser sobrescritos antes de liberar dicho recurso.

. Si en memoria existen variables
u objetos creados dentro de la aplicación,
y que además, almacenan datos asociados a un recurso específico,
estos deben ser destruidos por la misma aplicación una vez no sean necesarios.

. En general, todo recurso que sea utilizado
y almacenado en memoria por la aplicación,
debe ser destruido sin esperar a que el recolector de basura los elimine.

De acuerdo a lo anterior, para limitar el riesgo
de exposición de información confidencial,
los programas deben minimizar la vida útil
de cualquier información sensible en memoria.

== Soluciones

. *+COBOL+* link:../../defends/cobol/liberar-recursos/[Liberar Recursos].
. *+JAVA+* link:../../defends/java/limitar-vida-recurso/[Limitar tiempo de vida de recursos].
. *+SCALA+* link:../../defends/scala/limitar-vida-recurso/[Limitar tiempo de vida de recursos].
. *+CSHARP+* link:../../defends/csharp/limitar-vida-recurso/[Limitar tiempo de vida de recursos].

== Casos de abuso

A continuación se describen dos casos de abuso,
los cuales, son aplicables para el presente criterio de seguridad:

. Un atacante que logre entrar
y pueda ejecutar código malicioso en el mismo sistema,
podría acceder a información confidencial
si esta se encuentra disponible en memoria.

. Cuando se produce un volcado de memoria (+core dump+),^<<r3,[3]>>,<<r4,[4]>>^
se generan archivos que podrían contener información confidencial
como contraseñas, si estos se encontraban en memoria
al momento de producirse el fallo.

== Referencias

. [[r1]] link:https://www.owasp.org/index.php/Category:Sensitive_Data_Protection_Vulnerability[Category:Sensitive Data Protection Vulnerability].
. [[r2]] link:https://wiki.sei.cmu.edu/confluence/display/java/MSC59-J.+Limit+the+lifetime+of+sensitive+data[MSC59-J. Limit the lifetime of sensitive data].
. [[r3]] link:https://en.wikipedia.org/wiki/Core_dump[Core dump].
. [[r4]] link:http://www.unixguide.net/linux/faq/07.13.shtml[What Is a "core" File?].
