:slug: products/rules/list/351/
:category: cryptography
:description: This requirement establishes the importance of using assigning unique cryptographic keys and certificates to each device.
:keywords: Device, Cryptographic, Key, Unique, Certificate, ASVS, CWE, Rules, Ethical Hacking, Pentesting
:rules: yes

= R351. Assign unique keys to each device

== Requirement

Each individual device must have unique cryptographic keys and certificates.

== References

. [[r1]] link:https://cwe.mitre.org/data/definitions/326.html[CWE-326: Inadequate Encryption Strength]
The software stores or transmits sensitive data using an encryption scheme that
is theoretically sound,
but is not strong enough for the level of protection required.

. [[r2]] link:https://cwe.mitre.org/data/definitions/330.html[CWE-330: Use of Insufficiently Random Values]
The software uses insufficiently random numbers or values in a security context
that depends on unpredictable numbers.

. [[r3]] link:https://owasp.org/www-project-application-security-verification-standard/[OWASP-ASVS v4.0.1
Appendix C: Internet of Things Verification Requirements.(C.2)]
Verify that cryptographic keys and certificates are unique to each individual
device.

. [[r4]] link:https://owasp.org/www-project-application-security-verification-standard/[OWASP-ASVS v4.0.1
V2.9 Cryptographic Software and Devices Verifier Requirements.(2.9.2)]
Verify that the challenge nonce is at least 64 bits in length,
and statistically unique or unique over the lifetime of the cryptographic
device.

. [[r5]] link:https://owasp.org/www-project-application-security-verification-standard/[OWASP-ASVS v4.0.1
V6.2 Algorithms.(6.2.6)]
Verify that nonces, initialization vectors, and other single use numbers must
not be used more than once with a given encryption key.
The method of generation must be appropriate for the algorithm being used.
