:slug: rules/269/
:category: rules
:description: En el presente documento se detallan los requerimientos de seguridad relacionados a los sistemas operativos manejados dentro de la organización. El objetivo del presente requerimiento es definir la importancia de establecer el principio de mínimo privilegio para objetos nuevos.
:keywords: Requerimiento, Seguridad, Sistema Operativo, Principio, Mínimo, Privilegio.
:rules: yes

= REQ.269 Usar principio mínimo privilegio

== Requisito

Los privilegios para objetos nuevos
deben establecerse según el principio de mínimo privilegio (`umask`).

== Referencias

. [[r1]] link:https://www.owasp.org/index.php/ASVS_V4_Access_Control[`OWASP-ASVS v3.1-4.1`]
Verificar que exista el principio de mínimo privilegio.
Los usuarios sólo deben tener acceso a funciones, datos, archivos, URLs,
controladores, servicios y otros recursos
para los cuales se posee autorización específica.
Esto implica protección contra `spoofing` y elevación de privilegio.

. [[r2]] link:https://nvd.nist.gov/800-53/Rev4/control/AC-6[`NIST` 800-53 AC-6]
La organización emplea el principio del mínimo privilegio,
permitiendo sólo accesos autorizados a los usuarios
(o procesos que actúan en nombre de los usuarios) necesarios para completar
las tareas asignadas de acuerdo a las misiones de la organización
y las funciones de negocio.
