:slug: products/rules/list/313/
:category: privacy
:description: This requirement establishes the importance of informing the user of the system's inability to identify them whenever it can be demonstrated.
:keywords: Requirement, Security, Data, GDPR, ISO, User Identification, Regulation, Rules, Ethical Hacking, Pentesting
:rules: yes

= R313. Inform inability to identify users

== Requirement

The system must inform its users whenever it can demonstrate its inability to
individually identify them using the information it has collected from them.

== Description

Systems usually request information from their users or collect it based
on their interactions with the application.
Some regulations related to the collection of personal data are only applicable
if users can be identified using this data.
Whenever the system is unable to individually identify its users with the data
it collects from them, and it can demonstrate this,
it must inform them of this situation.

== Findings

* [inner]#link:/products/rules/findings/088/[F088. Privacy violation]#

== References

. [[r1]] link:https://gdpr-info.eu/art-11-gdpr/[GDPR. Art. 11: Processing which does not require identification.(2).]
Where the controller is able to demonstrate that it is not in a position to
identify the data subject,
the controller shall inform the data subject accordingly,
if possible.

. [[r2]] link:https://owasp.org/www-project-application-security-verification-standard/[OWASP-ASVS v4.0.1
V8.3 Sensitive Private Data.(8.3.4)]
Verify that all sensitive data created and processed by the application has
been identified,
and ensure that a policy is in place on how to deal with sensitive data.

. [[r3]] link:https://www.iso.org/obp/ui/#iso:std:54534:en[ISO 27001:2013. Annex A - 18.1.4]
When applicable, guarantee the privacy and security of personal information,
as required by the relevant legislation and regulations.
