:slug: rules/176/
:category: data
:description: This document details the security guidelines and requirements related to the organization's sensitive data. The purpose of this security requirement is to establish the importance of restricting access to sensitive information to authorized users only.
:keywords: Requirement, Security, Data, Authorization, Restriction, GDPR
:rules: yes

= REQ.176 Restrict system objects

== Requirement

The system must restrict access to system objects
that have sensitive content.
It will only allow access to authorized users.

== Description

Applications usually handle personal and confidential information
such as personal identifications, social security numbers,
credentials and health histories.
This data should be protected as a fundamental right,
therefore, it should be stored and transmitted using secure mechanisms that
prevent access to it by unauthorized actors.

== References

. [[r1]] link:https://gdpr-info.eu/recitals/no-2/[GDPR. Recital 6: Ensuring a High Level of Data Protection Despite
the Increased Exchange of Data].
Technology has transformed both the economy and social life,
and should further facilitate the free flow of personal data,
while ensuring a high level of the protection of personal data.
