:slug: rules/176/
:category: data
:description: This document details the security guidelines and requirements related to the organization's sensitive data. The purpose of this security requirement is to establish the importance of restricting access to sensitive information to authorized users only.
:keywords: Data, Authorization, Restriction, GDPR, ASVS, CWE
:rules: yes

= REQ.176 Restrict system objects

== Requirement

The system must restrict access to system objects
that have sensitive content.
It will only allow access to authorized users.

== Description

Applications usually handle personal and confidential information
such as personal identifications, social security numbers,
credentials and health histories.
This data should be protected as a fundamental right,
therefore, it should be stored and transmitted using secure mechanisms that
prevent access to it by unauthorized actors.

== References

. [[r1]] link:https://gdpr-info.eu/recitals/no-2/[GDPR. Recital 6: Ensuring a High Level of Data Protection Despite
the Increased Exchange of Data].
Technology has transformed both the economy and social life,
and should further facilitate the free flow of personal data,
while ensuring a high level of the protection of personal data.

. [[r2]] link:https://gdpr-info.eu/art-32-gdpr/[GDPR. Art. 32: Security of processing.(4)]
The controller and processor shall take steps to ensure that any natural person
acting under the authority of the controller or the processor who has access to
personal data does not process them except on instructions from the controller.

. [[r3]] link:https://owasp.org/www-project-application-security-verification-standard/[OWASP-ASVS v4.0.1
V1.2 Authentication Architectural Requirements.(1.2.2)]
Verify that communications between application components,
including APIs, middleware and data layers, are authenticated.
Components should have the least necessary privileges needed.

. [[r4]] link:https://cwe.mitre.org/data/definitions/306.html[CWE-306 Missing Authentication for Critical Function]
The software does not perform any authentication for functionality that
requires a provable user identity or consumes a significant amount of
resources.

. [[r5]] link:https://cwe.mitre.org/data/definitions/287.html[CWE-287 Improper Authentication]
When an actor claims to have a given identity,
the software does not prove or insufficiently proves that the claim is correct.
