:slug: rules/080/
:category: logs
:description: This requirement establishes the importance of preventing log modifications or alterations in order to keep permanent records of all system activity.
:keywords: Logs, Events, Modification, Alteration, ASVS, CWE, Rules, Ethical Hacking, Pentesting
:rules: yes

= R080. Prevent log modification

== Requirement

System logs must not allow modifications or alterations.

== Description

Logs are used to analyze a system's behavior.
They help detect errors and suspicious activity,
and often hold very sensitive information.
Therefore, they should be protected so that no unauthorized actor can modify
them,
since this could prevent a vulnerability or a breach from being noticed timely.

== References

. [[r1]] link:https://cwe.mitre.org/data/definitions/200.html[CWE-200: Exposure of Sensitive Information to an Unauthorized Actor].
The product exposes sensitive information to an actor that is not explicitly
authorized to have access to that information.

. [[r3]] link:https://cwe.mitre.org/data/definitions/285.html[CWE-285: Improper Authorization].
The software does not perform or incorrectly performs an authorization check
when an actor attempts to access a resource or perform an action.

. [[r4]] link:https://owasp.org/www-project-application-security-verification-standard/[OWASP-ASVS v4.0.1
V7.3 Log Protection Requirements.(7.3.3)]
Verify that security logs are protected from unauthorized access and
modification.
