:slug: rules/080/
:category: logs
:description: This requirement establishes the importance of preventing log modifications or alterations in order to keep permanent records of all system activity.
:keywords: Logs, Events, Modification, Alteration, ASVS, CWE, OWASP, PCI DSS, Rules, Ethical Hacking, Pentesting
:rules: yes

= R080. Prevent log modification

== Requirement

System logs must not allow modifications or alterations.

== Description

Logs are used to analyze a system's behavior.
They help detect errors and suspicious activity,
and often hold very sensitive information.
Therefore, they should be protected so that no unauthorized actor can modify
them,
since this could prevent a vulnerability or a breach from being noticed timely.

== References

. [[r1]] link:https://cwe.mitre.org/data/definitions/200.html[CWE-200: Exposure of Sensitive Information to an Unauthorized Actor].
The product exposes sensitive information to an actor that is not explicitly
authorized to have access to that information.

. [[r3]] link:https://cwe.mitre.org/data/definitions/285.html[CWE-285: Improper Authorization].
The software does not perform or incorrectly performs an authorization check
when an actor attempts to access a resource or perform an action.

. [[r4]] link:https://owasp.org/www-project-top-ten/OWASP_Top_Ten_2017/Top_10-2017_A5-Broken_Access_Control[OWASP Top 10 A5:2017-Broken Access Control].
Restrictions on what authenticated users are allowed to do are often not
properly enforced.
Attackers can exploit these flaws to access unauthorized functionality and/or
data, such as access other users’ accounts, view sensitive files,
modify other users’ data, change access rights, etc.

. [[r5]] link:https://owasp.org/www-project-application-security-verification-standard/[OWASP-ASVS v4.0.1
V7.3 Log Protection Requirements.(7.3.3)]
Verify that security logs are protected from unauthorized access and
modification.

. [[r6]] link:https://www.pcisecuritystandards.org/documents/PCI_DSS_v3-2-1.pdf[PCI DSS v3.2.1 - Requirement 6.5.8]
Address common coding vulnerabilities in software-development processes
including improper access control
(such as insecure direct object references, failure to restrict URL access,
directory traversal, and failure to restrict user access to functions).

. [[r7]] link:https://www.pcisecuritystandards.org/documents/PCI_DSS_v3-2-1.pdf[PCI DSS v3.2.1 - Requirement 10.5.2]
Protect audit trail files from unauthorized modifications.
