:slug: defends/cobol/generar-llaves/
:category: cobol
:description: Nuestros ethical hackers explican como evitar vulnerabilidades de seguridad mediante la programacion segura en COBOL al generar llaves criptograficas. Las llaves criptograficas son muy utilizadas para incrementar la seguridad de la informacion critica como credenciales de acceso y autenticacion.
:keywords: Cobol, Seguridad, Generar, Llaves, Números, Aleatorios.
:defends: yes

= Generar Llaves

== Necesidad

Usar la función criptográfica más segura del lenguaje
para la generación de llaves aleatorias en +COBOL+.

== Contexto

A continuación se describe las circunstancias
bajo las cuales la siguiente solución tiene sentido:

. Se está desarrollando una aplicación en +COBOL+.

. Debe usarse el mecanismo criptográfico más seguro
ofrecido por la plataforma de desarrollo
para la generación de números aleatorios,
de los cuales se deriven riesgos de seguridad en caso de predecirse el número
(ej: Generación de +ID+, mapeo de códigos, llaves),
evaluando previamente un posible impacto en la disponibilidad<<r1,^[1]^>>.

== Solución

. La generación de números pseudoaleatorios
es realizada aplicando los conceptos del apéndice 3 de +FIPS 186-1+.
El servidor automáticamente genera la semilla
usando datos recolectados de la información del sistema
o usando un coprocesador criptográfico como el +4764+ si está disponible.

. El procedimiento +Qc3GenPRNs+ tiene como propósito
la generación de números pseudoaleatorios criptográficamente seguros.

. Comenzamos la solución definiendo la división +IDENTIFICATION DIVISION+<<r2,^[2]^>>:
+
.cobolrnds.cbl
[source,cobol,linenums]
----
       PROCESS NOMONOPRC.
       IDENTIFICATION DIVISION.
      ******************
      * Identification *
      ******************
       PROGRAM-ID. COBOLRNDS.
----
+
En esta división mediante la sentencia +PROGRAM-ID+,
se denomina al programa como +COBOLRNDS+.

. En la división +ENVIRONMENT DIVISION+<<r3,^[3]^>>
y dentro de la sección +CONFIGURATION SECTION+,
enlazamos el procedimiento externo +Qc3GenPRNs+:
+
[source,cobol,linenums]
----
      ***************
      * Environment *
      ***************
       ENVIRONMENT DIVISION.
       CONFIGURATION SECTION.
         SOURCE-COMPUTER. IBM-ISERIES.
         OBJECT-COMPUTER. IBM-ISERIES.
         SPECIAL-NAMES.
         LINKAGE TYPE PROCEDURE FOR "Qc3GenPRNs".
----
. En la división +DATA DIVISION+<<r4,^[4]^>>
se copia las estructuras contenidas en +QC3CCI+ (Manejo criptográfico)
y +QUSEC+ (Manejo de errores):
+
[source,cobol,linenums]
----
      ********
      * Data *
      ********
       DATA DIVISION.

       WORKING-STORAGE SECTION.
       COPY QC3CCI OF QSYSINC-QCBLLESRC.
       COPY QUSEC OF QSYSINC-QCBLLESRC.
----
. Se declara la variable +WS-RAND-BYTES+,
la cual va a almacenar la llave generada aleatoriamente:
+
[source,cobol,linenums]
----
       01 WS-RAND-BYTES PIC X(32).
----
. En la división +PROCEDURE DIVISION+ se encuentra la lógica de negocio:
+
[source,cobol,linenums]
----
      ********
      * Main *
      ********
       PROCEDURE DIVISION.
       MAIN.
----
. Se hace un llamado al procedimiento +Qc3GenPRNs+.
Los argumentos que espera el procedimiento<<r5,^[5]^>> son:

* +Data:+ La variable donde se va a almacenar el flujo de datos aleatorios.

* +Longitud de datos:+ La longitud de la variable portadora.

* +Tipo:+ Indica el tipo de flujo.
0 para la generación de números pseudoaleatorios reales,
1 para la generación de números pseudoaleatorios de prueba.

* +Paridad:+ Indica la paridad en cada byte del flujo.
0 para no establecer paridad,
1 para establecer paridad par y
2 para establecer paridad impar.

* +Error:+ Estructura donde se almacena el error en caso de excepción.

+
[source,cobol,linenums]
----
       CALL "Qc3GenPRNs" USING
           BY REFERENCE WS-RAND-BYTES,
           BY CONTENT   LENGTH OF WS-RAND-BYTES,
           BY CONTENT   "0",
           BY CONTENT   "0",
           BY REFERENCE QUS-EC.
----

. Se despliega en pantalla el flujo aleatorio
y se detiene la ejecución del programa:
+
[source,cobol,linenums]
----
       DISPLAY "Random: " WS-RAND-BYTES.

       STOP RUN.
----
. Algunas de las llaves generadas al ejecutar el programa
pueden ser observadas a continuación:
+
[source,bat,linenums]
----
Random:  iÂQW½ &l  º|äF Êú§± zº PïõM#OÝÖ
Random: Üæ@  & Ï¬Ó÷2]#` ä« ñÒ´    =5fr4ÿ
Random: üQ;ý Øi âÒãyè*  ñ ß:¿¯S}  e9$óóâ
Random: %xërW 8W!îæ @ëÆ?Æ 5(    é"  íõ ä
Random: Á  ÅûÀ·d,é P~J¾}Ãðø£  ® >  zY"6÷
Random: F`IG9q£þ#    £ #¯¥6 VæU V¼½m8 OÙ
----

== Descargas

Puedes descargar el código fuente
pulsando en el siguiente enlace:

. [button]#link:src/cobolrnds.cbl[cobolrnds.cbl]# contiene
todas las instrucciones +COBOL+
que generan las llaves como se explicó anteriormente.

== Referencias

. [[r1]] link:../../../rules/224/[REQ.224 Usar mecanismos criptográficos seguros].
. [[r2]] link:https://www.ibm.com/support/knowledgecenter/en/ssw_ibm_i_73/rzasb/iddiv.htm[Identification Division].
. [[r3]] link:https://www.ibm.com/support/knowledgecenter/en/ssw_ibm_i_72/rzasb/envcon.htm[Environment Division].
. [[r4]] link:https://www.ibm.com/support/knowledgecenter/en/ssw_ibm_i_73/rzasb/datdivs.htm[Data Division Structure].
. [[r5]] link:https://www.ibm.com/support/knowledgecenter/ssw_i5_54/apis/qc3genprns.htm[Generate Pseudorandom Numbers (QC3GENRN, Qc3GenPRNs) API].
