:slug: clientes/
:description: Fluid Attacks es una compañía especializada en seguridad informática, ethical hacking, y detección de vulnerabilidades en aplicaciones e infraestructura con más de 18 años prestando sus servicios en el mercado colombiano. En esta página presentamos los sectores en los cuales nos especializamos.
:keywords: Fluid Attacks, Seguridad, Clientes, Información, Pentesting, Ethical Hacking.
:caption:

= Clientes

[role="tb-alt"]
[cols=3, frame="topbot"]
|====
2+a|== link:financiero/[Financiero]

Los clientes de +Fluid Attacks+ en el sector financiero
comprenden algunos de los bancos más importantes de América Latina,
además de empresas encargadas del recaudo de aportes sociales, entre otras.
Algunos de nuestos clientes son +Bancolombia+, +BBVA+,
+Davivienda+, +Sura+, +Protección+, +Colpatria+.
a|image::financiero.svg[Signo de dólar]


a|image::comunicaciones.svg[Teléfono inteligente]
2+a|== link:comunicaciones/[Comunicaciones]

+Fluid Attacks+ ha ofrecido soluciones a algunos de los principales proveedores
de servicios de comunicaciones en Colombia, entre ellos +Claro+,
+Tigo UNE+, +ETB+ y +Edatel+.

2+a|== link:comercial/[Comercial]

Hemos trabajado con varias compañías cuyo objetivo es complacer al consumidor
desde diferentes áreas, sea ventas al detal, +E-Commerce+, la industria textil,
o soluciones de tecnología. Algunos de estos clientes son
+Grupo Éxito+, +Grupo Uribe+, +Rappi+, +Semana+,
y la compañía australiana +The Missing Link+.
a|image::comercial.svg[Consumidores con diferentes reacciones]

a|image::tecnologia.svg[Servidor y base de datos]
2+a|== link:tecnologia/[Tecnología]

+Fluid Attacks+ ha contribuido a empresas que ofrecen +software+,
infraestructura y otras soluciones de tecnología a sus clientes,
en un rango amplio de aplicaciones.
Algunos de nuestros clientes en esta área son
+PSL+, +S4N+, +Arus+, +Ceiba+, las empresas americanas +Cre8tive+, +KometSales+
and +VM2020+, y la empresa española +Indra+.

2+a|== link:energia/[Energía]

También hemos ejecutado proyectos en compañías que se especializan
en el sector de la energía, ya sea en la generación, distribución
y comercialización, como +Celsia+, o en la planeación, diseño y manejo
de los sistemas transaccionales, como +XM+.
a|image::energia.svg[Símbolo de un trueno]

a|image::industrial.svg[Fábrica]
2+a|== link:industrial/[Industrial]

También hemos asistido a diversos fabricantes y participantes
del sector industrial en sus necesidades de seguridad de +software+
y seguridad de infraestructura.
Algunos de estos clientes son +Grupo Argos+, +Manuelita+, +Corona+,
+Cadena+ y +Odinsa+.

2+a|== link:transporte/[Transporte]

+Fluid Attacks+ ha trabajado con gigantes del sector de transporte
como +Avianca+ y +F2X+, para asegurar que sus aplicaciones
y plataformas +Web+ ofrezcan la mejor seguridad a sus usuarios.
a|image::transporte.svg[Vista frontal de un bus]

|====
