:slug: rules/029/
:category: session
:description: This documents contains the details of the security requirements related to web application session management and session variables. This requirement establishes the importance of using cookies with the required security attributes such as HttpOnly and Secure.
:keywords: Session, Cookies, Attributes, HttpOnly, ASVS, CWE
:rules: yes

= R029. Cookies with security attributes

== Requirement

The session *cookies* of web applications
must have security attributes (*HttpOnly*, *Secure*).

== Description

When you have web applications that handle sessions,
you can use different attributes
to improve the security related to the *cookies* that handle these sessions.
The attributes *HttpOnly* and *Secure*
prevent the theft of the session *cookie*
by denying the browser visibility and access to it
(even when *Cross Site Scripting [XSS]* attacks are used)
and allow the *cookie* to be sent
only when the request is encrypted (using *HTTPS*),
in this manner, session theft is greatly mitigated
and therefore increases the integrity of the application.

== Implementation

. Implement the *HttpOnly* attribute:
If the *HttpOnly* attribute
is present in the *HTTP* response header,
the *cookie* can not be accessed using client side *scripts*.
As a result and even if there exist a
link:https://cwe.mitre.org/data/definitions/87.html[*cross-site scripting (XSS) vulnerability*]
and a user accidentally accesses the link that exploits this vulnerability,
the browser will not reveal the *cookie* to a third party.
*
If a browser does not support *HttpOnly*
and the website tries to set the *HttpOnly* attribute,
said attribute will be ignored by the browser
thus creating a traditional *cookie* accessible by *scripts*.
As a result, the *cookie* (usually a *session cookie*)
becomes vulnerable to theft or modification by a *malicious script*.

. Implement the *Secure* attribute:
The link:https://cwe.mitre.org/data/definitions/614.html[*secure*] attribute is an option
that can be applied from the application server
when a new *cookie* is sent to the user in a *HTTP* response.
The purpose of the *secure* attribute
is to prevent *cookies* from being viewed by unauthorized third parties
due to the plain text transmission of the *cookie*.

== Exceptions

. Exceptions for the *HttpOnly* attribute:
Web applications that use JavaScript for the majority of their operations
may use an anti-Cross-Site-Request-Forgery(*CSRF*) technique
that relies on same-origin policy.
This technique consist of setting a cookie containing a random token.
Client side JavaScript reads its value
and copies it into a custom *HTTP CSRF* header sent with each request.
The security of this technique
is based on the assumption that only JavaScript
running within the same origin will be able to access the cookie.
JavaScript running from a rogue file or email
will not be able to read it and copy into the custom header.
Even though the *CSRF* cookie will be automatically sent with the rogue request,
the server will be still expecting a valid *CSRF* header.
In this implementation,
the *CSRF* cookie must not have *HttpOnly* attribute,
as it is intended to be read by the JavaScript by design.
However, the protection provided by this technique
can be thwarted if the target website disables its same-origin policy
using one of the following techniques <<r8,^[8]^>>:

* Access-Control-Allow-Origin header set to ***.
* *clientaccesspolicy.xml* file granting unintended access
to Silverlight controls.
* *crossdomain.xml* file granting unintended access to Flash.

== Attacks

. An attacker generates a *script* that is executed
by a valid authenticated user
without their knowledge,
without the *HTTPOnly* and *Secure* attributes
the *script* sends information to the attacker^<<r1,[1]>>,<<r2,[2]>>^
containing the session *cookie* used for session theft.

. An attacker link:https://puppet.com/security/cve/cve-2013-4964[captures]
*HTTP* traffic using a *Man in The Middle (MiTM)* attack
intercepting request and responses in plain text
and extracting the session *cookie* used for session theft.

== Attributes

. Layer: Application layer.
. Asset: Session management.
. Scope: Confidentiality.
. Phase: Construction.
. Type of Control: Procedure.

== Findings

* [inner]#link:/web/findings/007/[F007. Cross-site request forgery]#

* [inner]#link:/web/findings/008/[F008. Reflected cross-site scripting (XSS)]#

* [inner]#link:/web/findings/010/[F010. Stored cross-site scripting (XSS)]#

* [inner]#link:/web/findings/042/[F042. Insecurely generated cookies]#

== References

. [[r1]] link:https://cwe.mitre.org/data/definitions/614.html[CWE-614: Sensitive Cookie in HTTPS Session Without 'Secure' Attribute].
The Secure attribute for sensitive cookies in HTTPS sessions is not set,
which could cause the user agent to send those cookies in plaintext over an
HTTP session.

. [[r2]] link:https://cwe.mitre.org/data/definitions/1004.html[CWE-1004: Sensitive Cookie Without 'HttpOnly' Flag].
The software uses a cookie to store sensitive information,
but the cookie is not marked with the HttpOnly flag.

. [[r3]] link:https://owasp.org/www-project-application-security-verification-standard/[OWASP-ASVS v4.0.1
V3.2 Session Binding Requirements.(3.2.3)]
Verify the application only stores session tokens in the browser using secure
methods such as appropriately secured cookies (see section 3.4) or HTML 5
session storage.

. [[r4]] link:https://pcinetwork.org/forum/index.php?threads/pci-dss-3-0-6-5-10-broken-authentication-and-session-management.667/[[PCI DSS 3.0\] 6.5.10 Broken authentication and session management].
