:slug: rules/224/
:category: rules
:description: En el presente documento se detallan los requerimientos de seguridad relacionados a los números aleatorios. En este requerimiento se establece la importancia de implementar mecanismos criptográficos seguros para la generación de números aleatorios usados en procesos críticos.
:keywords: Requerimiento, Seguridad, Aleatorios, Mecanismos, Criptográficos, Seguros.
:rules: yes

= REQ.224 Usar mecanismos criptográficos seguros

== Requisito

Debe usarse el mecanismo criptográfico más seguro
ofrecido por la plataforma (ej: +java.security.SecureRandom+)
para la generación de números aleatorios usados en procesos críticos
(ej: generación de +ID+, mapeo de códigos, llaves).

== Referencias

. [[r1]] link:https://www.owasp.org/index.php/ASVS_V1_Architecture[+OWASP-ASVS v3.1-1.12+]
Verificar que exista una política explícita
sobre cómo administrar las claves criptográficas (si las hay)
y se impone el ciclo de vida de las claves criptográficas.
Idealmente, seguir un estándar de gestión de claves como +NIST SP 800-57+.

. [[r2]] link:https://www.owasp.org/index.php/ASVS_V7_Cryptography[+OWASP-ASVS v3.1-7.6+]
Verificar que todos los números aleatorios, archivos aleatorios,
GUIDs aleatorios y cadenas aleatorias sean generadas
utilizando el generador de números aleatorios aprobado
del módulo criptográfico cuando se espera que estos valores aleatorios
no puedan ser adivinados por un atacante.

. [[r3]] link:https://www.owasp.org/index.php/ASVS_V7_Cryptography[+OWASP-ASVS v3.1-7.15+]
Verificar que los números aleatorios sean creados
con una entropía adecuada, incluso cuando la aplicación
se encuentre bajo cargas pesadas,
o que la aplicación se degrade adecuadamente en tales circunstancias.

. [[r4]] link:https://nvd.nist.gov/800-53/Rev4/control/IA-7[+NIST+ 800-53 IA-7]
Módulo de autenticación criptográfica:
Los sistemas de información deben implementar mecanismos
para la autenticación con un módulo criptográfico
que cumpla los requerimientos de las leyes federales aplicables,
órdenes ejecutivas, directivas, políticas, regulaciones, estándares
y guías para tal autenticación.
