:slug: valores/
:description: Esta página establece expectativas sobre cómo los socios, empleados y aliados comerciales actúan frente a las situaciones cotidianas. FLUID está comprometida con un comportamiento íntegro y correcto espera que cada uno actúe cumpliendo la ley y las políticas definidas por la empresa.
:keywords: FLUID, Valores, Políticas, Ética, Protección, Información.
:translate: values/

= Valores

== 1. Propósito y alcance

Esta página establece expectativas sobre cómo los socios,
empleados y aliados comerciales actúan frente a las situaciones cotidianas.
FLUID está comprometida con un comportamiento íntegro y correcto espera que
cada uno actúe cumpliendo la ley y las políticas definidas por la empresa.
Se espera de cada uno comprensión y acatamiento.
El incumplimiento de los principios aquí expresados podrá generar sanciones
civiles y/o penales y puede acarrear el fin de la relación con FLUID.

== 2. Principios

FLUID es una empresa colombiana, que cree firmemente en sus fundamentos, los
promueve y defiende. Nuestros principios no se negocian.

Estos son, en orden de prioridad:

* La *HONESTIDAD*, la verdad para FLUID es el bien mayor
que prima sobre todo lo demás.
Las acciones y palabras de cada uno deben reflejar legitimidad,
el fraude es considerado una falta grave.
* El *EQUIPO*, los resultados en FLUID son conseguidos
mediante el trabajo colaborativo de su personal.
Por consiguiente, promovemos el trato digno y respetuoso a cada uno
con igualdad de oportunidades.
* La *DISCIPLINA*, entendida como la suma
del cabal cumplimiento de los compromisos,
la dedicación, el empeño y la perseverancia.

== 3. Manifestaciones

A continuación detallamos solo algunos de los comportamientos
que deben manifestarse como implicación directa
de la adherencia a nuestro código de ética, nuestro valores y principios:

. *Toda vulnerabilidad detectada es reportada*:
No existen vulnerabilidades que se detectan
y que se guardan para un futuro uso, personal o de la organización.

. *Solo se realizan ataques cuando existe la autorización del cliente,
en ambientes de prueba personales
o ambientes creados para ser hackeados (CTFs, sitios de retos, etc)*:
Ni a modo de prueba, ni en tiempo fuera del trabajo,
ni fuera de la organización, se realizan ataques a terceros
(compañeros, otras empresas, amigos, etc).

. *Las vulnerabilidades encontradas por el hacker no son reveladas:*
El hacker que encuentra la vulnerabilidad
no cuenta a ninguna persona interna de +Fluid Attacks+
o incluso de su circulo familiar,
ni los detalles ni la existencia misma
de las vulnerabilidades que descubre o conoce.
Solo el cliente y las personas del proyecto deben enterarse de las mismas.

. *Toda infección realizada durante un ataque se desinfecta*:
Después de finalizar un proyecto todo el software instalado para infectar
es completamente desinstalado o de no ser posible
se notifica esta situación al cliente por escrito.

. *Toda violación de seguridad de la cual nos enteramos es reportada*:
Si conocemos una violación de seguridad,
sea accidental o intencional,
ésta se comunica por escrito o mediante un testigo
a los niveles de autoridad superiores
a las personas implicadas en la violación.

. *Ante un error de cualquier naturaleza se reconoce la falta sin excusas*:
Ante un incumplimiento de un compromiso de cualquier naturaleza
que tenga una persona de +Fluid Attacks+ con cualquier tercero,
actuamos reconociendo la falta de forma inmediata,
explícita, directa, presencial y sin escusas
ante todos los afectados por dicho incumplimiento.

== 4. Ética

En nuestra empresa importa el proceso más que el resultado.
Es por esto que rechazamos prácticas como el soborno,
el monopolio y la competencia desleal.
Por el contrario, favorecemos prácticas empresariales justas,
así como promovemos el apoyo a nuestros empleados y aliados.

Cada uno de nuestros empleados
está afiliado a seguridad social por el +100%+ de su salario.
Nuestra jornada laboral está limitada a lo establecido por la ley colombiana,
sin embargo, en los casos en los que se ve excedida,
los empleados pueden solicitar su compensación.
Rechazamos el trabajo infantil.

== 5. Protección de información

Estamos en permanente monitoreo y gestión de los riesgos
relacionados con la información de nuestros clientes.

== 6. Reportes y denuncias

Pueden ser reportados hechos relacionados
con el incumplimiento de nuestros valores
en la dirección etica@fluidattacks.com
