:slug: about-us/events/burn-the-datacenter/
:subtitle: From pets to cattle
:category: events
:description: Future of technologies, software development, security testing and management of development lifecycle in one talk. Find out more about it here.
:keywords: Fluid Attacks, Burn the Datacenter, Technology, Continuous Integration Security Testing, Software Development, Development Lifecycle, Pentesting, Ethical Hacking
:eventspage: yes
:banner: events-bg

= Burn the Datacenter

== 1. Objective

In this space we seek to share our beliefs
about the future of technologies, software development
and management of the development lifecycle over the next `10` years.
We also include recommendations on how to adapt the complete ecosystem,
particularly regarding our area of expertise: security testing.

== 2. Content

The fields of software development and infrastructure management
have been typically separated into two different and antagonistic worlds.
There is a dichotomy between the flexibility to changes
during the development phase
and the stability in the infrastructure.
We have recently found misapplied concepts such as `DevOps`, `DevOps` profiles
and companies that create `DevOps` transformation areas.
The question is: Beyond the management aspects
(roles, responsibilities and processes),
how can these concepts be translated into a simple technical approach
in additional spaces to the applications?

In this methodological universe,
we are losing sight of a critical need for programming languages
scoped to infrastructure and networks,
which have been around for more than `20` years.
These languages would allow programming practices
that have been developed for half a century
to also apply to infrastructure development.

* Can we compile a server?
* Can we perform infrastructure linting?
* Can we perform network static analysis?
* Can we perform continuous integration over infrastructure?
* Can we perform continuous deployment over infrastructure?
* Can infrastructure be immutable and hence, disposable?

In this conference, we will talk about
how the world belongs to the programmers
and how the environments can be infinite.

== 3. Experience

We have given this free academic conference for a year, in:

* *Large companies:*
link:https://www.avianca.com/co/es/[Avianca],
link:https://www.grupobancolombia.com/wps/portal/personas[Bancolombia],
link:https://www.bcp.com.bo/[Banco de Credito del Peru],
link:https://www.banistmo.com/[Banistmo],
link:http://www.celsia.com/[Celsia-EPSA],
link:https://www.comfama.com/webinicio/default.asp[Comfama],
link:https://www.velez.com.co/[Cueros Velez],
link:https://www.gnbsudameris.com.co/[GNB Sudameris],
link:https://www.grupoexito.com.co/es/[Grupo Éxito],
link:http://www.homecenter.com.co/homecenter-co/[Homecenter],
link:https://www.stgeorgesbank.com/[St. Georges Bank],
link:https://www.segurossura.com.co/Paginas/default.aspx[Sura],
link:https://www.tigoune.com.co/[Tigo Une].

* *Universities:* link:http://www.eafit.edu.co/[EAFIT],
link:https://www.udem.edu.co/[UdeM],
link:https://www.udea.edu.co/[UdeA],
link:https://medellin.unal.edu.co/[UNALMed],
link:http://www.politecnicojic.edu.co/[Politécnico Jaime Isaza Cadavid],
link:https://www.upb.edu.co/es/home[UPB],
link:http://www.uniminuto.edu/[Uniminuto Bogotá]

* *IT vendor enterprises:*
link:https://www.arus.com.co/[ARUS],
link:https://www.cadena.com.co/[Cadena],
link:https://www.choucairtesting.com/[Choucair Testing],
link:https://cidenet.com.co/[Cidenet],
link:http://www.cognox.com/[Cognox],
link:http://flypass.com.co/[Flypass],
link:http://gluky.com/[Gluky],
link:http://www.internexa.com/Paginas/Home.aspx[Internexa],
link:https://www.kometsales.com/[Komet Sales],
link:http://perceptio.co/[Perceptio],
link:http://www.mareigua.com/[Mareigua],
link:http://novit.pe/[NovitIT Peru],
link:https://seti.com.co/[SETI],
link:https://www.todo1services.com/[Todo1].

* *Open spaces:* link:https://www.rutanmedellin.org/es/[RutaN],
link:https://www.meetup.com/es/mde-devops[MeetUp-Medellin-DevOps].

We have given more than *35 conferences*
with a total of approximately *900 participants*
and an overall *satisfaction rate of 165%*.

== 4. Where?

The presentation can be hosted
at your company's facilities or an external venue.

The event can be held in Medellín with a minimum of `20` participants,
at least `10` of whom should be colleagues from one particular company.
For other cities in Colombia and Latin America
there must be one company which provides at least `20` of the participants.

== 5. Duration

The conference has a duration of `2` hours
(duration cannot be reduced).

== 6. When?

[button]#link:../#when[When]#

== 7. Audience

The conference is suitable for both technical and managerial personnel,
and the satisfaction rate for both profiles is equally high.
However, if you wish to promote new changes
and experimentation within your company,
it is important to include people with decision-making power.

The maximum number of attendees is defined according to the venue.
The conference has been given to groups of `20` people
and in auditoriums with over `80` people.

== 8. Speaker

[button]#link:../../people/ralvarez/[Rafael Alvarez]#

== 9. Videos

++++
<iframe width="560" height="315" src="https://www.youtube.com/embed/qKsz-nvgMrU" frameborder="0" allowfullscreen></iframe>
++++
