:slug: servicios/hacking-puntual/
:category: servicios
:description: En esta página presentamos nuestro servicio de Hacking Puntual, mediante el cual nuestro equipo de profesionales se encarga de encontrar y reportar todas las vulnerabilidades y hallazgos de seguridad existentes en la aplicación garantizando la ausencia de falsos positivos.
:keywords: Fluid Attacks, Servicios, Ethical Hacking, Seguridad, Aplicación, Hacking Puntual.

= Hacking Puntual

El Hacking puntual busca detectar y reportar todas las vulnerabilidades
y problemas de seguridad de una versión específica de un sistema.
La inspección rigurosa de nuestro equipo
permite detectar todos los hallazgos de seguridad sin falsos positivos.

[role="tb-alt"]
[cols=3, frame="topbot"]
|====

2+a|== Tipos de hacking
Es posible analizar código fuente,
aplicación e infraestructura correspondiente a un sistema específico,
el cliente puede decidir ejecutar todos los tipos de hacking,
o solo uno en específico.

a|image::tecnicas-hacking.svg[alt="Símbolo de código fuente"]

a|image::cobertura.svg[alt="Símbolo de código fuente con verificaciones exitosas"]

2+a|== Cobertura

La cobertura puede ser específica,
cuando se hace una enumeración del total de campos/lineas/puertos
que componen el sistema a probar
y se define posteriormente solo cubrir un porcentaje específico del mismo.

Puede ser variable cuando no se hace enumeración de tamaño del sistema
y se define un tamaño de hacking específico
sin saber a que porcentaje corresponde del total.

Puede ser completa cuando se enumeran
y prueban el total de campos/líneas/puertos que componen el sistema.

2+a|== Rigurosidad

Es posible que el cliente decida los requisitos de seguridad
que se revisarán en el hacking (perfilamiento)
a través de nuestro producto [button]#link:../../productos/rules/[Rules]#.

Además sabrá la rigurosidad exacta del hackeo (lo revisado y lo no revisado).

a|image::rigurosidad.svg[alt="Lista de revisiones"]

a|image::duracion.svg[alt="Reloj"]

2+a|== Duración específica

Dependiendo del tamaño de la superficie de ataque
del objetivo de evaluación.

2+a|== Ciclos de hacking

Al ser un proceso de hacking a una versión específica
solo se contará con un ciclo de hacking.

a|image::ciclos-inspeccion.svg[alt="Engranaje"]

a|image::seguimiento.svg[alt="Persona trabajando en un computador"]

2+a|== Seguimiento personalizado

Cada proyecto tiene asignado un +project manager+
a través del cual los clientes pueden gestionar todo lo necesario
antes, durante y después de la ejecución.

2+a|== Ejecución programada

Se acuerda una fecha de inicio y una fecha de fin
previa confirmación de los insumos necesarios para el inicio.

a|image::ejecucion-programada.svg[alt="Calendario"]

a|image::hacking-ambientes.svg[alt="Ambiente en un servidor"]

2+a|== Ambientes de hacking

Es posible elegir un único ambiente de hacking
entre producción, pruebas e integración.

2+a|== Equipo de hacking altamente calificado

Personal con certificaciones prácticas
y estudios relacionados en temas de seguridad,
realiza hacking manual y con herramientas
para garantizar el reporte de hallazgos de impacto específicos del negocio,
prácticas inseguras de programación, alineación a estándares
y regulaciones de seguridad sin falsos positivos,
posibilitando la detección de vulnerabilidades +Zero Day+.

a|image::equipo-entrenado.svg[alt="Equipo técnico"]

a|image::explotacion.svg[alt="Computador con un símbolo de un candado abierto"]

2+a|== Explotación de hallazgos

Siempre que se tenga acceso a la aplicación desplegada
y se cuente con autorización por parte del cliente
para la afectación de ambientes
usando nuestro motor de explotación propio [button]#link:../../productos/asserts/[Asserts]#.

2+a|== Extracción de información crítica

En los hallazgos donde es posible se extraen todos los registros comprometidos
con el fin de maximizar el impacto generado y comprometer información sensible.
[button]#link:../../productos/integrates/#registros-comprometidos[Ejemplo]#.

a|image::info-critica.svg[alt="Flechas saliendo de un candado"]

a|image::infeccion.svg[alt="Computador con un símbolo de un cráneo en frente"]

2+a|== Infección

De ser posible se compromete la infraestructura
con el uso de archivos maliciosos con el fin de obtener información adicional,
comprometer servidores y verificar controles a nivel de red.
Se hace uso de +shells+ y nuestro troyano personalizado
[button]#link:../../productos/commands/[Commands]#
con previa autorización por parte del cliente.

2+a|== Envío diario de informes de avance

Informes de avance diarios al correo electrónico
con estadísticas de cobertura, rigurosidad,
resultados parciales y avance ponderado.

a|image::reporte-avance.svg[alt="Carta dentro de un sobre"]

a|image::seguimiento-hallazgo.svg[alt="Gráfica de barra con una línea continua encima"]

2+a|== Seguimiento de hallazgos a través de Integrates

Durante la ejecución del proyecto es posible verificar
los hallazgos reportados en nuestra plataforma
[button]#link:../../productos/integrates/[Integrates]#.

2+a|== Soporte de remediación.

Durante el proyecto es posible solicitar aclaraciones
directamente a los hackers mediante
[button]#link:../../productos/integrates/[Integrates]#.

Es posible utilizar nuestras guias detalladas de remediación
mediante [button]#link:../../productos/defends/[Defends]#.

a|image::remediacion.svg[alt="Símbolo de pregunta y respuesta"]

a|image::entrega-reporte.svg[alt="Computador protegido por contraseña"]

2+a|== Entrega de informes vía bóveda segura

Entrega de versión definitiva de informes con evidencias
a través de un sitio de transferencia de archivos.

2+a|== Reunión de validación

Reunión con el equipo técnico
para validar los informes y atender observaciones.
La reunión se realiza de manera virtual.

a|image::reunion-validacion.svg[alt="Dos personas teniendo una conversación"]

a|image::presentacion-reporte.svg[alt="Gráfico de barras en una presentación"]

2+a|== Reunión de entrega

Presentación formal de informes ejecutivos a todos los interesados.
Consta de dos reuniones: una de validación y una de socialización general.

2+a|== Borrado seguro de información

+7+ días hábiles luego de la aprobación final de los informes
se borra toda la información de nuestros sistemas

a|image::borrado-seguro.svg[alt="Caneca de basura con una nube detrás"]

a|image::validar-remediacion.svg[alt="Lista de pendientes"]

2+a|== Verificación de cierre (Opcional)

Se realiza un único ciclo validación de estado de los hallazgos
hasta +3+ meses luego de la aprobación final de los informes iniciales,
para esto es necesario que el cliente
comparta nuevamente los informes iniciales
y garantice el acceso al ambiente de hacking.
No se buscan nuevas vulnerabilidades,
solo se valida el cierre efectivo de lo ya encontrado previamente.

|====

* Si desea conocer las diferencias entre nuestros servicios
y otros proveedores puede conocer nuestros diferenciadores
[button]#link:../diferenciadores/[aquí]#.

* Si desea conocer las diferencias entre nuestros servicios
puede ver nuestra tabla comparativa
[button]#link:../comparativo/[aquí]#.
