:slug: rules/177/
:category: data
:description: This document contains the details of the security requirements related to the definition and management of sensitive information in the organization. This requirement establishes the importance of storing sensitive data securely, avoiding temporary files and cache memory.
:keywords: Data, Storage, Cache, ASVS, CWE, GDPR
:rules: yes

= REQ.177 Avoid caching and temporary files

== Requirement

The system must not store sensitive information
in temporary files or cache memory.

== Description

Applications sometimes reside in or get consumed by environments in which
caching is possible.
Caching helps performance or makes certain actions more comfortable for the
application users.
However, cached information is often more susceptible to being exposed or
corrupted.
Thus, avoiding cache memory and temporary files helps protect sensitive
information.

== Findings

* [inner]#link:/web/findings/019/[F019. Administrative credentials stored in cache memory]#

* [inner]#link:/web/findings/028/[F028. Insecure temporary files]#

* [inner]#link:/web/findings/038/[F038. Business information leak]#

* [inner]#link:/web/findings/065/[F065. Cached form fields]#

* [inner]#link:/web/findings/085/[F085. Sensitive data stored in the client-side storage]#

== References

. [[r1]] link:https://cwe.mitre.org/data/definitions/524.html[CWE-524: Use of Cache Containing Sensitive Information]
The code uses a cache that contains sensitive information,
but the cache can be read by an actor outside of the intended control sphere.

. [[r2]] link:https://cwe.mitre.org/data/definitions/525.html[CWE-525: Use of Web Browser Cache Containing Sensitive Information]
The web application does not use an appropriate caching policy that specifies
the extent to which each web page and associated form fields should be cached.

. [[r3]] link:https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:02002L0058-20091219[Directive 2002/58/EC (amended by E-privacy Directive 2009/136/EC).
Art. 4: Security of processing.(1a)]
The measures referred to in paragraph 1 shall at least protect personal data
stored or transmitted against accidental or unlawful destruction,
accidental loss or alteration,
and unauthorized or unlawful storage, processing, access or disclosure.

. [[r4]] link:https://gdpr-info.eu/art-5-gdpr/[GDPR. Art. 5: Principles relating to processing of personal data.(1)(f).]
Personal data shall be processed in a manner that ensures appropriate security
of the personal data,
including protection against unauthorized or unlawful processing and against
accidental loss, destruction or damage.

. [[r5]] link:https://owasp.org/www-project-application-security-verification-standard/[OWASP-ASVS v4.0.1
V8.1 General Data Protection.(8.1.1)]
Verify the application protects sensitive data from being cached in server
components such as load balancers and application caches.

. [[r6]] link:https://owasp.org/www-project-application-security-verification-standard/[OWASP-ASVS v4.0.1
V8.1 General Data Protection.(8.1.2)]
Verify that all cached or temporary copies of sensitive data stored on the
server are protected from unauthorized access or purged/invalidated after the
authorized user accesses the sensitive data.

. [[r7]] link:https://owasp.org/www-project-application-security-verification-standard/[OWASP-ASVS v4.0.1
V8.2 Client-side Data Protection.(8.2.1)]
Verify the application sets sufficient anti-caching headers so that sensitive
data is not cached in modern browsers.

. [[r8]] link:https://owasp.org/www-project-application-security-verification-standard/[OWASP-ASVS v4.0.1
V8.2 Client-side Data Protection.(8.2.2)]
Verify that data stored in client side storage (such as HTML5 local storage,
session storage, IndexedDB, regular cookies or Flash cookies) does not contain
sensitive data or PII.
