:slug: rules/177/
:category: data
:description: This document contains the details of the security requirements related to the definition and management of sensitive information in the organization. This requirement establishes the importance of storing sensitive data securely, avoiding temporary files and cache memory.
:keywords: Requirement, Security, Data, Storage, GDPR, Cache
:rules: yes

= REQ.177 Avoid caching and temporary files

== Requirement

The system must not store sensitive information
in temporary files or cache memory.

== Description

Applications sometimes reside in or get consumed by environments in which
caching is possible.
Caching helps performance or makes certain actions more comfortable for the
application users.
However, cached information is often more susceptible to being exposed or
corrupted.
Thus, avoiding cache memory and temporary files helps protect sensitive
information.

== Findings

* link:/web/findings/019/[F019. Administrative credentials stored in cache memory]

* link:/web/findings/038/[F038. Business information leak]

* link:/web/findings/065/[F065. Cached form fields]

* link:/web/findings/085/[F085. Sensitive information stored in the local storage]

== References

. [[r1]] link:https://gdpr-info.eu/art-5-gdpr/[GDPR. Art. 5: Principles relating to processing of personal data.(1)(f).]
Personal data shall be processed in a manner that ensures appropriate security
of the personal data,
including protection against unauthorised or unlawful processing and against
accidental loss, destruction or damage.

. [[r2]] link:https://www.owasp.org/index.php/ASVS_V9_Data_Protection[+OWASP-ASVS v3.1-9.1+]
Verify that all forms containing sensitive information
have disabled client side caching, including autocomplete features.
