:slug: defends/java/almacenar-sesion-servlet/
:category: java
:description: Nuestros ethical hackers explican cómo evitar vulnerabilidades de seguridad mediante la programación segura en Java al almacenar el estado de sesión utilizando Servlets. Las sesiones son frecuentemente utilizadas ya que permiten guardar información accesible en diferentes páginas web.
:keywords: Java, Seguridad, Estado , Sesión, Estándar empresarial, Servlets.
:defends: yes

= Almacenar Estado de Sesión en Capa Web con Servlets

== Necesidad

Almacenar estado de sesión en la capa web con +Servlets+.

== Contexto

A continuación se describen las circunstancias
bajo las cuales la siguiente solución tiene sentido:

. Se dispone de una aplicación web
construida acorde al estándar empresarial de +Java+ o +JEE+.

. Se dispone de un servidor de aplicaciones
el cual soporta el estándar empresarial de +Java+.

. Se requiere evitar el envió de información
entre páginas a través de parámetros de la +URL+.

. Se conoce como hacer una aplicación usando +Servlets+.

== Solución

La conexión que se establece entre un usuario
y un servidor Web se denomina sesión.
Las sesiones permiten almacenar información
a lo largo de diferentes páginas,
permitiendo acceder a ella en el momento que se requiera.
Dentro de las sesiones es posible
guardar cierta información la primera vez que el usuario visita la página,
y dicha información puede ser mostrada en una visita posterior
sin necesidad de interactuar con una base de datos o un archivo externo.
Como estas sesiones son manejadas por lado del servidor,
no se corre el riesgo de que el usuario las pueda alterar.
Por lo general, dicha información contiene los datos del usuario,
y el estado de las diferentes operaciones
que el usuario realiza en la aplicación.
En otras palabras, una sesión puede abarcar múltiples páginas Web
y su seguimiento se realizará mediante la administración del estado
sin que el usuario tenga que intervenir en ello.

La administración del estado es el proceso por el cual
se mantiene la misma información a través de múltiples peticiones
para las mismas o distintas páginas web.

En esta solución se explorará la manera de almacenar
el estado de una sesión usando +Servlets+.

. Lo primero que hay que hacer es recuperar una sesión existente.
+
.sesion.java
[source, java, linenums]
----
HttpSession session = request.getSession();
HttpSession session = request.getSession(false);
----

. En caso de que  la sesión aún no exista,
esta se debe de crear.
+
[source, java, linenums]
----
HttpSession session = request.getSession();
HttpSession session = request.getSession(true);
----

. Una vez recuperada o creada la sesión,
es posible ingresar la información
que se requiere que persista
a través de todas las páginas
de la aplicación.

. Lo anterior se hace usando +session.setAttribute+.
+
[source, java, linenums]
----
String par1 = request.getParameter("par1");
session.setAttribute("par1", par1);
----

. Es posible recuperar la información
en cualquier momento,
siempre que la sesión permanezca activa.

. Se debe usar +session.getAttribute+
para recuperar la información.
+
[source, java, linenums]
----
String par1 = session.getAttribute("par1");
----

. Por último, una vez se termina de trabajar con la sesión
esta debe ser destruida
+
[source, java, linenums]
----
session.invalidate();
----

== Referencias

. [[r1]] link:https://tomcat.apache.org/tomcat-5.5-doc/servletapi/javax/servlet/http/HttpSession.html[Interface HttpSession]
. [[r2]] link:https://www.ibm.com/support/knowledgecenter/es/SSEQTP_8.5.5/com.ibm.websphere.base.doc/ae/tprs_sesi.html[Desarrollo de la gestión de sesiones en servlets]
. [[r3]] link:../../../rules/024/[REQ.024 Transferir información con objetos de sesión]
