{ path
, integratesPkgs
, ...
} @ _:
let
  buildPythonRequirements = import (path "/makes/utils/build-python-requirements") path integratesPkgs;
  makeTemplate = import (path "/makes/utils/make-template") path integratesPkgs;
in
makeTemplate {
  arguments = {
    envPythonRequirements = buildPythonRequirements {
      dependencies = [ ];
      name = "integrates-back-development";
      requirements = {
        direct = [
          "aniso8601==8.0.0"
          "attrs==19.3.0"
          "boto3-stubs==1.13.25.0"
          "cloudmersive-virus-api-client==2.0.6"
          "codecov==2.1.4"
          "freezegun==0.3.15"
          "GitPython==3.1.3"
          "gunicorn==20.0.4"
          "lxml==4.5.2"
          "mandrill-really-maintained==1.2.4"
          "moto==1.3.14"
          "mypy-extensions==0.4.3"
          "mypy==0.780"
          "prospector[with_everything]==1.2.0"
          "PyExcelerate==0.9.0"
          "pyotp==2.3.0"
          "pytest-asyncio==0.12.0"
          "pytest-cov==2.9.0"
          "pytest-rerunfailures==9.0"
          "pytest-test-groups==1.0.3"
          "pytest-xdist==1.32.0"
          "pytest==5.4.1"
          "uvicorn==0.11.5"
        ];
        inherited = [
          "apipkg==1.5"
          "astroid==2.3.3"
          "aws-sam-translator==1.34.0"
          "aws-xray-sdk==2.6.0"
          "bandit==1.7.0"
          "boto3==1.16.63"
          "boto==2.49.0"
          "botocore==1.19.63"
          "certifi==2020.12.5"
          "cffi==1.14.4"
          "cfn-lint==0.44.5"
          "chardet==4.0.0"
          "click==7.1.2"
          "coverage==5.4"
          "coveralls==3.0.0"
          "cryptography==3.3.1"
          "decorator==4.4.2"
          "docker==4.4.1"
          "docopt==0.6.2"
          "docutils==0.16"
          "dodgy==0.2.1"
          "ecdsa==0.16.1"
          "execnet==1.8.0"
          "frosted==1.4.1"
          "future==0.18.2"
          "gitdb==4.0.5"
          "h11==0.9.0"
          "httptools==0.1.1"
          "idna==2.8"
          "importlib-metadata==3.4.0"
          "isort==4.3.21"
          "Jinja2==2.11.3"
          "jmespath==0.10.0"
          "jsondiff==1.1.2"
          "jsonpatch==1.28"
          "jsonpickle==1.5.1"
          "jsonpointer==2.0"
          "jsonschema==3.2.0"
          "junit-xml==1.9"
          "lazy-object-proxy==1.4.3"
          "MarkupSafe==1.1.1"
          "mccabe==0.6.1"
          "mock==4.0.3"
          "more-itertools==8.6.0"
          "mypy-boto3==1.13.25.0"
          "networkx==2.5"
          "nose==1.3.7"
          "packaging==20.9"
          "pbr==5.5.1"
          "pep8-naming==0.4.1"
          "pies==2.6.7"
          "pluggy==0.13.1"
          "py==1.10.0"
          "pyasn1==0.4.8"
          "pycodestyle==2.4.0"
          "pycparser==2.20"
          "pydocstyle==5.1.1"
          "pyflakes==2.1.1"
          "Pygments==2.7.4"
          "pylint-celery==0.3"
          "pylint-django==2.0.12"
          "pylint-flask==0.6"
          "pylint-plugin-utils==0.6"
          "pylint==2.4.4"
          "pyparsing==2.4.7"
          "pyroma==2.6"
          "pyrsistent==0.17.3"
          "pytest-forked==1.3.0"
          "python-dateutil==2.8.1"
          "python-jose==3.2.0"
          "pytz==2021.1"
          "PyYAML==5.4.1"
          "requests==2.25.1"
          "requirements-detector==0.7"
          "responses==0.12.1"
          "rsa==4.7"
          "s3transfer==0.3.4"
          "setoptconf==0.2.0"
          "six==1.15.0"
          "smmap==3.0.5"
          "snowballstemmer==2.1.0"
          "sshpubkeys==3.3.0"
          "stevedore==3.3.0"
          "typed-ast==1.4.2"
          "typing-extensions==3.7.4.3"
          "urllib3==1.26.3"
          "uvloop==0.14.0"
          "vulture==0.24"
          "wcwidth==0.2.5"
          "websocket-client==0.57.0"
          "websockets==8.1"
          "Werkzeug==1.0.1"
          "wrapt==1.12.1"
          "xmltodict==0.12.0"
          "zipp==3.4.0"
        ];
      };
      python = integratesPkgs.python37;
    };
    envPythonUtils = path "/makes/utils/python/template.sh";
  };
  name = "integrates-back-config-development";
  template = path "/makes/packages/integrates/back/config/development/template.sh";
}
