:slug: products/rules/list/346/
:category: cryptography
:description: This requirement establishes the importance not reusing nonces and initialization vectors.
:keywords: Nonce, Initialization, Vector, Encryption, CWE, ASVS
:rules: yes

= R346. Use initialization vectors once

== Requirement

The system should use initialization vectors, nonces and other single use
numbers only once with a given encryption key.

== Descriptions

System cryptographic keys are essential for maintaining the confidentiality
and integrity of transactions and communications.
Some encryption mechanisms use initialization vectors to reduce the chances
that a message will be decrypted.
These vectors should be generated using cryptographically secure random number
generators and should only be used once with a given encryption key.

== References

. [[r1]] link:https://cwe.mitre.org/data/definitions/326.html[CWE-326: Inadequate Encryption Strength]
The software stores or transmits sensitive data using an encryption scheme that
is theoretically sound,
but is not strong enough for the level of protection required.

. [[r2]] link:https://cwe.mitre.org/data/definitions/330.html[CWE-330: Use of Insufficiently Random Values]
The software uses insufficiently random numbers or values in a security context
that depends on unpredictable numbers.

. [[r3]] link:https://owasp.org/www-project-application-security-verification-standard/[OWASP-ASVS v4.0.1
V6.2 Algorithms.(6.2.6)]
Verify that nonces, initialization vectors, and other single use numbers must
not be used more than once with a given encryption key.
The method of generation must be appropriate for the algorithm being used.

. [[r4]] link:https://owasp.org/www-project-application-security-verification-standard/[OWASP-ASVS v4.0.1
V6.3 Random Values.(6.3.1)]
Verify that all random numbers, random file names, random **GUID**s, and random
strings are generated using the cryptographic module's approved
cryptographically secure random number generator when these random values are
intended to be not guessable by an attacker.
