:slug: defends/programacion/manejar-bitacoras/
:category: programacion
:description: Nuestros ethical hackers explican que son las bitácoras y porque es importante usarlas en el proceso de creación y puesta en marcha de un sistema de información. Además, mencionan algunas reglas que se deben tener en cuenta al momento de su creación.
:keywords: Programacion, Bitacoras, Logs, Eventos, Seguridad, Error.
:defends: yes

= Buenas Prácticas en el Manejo de Bitácoras

== Necesidad

Identificar buenas prácticas de programación
relacionadas con las bitácoras de una aplicación.

== Contexto

A continuación se describen las circunstancias
bajo las cuales la siguiente solución tiene sentido:

. Se tiene una aplicación web de la cual
se desea controlar el uso de bitácoras de una manera correcta.

== Solución

Una bitácora o +log+ es una grabación secuencial en un archivo
o en una base de datos de todos los acontecimientos
es decir, los eventos o las acciones
que afectan a un proceso particular.
Tales eventos pueden ser;
cambio de los datos en una aplicación, actividad de una red,
acceso a un sistema de información autorizado o no, entre otros.
De esta forma constituye una evidencia
del comportamiento del sistema ^<<r1,[1]>>^.

Generalmente los acontecimientos vienen anotados
con el momento exacto o +data+ (fecha, hora, minuto, segundo)
en el que ocurrió, lo que permite analizar paso a paso
la actividad presentada permitiendo,
de esta forma, realizar
un seguimiento casi exacto de dicho acontecimiento.
Además, una o más categorizaciones del acontecimiento registrado.
Es frecuente usar categorías distintas
para distinguir la importancia del acontecimiento
estableciendo distintos niveles de registro
los cuales suelen ser: depuración, información, advertencia y error.

El uso de bitácoras puede servir para:

* Análisis forense.
* Detección de intrusos.
* Depuración de errores.
* Motorización.
* Cumplir con las leyes establecidas.
* Auditoría.

Por otro lado, los +logs+ pueden contener información confidencial
que no debe ser revelada por privacidad e incluso seguridad del sistema.
En estos casos es necesaria proteger la confidencialidad de la información
haciendo uso de métodos de cifrado y demás.

Por lo tanto, cuando esté generando bitácoras de una aplicación
es necesario tener en cuenta los siguientes lineamientos:

. Deben proveer registro individual de todos los eventos.

. Deben proveer introspección acerca del uso de la aplicación web.

. Deben ayudar a determinar acciones sospechosas sobre la aplicación.

. Se debe poder reconstruir una secuencia de eventos
después de un incidente de seguridad,
llevando a la identificación del culpable.

. Deben ser útiles en un proceso legal para probar malas intenciones.

. Deben ser difícilmente modificables,
además debe existir una copia confiable
centralizada de eventos de bitácora.

== Referencias

. [[r1]] link:https://es.wikipedia.org/wiki/Log_(inform%C3%A1tica)[Log (informática)]
. [[r2]] link:http://www.manageengine.com.mx/Blog/8-habitos-efectivos-para-la-gestion-de-bitacoras-de-ti.html[8 Hábitos Efectivos para la Gestión de Bitácoras de TI]
. [[r3]] link:../../../rules/075/[REQ.075 Registrar eventos en bitácoras]
