:slug: rules/008/
:category: rules
:description: This document contains the details of the security requirements related to a company's information assets. This requirement sets the importance of defining a system threat model covering STRIDE (Spoofing, Tampering, Repudiation, Information Disclosure, Denial of Service, Elevation of Privilege).
:keywords: Requirement, Security, Information, Assets, Threat Model, STRIDE
:rules: yes
:translate: rules/008/

= REQ.008 Generate system threat model

== Requirement

The organization must generate a threat model for the system,
identifying all potential threats and covering +STRIDE+
(Spoofing, Tampering, Repudiation, Information Disclosure,
Denial of Service, Elevation of Privilege).

== References

. [[r1]] link:https://www.law.cornell.edu/cfr/text/45/164.308[+HIPAA Security Rules+ 164.308(a)(1)(ii)(A):]
Risk Analysis: Conduct an accurate and thorough assessment
of the potential risks and vulnerabilities to the confidentiality,
integrity, and availability of electronic protected health information
held by the covered entity.

. [[r2]] link:https://www.law.cornell.edu/cfr/text/45/164.310[+HIPAA Security Rules+ 164.310(a)(2)(ii):]
Facility Security Plan: Implement policies and procedures
to safeguard the facility and the equipment therein
from unauthorized physical access, tampering, and theft.
