:slug: careers/faq/
:category: careers
:description: The main goal of the following page is to inform potential talents and people interested in working with us about our selection process. Here we present a Frequently Asked Questions (FAQ) section which intends to guide our candidates through the selection process.
:keywords: Fluid Attacks, Careers, Selection, Process, FAQ, Questions.

= Frequently Asked Questions (FAQ)

If you have a question about the selection process,
please read through the FAQ list before you contact us.
You might find the answer to your question is already here.

== Before Entering

[qanda]

*I already applied in a job portal.*::
*Why haven't I been invited to the process?*::
  After you apply to a vacancy
  listed on any of the portals we are registered in,
  it takes from +1+ to +2+ days for us to identify potential candidates,
  classify them, and send invitations via email.
  If you apply and have not received an invitation
  or other notification after 2 consecutive business days,
  and you believe your profile fits the vacancy,
  send us an email query at careers@autonomicmind.com.

*The test application won't allow me to exit Moodle. What should I do?*::
  If you already finished the exam,
  click the button located on the lower right side of the screen to exit.
  If this doesn’t work, try restarting your machine.
  Don’t worry, you have already sent the test
  and there won’t be any data loss.

*I don't have a RUT. How can I complete the third party form?*::
  On the link:http://www.dian.gov.co/contenidos/servicios/rut.html[+DIAN+ webpage]
  you can find out how to get your +RUT+, or how to update it,
  if you already have one.

*I don’t know what vacancy I applied for. How can I find out?*::
  Ask us via email at careers@autonomicmind.com.

*If I already applied for a specific vacancy, can I apply again*::
*using the same application but for different vacancies?*::
  Yes. If it has not been more than six months,
  you can send us an email at career@autonomicmind.com
  telling us you want to apply for a different vacancy
  using your original application.
  If it has been more than six months since your last application
  you cannot use your original application;
  you must apply again starting at the beginning.

*Can I apply for two different vacancies at the same time?*::
  Yes. You can apply for as many vacancies as you believe you qualify for;
  just send us an email via careers@autonomicmind.com
  telling us which vacancies you want to apply for.

*What experience should I already have in order to apply for vacancies?*::
  You don’t need to have any experience.
  What is essential is the ability to do research,
  solve issues, and be capable of teaching yourself.

*What do I need to know to apply for vacancies?*::
  We look for talented people with great potential and flexibility.
  It doesn’t matter what your career currently is
  or if you haven’t graduated yet.
  What matters is your ability to adapt and follow our philosophy and values.
  It is preferable if you have experience with programming languages,
  but it is not mandatory.
  We value your ability to successfully address a problem,
  more than your professional degrees.
  Our selection process is designed to encourage you
  to acquire knowledge yourself and then use it to problem-solve.

*Does the company offer on-the-job training??*::
  At +Fluid Attacks+ we do not require work experience,
  nor do we certify the knowledge you acquire while working with us.
  We do not offer on-the-job training.
  It is up to you to acquire the knowledge you may need
  and have the ability and the capability to overcome technical challenges
  and successfully complete the immersion stages.
  We evaluate all your abilities, including the attitude,
  perseverance, and productivity you exhibit during the selection process
  since all of these are necessary for any role in our organization.

*The application test doesn’t work. What should I do?*::
  Try executing the test as an administrator.
  If the problem persists,
  you should try accessing the test from a different computer.
  If you still have problems send us an email via careers@autonomicmind.com.

*I didn’t receive the attached file for data analysis. How do I get it?*::
  Try downloading the file from [button]#link:../non-technical-challenges/hallazgos-open-data.tar.bz2[here]#.

*I ran out of time for the test. Can I get more time?*::
   If you have a valid reason
   (application lockouts, unexpected restarts, connection issues),
   send us an email at careers@autonomicmind.com
   explaining what happened
   and we will tell you how to proceed.

*I couldn’t send my data analysis. What should I do?*::
  If you believe you have a valid reason
  for not meeting the data analysis deadline,
  send us an email at careers@autonomicmind.com
  telling us why you didn't meet it,
  and ask for a new delivery date.

*What should I put in my portfolio?*::
  You can find instructions and
  advice for creating your portfolio [button]#link:../portfolio/[here]#.

*I do not have a VISA. What should I put in that field?*::
  This field is not mandatory.
  Do not fill it in if you don’t have a +VISA+.

*What should I do after finishing the character test?*::
  When you finish this test,
  you can proceed with the next stage (knowledge test).
  We will send your result via email moments after.

*Do I have to present the polygraph test?*::
  In most cases, this test is not mandatory
  during the selection process.
  However, since our main business is the information security,
  it may be necessary to complete this test
  depending on your selection process.

*Do I have to present the Gallup test?*::
  This test only is required in some cases,
  therefore, please notify us via email
  when you reach this stage,
  and we will indicate you how to proceed.

*Does this process perform any risk analysis with my data?*::
  Yes, in the stage previous to the hiring,
  a confirmation is made on the risk central
  about the candidate data, among other references.

*I haven't notified my company about my current selection process,*::
*is the reverse references stage mandatory?*::
  Yes, it is mandatory and since it's an advanced stage
  in the selection process
  it is necessary for all the parties
  to have clear expectations.

*I'm very shy to present in public,*::
*is it mandatory to perform the audition?*::
  This stage is optional during the selection process.
  However, you must consider that in +Fluid Attacks+
  keeping good communication is essential,
  no matter the role to fulfill.

*Is it mandatory to complete all the stages of the process?*::
  Depending on the vacancy you applied for,
  and your selection process,
  we will indicate you how to proceed.

*What does offer validity time mean?*::
  It is the time during which +Fluid Attacks+ can hold up the offer.
  If during this time, we don't receive
  the explicit and written acceptance of the talent,
  the offer will become invalid.
  The purpose of this measure is to give other candidates
  in the selection process the possibility to be hired
  as soon as possible.

*If I do not accept the offer, what happens with my immersion process?*::
  The immersion ends immediately.
  +Fluid Attacks+ will remove the access to the training systems
  and will send you the time report of the hours
  pending to be charged in your billing statement.

== After Entering

+Fluid Attacks+ is a company focused and specialized in +Red Team+ testing.
We aim information security concepts towards an offensive approach,
looking for all the vulnerabilities and reporting them
as soon as possible.
Below we list some Frequently Asked Questions (+FAQ+)
presented when the talent is hired
and is part of our work team:

[qanda]

*What are the responsibilities of my role?*::
  +Fluid Attacks+ seeks to be agile and flexible,
  capable of adapting to changes at high speed.
  To accomplish this goal, we have decided to keep
  a work team below +50+ persons.
  In addition to that,
  we require generic roles and a lot of team work,
  which allows co-workers to complement each other's weaknesses.
  Because of this, each profile is grouped
  in any of these +2+ kind of roles: technical and non-technical.
  +
  * In technical roles, the responsibilities typically are:
  hacking systems, audit source code, develop attack exploits,
  develop tools for hackers, document found vulnerabilities,
  configure infrastructure as code, perform peer review,
  present reports to the customers,
  spread knowledge among customers and co-workers,
  migration of obsolete information and creation of new information,
  among others.
  +
  +
  * Non-technical roles comprise responsibilities of:
  customer management, technical pre-sales, marketing,
  +Fluid Attacks+ representation in other companies,
  speakers for conferences or seminars,
  crisis management, among others.
  +
  In short, the responsibilities defined for each role
  are unknown, and we expect you to contribute
  to any aspect of the previous kind of roles,
  depending on the needs of the company.
  We truly appreciate high technical talents that,
  after fulfilling technical roles,
  gradually migrate to non-technical roles.

*What kind of contract does Fluid Attacks offer?*::
  In +Fluid Attacks+ we offer just one type of contract:
  Labour contract for an indefinite period,
  with all the benefits required by law
  and parafiscal contributions
  (healthcare, retirement fund, allowances, layoffs)
  all paid on the +100%+ of the salary.
  All the talents have the same type of contract no matter their role,
  the only change is the salary amount.

*Does the salary offer correspond to the amount deposited into my account?*::
  No, the salary offer corresponds to the gross salary.
  The net salary will depend on personal variables
  that the employer cannot define
  (such as contribution to retirement funds, housing interests,
  number of dependents, among others ).
  However, in the following [button]#link:http://www.elempleo.com/co/calculadora-salarial/[link]#
  you can simulate an approximated value for your net salary.
  Enter the proposed salary in the first field (+Salario+).
  And then press +Calcular+.
  In the monthly net compensation field,
  you will find an approximated value of the the money
  that you will receive monthly in your payroll account.

*Why is there a difference between the gross salary and the net salary?*::
  There are law deductions that the government makes to the employees.
  These values are fixed and neither the talent
  nor +Fluid Attacks+ may modify them.
  The only value to agree is the amount of the gross salary.

*Must the talent pay his/her own social security?*::
  No, the talent must not pay anything on his/her own.
  It is +Fluid Attacks+ who directly performs the deductions
  and makes the payment to the corresponding entities.
  (+EPS+, retirement funds, compensation funds, among others).
  +Fluid Attacks+ includes all benefits demanded by law
  in the 100% of the salary,
  ensuring that the talent must not perform additional payments
  to the deductions previously indicated.

*The offered salary may change?*::
  No. +Fluid Attacks+ respects the talent salary expectation,
  and do not question nor comment it.
  Any salary expectation is reasonable
  and may be based on salaries from other enterprises,
  on different sectors, business or funding models.
  Each salary offer made by +Fluid Attacks+
  is carefully assessed by a committee of +3+ and +5+ persons,
  seeking to guarantee the inner equality
  (employees with same performance and long term alignment
  have the same salary and the group salary can be maintained over time).
  For this reason, the salary offer you receive
  was evaluated taken those factors into account
  and a higher salary value implies to generate
  a promotion without fuhrer information.
  Thus, the value of each offer that +Fluid Attacks+
  sends is definitive and always express our best offer.
  We understand that sometimes those values
  may not compete with other enterprises,
  but we prefer to keep the inner equality
  instead of generating exceptional cases
  for external factors out of our control.
  We recommend you to keep reading to understand
  when and how +Fluid Attacks+ can increase your salary.

*Does the variable salary exist in Fluid Attacks?*::
  No, we don't use a variable salary schema for any person.
  Even in the commercial roles, this model is not applied.
  We consider that this practice individualize the enterprise,
  difficult the team work, increases the documentary management,
  discourage talents in crisis times
  and transmits the wrong message of focusing in the results
  instead of the process.

*What additional benefits do I have as employee?*::
  We don't have additional benefits such as gym,
  prepaid healthcare, days off for birthday or seniority,
  additional bonuses or food allowance.
  Our vision is to focus all our efforts in the salary,
  so each employee may invert it on his/her individual priorities:
  health, education, entertainment, food, traveling, etc.
  With this, we also seek to make a contribution to the retirement funds
  based on the +100%+ of your salary
  and to avoid decreasing the retirement savings
  by short term benefits.

*How does Fluid Attacks support the talent knowledge?*::
  With time and money:
  +
  * In time, all the effort you decide to devote into your training
  can be reported and hence, subject to compensation,
  in case of extra efforts on working days or dedication on weekends.
  +
  +
  * In money, for the acquisition of official material
  and sponsorship of the certification tests,
  through a condoned funding by permanence.

*Is it mandatory to certificate?*::
  No. It's a professional development mechanism
  that +Fluid Attacks+ offer to their talents.
  However, deciding to not taking the suggested certifications
  will always lead into talking about the long term alignment
  to search other possibles required roles
  that the talent may be interested in.
  In case of finding such alignment,
  the sponsored certification will change to the related role.
