:slug: careers/faq/
:category: careers
:description: The main goal of the following page is to inform potential talents and people interested in working with us about our selection process. Here we present a Frequently Asked Questions (FAQ) section which intends to guide our candidates through the selection process.
:keywords: Fluid Attacks, Careers, Selection, Process, FAQ, Questions.

= Frequently Asked Questions (FAQ)

If you have a question about the selection process,
please read through the FAQ list before you contact us.
You might find the answer to your question is already here.

== Before Entering

[qanda]

*I already applied in a job portal.*::
*Why haven't I been invited to the process?*::
  After you apply to a vacancy
  listed on any of the portals we are registered in,
  it takes from +1+ to +2+ days for us to identify potential candidates,
  classify them, and send invitations via email.
  If you apply and have not received an invitation
  or other notification after 2 consecutive business days,
  and you believe your profile fits the vacancy,
  send us an email query at careers@autonomicmind.com.

*The test application won't allow me to exit Moodle. What should I do?*::
  If you already finished the exam,
  click the button located on the lower right side of the screen to exit.
  If this doesn’t work, try restarting your machine.
  Don’t worry, you have already sent the test
  and there won’t be any data loss.

*I don't have a RUT. How can I complete the third party form?*::
  On the link:http://www.dian.gov.co/contenidos/servicios/rut.html[+DIAN+ webpage]
  you can find out how to get your +RUT+, or how to update it,
  if you already have one.

*I don’t know what vacancy I applied for. How can I find out?*::
  Ask us via email at careers@autonomicmind.com.

*If I already applied for a specific vacancy, can I apply again*::
*using the same application but for different vacancies?*::
  Yes. If it has not been more than six months,
  you can send us an email at career@autonomicmind.com
  telling us you want to apply for a different vacancy
  using your original application.
  If it has been more than six months since your last application
  you cannot use your original application;
  you must apply again starting at the beginning.

*Can I apply for two different vacancies at the same time?*::
  Yes. You can apply for as many vacancies as you believe you qualify for;
  just send us an email via careers@autonomicmind.com
  telling us which vacancies you want to apply for.

*What experience should I already have in order to apply for vacancies?*::
  You don’t need to have any experience.
  What is essential is the ability to do research,
  solve issues, and be capable of teaching yourself.

*What do I need to know to apply for vacancies?*::
  We look for talented people with great potential and flexibility.
  It doesn’t matter what your career currently is
  or if you haven’t graduated yet.
  What matters is your ability to adapt and follow our philosophy and values.
  It is preferable if you have experience with programming languages,
  but it is not mandatory.
  We value your ability to successfully address a problem,
  more than your professional degrees.
  Our selection process is designed to encourage you
  to acquire knowledge yourself and then use it to problem-solve.

*Does the company offer on-the-job training??*::
  At +Fluid Attacks+ we do not require work experience,
  nor do we certify the knowledge you acquire while working with us.
  We do not offer on-the-job training.
  It is up to you to acquire the knowledge you may need
  and have the ability and the capability to overcome technical challenges
  and successfully complete the immersion stages.
  We evaluate all your abilities, including the attitude,
  perseverance, and productivity you exhibit during the selection process
  since all of these are necessary for any role in our organization.

*The application test doesn’t work. What should I do?*::
  Try executing the test as an administrator.
  If the problem persists,
  you should try accessing the test from a different computer.
  If you still have problems send us an email via careers@autonomicmind.com.

*I didn’t receive the attached file for data analysis. How do I get it?*::
  Try downloading the file from [button]#link:../non-technical-challenges/hallazgos-open-data.tar.bz2[here]#.

*I ran out of time for the test. Can I get more time?*::
   If you have a valid reason
   (application lockouts, unexpected restarts, connection issues),
   send us an email at careers@autonomicmind.com
   explaining what happened
   and we will tell you how to proceed.

*I couldn’t send my data analysis. What should I do?*::
  If you believe you have a valid reason
  for not meeting the data analysis deadline,
  send us an email at careers@autonomicmind.com
  telling us why you didn't meet it,
  and ask for a new delivery date.

*What should I put in my portfolio?*::
  You can find instructions and
  advice for creating your portfolio [button]#link:../portfolio/[here]#.

*I do not have a VISA. What should I put in that field?*::
  This field is not mandatory.
  Do not fill it in if you don’t have a +VISA+.

*What should I do after I've finished the character test?*::
 Once the character test is completed,
 you will receive your test results within minutes.
 While you wait, we suggest you go to the next stage
 and begin the knowledge test.

*Do I have to take the polygraph test?*::
  In most cases, this test is not mandatory during the selection process.
  However, since our business is information security,
  it may be necessary for you to take this test
  depending on the position you are applying for.

*Do I have to take the Gallup test?*::
  This test is only required in certain cases.
  Please notify us via email when you reach this stage,
  and we will tell you whether or not you need to take it.

*Does this process perform a risk analysis with my data?*::
  Yes, in the stage before hiring,
  confirmation is made on the central risk
  concerning any of your candidate data.

*I haven’t notified my current employer that I am applying for a job*::
*with another company. Is the reverse references stage mandatory?*::
  Because this is an advanced stage in the selection process,
  yes, it is mandatory.

*I’m very shy when presenting in public.*::
*Is it mandatory to do the audition?*::
  During the selection process this stage is optional.
  However, if you work at +Fluid Attacks+,
  we expect you to have excellent communication skills,
  regardless of the position you are hired for.

*Is it mandatory to complete all of the stages in the process?*::
  Not necessarily.
  It depends on the vacancy you applied for and your selection process.
  We will tell you how to proceed,
  and as always, if you have any questions, contact us.

*What does "offer validity time" mean?*::
  It is the length of time +Fluid Attacks+
  will hold open a job offer made to a specific candidate.
  If during this time the candidate does not respond
  with explicit and written acceptance of the job offer,
  the offer will become invalid.
  Another candidate will then be offered the job.
  This allows us to fill vacancies as soon as possible.

*If I do not accept the offer, what happens to my immersion process?*::
  Your immersion process ends immediately.
  +Fluid Attacks+ will remove access to all training systems
  and notify you of the total work hours
  to be put on your monthly time-worked invoice.

== After Entering

+Fluid Attacks+ is a company focused and specialized in +Red Team+ testing.
We aim information security concepts towards an offensive approach,
looking for all the vulnerabilities and reporting them
as soon as possible.
Below we list some Frequently Asked Questions (+FAQ+)
presented when the talent is hired
and is part of our work team:

[qanda]

*What are the responsibilities of my role?*::
  +Fluid Attacks+ seeks to be agile and flexible,
  capable of adapting to changes at high speed.
  To accomplish this goal, we have decided to keep
  a work team below +50+ persons.
  In addition to that,
  we require generic roles and a lot of team work,
  which allows co-workers to complement each other's weaknesses.
  Because of this, each profile is grouped
  in any of these +2+ kind of roles: technical and non-technical.
  +
  * In technical roles, the responsibilities typically are:
  hacking systems, audit source code, develop attack exploits,
  develop tools for hackers, document found vulnerabilities,
  configure infrastructure as code, perform peer review,
  present reports to the customers,
  spread knowledge among customers and co-workers,
  migration of obsolete information and creation of new information,
  among others.
  +
  +
  * Non-technical roles comprise responsibilities of:
  customer management, technical pre-sales, marketing,
  +Fluid Attacks+ representation in other companies,
  speakers for conferences or seminars,
  crisis management, among others.
  +
  In short, the responsibilities defined for each role
  are unknown, and we expect you to contribute
  to any aspect of the previous kind of roles,
  depending on the needs of the company.
  We truly appreciate high technical talents that,
  after fulfilling technical roles,
  gradually migrate to non-technical roles.

*What kind of contract does Fluid Attacks offer?*::
  In +Fluid Attacks+ we offer just one type of contract:
  Labour contract for an indefinite period,
  with all the benefits required by law
  and parafiscal contributions
  (healthcare, retirement fund, allowances, layoffs)
  all paid on the +100%+ of the salary.
  All the talents have the same type of contract no matter their role,
  the only change is the salary amount.

*Does the salary offer correspond to the amount deposited into my account?*::
  No, the salary offer corresponds to the gross salary.
  The net salary will depend on personal variables
  that the employer cannot define
  (such as contribution to retirement funds, housing interests,
  number of dependents, among others ).
  However, in the following [button]#link:http://www.elempleo.com/co/calculadora-salarial/[link]#
  you can simulate an approximated value for your net salary.
  Enter the proposed salary in the first field (+Salario+).
  And then press +Calcular+.
  In the monthly net compensation field,
  you will find an approximated value of the the money
  that you will receive monthly in your payroll account.

*Why is there a difference between the gross salary and the net salary?*::
  There are law deductions that the government makes to the employees.
  These values are fixed and neither the talent
  nor +Fluid Attacks+ may modify them.
  The only value to agree is the amount of the gross salary.

*Must the talent pay his/her own social security?*::
  No, the talent must not pay anything on his/her own.
  It is +Fluid Attacks+ who directly performs the deductions
  and makes the payment to the corresponding entities.
  (+EPS+, retirement funds, compensation funds, among others).
  +Fluid Attacks+ includes all benefits demanded by law
  in the 100% of the salary,
  ensuring that the talent must not perform additional payments
  to the deductions previously indicated.

*The offered salary may change?*::
  No. +Fluid Attacks+ respects the talent salary expectation,
  and do not question nor comment it.
  Any salary expectation is reasonable
  and may be based on salaries from other enterprises,
  on different sectors, business or funding models.
  Each salary offer made by +Fluid Attacks+
  is carefully assessed by a committee of +3+ and +5+ persons,
  seeking to guarantee the inner equality
  (employees with same performance and long term alignment
  have the same salary and the group salary can be maintained over time).
  For this reason, the salary offer you receive
  was evaluated taken those factors into account
  and a higher salary value implies to generate
  a promotion without fuhrer information.
  Thus, the value of each offer that +Fluid Attacks+
  sends is definitive and always express our best offer.
  We understand that sometimes those values
  may not compete with other enterprises,
  but we prefer to keep the inner equality
  instead of generating exceptional cases
  for external factors out of our control.
  We recommend you to keep reading to understand
  when and how +Fluid Attacks+ can increase your salary.

*Does the variable salary exist in Fluid Attacks?*::
  No, we don't use a variable salary schema for any person.
  Even in the commercial roles, this model is not applied.
  We consider that this practice individualize the enterprise,
  difficult the team work, increases the documentary management,
  discourage talents in crisis times
  and transmits the wrong message of focusing in the results
  instead of the process.

*What additional benefits do I have as employee?*::
  We don't have additional benefits such as gym,
  prepaid healthcare, days off for birthday or seniority,
  additional bonuses or food allowance.
  Our vision is to focus all our efforts in the salary,
  so each employee may invert it on his/her individual priorities:
  health, education, entertainment, food, traveling, etc.
  With this, we also seek to make a contribution to the retirement funds
  based on the +100%+ of your salary
  and to avoid decreasing the retirement savings
  by short term benefits.

*How does Fluid Attacks support the talent knowledge?*::
  With time and money:
  +
  * In time, all the effort you decide to devote into your training
  can be reported and hence, subject to compensation,
  in case of extra efforts on working days or dedication on weekends.
  +
  +
  * In money, for the acquisition of official material
  and sponsorship of the certification tests,
  through a condoned funding by permanence.

*Is it mandatory to certificate?*::
  No. It's a professional development mechanism
  that +Fluid Attacks+ offer to their talents.
  However, deciding to not taking the suggested certifications
  will always lead into talking about the long term alignment
  to search other possibles required roles
  that the talent may be interested in.
  In case of finding such alignment,
  the sponsored certification will change to the related role.

*When it starts to run my certification time? Is it negotiable?*::
  It is not negotiable. All the certifications sponsored by +Fluid Attacks+
  follow the same funding model.
  However, this model allows certain variations.
  For example, the talent can decide to not certificate,
  or to pay the certifications or the materials on his/her own,
  and hence the funding is not entirely required.
  It is also possible to quit before +48+ months
  and the funding will be proportional.
  Finally, the certification and the acquired knowledge
  are an asset of the talent,
  and such asset will be lost
  in case the talent leaves the organization.

*What happens if I lose the certification test?*::
  Nothing happens if you lose the certification test
  unless you are not willing to keep trying.
  +Fluid Attacks+ encourage the process over the results.
  For this reason, as well as when the certification is obtained
  there is no salary adjustment,
  also there are no adverse effects when it's lost.
  +Fluid Attacks+ may sponsor the retest if you wish,
  and this cycle can be repeated indefinitely,
  as long as there are evidence of effort and dedication to obtain it
  (training time reports).
  We have people who have presented the same test for over +4+ times
  always with the sponsorship of +Fluid Attacks+.
  Finally if the talent doesn't approve the tests
  and doesn't wish to keep trying
  there would be a monthly salary deduction
  during the following +24+ months
  and in case of retreat this amount
  will be subtracted from the settlement pending balance.

*What is the exact amount of the certification funding?*::
  The exact value is known only during the purchase,
  because it varies depending on the certification,
  the components you want to cover (test or official material),
  price variations on the vendor side, among others.
  For reference purposes,
  there are certification from +300 USD+ up to +1000 USD+.

*How should I manage my time?*::
  Every talent should agree with their direct leader
  the personal reference schedules of +48+ hours per week
  from Monday to Friday, starting at +7 AM+.
  This reference schedule must intersect +75%+
  of our customers schedules (+7AM+ a +6PM+ COT).
  However, this schedule is a reference,
  you must take into account the timing of your duties,
  notifying in due time without asking permissions
  about the exceptions on your reference schedule.
  This grants you autonomy and freedom
  without paperwork when your role and compromises allow it.
  There are *zero tolerance* on failures to comply deadlines
  or third party meetings either with customers or coworkers.

*Can I adjust my schedule if I'm currently studying?*::
  In the framework of the previous answer, yes.

*How is it made the time report?*::
  We use a time report system called +TimeDoctor+
  which allows to track activities in real time,
  without additional efforts from the talent
  aside of the efforts dedicated to the customer and the project.
  This system logs all the activities performed by the talent
  while he/she is working,
  but it also can be disabled when the talent is not working
  and to perform personal activities.
  This allows us to keep a healthy balance between control and autonomy.
  There is no expected total working time share,
  we leave this value to the talent criteria.
  However in exceptional cases that a talent
  exceeds +48+ hours per week systematically,
  the organization unilaterally adjusts its assignments,
  in addition to granting compensatory days as soon as possible.

*Why is the reporting fee not 48h if the schedule is 48h?*::
  Because the reference schedule
  defines the availability expectation for the talent
  based on a focused dedication.
  We understand that each person has different work paces
  which may vary over weeks,
  for this reason,
  expecting a rigid dedication of +48+ hours per week is unrealistic.
  Additionally, our method for measuring the effort
  is very accurate and strict
  and hence we focus on reporting the reality.

*Is there a dress code in Fluid Attacks?*::
  We can execute projects on +Fluid Attacks+ facilities
  or in the customer facilities:
  +
  * When we attend to +Fluid Attacks+ facilities
  there is no dressing code.
  You may dress as comfortable as you want.
  +
  +
  * When we execute projects on the clients facilities
  we must know and comply with their dress code.

*Do I have to work on weekends or at night?*::
  It is not usual for the company to request for this situation.
  If it happens to occur is something exceptional.
  In order to assume the worst scenario,
  in a year we may ask you to work on +4+ weekends and +10+ nights.
  These values correspond to the company request
  and do not include the instances on which the talent
  have to work on weekends or nights in order to fulfill
  the schedule or the working fee.

*Where do I have to work?*::
  We can execute projects on +Fluid Attacks+ facilities
  or in the customer facilities.

*Does exist teleworking in Fluid Attacks?*::
  Teleworking doesn't exist as an alternative of on-site working.
  However, is it possible as an exception
  made to manage events of force majeure.

*Can I anticipate my vacations?*::
  In +Fluid Attacks+ you can anticipate your vacations
  even if you haven't finished your period.
  Vacations must be requested with minimum +30+ calendar days of anticipation,
  and will be assessed regarding other vacation applications
  requested before by other employees (+FIFO+).
  You have to consider that the minimum vacation term
  must be of +5+ days including weekends.
  If you have an exceptional event that you have to attend,
  you don't need to request vacations for that,
  it suffices to notify the corresponding exception.

*When do I get a salary revision?*::
  The salary can be reviewed under +3+ possible circumstances.
  The first, named yearly review, is mandatory
  and it occurs after +12+ months with the same salary.
  The second, named extemporaneous review, is optional
  and it occurs before +12+ months with the same salary.
  The third, named requested review,
  can be asked anytime by the talent.
  It is named requested review because the first two reviews
  are always made by +Fluid Attacks+
  without any request of the talent.

*What are the possible outcomes of a salary review?*::
  In any kind of review either yearly, extemporaneous or requested,
  there are only two possible outcomes:
  first, an inflation adjustment which results by determining
  that the current salary is appropriated
  and hence, the salary is not modified
  or it is slightly adjusted regarding the legal minimum wage
  of the previous year.
  The second, named re-scaling,
  results when the current salary must be adjusted to a higher scale.

*What factors determine my salary?*::
  The salary is determined by +3+ factors:
  historical performance, long term alignment, and group payment capacity.
  +
  * Historical performance corresponds to a constant value generation,
  in the framework of the company values and processes.
  +
  +
  * The long term alignment represents that your vision
  and +Fluid Attacks'+ vision are completely aligned,
  and hence your career scheme can be fully developed
  in long term inside the company.
  +
  +
  * The group payment capacity is an external factor
  which defines the capacity of +Fluid Attacks+
  to fulfill all the commitments on a long term.

*What factors DO NOT determine my salary?*::
  The salary is not affected by factors such as:
  academic level, certifications, seniority,
  experience inside and outside +Fluid Attacks+,
  hierarchy, previous salaries in different companies or salary expectations.
  The salary is only defined
  by the factors mentioned in the <<q25, previous question>>.
  This means that there could be hackers or programmers
  with higher salaries than their bosses,
  and people with basic education gaining more than people with master degrees.
  More certifications does not necessarily mean more salary,
  the salary is only increased if the historic performance
  and long term alignment is improved
  as a result of the new certifications
  and knowledge of the talent,
  and if +Fluid Attacks+ can afford such increase in long term.

*How Fluid Attacks determines the salary factors for a new talent?*::
  The historic performance and long term alignment for a new talent
  that has never worked for +Fluid Attacks+
  are defined by regarding his/her selection process.
  For this reason, this process is strict and rigorous.
  However there can be two posible failure scenarios:
  underestimation, in which case we perform extemporaneous salary reviews,
  or overestimation, which results only on inflation adjustments
  in yearly salary reviews.

*What would be my estimated salary after one year?*::
  <<q23,See question 23>>

*What are the available salary ranges?*::
  In +Fluid Attacks+ there are salaries from +$1.4M COP+ to +$14M COP+.
  For lower salaries there are more people in that range,
  for higher salaries there are less people.
  That means these values follow an exponential distribution.

*What does Fluid Attacks expect from a new talent?*::
  In +Fluid Attacks+ we have three immovable and non-negotiable link:../../values[values]:
  +
  * *HONESTY:* We expect the talent to stick strictly to our ethics code,
  to genuinely accept our working philosophy,
  always speaking with the *truth*,
  using the defined channels
  and in a prudent manner.
  We expect an immaculate care of +Fluid Attacks+ and customers
  confidential information,
  as well as a responsible use of the hacking knowledge.
  Do not hack without authorization, even outside +Fluid Attacks+.
  +
  +
  * *TEAM WORK:* We expect the talent to help his/her coworkers,
  either peers or leaders in the tasks they don't like
  but the work nature requires.
  to work in a dedicated and focused manner in the assigned projects,
  preferentially finishing them early without sacrificing the quality.
  +
  +
  * *DISCIPLINE:* We expect the talent to self-manage without a leader,
  to comply the deadlines without excuses,
  to arrive on time for commitments and meetings
  either with customers or coworkers,
  to send deliverables with zero adjustments,
  to voluntary involve and try to solve the issues affecting the company,
  and to self empower through new horizons to improve the company.
  +
  +
  Finally, we expect these expectations to be fully fulfilled always,
  and to increase the rigor on its application over time.

*What does Fluid Attacks expect technically from a new talent?*::
  As our motto says:
  *"Find all vulnerabilities and report them as soon as possible"*
  for that, we expect the talent to:
  +
  +
  * Program in a fancy, functional way.
  +
  +
  * Generate daily value in production deployments.
  +
  +
  * Search ways to make things work instead of making excuses
  to avoid doing them.
  +
  +
  * Hack the customer systems without being detected.
  +
  +
  * Extract as much information as possible from the customer systems
  to increase the awareness of the real impact of a vulnerability.
  +
  +
  * Document all vulnerabilities immediately after finding them.
  +
  +
  * Report all existing vulnerabilities.
  +
  +
  * Notify about the installed +backdoors+ and uninstall them
  after finished the project.
  +
  +
  * Hack as much systems as possible in the assigned time.
  +
  +
  * Find not evident and critical vulnerabilities.
  +
  +
  * Teach his/her coworkers the new hacking techniques
  without jealousy.
  +
  +
  * Make contributions to the company products.
  +
  +
  * Dedicate to his/her default activity when a lockout comes out
  (migration, product, blog articles, etc).
  +
  +
  * Search solutions on his/her own in a investigative manner.
  +
  +
  * Be willing to learn when a solution can't be found
  instead of expecting someone else to solve it.
  +
  +
  In general, we look for dedicated persons
  who are willing to share their knowledge
  and fulfill their roles with no excuses.

*Can I grow professionally in Fluid Attacks?*::
  In order to answer this question we classify
  growth in 3 aspects:
  power, knowledge, and money.
  +
  +
  * The power growth is usually low,
  since we do not aim to grow in workforce,
  but to have highly competitive products,
  and hence the managerial positions are opened
  only when there are personnel retirements.
  However, our current +CEO+ started as Support Engineer +10+ years ago.
  +
  +
  * We consider the knowledge growth is high,
  since we control the technologies we use (not the customer),
  we constantly update our tools
  because we audit many customers
  and hence we must learn the current and emergent technologies
  in a very short time.
  The projects are short and the learning is constant.
  In the security and hacking area
  we have the experience and the track record
  to consider us the biggest Hacking company in Latin America.
  +
  +
  * The money growth tends to be medium,
  first because the salary in +Fluid Attacks+
  is not only attached to the power (non-tecnical scale)
  but also to the knowledge (technical scale)
  and hence, is common to find engineers with higher salaries
  than their bosses (see <<q23, Question 23>>).

*Can my role evolve over time and according to*::
*the acquired knowledge and certifications?*::
  The seniority, certifications and knowledge
  don't guarantee the evolution of the role.
  One employee can play the same role for a long time,
  have many certifications,
  learn about many new technologies
  and nevertheless do not improve his/her performance,
  or use these factors to improve the company with dedication.
  For this reason, none of the previously mentioned variables
  can guarantee the evolution of the role.
  As an employee, you can evolve
  if your performance keeps improving every trimester,
  if you follow the defined process and deliver the best results consistently.

*How does Fluid Attacks recognize a performance that exceeds the expected?*::
  +Fluid Attacks+ has a simple philosophy regarding this aspect,
  the constant performance over the expected is rewarded
  through a salary re-scaling.
  The reward is more significant if it's made in a extemporaneous way
  (before +12+ months).
  This implies that the reward is always made in private
  and results in a higher standard for the future performance of te talent,
  and hence a new re-scaling will be more difficult to reach.

*If my salary is not re-scaled, am I doing something wrong?*::
  No. If in a yearly salary review there is no a re-scaling
  means that the assigned salary
  corresponds to the historical performance and long term alignment
  and is equivalent to the coworkers in the same variable range.
  The more time a talent spend with +Fluid Attacks+
  the more the salary converges to the possible salary ranges
  by all the salary re-scalings,
  and these in turn become less often.
  When a talent presents a higher salary range than his/her performance
  or the long term alignment is different from the company,
  we have a private conversation with the talent
  to implement an improvement plan
  which of not implementing in short term
  will result in the retirement of the talent from +Fluid Attacks+.
  If such conversation doesn't occur,
  means everything is going according to the planned.
