:slug: rules/023/
:category: rules
:description: En el presente documento se detallan los requerimientos de seguridad relacionados a la gestion de sesiones de usuarios de un sistema, estableciendo los lineamientos para determinar cuándo es necesario cerrar una sesión si existe inactividad por parte del usuario durante cierto periodo de tiempo.
:keywords: Requerimiento, Seguridad, Sesión de usuario, Cerrar sesión, Inactividad, Periodo de tiempo.
:rules: yes

= REQ.023 Cerrar sesión de un usuario inactivo

== Requisito

El sistema debe cerrar una sesión
si se presenta un tiempo de inactividad por parte del usuario,
superior o igual a `5` minutos.

== Descripción

Un sistema que cuente con autenticación e inicio de sesión
puede mantener la misma abierta por un tiempo indefinido
si no existe un control automático de cerrado de sesión
y el usuario no la cierra manualmente.
El no controlar los tiempos de cierre
puede permitir a un atacante
aprovechar sesiones desatendidas y ejecutar acciones
a nombre del usuario autenticado sin su autorización
y alterar información confidencial asociada a cuentas,
este riesgo puede aumentar su criticidad notablemente
si el sistema permite el ingreso a usuarios administradores
con privilegios altos, pues afectaría la integridad, confidencialidad
y disponibilidad del sistema, sus usuarios
y de la información que contiene.

== Implementación

. Fijar los tiempos de sesión:
Dependiendo de las necesidades del negocio
y/o de las políticas de manejo de sesiones de la compañía
se deben configurar los tiempos de finalización de sesiones desatendidas
a un tiempo prudencial (recomendado de `5` minutos o cercano).<<r1,^[1]^>>

== Ataques

. Un usuario empleado o anónimo
toma control de una cuenta desatendida
por otro usuario sin su autorización.^<<r2,[2]>>,<<r3,[3]>>^

. En un servidor `web` muchas sesiones abiertas durante un tiempo muy alto
obligan al servidor a consumir mucha memoria desplegando
y manteniendo los objetos de sesión.

== Atributos

. Capa: Capa de Aplicación
. Activo: Administración de sesiones
. Alcance: Adherencia
. Fase: Operación
. Tipo de Control: Procedimiento

== Referencias

. [[r1]] link:http://www.certicamara.com/download/correspondencia/20121005_Anexos_12_circular_042_de_2012.pdf[Capítulo Décimo Segundo: Requerimientos Mínimos de Seguridad y Calidad
para la Realización de Operaciones].

. [[r2]] link:https://pcinetwork.org/forum/index.php?threads/pci-dss-3-0-6-5-10-broken-authentication-and-session-management.667/[[PCI DSS 3.0\] 6.5.10 Broken authentication and session management].

. [[r3]] link:https://www.owasp.org/index.php/Top_10_2013-A2-Broken_Authentication_and_Session_Management[Top 10 2013-A2-Broken Authentication and Session Management].

. [[r4]] link:https://www.law.cornell.edu/cfr/text/45/164.312[`HIPAA Security Rules` 164.312(a)(2)(iii):]
Cierre de Sesión Automático: Implementar procedimientos electrónicos
que terminen una sesión después de un determinado tiempo de inactividad.

. [[r5]] link:https://www.owasp.org/index.php/ASVS_V3_Session_Management[`OWASP-ASVS v3.1-3.3`].
Verificar que las sesiones se cierren automáticamente
luego de un periodo de inactividad específico

. [[r6]] link:https://www.owasp.org/index.php/ASVS_V3_Session_Management[`OWASP-ASVS v3.1-3.4`].
Verificar que las sesiones se cierren automáticamente
luego de un tiempo administrativo configurable
sin importar si está activa.
(Vencimiento de sesión absoluto)

. [[r7]] link:https://nvd.nist.gov/800-53/Rev4/control/AC-12[`NIST` 800-53 AC-12]
Cierre de sesión: El sistema de información
debe terminar la sesión del usuario cuando se presente
una condición o evento definido por la organización
que requiera la terminación de la sesión.

. [[r8]] link:https://nvd.nist.gov/800-53/Rev4/control/IA-3[`NIST` 800-53 AC-2 (2)]
La organización requiere que el usuario termine la sesión
cuando se presente un periodo de inactividad definido
o un evento que requiera el cierre de sesión.

. [[r9]] link:https://www.bsimm.com/framework/governance/software-security-metrics-strategy.html[`BSSIM9` SM2.6:]
Requerir cierre de sesión de seguridad.
