:slug: kb/java/implementar-cifrado-simetrico/
:eth: no
:category: java
:description: TODO
:keywords: TODO
:kb: yes

= Implementar Cifrado Simétrico

== Necesidad

Criptografía simétrica en Java

== Contexto

A continuación se describen las circunstancias bajo las cuales la siguiente 
solución tiene sentido:

. Se dispone de un programa realizado en Java 1.4 o superior.

== Solución

Para cifrar, descifrar y crear la llave de cifrado, Java proporciona las clases 
Cipher, KeyGenerator y SecretKey del paquete javax.crypto . A continuación se 
enumeran las consideraciones que se deben tener en cuenta al momento de implementar el 
algoritmo de cifrado simétrico AES con un tamaño de clave de 256 bits:

. Cree una clase para encapsular los métodos de cifrado y descifrado
. Importe las clases Cipher, KeyGenerator y SecretKey del paquete javax.crypto.
+
.test.py
[source, java, linenums]
----
 import javax.crypto.Cipher;
 import javax.crypto.KeyGenerator;
 import javax.crypto.SecretKey;
----

. Cree el método para generar la llave privada con un tamaño de 256 bits.
+
[source, java, linenums]
----
 Cipher cipher = Cipher.getInstance(algorithm);
 String algorithm = "AES";
 KeyGenerator kgen = KeyGenerator.getInstance(algorithm);
 //Para establecer un tamaño de clave de 128 bits se debe cambiar este valor
 kgen.init(256);
 SecretKey key = kgen.generateKey();
 cipher.init(Cipher.ENCRYPT_MODE, key);
 byte[] cipherText = cipher.doFinal(secret.getBytes());
----
 
. Cree un objeto Cipher que referencie a un algoritmo de cifrado simétrico, para 
este caso se va hacer refencia al algoritmo AES. En el caso en que se desee 
utilizar el algoritmo Triple DES se debe especificar el valor de desde. [2]

== Referencias

. REQ.0144: Debe utilizarse como mecanismo de cifrado simétrico un tamaño de 
clave mínimo de 256 bits.