:slug: products/
:description: The purpose of this page is to present the products offered by Fluid Attacks, which focus on helping customers in the security testing process, aiming to improve their experience and allowing us to keep close contact with them. Our star products are Integrates and Asserts.
:keywords: Fluid Attacks, Products, Ethical Hacking, Pentesting, Security, Information.
:caption:

= Products

[role="tb-alt"]
[cols=3, frame="topbot"]
|====

2+a|== link:integrates/[Integrates]

System where all the project's stakeholders come together.
It aims to bring the hacker and the developer closer together,
besides giving the ability to remediate reported vulnerabilities
in an effective manner.
Click [inner]#link:integrates/[here]# for more information.

a|image::integrates.svg[Web browser window]

a|image::asserts.svg[Magnifying glass finding error in document]
2+a|== link:asserts/[Asserts]

Engine to automate the closing of security findings
over execution environments.
It can be executed in computers running OS +Windows+ or +Linux+, and it can
also be included in your +Continuous Integration+ environment.
Click [inner]#link:asserts/[here]# for more information.

2+a|== link:rules/[Rules]

Set of requirements  used to parameterize a +pen test+.
These rules determine how rigurous a +pen test+ really is,
by defining what is going to be tested,
and what is going to be considered a vulnerability.
Click [inner]#link:rules/[here]# for more information.

a|image::rules.svg[Checklist]

|====

Want to know more about our products?
Do not hesitate to
[button]#link:../contact-us/[contact us]#.
