:slug: defends/weblogic/evitar-atq-repeticion/
:category: weblogic
:description: Nuestros ethical hackers explican como evitar vulnerabilidades de seguridad mediante la programacion segura en WebLogic 11g al desactivar la consola de administración. Esta aplicación permite realizar configuraciones dentro del servidor por lo que su acceso debe ser restringido.
:keywords: WebLogic 11g, Desactivar, Consola, Administración, Servidor, Oracle.
:defends: yes

= Desactivar Consola de Administración

== Necesidad

Desactivar consola de administración
en servidor de aplicaciones +WebLogic+

== Contexto

A continuación se describe las circunstancias
bajo las cuales la siguiente solución tiene sentido:

. Se utiliza el servidor de aplicaciones +Oracle WebLogic 11g+.
. Se desea desactivar la consola de administración.

== Solución

En +Oracle WebLogic Server+ contamos con la consola de administración,
la cual es una aplicación de gestión basada en el explorador
que se utiliza para administrar un dominio de +Oracle Web Server+.
La consola de administración es alojada dentro del servidor de administración.
Consiste en una aplicación web
accesible desde cualquier explorador web soportado
con acceso de red a las aplicaciones +host+
de servidores gestionados en el servidor de administración.

Algunas de las cosas para las que podemos utilizar
la consola de administración son:

* Configurar, iniciar y parar los dominios de +Oracle WebLogic Server+.

* Configurar +clusters+ de +Oracle WebLogic Server+.

* Configurar servicios de +Oracle WebLogic Server+
tales como conectividad de base de datos (+JDBC+) y mensajes (+JMS+).

* Configurar parámetros de seguridad,
incluida la creación y gestión de usuarios, grupos y roles.

* Configurar y desplegar aplicaciones.

* Supervisar el rendimiento del servidor y la aplicación.

* Ver archivos +log+ del servidor y el dominio.

* Ver descriptores de despliegue de aplicación.

* Editar elementos de descriptor de despliegue
de aplicación de tiempo de ejecución seleccionados.

Como es de esperarse, la consola ofrece una gran variedad de configuraciones
que deben ser realizadas únicamente por el administrador del servidor.
Debido a esto, bloquear el acceso a la consola de administración
es una medida de seguridad necesaria para evitar comprometer la información
sensible alojada en el servidor.

Por defecto, cada vez que se inicia el servidor de administración
éste despliega automáticamente la consola de administración.
Si desea evitar el acceso a la consola de administración
puede evitar que el servidor de administración la despliegue.
Para desactivar el acceso a la consola de administración
es necesario seguir los siguientes pasos:

. En el centro de cambios de la Consola de Administración,
haga clic en +Bloquear y Editar+.

. En el panel izquierdo de la consola, en +Estructura de Dominio+,
seleccione el nombre del dominio.

. Seleccione +Configuración+ > +General+.
Luego haga clic en +Avanzada+ en la parte inferior de la página.

. Anule la selección de +Consola Activada+.

. Haga clic en +Guardar+.

. Para activar estos cambios,
en el centro de cambios de la Consola de Administración,
haga clic en +Activar Cambios+.

. No todos los cambios se aplican de manera inmediata;
para que algunos se apliquen, es necesario reiniciar.

. Después de terminar, reinicie el servidor de administración.

== Referencias

. [[r1]] link:../../../rules/033/[REQ.033 Restringir acceso administrativo].

. [[r2]] link:http://164.156.186.112/_ocsh/help/topics/help_for_translation_urm_user_es_urm_user_html_help_l10n_rmdug_l10n/help_for_translation/cs_admin/es/cs_sysadmin_html_l10n/c01_introduction005.htm?tp=true&locale=es[Consola de Administración de Oracle WebLogic Server].
