:slug: rules/033/
:category: business-management
:description: This document contains the details of the security requirements related to the definition and management of systems in the organization. This requirement establishes the importance of limiting administrative access to applications only to authorized users, in order to avoid several common attacks.
:keywords: Requirement, Security, Restrict, Administrative, Access Control, Network
:rules: yes
:extended: yes

= REQ.033 Restrict administrative access

== Requirement

If the system has an administration mechanism,
it must be accessible only from administrative network segments.

== Description

Network access to modules or system management mechanisms
must be limited only to the parties
that require access to them (administrators),
personnel that do not have needs, tasks or administrative obligations
must not access to these mechanisms.
Following this recommendation fulfills the objective
of reducing the attack surface of the above mentioned systems
(thus a malicious third parties can not attempt
to access directly to the system administration settings)
 and increases the level of confidentiality and availability of the system.

== Implementation

. Principle of least privilege:
For each system in the organization
it must be guaranteed that each module
(process, user or program) can access
only to the necessary information and resources
to accomplish its legitimate purpose.

== Attacks

. An anonymous attacker attempts to access by brute force
to an exposed administrator interface,
which may cause system denial, account lockouts,
or interface/system lockout.

. An anonymous attacker and/or registered user
exploits a known vulnerability in the management system
which may allow the access to the system settings,
system denial or elevation of privilege for system users or processes.

. An anonymous attacker obtains system technical information
through data analysis of the administrator interface
in order to perform deeper and more detailed attacks.

== Attributes

* Layer: Application Layer
* Asset: System management
* Scope: Confidentiality
* Phase: Operation
* Type of Control: Recommendation

== References

. [[r1]] link:https://cwe.mitre.org/data/definitions/419.html[CWE-419: Unprotected Primary Channel].
. [[r2]] link:https://cwe.mitre.org/data/definitions/264.html[CWE CATEGORY: Permissions, Privileges, and Access Controls].
. [[r3]] link:https://www.owasp.org/index.php/Category:Access_Control[Category:Access Control].
. [[r4]] link:https://www.owasp.org/index.php/Top_10_2013-A5-Security_Misconfiguration[Top 10 2013-A5-Security Misconfiguration].
. [[r5]] link:https://www.owasp.org/index.php/ASVS_V2_Authentication[+OWASP-ASVS v3.1-2.32+]
Verify that access to administrative interfaces
are strictly controlled and not accessible to untrusted parties.
