:slug: products/rules/list/237/
:category: authentication
:description: This requirement states that the system must guarantee that all user actions are executed by a human and not by robots performing automated tasks.
:keywords: Robot, Human Interaction, User, Limit, ASVS, CAPEC, CWE, NERC, OWASP, PCI DSS, Rules, Ethical Hacking, Pentesting
:rules: yes

= R237. Ascertain human interaction

== Requirement

The system must guarantee that user actions are performed by a human
(e.g., registration, authentication and password recovery).
This can be achieved using *CAPTCHA*, incremental delays or mechanisms that
prevent excessive crawling and indexing.

== Description

There exist several attacks that have been automated or depend on a robot
for their execution.
Many of them focus on exploiting vulnerabilities in authentication forms.
In order to hinder the effectiveness of these attacks,
the system must implement mechanisms that help ensure that the entity with
which it is interacting is a human being.

== Findings

* [inner]#link:/products/rules/findings/003/[F003. Symmetric denial of service]#

* [inner]#link:/products/rules/findings/047/[F047. Automatic information enumeration]#

* [inner]#link:/products/rules/findings/053/[F053. Lack of protection against brute force attacks]#

* [inner]#link:/products/rules/findings/069/[F069. Weak CAPTCHA]#

== References

. [[r1]] link:http://capec.mitre.org/data/definitions/49.html[CAPEC-49: Password Brute Forcing].
In this attack, the adversary tries every possible value for a password until
they succeed.
A brute force attack, if feasible computationally, will always be successful
because it will essentially go through all possible passwords given the
alphabet used (lower case letters, upper case letters, numbers, symbols, etc.)
and the maximum length of the password.

. [[r2]] link:https://cwe.mitre.org/data/definitions/287.html[CWE-287: Improper Authentication].
When an actor claims to have a given identity,
the software does not prove or insufficiently proves that the claim is correct.

. [[r3]] link:https://cwe.mitre.org/data/definitions/307.html[CWE-307: Improper Restriction of Excessive Authentication Attempts].
The software does not implement sufficient measures to prevent multiple failed
authentication attempts within a short time frame,
making it more susceptible to brute force attacks.

. [[r4]] link:https://cwe.mitre.org/data/definitions/799.html[CWE-799: Improper Control of Interaction Frequency].
The software does not properly limit the number or frequency of interactions
that it has with an actor,
such as the number of incoming requests.

. [[r5]] link:https://cwe.mitre.org/data/definitions/804.html[CWE-804: Guessable CAPTCHA].
The software uses a CAPTCHA challenge,
but the challenge can be guessed or automatically recognized by a non-human
actor.

. [[r6]] link:https://www.nerc.com/pa/Stand/Reliability%20Standards/CIP-007-6.pdf[NERC CIP-007-6. B. Requirements and measures. R5.7]
Where technically feasible,
either limit the number of unsuccessful authentication attempts;
or generate alerts after a threshold of unsuccessful authentication attempts.

. [[r7]] link:https://owasp.org/www-project-top-ten/OWASP_Top_Ten_2017/Top_10-2017_A2-Broken_Authentication[OWASP Top 10 A2:2017-Broken Authentication].
Application functions related to authentication and session management are
often implemented incorrectly,
allowing attackers to compromise passwords, keys, or session tokens,
or to exploit other implementation flaws to assume other users' identities
temporarily or permanently.

. [[r8]] link:https://owasp.org/www-project-application-security-verification-standard/[OWASP-ASVS v4.0.1
V1.2 Authentication Architectural Requirements.(1.2.4)]
Verify that all authentication pathways and identity management APIs implement
consistent authentication security control strength,
such that there are no weaker alternatives per the risk of the application.

. [[r9]] link:https://owasp.org/www-project-application-security-verification-standard/[OWASP-ASVS v4.0.1
V2.2 General Authenticator Requirements.(2.2.1)]
Verify that anti-automation controls are effective at mitigating breached
credential testing, brute force, and account lockout attacks.
Such controls include blocking the most common breached passwords,
soft lockouts, rate limiting, *CAPTCHA*, ever increasing delays between
attempts, IP address restrictions,
or risk-based restrictions such as location, first login on a device,
recent attempts to unlock the account, or similar.
Verify that no more than 100 failed attempts per hour is possible on a single
account.

. [[r10]] link:https://owasp.org/www-project-application-security-verification-standard/[OWASP-ASVS v4.0.1
V8.1 General Data Protection.(8.1.4)]
Verify the application can detect and alert on abnormal numbers of requests,
such as by IP, user, total per hour or day, or whatever makes sense for the
application.

. [[r11]] link:https://owasp.org/www-project-application-security-verification-standard/[OWASP-ASVS v4.0.1
V11.1 Business Logic Security Requirements.(11.1.2)]
Verify the application will only process business logic flows with all steps
being processed in realistic human time,
i.e. transactions are not submitted too quickly.

. [[r12]] link:https://owasp.org/www-project-application-security-verification-standard/[OWASP-ASVS v4.0.1
V11.1 Business Logic Security Requirements.(11.1.8)]
Verify the application has configurable alerting when automated attacks or
unusual activity is detected.

. [[r13]] link:https://owasp.org/www-project-application-security-verification-standard/[OWASP-ASVS v4.0.1
V13.2 RESTful Web Service Verification Requirements.(13.2.4)]
Verify that *REST* services have anti-automation controls to protect against
excessive calls, especially if the API is unauthenticated.

. [[r14]] link:https://www.pcisecuritystandards.org/documents/PCI_DSS_v3-2-1.pdf[PCI DSS v3.2.1 - Requirement 6.5.10]
Address common coding vulnerabilities in software-development processes such as
broken authentication and session management.
