:slug: partners/terms/
:category: partners
:description: Terms of the contractual relationship between FLUIDAttacks and its PARTNERS. Commissions, cut-off dates,  and goals to be achieved to stay within a commission range are specified, among other aspects. These can change at any time and are established only by signing the physical document.
:keywords: FLUID, Partners, Pentesting, Terms, Agreement, Information Security.
:translate: aliados/condiciones/

= Terms

Terms of the contractual relationship between +FLUIDAttacks+ and its PARTNERS
(be them channels or integrators).
Commissions, cut-off dates,  and goals to be achieved
to stay within a commission range are specified, among other aspects.
These can change at any time and are established
only by signing the physical document.

. +FLUIDAttacks+ together with the PARTNER
will set the final sale price for each customer.

. The final price for the customer will be the base value
used to calculate the commission to be paid to the PARTNER.

. +FLUIDAttacks+ will always be a visible brand to the final customer.
Co-branding is also an option, but white-labeling is not.

. All the PARTNERS start with a minimum commission of *30%*,
until *2 cut-off dates* have elapsed.

. The cut-off date will be *December 31* of each year.

. Every *15th of January* after the second cut-off date,
the growth of the cash collected by +FLUIDAttacks+
between the two previous cut-off dates will be evaluated
to determine the commission of the year that starts:

.. If the growth is equal to or greater than *30%*,
the PARTNER will receive a commission of *30%*.

.. Otherwise, the commission will be of *15%*.

. If the PARTNER wishes to add more value to the customer on their own accord,
the commission can be higher, with previous mutual agreement of:
final price to the customer, value that will be added, minimum final price
and commision percentage for the PARTNER
(higher than *30%*).
.. This option is also susceptible to the *15* percentual points
reduction in the comission
(*50%* of the minimum *30%*) if there is no yearly growth.

. If the PARTNER is the one that collects,
they must guarantee that the money is in the +FLUIDAttacks+ account
by the *15th calendar day* of each month.

. +FLUIDAttacks+ will suspend its services if they do not receive payments
as of the *16th calendar day* of the current month.

. If +FLUIDAttacks+ is the one who collects,
it must pay the PARTNER no later than the *15th calendar day* of each month.

. All services will be provided remotely.

. In case the talent has to travel:

.. +FLUIDAttacks+ covers the talent's fees and plane tickets.

.. The PARTNER must cover every additional expense that is required.

. +FLUIDAttacks+ does not sign exclusivity with any PARTNER.

. The PARTNER must sign a confidentiality and non-solicitation agreement.

. Each party is responsible for paying their respective taxes
based on the USA tax legislation.

. The PARTNER is obliged to inform in advance
about the potential customers where +FLUIDAttacks+ professional services
will be presented.

. If +FLUIDAttacks+ bills the final customer in Latin America,
the contractual relationship between the PARTNER and +FLUIDAttacks+
will be carried out through a Letter of Attorney

. +FLUIDAttacks+ will not approach  the prospects
that the PARTNER has nominated for sales
unless the PARTNER fails to provide evidence of sales progress
in terms that never exceed *30 days*.

. This agreement is reciprocal in its entirety, which means that
the same clauses apply if +FLUIDAttacks+ successfully sells the PARTNER.
