:slug: rules/092/
:category: rules
:description: En el presente documento se detallan los lineamientos o requerimientos de seguridad relacionados al uso de certificados, los cuales, se recomienda, deben ir firmados por entidades certificadoras externas válidas cuando estos sean para aplicaciones externas.
:keywords: Certificado, Entidades certificadoras, Aplicaciones, Firma, Requerimiento, Seguridad.
:rules: yes

= REQ.092 Utilizar certificados firmados externos

== Requisito

Debe utilizarse certificados firmados
por entidades certificadoras externas válidas
cuando estos sean para aplicaciones externas.

== Descripción

La organización debe implementar certificados
firmados por entidades certificadores externas válidas
siempre y cuando sean para aplicaciones externas,
de esta manera un cliente que utilice una aplicación
desde fuera de la organización validará
y usará con confianza la aplicación
y tendrá protegida la información que comparta con la aplicación.

== Implementación

. Tras montar la solicitud del certificado
a una entidad certificadora externa reconocida,
se debe implementar el certificado recibido
sobre la plataforma o sistema para el que fue adquirido
y se debe mantener actualizado de acuerdo a las mejores prácticas.

== Ataques

. Un sitio con un certificado `SSL` mal configurado
puede causar alertas en un navegador para los usuarios.
Los usuarios tienen que aceptar tales advertencias
y continuar para poder usar el sitio,
esto causa que los usuarios se acostumbren a dichas advertencias.
En un ataque tipo `Phishing` contra el sitio
los usuarios son atraídos hacia un sitio falso
que se ve y actúa muy similar al original,
y el cual además genera advertencias prácticamente iguales,
debido a que las víctimas están acostumbradas a dichas advertencias
proceden a usar el sitio del `Phishing`,
entregando así contraseñas y otra información privada.

== Atributos

* Capa: Capa de Aplicación
* Activo: Certificados Digitales
* Alcance: Autenticidad
* Fase: Operación
* Tipo de Control: Procedimiento

== Referencias

. [[r1]] link:https://www.owasp.org/index.php/Transport_Layer_Protection_Cheat_Sheet#Rule_-_Use_an_Appropriate_Certification_Authority_for_the_Application.27s_User_Base[OWASP Transport Layer Protection Cheat Sheet]
. [[r2]] link:https://www.owasp.org/index.php/Top_10_2010-A9-Insufficient_Transport_Layer_Protection[OWASP - Top 10 2010-A9-Insufficient Transport Layer Protection]
. [[r3]] link:http://cwe.mitre.org/data/definitions/319.html[CWE-319: Cleartext Transmission of Sensitive Information]
