ARG BUILDER_IMAGE

FROM "${BUILDER_IMAGE}" AS deps

ARG CI_COMMIT_REF_NAME
ARG CI_REPOSITORY_URL

# Variables must be defined to run SCons, but their value is not used
ENV DOCKER_USER="value"
ENV DOCKER_PASS="value"
ENV WEBBOT_GMAIL_USER="value"
ENV WEBBOT_GMAIL_PASS="value"
ENV PYPI_USER="value"
ENV PYPI_PASS="value"
ENV AWS_ACCESS_KEY_ID="value"
ENV AWS_SECRET_ACCESS_KEY="value"
ENV CODECOV_TOKEN="value"
ENV GOOGLE_APPLICATION_CREDENTIALS_CONTENT="value"
ENV KUBERNETES_API_SERVER="value"
ENV KUBERNETES_API_TOKEN="value"
ENV AZURE_SUBSCRIPTION_ID="value"
ENV AZURE_CLIENT_ID="value"
ENV AZURE_CLIENT_SECRET="value"
ENV AZURE_TENANT_ID="value"

RUN git clone --depth 1 \
        -b "${CI_COMMIT_REF_NAME}" "${CI_REPOSITORY_URL}" /home/asserts \
    && cd /home/asserts \
    && scons dist

FROM python:3.7-alpine3.10 AS light

WORKDIR /home
COPY --from=deps /home/asserts/build/dist/* /home/

RUN apk update \
    && apk upgrade \
    && apk add -u --no-cache \
        jpeg-dev \
        zlib-dev \
        alpine-sdk \
        xmlsec-dev \
        libffi-dev \
        libxml2-dev \
        libxslt-dev \
        openssl-dev \
        freetype-dev \
        postgresql-dev \
        freetds-dev \
        libmagic \
    && pip3 install --no-cache-dir cython==0.29.14 \
    && pip3 install --no-cache-dir -U ./*.zip \
    && apk del -r --purge \
        gcc \
        g++ \
        jpeg-dev \
        libc-dev \
        libffi-dev \
        libressl2.7-libtls \
        make \
        musl-utils \
        libc-utils \
        openssl-dev \
        python3-dev \
        scanelf \
        ssl_client \
    && apk add -u --no-cache \
        libssl1.1 \
        libcrypto1.1 \
        libxslt-dev \
        libjpeg \
        curl \
    && rm -rf \
        /var/cache/apk/* \
        /home/*

FROM light as full

RUN apk add --no-cache \
        udev \
        wget \
        xvfb \
        libexif \
        chromium \
        chromium-chromedriver \
    && rm -rf \
        /var/cache/apk/* \
        /home/*
