source 'https://rubygems.org'

gem 'awspec'
gem 'dockerspec'
gem 'rake'
gem 'rspec'
gem 'serverspec'
gem 'specinfra'
gem 'serverspec-extended-types'
gem 'danger-gitlab', '6.0.0'
gem 'faraday', '0.15.4'
