#!/usr/bin/env bash

# This script solves the issue of the main domain not being included in the
# sitemaps generated by Pelican.

# Main file that has the main domain of the site predefined
cp sitemap.xml output/sitemap.xml

# Append all the URLs of the english subsite to the main file without the XML headers and the closing tag
tail -n +6 output/web/en/sitemap.xml >> output/sitemap.xml

# With the main file complete, remove the incomplete files
rm output/web/en/sitemap.xml
