:slug: kb/aix/establecer-tiempo-limite-sesion/
:eth: no
:category: aix
:kb: yes

= Establecer Tiempo Límite para Sesión Inactiva

== Necesidad

Establecer el tiempo limite de sesión inactiva en un sistema Unix.

== Contexto

A continuación se describen las circunstancias bajo las cuales la siguiente 
solución tiene sentido:

. Disponer de un sistema operativo conforme con la especificación Unix.
. Se tiene acceso a la interfaz de comandos (CLI) del sistema en cuestión.

== Solución

. El tiempo de vida de la sesión es el tiempo que ella estará activa sin que se 
realice actividad por parte del usuario.

. Este tiempo se especifica en segundos y se parametriza a través de una 
variable de entorno cuyo nombre varia dependiendo del shell con el cual se este 
trabajando.

. Los shells bourne y korn utilizan la variable TMOUT.

. Para establecer dicha variable a nivel de sistema se debe parametrizar el 
archivo de inicio de sesión así:
+
[source, bash, linenums]
----
% cat /etc/profile
typeset -xr TMOUT=300
----

. Con la parametrización anterior se logra que la variable sea definida como de 
solo lectura (-r), por tal motivo los usuarios no pueden eliminarla o 
establecerla en un nuevo valor. La variable sea copiada (exportada, -x) a 
shells hijos del shell actual.

. Si a nivel de sistema no se define política de tiempo de vida o esta se 
define pero se le permite a un usuario su redefinición, el usuario podrá 
parametrizar nuevos valores o la anulación de la política mediante la misma 
sintaxis anterior pero en el archivo ~/.profile.

. Para verificar el valor actual del tiempo de sesión se puede realizar lo
siguiente:
+
[source, bash, linenums]
----
%  ssh server -fluid
fluid@server's password:
...
% set | grep TMOUT
TMOUT=300
...
Shell will time out in 60 seconds.
Connection to server closed by remote host.
Connection to server closed.
----

. Es importante aclarar que a pesar de la parametrización anterior, la política 
puede ser evitada por un usuario, lanzando un nuevo shell que ignore la 
semántica asociada a la variable de entorno TMOUT:
+
[source, bash, linenums]
----
% typeset -rx TMOUT=5
% csh
% echo $TMOUT
5
% date
mié jun 9 16:15:04 COT 2010
% date
mié jun 9 16:15:13 COT 2010
----

. En el ejemplo anterior vemos como un shell tipo c a pesar de tener definida 
(exportada) la variable de entorno TMOUT, hace caso omiso de su comportamiento.

== Referencias

. http://rm-rf.es/bash-y-ssh-establecer-timeout-por-inactividad/[Establecer timeout por inactividad]