:slug: rules/157/
:category: source
:description: This requirement establishes the importance of compiling and interpreting the source code in strict mode.
:keywords: Source Code, Strict, Mode, Compilation, ASVS, CWE, Interpretation, Rules, Ethical Hacking, Pentesting
:rules: yes

= R157. Use the strict mode

== Requirement

The organization should set its parsers, linters, compilers, and interpreters
to run in strict mode.

== Rereferences

. [[r1]] link:https://cwe.mitre.org/data/definitions/120.html[CWE-120: Classic Buffer Overflow].
The program copies an input buffer to an output buffer without verifying that
the size of the input buffer is less than the size of the output buffer,
leading to a buffer overflow.

. [[r2]] link:https://cwe.mitre.org/data/definitions/611.html[CWE-611: Improper Restriction of XML External Entity Reference].
The software processes an *XML* document that can contain *XML* entities with
**URI**s that resolve to documents outside of the intended sphere of control,
causing the product to embed incorrect documents into its output.

. [[r3]] link:https://owasp.org/www-project-top-ten/OWASP_Top_Ten_2017/Top_10-2017_A4-XML_External_Entities_(XXE)[OWASP Top 10 A4:2017-XML External Entities (XXE)].
Many older or poorly configured *XML* processors evaluate external entity
references within *XML* documents.
External entities can be used to disclose internal files using the file *URI*
handler, internal file shares, internal port scanning, remote code execution,
and denial of service attacks.

. [[r4]] link:https://owasp.org/www-project-top-ten/OWASP_Top_Ten_2017/Top_10-2017_A6-Security_Misconfiguration[OWASP Top 10 A6:2017-Security Misconfiguration].
Security misconfiguration is the most commonly seen issue.
This is commonly a result of insecure default configurations,
incomplete or ad hoc configurations, open cloud storage,
misconfigured *HTTP* headers,
and verbose error messages containing sensitive information.
Not only must all operating systems, frameworks, libraries, and applications be
securely configured, but they must be patched/upgraded in a timely fashion.

. [[r5]] link:https://owasp.org/www-project-application-security-verification-standard/[OWASP-ASVS v4.0.1
Appendix C: Internet of Things Verification Requirements.(C.33)]
Verify that secure compiler flags such as **-fPIE**, **-fstack-protector-all**,
**-Wl**, **-z,noexecstack**, **-Wl**, **-z,noexecheap** are configured for
firmware builds.

. [[r6]] link:https://owasp.org/www-project-application-security-verification-standard/[OWASP-ASVS v4.0.1
V5.5 Deserialization Prevention Requirements.(5.5.2)]
Verify that the application correctly restricts *XML* parsers to only use the
most restrictive configuration possible and to ensure that unsafe features such
as resolving external entities are disabled to prevent *XXE*.

. [[r7]] link:https://owasp.org/www-project-application-security-verification-standard/[OWASP-ASVS v4.0.1
V14.1 Build.(14.1.2)]
Verify that compiler flags are configured to enable all available buffer
overflow protections and warnings,
including stack randomization, data execution prevention,
and to break the build if an unsafe pointer, memory, format string, integer,
or string operations are found.
