:slug: empleos/razones/
:category: empleos
:description: Si eres una persona talentosa, apasionada por el desarrollo de software, la informática y con muchas ganas de aprender, considera ser parte del equipo de trabajo de Fluid Attacks. Aquí te presentamos algunas razones por las que Fluid Attacks es un gran lugar para trabajar.
:keywords: Fluid Attacks, Empleo, Razones, Trabajar, Proyectos, Clientes.
:translate: careers/reasons/

= Razones para trabajar con nosotros

+Fluid Attacks+ es un gran lugar para trabajar.
Esto esto se debe a que:

== Hacker que hace sus propias herramientas

Cuando tenemos proyectos son hackeando aplicaciones o redes de empresas,
cuando no tenemos proyectos
realizamos desarrollo de software de nuestras propias herramientas.
Buscamos por ende hackers apasionados por el desarrollo y la programación.
Nuestras tecnologías favoritas son +Linux+, +Git+, +Python+,
+Docker+, +Ansible+ y +Amazon Web Services+.
Si no las dominas no importa,
en +Fluid Attacks+ importa es tu capacidad de aprender autónomamente
sobre los diversos retos que nos enfrentamos día a día,
la disciplina con los que los enfrentas,
la honestidad para decir lo que hay que decir
y la colaboración sin pretender ser más que nadie.
Si quieres participar del proceso de selección más retador que existe,
y del cual pase lo que pase aprenderás más que en ninguna otra empresa,
te invitamos a conocerlo y ver por tu mismo
que en +Fluid Attacks+ vale más hacer que saber.
Nuestro proceso de selección es guiado mediante +Git+,
es retroalimentado a través de un integrador continuo
y además permite subir tu ranking mundial en programación y hacking,
así como tu perfil de +GitLab+.
No tienes que estar graduado, no tienes que ser de ninguna carrera particular,
ni tener experiencia específica.
Lo único que importa es que demuestres
que puedes aprender solo a la velocidad esperada.

== Proyectos cortos y alta rotación

El +70%+ de los proyectos de la organización
son de modelo menor (menos de 1 mes)
y mediano (entre +1+ mes y +6+ meses).
Estos te permiten estar conociendo múltiples organizaciones,
problemas diferentes, métodos diferentes y ampliar tu conocimiento.

== Mejora continua basada en Estándares Internacionales

+Fluid Attacks+ fue la primera empresa en Colombia
en obtener la certificación +ISO/IEC 27001+ (Seguridad de la Información)
al mismo tiempo que obtuvo la certificación +ISO 9001+.
Además, nuestro proceso de mejora continua
utiliza como modelo de referencia para el Ethical Hacking,
los estandares +ISO/IEC 17025+ y el estándar +Common Criteria+.

== Trabaja con los grandes

+Fluid Attacks+ provee servicios de seguridad de la información
a algunas de las mayores organizaciones de Colombia.
Esto significa que siempre habrá proyectos
con grandes retos en los que puedes participar.
link:../../clientes/financiero/#bancolombia[Bancolombia],
link:../../clientes/financiero/#colpatria[Colpatria],
link:../../clientes/financiero/#davivienda[Davivienda],
los mayores bancos del país;
link:../../clientes/comunicaciones/#tigo-une[+UNE+],
link:../../clientes/comunicaciones/#etb[+ETB+],
link:../../clientes/comunicaciones/#edatel[+EDATEL+],
link:../../clientes/comunicaciones/#claro[Claro],
los mayores ISP del país y muchos más.
Para ver una lista más completa de los
clientes, visita la sección link:../../clientes[Clientes].

== Grandes talentos trabajando juntos

Nuestro componente más valioso es la gente,
y nos sentimos orgullosos de nuestro gran equipo de trabajo.
De hecho, es un equipo bastante joven con un promedio de edad de 25 años.
Creemos que los talentos en nuestro equipo hacen de +Fluid Attacks+
un lugar muy competitivo para trabajar
y al mismo tiempo aprender y desarrollar tus habilidades.
Los primeros tres desarrolladores de +Debian+ en Colombia
trabajan con +Fluid Attacks+,
el mayor porcentaje de colombianos certificados en link:../../servicios/certificaciones/#ethical-hacker-certificado-(ceh)[+CEH+] y link:../../servicios/certificaciones/#profesional-en-seguridad-ofensiva-inalambrica-(oswp)[+OSCP+]
están en nuestra organización,
la mayoría de los miembros del equipo campeón latinoamericano de +wargames+
de seguridad trabajan en nuestra organización.
Adicionalmente nuestro personal cuenta con certificaciones importantes como
link:../../servicios/certificaciones/#ethical-hacker-certificado-(ceh)[+CEH+],
link:../../servicios/certificaciones/#profesional-en-seguridad-ofensiva-inalambrica-(oswp)[+OSCP+],
link:../../servicios/certificaciones/#auditor-certificado-en-sistemas-de-informacion-(cisa)[+CISA+],
link:../../servicios/certificaciones/#gerente-certificado-en-seguridad-de-la-informacion-(cism)[+CISM+],
link:../../servicios/certificaciones/#profesional-en-seguridad-de-la-informacion-avalado-por-giac-(gisp)[+GISP+]
link:../../servicios/certificaciones/#profesional-certificado-en-seguridad-de-sistemas-de-informacion-(cissp)[+CISSP+], link:../../servicios/certificaciones/#comptia-security+[+CompTIA Security++] e
link:../../servicios/certificaciones/#certificacion-en-bibliotecas-de-infraestructura-de-it-(itil)[+ITIL+].

== Responsables socialmente

+Fluid Attacks+ adicionalmente es consciente de que las organizaciones,
independiente de su tamaño y sector,
deben retribuir a la sociedad permanentemente.
Por tal motivo +Fluid Attacks+ participa como organización
y estimula activamente a sus talentos
a apoyar a la educación de los mas necesitados
a través de la organización Dividendo por Colombia.
Además, +Fluid Attacks+ separa los residuos en vidrio, papel,
plástico y ordinarios para beneficio de la comunidad y los recicladores.

== Ex-empleados

También nos sentimos orgullosos que muchos de nuestros ex-empleados
trabajan o estudian en grandes compañías y universidades alrededor del mundo.
A continuación un breve listado:

. Rafael: Maestría en Matemáticas en Real Instituto de Tecnología de Suecia,
actualmente Ph.D en Matemáticas en la Universidad de Miami.
. Miguel: Maestría en Ciencias de la Computación
en el Max-Plank Institute de Alemania,
y actualmente realizando estudiosde Ph.D en el mismo instituto.
. Diego: Maestría en Seguridad de la Información en Australia.
. Juan: Maestría en Innovación en Suiza.
. Manuel: Maestría en Innovación en Inglaterra.
. Jorge: Maestría en Matemáticas en la Universidad de Miami.
. Julian: Yahoo Taiwan.
. Luis: Consultor de Seguridad en SAP Inglaterra.
. Sebastian y Juan: Fundadores de Coffee Grid.
. Jaime: Emprendedor de nuestra empresa aliada en servicio de nube Nuva.

== Cercanos a la academia

Para nosotros es muy importante mantenernos cerca de la academia.
Es por eso que algunos de nuestros empleados dictan
o han dictado cursos o cátedras en diferentes universidades de Medellín.
Cursos en temas tales como:

* Seguridad de la Información.
* Seguridad informática.
* Seguridad en Ciclo de Vida de Desarrollo de software.
* Programación, Telemática.
* Sistemas Operativos.
* Sistemas Distribuidos.

Adicionalmente hacemos parte de la Cátedra Empresarial en la universidad EAFIT,
Universidad de Medellín, Corporación Universitaria la Sallista,
y la Universidad de Antioquia.
Esto es un programa donde nuestros empleados dictan cursos cortos
en temas específicos de manera gratuita
a estudiantes de diferentes universidades.
Actualmente hemos terminado dos ciclos de cursos
en los que hemos ofrecido los temas de Linux Básico,
Principios de Seguridad de la Información y Hacking por medio de +Wargames+.

== Computador Portátil

A cada empleado de +Fluid Attacks+ se le asigna un computador portátil.
Puedes llevarlo a donde quieras, escoger tu distribución
o sistema operativo y convertir en un computador personal de verdad.
El computador deberá cumplir las políticas de uso de +Fluid Attacks+
y deberá tener en funcionamiento un sistema de control de tiempos
mientras se está trabajando.
