:slug: defends/java/remover-metadata-imgs/
:category: java
:description: Nuestros ethical hackers explican cómo evitar vulnerabilidades de seguridad mediante la programación segura en Java al remover los metadatos de las imágenes. La información sensible puede filtrarse a través de los metadatos presentes en imágenes y fotografías.
:keywords: Java, Eliminar, Metadatos, Imágenes, Seguridad, Información Sensible.
:defends: yes

= Remover Metadatos de Imágenes

== Necesidad

Remover metadatos de imágenes en +Java+.


== Contexto

A continuación se describen las circunstancias
bajo las cuales la siguiente solución tiene sentido:

. Se está desarrollando una aplicación en +Java+.
. La aplicación utiliza imágenes o fotografías.
. Se requiere remover metadatos en imágenes.

== Solución

Cuando se captura una fotografía o se guarda una imagen
ésta normalmente contiene metadatos.
Los metadatos proporcionan información adicional sobre la imagen,
como fecha de captura (para el caso de una fotografía),
tamaño en pixeles, información sobre el dispositivo con el que se tomó
(marca, modelo, etc.), última fecha de modificación,
ubicación geográfica entre muchos otros datos.
Un ejemplo de esto son las cabeceras +EXIF+
(Exchangeable Image Format)
presente en los formatos +JPG+, +TIFF+, +RIFF+ y +WAVE+ <<r2, ^[2]^>>.
Esta información es utilizada para permitir
el ordenamiento de las imágenes de acuerdo a un criterio específico.
Sin embargo, también puede ser utilizada con fines maliciosos
por los ciberdelincuentes.
Debido a esto, una práctica muy recomendada es eliminar los metadatos
antes de compartir imágenes con terceras partes.
En este artículo nos enfocaremos en cómo remover los metadatos
de las imágenes haciendo uso del lenguaje de programación +Java+.
Para ello debemos seguir los siguientes pasos:

. En el caso de +Java+ podremos eliminar los metadatos
utilizando la biblioteca +ImageIO+.
Para ello, incluiremos las librerías +java.io+, +java.imageio+
y +java.awt.image+ para el tratamiento de imágenes.
Posteriormente definimos la clase +Metadata+
como se muestra a continuación:
+
.CleanImg.java
[source, java, linenums]
----
import java.io.*;
import javax.imageio.*;
import java.awt.image.*;
public class Metadata {
----

. Desarrollamos el método +main+
donde llamamos al método +removeMetadata+ y capturamos los errores posibles
con una sentencia +try - catch+:

[source, java, linenums]
----
  public static void main(String[] args) {
    try {
      removeMetadata("ski.jpg", "jpg");
    }
    catch (IOException e) {
     System.err.println("I/O Exception");
    }
----

. El método +removeMetadata+ se encarga de leer la imagen pixel por pixel,
sin tener en cuenta cualquier otro tipo de dato,
por lo que es una función segura al momento de eliminar información extra
contenida en la imagen.

. Este método recibe dos parámetros,
el primero es la ruta donde se encuentra alojada la imagen,
y el segundo el tipo de imagen.
+
[source, java, linenums]
----
  public static void removeMetadata(String imagePath, String imageType)
    throws IOException {
----

. Se lee la imagen con el método +read+ de la clase +image+
y se vuelve a guardar.
Esto permite sobrescribir la imagen, eliminando todos los metadatos:
+
[source, java, linenums]
----
    BufferedImage image = ImageIO.read(new File(imagePath));
    ImageIO.write(image, imageType, new File(imagePath));
  }
}
----

== Referencias

. [[r1]] link:https://www.genbeta.com/imagen-digital/que-se-sabe-de-una-fotografia-a-partir-de-sus-metadatos[GenBeta - ¿Qué se sabe de una fotografía a partir de sus metadatos?].
. [[r2]] link:https://www.welivesecurity.com/la-es/2014/05/13/metadatos-fotos-podrian-mostrar-mas/[ESET image metadata].
. [[r3]] link:https://opendatasecurity.io/es/que-revelan-los-metadatos-en-las-fotos/[Open Data Security - ¿Qué revelan los metadatos en las fotos?].
. [[r4]] link:../../../rules/045/[REQ.045 Eliminar metadatos al compartir archivos].
