:slug: rules/339/
:category: files
:description: This requirement states that the system must not store user-uploaded files or files containing sensitive information in the web root.
:keywords: Web, Root, File, Directory, ASVS, CWE, Rules, Ethical Hacking, Pentesting
:rules: yes

= R339. Avoid storing sensitive files in the web root

== Requirement

The system should store neither user-uploaded files nor files containing
sensitive information in the **web root**.

== Description

The **web root** is the topmost directory on a web server.
If there is no sufficient access control,
any file in this directory will be publicly available.
Therefore, user-uploaded files and files containing sensitive information
should not be stored in it.

== References

. [[r1]] link:https://cwe.mitre.org/data/definitions/219.html[CWE-219: Storage of File with Sensitive Data Under Web Root].
The application stores sensitive data under the web document root with
insufficient access control,
which might make it accessible to untrusted parties.

. [[r2]] link:https://cwe.mitre.org/data/definitions/552.html[CWE-552: Files or Directories Accessible to External Parties].
The product makes files or directories accessible to unauthorized actors,
even though they should not be.

. [[r3]] link:https://cwe.mitre.org/data/definitions/922.html[CWE-922: Insecure Storage of Sensitive Information].
The software stores sensitive information without properly limiting read or
write access by unauthorized actors.

. [[r4]] link:https://owasp.org/www-project-application-security-verification-standard/[OWASP-ASVS v4.0.1
V1.12 Secure File Upload Architectural Requirements.(1.12.1)]
Verify that user-uploaded files are stored outside of the **web root**.

. [[r5]] link:https://owasp.org/www-project-application-security-verification-standard/[OWASP-ASVS v4.0.1
V12.4 File Storage Requirements.(12.4.1)]
Verify that files obtained from untrusted sources are stored outside the
**web root**, with limited permissions, preferably with strong validation.
