:slug: compliance/
:description: Here you can find the international standards and regulations we consider fundamental in order to guarantee systems' and information assets' security.
:keywords: Standards, Regulations, OWASP, PCI, HIPAA, NIST, GDPR, Pentesting, Ethical Hacking
:phrase: At Fluid Attacks, we compile diverse international standards and regulations, focused on the security of systems and information assets, that guide us in evaluating your software.
:template: indexof
:arrow: image:../theme/images/arrow-btn.svg[Young hacker smiling, width=15px, height=15px]

= Compliance

== OWASP

OWASP is a non-profit foundation committed to improving software security.
They establish various cybersecurity risk rankings.
With our vulnerability detection, we can help you meet
the corresponding requirements so that your company's IT systems
are protected from such risks. +
[button]#link:owasp/[Go to OWASP {arrow}]#

== PCI
PCI DSS is a standard created by the Payment Card Industry
that establishes minimum requirements to be fulfilled by companies
that manage cardholder information.
We can assist you in detecting vulnerabilities in your systems
related to this standard through our ethical hacking. +
[button]#link:pci/[Go to PCI {arrow}]#

== HIPAA
HIPAA is a legislation created in the U.S.
to regulate and optimize the flow of Protected Health Information (PHI)
within the healthcare environment.
We support you in complying with this legislation
by identifying vulnerabilities in your systems
that could allow attackers to breach data privacy. +
[button]#link:hipaa/[Go to HIPAA {arrow}]#

== NIST
The NIST SP 800-53 is a U.S. security and privacy control database
that can guide the protection of federal agencies'
and citizens' private information.
We can help you follow this standard's security best practices
by discovering the weaknesses in your systems associated with them. +
[button]#link:nist/[Go to NIST {arrow}]#

== GDPR
GDPR is a European regulation for data protection and privacy that applies
to any organization that stores, processes or transfers European citizens'
personal information. We help you achieve compliance with this regulation,
starting with identifying all relevant vulnerabilities in your software. +
[button]#link:gdpr/[Go to GDPR {arrow}]#
