:slug: rules/169/
:category: source
:description: This document contains the details of the security requirements related to the definition and management of source code in the organization. This requirement establishes the importance of using parameterized sentences in order to avoid injection attacks such as SQLi.
:keywords: Parameterized, Sentences, SQLi, Injection, ASVS, CWE
:rules: yes

= R169. Use parameterized queries

== Requirement

The system must use parameterized queries or stored procedures
to create dynamic sentences (e.g *java.sql.PreparedStatement*).

== Findings

* [inner]#link:/web/findings/001/[F001. SQL injection]#

* [inner]#link:/web/findings/105/[F105. Apache Lucene query injection]#

== References

. [[r1]] link:https://cwe.mitre.org/data/definitions/89.html[CWE-89: SQL Injection].
The software constructs all or part of an SQL command using
externally-influenced input from an upstream component,
but it does not neutralize or incorrectly neutralizes special elements that
could modify the intended SQL command.

. [[r2]] link:https://owasp.org/www-project-application-security-verification-standard/[OWASP-ASVS v4.0.1
V5.3 Output encoding and Injection Prevention Requirements.(5.3.4)]
Verify that data selection or database queries
(e.g. *SQL*, *HQL*, *ORM*, *NoSQL*) use parameterized queries, *ORMs*,
entity frameworks, or are otherwise protected from database injection attacks.
