=== Certificación de Servicio de Pruebas


Fluidsignal Group S.A. identificada con número de registro *8110285148*
certifica que mantiene en la actualidad relaciones comerciales con la empresa
{{business}} identificada con número de registro *{{business_number}}*.

Desde el {{start_day}} de {{start_month}} de {{start_year}} se han
desarrollado pruebas integrales de seguridad (SAST, DAST, SCA, IAS)
en modalidad Hacking Continuo sobre la solución {{solution}}.

El resultado actual de las pruebas realizadas es el siguiente:

[cols="5*^",options=header]
|===
|{{words['severity_title']}}|{{words['finding_number_title']}}|{{words['total_vulns_title']}}|{{words['closed_vulns_title']}}|{{words['resume_perc_title']}}
{% for row in remediation_table %}
  {% for col in row %}
    {{"| "+col|string}}
  {%- endfor %}
{%- endfor %}
|===


Las vulnerabilidades encontradas son notificadas a todos los interesados
quienes continuamente ejecutan las acciones correctivas para darles
solución y *Fluid Attacks* realiza la verificación de estas
correcciones para garantizar la calidad de la solución.

La presente certificación se expide por solicitud a los {{report_day}} días
del mes de {{report_month}} de {{report_year}}.

{{signature_img}}
Head of Delivery +
Fluidsignal Group S.A.
