:slug: rules/189/
:category: data
:description: This document contains the details of the security requirements related to the definition and management of data access in the organization. This requirement establishes the importance of specifying the purpose of personal data collection in order to fulfill all legal requirements
:keywords: Requirement, Security, Data, Privileges, System, GDPR
:rules: yes
:extended: yes

= REQ.189 Specify the purpose of data collection

== Requirement

The system must specify the purpose
of the personal data collection (+OECD.9+, +ISACA.G31.3.+).

== Description

Applications usually request or collect personal data from their users.
Such collection must be properly justified according to the legal requirements
of each nation.
These reasons must be accessible for the user in a clear manner and in an easy
to understand language.

== References

. [[r1]] link:https://gdpr-info.eu/recitals/no-39/[GDPR. Recital 39:  Principles of data processing].
It should be transparent to natural persons that personal data concerning them
are collected, used, consulted or otherwise processed and to what extent
the personal data are or will be processed.
. [[r2]] link:https://gdpr-info.eu/recitals/no-40/[GDPR. Recital 40: Lawfulness of data processing].
In order for processing to be lawful,
personal data should be processed on the basis of the consent of the data
subject concerned or some other legitimate basis.
. [[r3]] link:https://gdpr-info.eu/recitals/no-45/[GDPR. Recital 45: Fulfillment of legal obligations].
Where processing is carried out in accordance with a legal obligation to which
the controller is subject, the processing should have a basis in Union or
Member State law.
