require 'rake'
require 'rspec/core/rake_task'

$host       = ENV['host']
$modulelist = ENV['modulelist']

task :spec => "spec:#{$host}"

namespace :spec do
  desc "Running serverspec on host #{$host}"
  RSpec::Core::RakeTask.new($host) do |t|
    ENV['TARGET_HOST'] = $host
    t.pattern = 'spec/{' + properties[key][:roles].join(',') + '}/*_spec.rb'
    t.fail_on_error = false
  end

