:slug: defends/cobol/usar-opciones-depuracion/
:category: cobol
:description: Nuestros ethical hackers explican cómo evitar vulnerabilidades de seguridad mediante la programación segura en COBOL al explicar en detalle como deben realizarse adecuadamente operaciones de depuración en etapa de desarrollo permitiendo un despliegue transparente de la misma en producción.
:keywords: COBOL, Debug, Desarrollo, Producción, Aplicación, Depuración.
:defends: yes

= Usar Adecuadamente Opciones de Depuración

== Necesidad

Usar adecuadamente las opciones de depuración que provee +COBOL+.

== Contexto

A continuación se describe las circunstancias
bajo las cuales la siguiente solución tiene sentido:

. Se está desarrollando una aplicación en +COBOL+.
. El desarrollador desea depurar el flujo de la aplicación
sin afectar el programa final.
. Los eventos con severidad de depuración
no deben estar habilitados en producción<<r1,^[1]^>>.

== Solución

. La cláusula +WITH DEBUGGING MODE+<<r2,^[2]^>>
ayuda a los programadores a depurar código
mientras la aplicación se encuentra en desarrollo
y permite un despliegue transparente de la misma
a un entorno de producción.

. Esta cláusula causa que cualquier procedimiento usado para depuración
(Letra +D+ en la columna 7) sea compilado.
Sin esta cláusula, estos procedimientos son tratados como comentarios.

. El siguiente código muestra un ejemplo sencillo
donde el programador requiere depurar el programa.
Es importante que en entornos de producción
no se generen eventos de depuración,
ya que podría afectar la disponibilidad de la aplicación.

. Se da inicio a la aplicación definiendo la división +IDENTIFICATION DIVISION+<<r3,^[3]^>>:
+
.coboldbg.cbl
[source,cobol,linenums]
----
       IDENTIFICATION DIVISION.
      ******************
      * Identification *
      ******************
       PROGRAM-ID. COBOLDBG.
----
. En la división +ENVIRONMENT DIVISION+<<r4,^[4]^>>
especificamos el modo +WITH DEBUGGING+
dentro de la sección +CONFIGURATION SECTION+.
Dicho modo debe ser desactivado en entornos de producción:
+
[source,cobol,linenums]
----
      ***************
      * Environment *
      ***************
       ENVIRONMENT DIVISION.
       CONFIGURATION SECTION.
       SOURCE-COMPUTER. IBM-ISERIES WITH DEBUGGING MODE.
----
. En la división +DATA DIVISION+<<r5,^[5]^>> definimos dos variables,
una llamada +CONTADOR+ y otra denominada +RESULTADO+
que llevará el resultado de una operación matemática:
+
[source,cobol,linenums]
----
      ********
      * Data *
      ********
       DATA DIVISION.
       WORKING-STORAGE SECTION.
       01 RESULTADO  PIC 9(04) VALUE 1.
       01 CONTADOR   PIC 9(02).
----
. Iteramos sobre la variable +CONTADOR+ 9 veces,
multiplicando la variable +RESULTADO+ por 2.
Note como la columna 7 de la sentencia +DISPLAY+ tiene la letra +D+.
Si el modo +WITH DEBUGGING+ está activado, esta línea es compilada,
en caso contrario, la línea es tratada como un comentario:
+
[source,cobol,linenums]
----
      ********
      * Main *
      ********
       PROCEDURE DIVISION.
       MAIN.
           PERFORM VARYING CONTADOR FROM 1 BY 1 UNTIL CONTADOR > 10
      D        DISPLAY "Actual: " RESULTADO
               COMPUTE RESULTADO = RESULTADO * 2
           END-PERFORM.
----
. Mostramos el resultado final:
+
[source,cobol,linenums]
----
       DISPLAY "Resultado: " RESULTADO.

       STOP RUN.
----
. El resultado usando el modo +WITH DEBUGGING+ es el siguiente:
+
[source,bat,linenums]
----
Actual: 0001
Actual: 0002
Actual: 0004
Actual: 0008
Actual: 0016
Actual: 0032
Actual: 0064
Actual: 0128
Actual: 0256
Actual: 0512
Resultado: 1024
----
. El resultado sin usar el modo +WITH DEBUGGING+ es el siguiente:
+
[source,bat,linenums]
----
Resultado: 1024
----

== Descargas

Puedes descargar el código fuente
pulsando en el siguiente enlace:

. [button]#link:src/coboldbg.cbl[coboldbg.cbl]# contiene
la implementación del código depurado anteriormente.

== Referencias

. [[r1]] link:../../../rules/078/[REQ.078 Eventos con severidad deshabilitados].
. [[r2]] link:http://www.mainframestechhelp.com/tutorials/cobol/cobol-configuration-section.htm[COBOL Configuration Section].
. [[r3]] link:https://www.ibm.com/support/knowledgecenter/en/ssw_ibm_i_73/rzasb/iddiv.htm[Identification Division - Format].
. [[r4]] link:https://www.ibm.com/support/knowledgecenter/en/ssw_ibm_i_72/rzasb/envcon.htm[Environment Division].
. [[r5]] link:http://www.escobol.com/modules.php?name=Sections&op=viewarticle&artid=13[Data Division].
