:slug: kb/lenguajes/cobol/comprobar-fortaleza-diccionario
:eth: no
:category: cobol
:kb: yes

= Comprobar Fortaleza Diccionario

== Necesidad

Comprobar fortaleza de contraseñas tipo palabra usando diccionarios de
contraseñas comunes en COBOL

== Contexto

A continuación se describe las circunstancias bajo las cuales la siguiente
solución tiene sentido:
. Se está desarrollando una aplicación en COBOL.
. Las claves tipo palabra no deben contener palabras de diccionario. [1]

== Solución

. Para la construcción de la solución deberemos definir o buscar una lista con
contraseñas comunes, las cuales serán usadas para comparar con la contraseña
ingresada por el usuario. En [2], [3], [4], [5] y [6], encontrará la lista de
diccionarios que se recomiendan para hacer la búsqueda.
. Por cuestiones de espacio se creó el archivo COMMONPASS con el siguiente
contenido:
[source,cobol,linenums]
----
123
password
hello
admin
busy
12345
dragon
qwerty
system
mustang
----
[start=3]
. Iniciamos el programa definiendo la división de identificación:
[source,cobol,linenums]
----
 IDENTIFICATION DIVISION.
 ******************
 * Identification *
 ******************
 PROGRAM-ID. COBOLCPASS.
----
[start=4]
. En la división de entorno asignamos la variable COMMON-PASS al archivo
COMMONPASS, el cual contiene las contraseñas comunes:
[source,cobol,linenums]
----
      ***************
      * Environment *
      ***************
       ENVIRONMENT DIVISION.
       INPUT-OUTPUT SECTION.
       FILE-CONTROL.
           SELECT COMMON-PASS ASSIGN TO "COMMONPASS"
           ORGANIZATION IS SEQUENTIAL.
----
[start=5]
. En la división de datos establecemos la estructura para el archivo con
contraseñas comunes:
[source,cobol,linenums]
----
      ********
      * Data *
      ********
       DATA DIVISION.

       FILE SECTION.
       FD COMMON-PASS.
       01 PASSWORD-RECORD.
           88 WS-PASS-EOF VALUE HIGH-VALUES.
           02 WS-PASSWORD PIC X(26).
----
[start=6]
. En la sección de almacenamiento declaramos cuatro variables:
* WS-USERPASS: Contraseña ingresada por el usuario.
* WS-COUNT: Contador que indica si la contraseña en el diccionario está
contenida en la contraseña ingresada por el usuario.
* WS-LENGTH: Longitud real de la contraseña en el diccionario.
* WS-FLAG: Bandera que indica si el requisito es cumplido.
[source,cobol,linenums]
----
       WORKING-STORAGE SECTION.
       01 WS-USERPASS     PIC X(26).
       01 WS-COUNT        PIC 9(02) VALUE 0.
       01 WS-LENGTH       PIC 9(02).
       01 WS-FLAG         PIC 9     VALUE 0.
           88 WS-FLAG-FALSE VALUE 0.
           88 WS-FLAG-TRUE  VALUE 1.
----
[start=7]
. En la división de procedimiento encontramos la lógica del programa. Obtenemos
la contraseña del usuario y la convertimos a mayúscula:
[source,cobol,linenums]
----
      ********
      * Main *
      ********
       PROCEDURE DIVISION.
       MAIN.
           DISPLAY "Ingrese clave a verificar: ".
           ACCEPT WS-USERPASS.
           MOVE FUNCTION UPPER-CASE(WS-USERPASS) TO WS-USERPASS.
----
[start=8]
. Abrimos el archivo con las contraseñas comunes:
[source,cobol,linenums]
----
OPEN INPUT COMMON-PASS.
----
[start=9]
. Leemos el primer registro del diccionario y a través del uso de la sentencia
AT END podemos saber si alcanzó el final del archivo:
[source,cobol,linenums]
----
           READ COMMON-PASS
               AT END SET WS-PASS-EOF TO TRUE
           END-READ.
----
[start=10]
. Convertimos la contraseña en el diccionario a mayúscula e inicializamos las
variables de contador y longitud. Tanto la contraseña ingresada por el usuario
como la contenida en el diccionario son convertidas a mayúscula por facilidad de
validación:
[source,cobol,linenums]
----
           PERFORM UNTIL WS-PASS-EOF
               MOVE FUNCTION UPPER-CASE(WS-PASSWORD) TO WS-PASSWORD
               MOVE 0 TO WS-COUNT
               MOVE 0 TO WS-LENGTH
----
[start=11]
. Obtenemos la longitud real de la contraseña en el diccionario para evitar
problemas con los espacios al final de la misma:
[source,cobol,linenums]
----
               INSPECT FUNCTION REVERSE(WS-PASSWORD)
               TALLYING WS-LENGTH FOR LEADING SPACES

               COMPUTE WS-LENGTH = FUNCTION LENGTH(WS-PASSWORD)
                                   - WS-LENGTH
----
[start=12]
. Se busca todas las coincidencias de la contraseña en el diccionario dentro de
la contraseña ingresada por el usuario:
[source,cobol,linenums]
----
               INSPECT WS-USERPASS
               TALLYING WS-COUNT
               FOR ALL WS-PASSWORD(1:WS-LENGTH)
----
[start=13]
. Si la contraseña está contenida en la contraseña ingresada por el usuario,
entonces salimos del procesamiento del archivo:
[source,cobol,linenums]
----
               IF WS-COUNT > 0 THEN
                   MOVE 1 TO WS-FLAG
                   PERFORM FINAL-PROCESS
               END-IF
----
[start=14]
. Leemos el próximo registro:
[source,cobol,linenums]
----
               READ COMMON-PASS
                   AT END SET WS-PASS-EOF TO TRUE
               END-READ
           END-PERFORM
----
[start=15]
. Como proceso final, cerramos el archivo:
[source,cobol,linenums]
----
       FINAL-PROCESS.
           CLOSE COMMON-PASS
----
[start=16]
. Si la bandera está en falso, significa que el requisito fue cumplido y la
contraseña no contiene palabras de diccionario:
[source,cobol,linenums]
----
           IF WS-FLAG-FALSE THEN
               DISPLAY "Requisito cumplido"
           ELSE
               DISPLAY "Requisito no cumplido"
           END-IF.

           STOP RUN.
----
[start=17]
. El resultado para la anterior aplicación es el siguiente:
|===
|Palabra |Resultado

|123
|No cumplido

|hello
|No cumplido

|admin
|No cumplido

|SystEM
|No cumplido

|abcd123abcd
|No cumplido

|My-Str0n6_P4assw0rd!
|Cumplido
|===

== Referencias

. REQ.0101: El sistema debe tener la capacidad de validar que ninguna contraseña
contenga palabras de diccionario.
. http://dazzlepod.com/uniqpass/[Dazzlepod Uniqpass]
. http://www.openwall.com/wordlists/[Openwall Wordlist]
. http://wordlist.aspell.net/[Wordlist project]
. https://packetstormsecurity.com/Crackers/wordlists/[Packet Storm Security Wordlists]
. http://www.deer-run.com/~hal/sysadmin/pam_cracklib.html[Linux Password Security with pam_cracklib]
