:slug: rules/040/
:category: rules
:description: En el presente documento se detallan los requerimientos de seguridad relacionados a la gestión de archivos dentro de la organización. Por lo tanto, en este requerimiento se recomienda que los formatos de los archivos correspondan a la extensión especificada por los mismos.
:keywords: Sistema, Tamaño, Archivo, MB, Seguridad, Usuario.
:rules: yes

= REQ.040 Contrastar formato y extensión de archivos

== Requisito

El sistema debe validar
que el formato (estructura) de los archivos
corresponda con su extensión.

== Descripción

Un sistema que permite la subida o recepción de archivos,
determina qué comportamiento debe tener
dependiendo de la extensión del archivo,
un atacante puede aprovechar una mala validación del sistema
(cuando el sistema solo valida que el tipo de extensión sea válido
más no que el formato del archivo
corresponda al de la extensión presentada),
de esta forma un atacante subiendo un archivo de extensión
que corresponde a un contenido diferente,
ejemplo un archivo `.php.gif`,
puede ser procesado como `gif` en principio
por el control de validación del contenido
y luego ya al haber subido al sistema
puede ser interpretado como `php`
causando comportamientos no deseados.

== Implementación

Tomar decisiones desde el lado del servidor,
basado en el contenido del archivo
y no solo en el nombre del archivo o su extensión.

== Ataques

. Un usuario malicioso entrega un archivo
a un sistema que no valida su contenido,
de esta forma el sistema se ve comprometido por la ejecución de `scripts`
o ejecutables maliciosos que pueden dar acceso no autorizado
o extraer información confidencial del mismo.

== Atributos

* Capa: Capa de Aplicación.
* Activo: Archivos.
* Alcance: Integridad.
* Fase: Operación.
* Tipo de Control: Recomendación.

== Referencias

. link:https://cwe.mitre.org/data/definitions/646.html[CWE-646: Reliance on File Name or Extension of Externally-Supplied File].
. link:http://capec.mitre.org/data/definitions/209.html[CAPEC-209: XSS Using MIME Type Mismatch].
. link:http://capec.mitre.org/data/definitions/18.html[CAPEC-18: XSS Targeting Non-Script Elements].
