:slug: defends/php/limitar-vida-recurso/
:category: php
:description: Nuestros ethical hackers explican cómo evitar vulnerabilidades de seguridad mediante la creación, manipulación y eliminación correcta de recursos dentro de un programa PHP, evitando que información disponible en memoria pueda ser capturada por usuarios no autorizados.
:keywords: PHP, Datos sensibles, Datos confidenciales, Lectura segura, Memoria, Tiempo de vida.
:defends: yes

= Limitar tiempo de vida de recursos

== Necesidad

Eliminar (limpiar) recursos
dentro de la aplicación
cuando ya no estén en uso.

== Contexto

A continuación se describe las circunstancias
bajo las cuales la siguiente solución tiene sentido:

. Se está desarrollando una aplicación en +PHP+ versión +7.0+ o superior.
. El código debe eliminar información sensible en memoria.
. La aplicación debe liberar recursos cuando ya no estén en uso,<<r1,^[1]^>>
limitando así su tiempo de vida.

== Solución

+PHP+ es un lenguaje de programación
que ofrece gran variedad de opciones al momento de procesar ficheros.
En este artículo veremos dos de ellas,
la primera mediante la instrucción +fopen+
y la segunda mediante +fread+.

* *Lectura segura de ficheros con +fopen+:*

. En primer lugar se declara la variable +$myresource+,
la cual, contiene la referencia o ubicación al fichero a ser leído:
+
.fopen.php
[source, php, linenums]
----
<?php
  $myresource = fopen("test.txt","r");
----
+
Como se observa, en esta ocasión +fopen+ recibe dos parámetros:
el primero corresponde a la ruta
donde está almacenado el fichero a procesar,
y el segundo corresponde al tipo de acceso al mismo.
En este caso el valor es +"r"+,
lo cual indica acceso de sólo lectura.
En el siguiente link:http://php.net/manual/es/function.fopen.php[enlace]
podrá encontrar mayor información sobre el método +fopen+.

. Mediante el método +feof+
y dentro de un ciclo +while+,
se verifica que no se ha llegado al final del fichero a leer:
+
[source, php, linenums]
----
while (!feof($myresource)) {
----
. Leemos línea por línea
el contenido del recurso
y lo imprimimos en pantalla:
+
[source, php, linenums]
----
  $line = fgets($myresource);
  echo $line;
}
----
. Por último, una vez ha terminado el procesamiento del recurso,
se procede a cerrar el flujo asociado al mismo:
+
[source, php, linenums]
----
  fclose($myresource);
?>
----
+
Nota: +PHP+ ofrece alternativas
para validar si un fichero existe
o si tiene los permisos suficientes para el acceso al mismo,
para dicho propósito existen los métodos link:http://php.net/manual/es/function.file-exists.php[file_exists] y link:http://php.net/manual/es/function.is-readable.php[is_readable],
sin embargo, para efectos prácticos,
dichos métodos no son necesarios
debido a que +fopen+ devuelve +FALSE+ en caso de error,
esto garantizará que el procesamiento de archivos
solo se realice si el archivo se abre correctamente.

. Para ejecutar el anterior programa,
desde la terminal se debe ubicar primero en el directorio del proyecto
y ejecutar el comando +php+
(se debe instalar previamente +PHP+):
+
[source, bash, linenums]
----
$ ls
fopen.php test.txt
$ php fopen.php
----
. La salida en consola luego de ejecutar el programa es la siguiente
(en este caso el contenido del fichero
son contraseñas de prueba):
+
[source, bash, linenums]
----
Contrasenas:
FLUIDtest
admin123
PHPTest
----

* *Lectura segura de ficheros con +fread+:*

. Al igual que con +fopen+, en primer lugar se declara la variable +$myfile+,
la cual, contiene la referencia o ubicación al fichero a ser leído:
+
.fread.php
[source, php, linenums]
----
<?php
  $myfile = fopen("test.txt","r");
----
+
Al igual que como se hizo anteriormente,
establecemos acceso de solo lectura al fichero +test.txt+.

. Una vez abierto el recurso,
se especifica los argumentos para el método +fread+:
+
[source, php, linenums]
----
$content = fread($myfile, filesize("test.txt"));
----
+
El primer argumento corresponde al fichero a leer
y el segundo especifica la cantidad de bytes a ser leídos.
Con el fin de garantizar que todo el fichero sea procesado,
se emplea el método link:http://php.net/manual/es/function.filesize.php[filesize]
especificando el fichero en cuestión.
Dicha función se detendrá al final del archivo
o cuando alcance la longitud especificada, lo que ocurra primero.

. Por último, cerramos el flujo asociado al recurso
y se imprime el contenido de la variable +$content+ en pantalla:
+
[source, php, linenums]
----
  fclose($myfile);
  print $content;
?>
----

. La salida en consola, será la misma que la obtenida para +fopen+.

== Descargas

Puedes descargar el código fuente
pulsando en los siguientes enlaces:

. [button]#link:src/fopen.php[fopen.php]# contiene
código +PHP+ utilizando el método +fopen+
para la manipulación segura de ficheros.

. [button]#link:src/fread.php[fread.php]# contiene
código +PHP+ utilizando el método +fread+
para la manipulación segura de ficheros.

== Referencias

. [[r1]] link:../../../rules/999/[REQ.999 Limitar tiempo de vida de recursos].
. *+CSHARP+* link:../../csharp/limitar-vida-recurso/[Limitar tiempo de vida de recursos].
. *+SCALA+* link:../../scala/limitar-vida-recurso/[Limitar tiempo de vida de recursos].
. *+Java+* link:../../java/limitar-vida-recurso/[Limitar tiempo de vida de recursos].
