:slug: about-us/
:description: The purpose of the following page is to present our applicants basic information about our organization. Next, we will introduce ourselves as a company in order to enable you to make an informed decision about where you will potentially continue your career.
:keywords: Fluid Attacks, About us, Company, Presentation, Information, Careers.

= About Us

=== Fluid Attacks is growing every day!

Since *2001*, `Fluid Attacks` has been developing technology
focused on cybersecurity, offering ethical hacking
and pentesting services to companies in the banking,
financial, technology, healthcare, insurance,
manufacturing, and airline industries, among others.
`Fluid Attacks` has a team of *70* security analysts in San Francisco, CA,
Bogotá, and Medellín (Colombia).
They implement more than *200* projects a year
and help their clients to manage their cybersecurity risks
and certify that their systems, which are critical to their operations,
are safe for their users.

`Fluid Attacks'` team of security experts
specializes in continuous hacking on applications, infrastructure,
and source code, covering all stages of software development.
`Fluid Attacks'` team ensures
that vulnerabilities in organizations' systems are recognized,
with no false positives or negatives.
With `Fluid Attacks'` products,
the clients can obtain high remediation vulnerability rates,
all this at `DevOps` speed.
Besides, `Fluid Attacks` has its technology
to support the work of the hacking team with automated attack processes,
and to allow the client —this through the `Integrates` platform—
to manage the projects and control the remediation processes
in any of the phases.
