:slug: defends/java/validar-archivo-header/
:category: java
:description: Nuestros ethical hackers explican cómo evitar vulnerabilidades de seguridad mediante la programación segura en Java al validar los tipos de archivos utilizando los encabezados. Esta práctica permite evitar ataques de tipo directorio transversal, reforzando así la seguridad de la aplicación.
:keywords: Java, Encabezados, Directorio, Transversal, Archivo, Validación
:defends: yes

= Validar Tipo de Archivo Usando los Encabezados

== Necesidad

Validar tipo de archivo usando los encabezados.

== Contexto

A continuación se describen las circunstancias
bajo las cuales la siguiente solución tiene sentido:

. Se está desarrollando una aplicación con +Java+.
. Se necesita validar la entrada de datos,
específicamente validar el tipo de archivo a ser manipulado.
. Se requiere determinar el tipo de archivo
usando mecanismos más confiables que solo revisar la extensión.

== Solución

Los ataques de tipo directorio transversal
se producen cuando una aplicación no cuenta
con un nivel de seguridad y validación adecuado.
Consiste en que un usuario sin privilegios
es capaz de escalar a directorios superiores,
visualizando los contenidos de las carpetas y archivos allí contenidos.
Esto supone un riesgo para la confidencialidad de los datos
presentes en esos archivos.
Existen muchas formas de abordar este problema,
en el caso de este artículo nos enfocaremos en realizar una validación
del tipo de archivo haciendo uso de los encabezados.
Para ello debemos seguir los siguientes pasos:

. Se hará uso de la biblioteca +Mime Type Detection Utility+ <<r2, ^[2]^>>,
la cual determina el tipo de archivo
revisando los encabezados (+magic headers+).

. La aplicación requiere que las dependencias
listadas a continuación se encuentren en el classpath <<r2, ^[2]^>> <<r3, ^[3]^>>:

. +mime-util-X.X.X.jar+
. +slf4j-api-X.X.X.jar+
. +slf4j-simple-X.X.X.jar+

. Una opción rápida para agregar clases al +classpath+
es copiando los +jar+ a +[jre path]/lib/ext/+

. Inicialmente creamos un archivo a utilizar
en las pruebas que denominaremos +test.pdf+,
cuyo único contenido sera la palabra +fsg+:
+
.sample text
[source, bash, linenums]
----
$ cat test.pdf
fsg
----

. Creamos el archivo +Main.java+ que contendrá el código de la aplicación.

. Importamos la interfaz +java.util.Collection+
para contener la lista de tipos de archivo y +java.io.File+
que representará el archivo a procesar.
+
[source,java,linenums]
----
import java.util.Collection;
import java.io.File;
...
----

. Importamos la clase +eu.medsea.mimeutil.MimeUtil+
que será la encargada hacer todo el proceso de consulta
del tipo de archivo.
+
[source,java,linenums]
----
import eu.medsea.mimeutil.MimeUtil;
...
----

. Registramos como detector de tipos
a +eu.medsea.mimeutil.detector.MagicMimeMimeDetector+
(puede usarse cualquier implementación de +AbstractMimeDetector+).
+
.ValidateFile.java
[source,java,linenums]
----
public class Main {
  public static void main(String[] args) {
    MimeUtil.registerMimeDetector("eu.medsea.mimeutil.detector.MagicMimeMimeDetector");
...
----

. A continuación creamos una instancia de +File+
referenciando a nuestro archivo de prueba +test.pdf+,
la cual se envía al método +getMimeTypes+
para retornar una colección con los tipos de archivos detectados
y mostrarlos por la salida estándar.
+
[source,java,linenums]
----
File f = new File ("test.pdf");
Collection mimeTypes = MimeUtil.getMimeTypes(f);
System.out.println(mimeTypes);
----

. Compilamos y ejecutamos la aplicación:
+
[source, bash, linenums]
----
$ javac -classpath .:mime-util-2.1.3.jar:slf4j-api-1.6.4.jar:slf4j-simple-1.6.4.jar Main.java

$ java -classpath .:mime-util-2.1.3.jar:slf4j-api-1.6.4.jar:slf4j-simple-1.6.4.jar Main
application/octet-stream
----

. Vemos como este mecanismo no tuvo en cuenta la extensión
y determinó correctamente que eran datos arbitrarios.

== Referencias

. [[r1]] link:http://www.rgagnon.com/javadetails/java-0487.html[Get the Mime Type of a File].
. [[r2]] link:https://sourceforge.net/projects/mime-util/[Mime Type Detection Utility].
. [[r3]] link:https://www.slf4j.org/download.html[Simple Logging Facade for Java].
. [[r4]] link:http://mime-util.sourceforge.net/apidocs/eu/medsea/mimeutil/MimeUtil.html[Mime util API].
. [[r5]] link:https://en.wikipedia.org/wiki/Media_type[Internet media type].
. [[r6]] link:../../../rules/040/[REQ.040 Contrastar formato y extensión de archivos].
