:slug: empleos/evaluacion-conocimientos/
:category: empleos
:description: La siguiente página tiene como objetivo informar a los interesados en ser parte del equipo de trabajo de Fluid Attacks sobre el proceso de selección realizado. Ésta prueba pretende evaluar los conocimientos del candidato en diferentes áreas para determinar si se ajustan al perfil requerido.
:keywords: Fluid Attacks, Empleo, Selección, Evaluación, Prueba, Conocimiento.
:translate: careers/knowledge-test/

= Evaluación de conocimientos

El siguiente paso para continuar con tu proceso de selección
es realizar nuestro examen de conocimientos.
Este examen contiene diversas áreas de conocimientos,
unas que aplican a tu perfil, y otras que no.
Sin embargo, debes presentarlas todas a conciencia,
pues con esto podremos validar si el examen es efectivo determinando
que los que saben, saben, y los que no, no.

[NOTE]
Este examen es totalmente en inglés y no es posible cambiar el idioma.

Los pasos para realizar el examen son los siguientes:

== Crear una cuenta

. Ingresar a la siguiente [button]#link:https://fluidattacks.com/courses/login/index.php[dirección web]#
. Dar click en el botón *+CREATE NEW ACCOUNT+*
y llenar el formulario con tu información.
Por favor, ten en cuenta que el nombre de usuario solo admite
letras en minúsculas, y la contraseña debe ser mayor a 8 caracteres,
tener una letra en mayúscula y al menos un carácter no alfanumérico (*,-, o #).
. Confirmar tu dirección de correo siguiendo las instrucciones.
Revisa tu buzón de correo y la carpeta +SPAM+
en caso tal de que no llegue a la bandeja principal.

== Instalar SafeExamBrowser

. Descargar el siguiente [button]#link:../../files/fluidexams.zip[software de seguridad]#
para presentar el examen.
+
[IMPORTANT]
Por favor termina de leer los demás pasos antes de ejecutar el aplicativo.

. Descomprimir el archivo +.ZIP+ descargado
y luego instalar en +Windows+ el archivo con nombre
*+SafeExamBrowserInstaller.exe+*.
El teclado puede cambiar su configuracion y quedar en inglés,
por lo que debes validar si es necesario volverlo a configurar
para que quede en español.

. Verificar que estés conectado a Internet y que tengas una conexión estable.

. En cualquier momento puedes salir del aplicativo con el botón
que está situado en la parte inferior derecha de la pantalla.

. Para presentar el examen, debes ir a la carpeta
y ejecutar el archivo *+fluidexams+*.
Desde este momento, el único programa activo será el examen.

== Realizar el examen

. Deberás iniciar sesión con tus credenciales,
las cuales registraste anteriormente.
. Al tener éxito en ingresar, debes ir a la barra de navegación izquierda
y buscar la pestaña *+Sites Home+*, luego dar click en ella.
. Bajas al final de la página y seleccionas *+General Knowlegde Exam+*.
. Da click en el botón *+ENROLL ME+*, luego, en la siguiente página,
da click en el botón que dice *+ATTEMPT QUIZ NOW+* para comenzar.
+
[IMPORTANT]
Por favor ten en cuenta que una vez respondas o saltes una pregunta,
no podrás volver a ella, por lo que no podrás modificar la respuesta.

. Al finalizar el examen, busca en la parte inferior del aplicativo,
y da click a *+FINISH ATTEMPT+* para validar que respondiste todas las preguntas
. Luego, en la parte inferior de la pagina,
da click en *+SUBMIT ALL AND FINISH+*.
. Para salir del aplicativo, debes hacerlo con el botón que está situado
en la parte inferior derecha de la pantalla.
. Envíanos un correo notificándonos que finalizaste el examen.

Desde el momento del registro en la plataforma del examen,
tienes *24 horas* para presentarlo y solo un (*1*) intento.
En caso de no poder presentar el examen en el tiempo indicado,
por favor escribe un correo proponiendo un nuevo compromiso
para la presentación del mismo.
El examen tiene una duración máxima de *3 horas y 20 minutos*,
por lo que debes disponer de tiempo suficiente
para realizarlo sin interrupciones.

¡Que te diviertas!  ... y buena suerte, aunque no la necesitas.
