:slug: rules/141/
:category: credentials
:description: This document contains the details of the security requirements related to the definition and management of access credentials in the organization. This requirement establishes the importance of forcing users to re-authenticate after a password change occurs.
:keywords: Re-authentication, Force, Password, Change, ASVS, CWE
:rules: yes

= R141. Force re-authentication

== Requirement

The system must force a user to re-authenticate or invalidate their session
if the state of their account changes
(password change/recovery, lockouts, user deletion, etc.).

== Findings

* [inner]#link:/web/findings/076/[F076. Insecure session management]#

== References

. [[r1]] link:https://cwe.mitre.org/data/definitions/613.html[CWE-613: Insufficient Session Expiration]
According to WASC, "Insufficient Session Expiration is when a web site permits
an attacker to reuse old session credentials or session IDs for authorization."

. [[r2]] link:https://owasp.org/www-project-application-security-verification-standard/[OWASP-ASVS v4.0.1
V3.3 Session Logout and Timeout Requirements.(3.3.3)]
Verify that the application terminates all other active sessions after a
successful password change,
and that this is effective across the application, federated login
(if present), and any relying parties.
