:slug: rules/141/
:category: credentials
:description: This requirement establishes the importance of forcing users to re-authenticate after their account changes.
:keywords: Re-authentication, Force, Password, Change, ASVS, CWE, OWASP, PCI DSS, Rules, Ethical Hacking, Pentesting
:rules: yes

= R141. Force re-authentication

== Requirement

The system must force users to re-authenticate or invalidate their session
if the state of their account changes
(e.g. password change/recovery, lockouts, user deletion, etc.).

== Findings

* [inner]#link:/web/findings/076/[F076. Insecure session management]#

== References

. [[r1]] link:https://cwe.mitre.org/data/definitions/613.html[CWE-613: Insufficient Session Expiration].
Insufficient Session Expiration is when a web site permits
an attacker to reuse old session credentials or session IDs for authorization.

. [[r2]] link:https://owasp.org/www-project-top-ten/OWASP_Top_Ten_2017/Top_10-2017_A2-Broken_Authentication[OWASP Top 10 A2:2017-Broken Authentication].
Application functions related to authentication and session management are
often implemented incorrectly,
allowing attackers to compromise passwords, keys, or session tokens.

. [[r3]] link:https://owasp.org/www-project-application-security-verification-standard/[OWASP-ASVS v4.0.1
V3.3 Session Logout and Timeout Requirements.(3.3.3)]
Verify that the application terminates all other active sessions after a
successful password change.

. [[r4]] link:https://owasp.org/www-project-application-security-verification-standard/[OWASP-ASVS v4.0.1
V3.7 Defenses Against Session Management Exploits.(3.7.1)]
Verify the application ensures a valid login session or requires
re-authentication or secondary verification before allowing any sensitive
transactions or account modifications.

. [[r5]] link:https://www.pcisecuritystandards.org/documents/PCI_DSS_v3-2-1.pdf[PCI DSS v3.2.1 - Requirement 6.5.10]
Address common coding vulnerabilities in software-development processes such as
broken authentication and session management.
