:slug: rules/324/
:category: architecture
:description: This document contains the details of the security requirements related to the definition and management of resources and services in the organization. This requirement establishes the importance of controlling redirects as they may lead to malicious sites.
:keywords: Control, Redirect, External, Site, ASVS, CWE
:rules: yes

= REQ.324 Control redirects

== Requirement

Redirects must be controlled,
especially when they depend on external input.

== Description

Systems must guarantee that all redirects lead to a controlled or trusted site.
In general, redirects based on input data should be avoided as they could
enable to *phishing* attacks.
If they are required, they should be controlled so that users are only
redirected to trusted sites.

== Findings

* link:/web/findings/023/[F023. Uncontrolled external site redirect]

* link:/web/findings/097/[F097. Reverse tabnabbing]

* link:/web/findings/100/[F100. Server-side request forgery (SSRF)]

== References

. [[r1]] link:https://cwe.mitre.org/data/definitions/601.html[CWE-601: URL Redirection to Untrusted Site ('Open Redirect')]
A web application accepts a user-controlled input that specifies a link to an
external site,
and uses that link in a Redirect.
This simplifies *phishing* attacks.

. [[r2]] link:https://cwe.mitre.org/data/definitions/602.html[CWE-602: Client-Side Enforcement of Server-Side Security]
The software is composed of a server that relies on the client to implement a
mechanism that is intended to protect the server.

. [[r3]] link:https://cwe.mitre.org/data/definitions/1022.html[CWE-1022: Use of Web Link to Untrusted Target with window.opener Access]
The software does not restrict or incorrectly restricts access to a resource
from an unauthorized actor.

. [[r4]] link:https://owasp.org/www-project-application-security-verification-standard/[OWASP-ASVS v4.0.1
V1.4 Access Control Architectural Requirements.(1.4.1)]
Verify that trusted enforcement points such as at access control gateways,
servers, and serverless functions enforce access controls.
Never enforce access controls on the client.

. [[r5]] link:https://owasp.org/www-project-application-security-verification-standard/[OWASP-ASVS v4.0.1
V1.5 Input and Output Architectural Requirements.(1.5.3)]
Verify that input validation is enforced on a trusted service layer.

. [[r6]] link:https://owasp.org/www-project-application-security-verification-standard/[OWASP-ASVS v4.0.1
V5.1 Input Validation Requirements.(5.1.5)]
Verify that URL redirects and forwards only allow whitelisted destinations,
or show a warning when redirecting to potentially untrusted content.
