:slug: rules/025/
:category: session
:description: This requirement establishes the importance of informing and controlling concurrent sessions to detect user impersonation and identity theft.
:keywords: Manage, Concurrent, Session, ASVS, CWE, NIST, OWASP, PCI DSS, Rules, Ethical Hacking, Pentesting
:rules: yes

= R025. Manage concurrent sessions

== Requirement

The concurrent sessions of a system
must be informed or controlled.

== Description

A system that uses authenticated access sessions
associated with unique users
may allow simultaneous access with the same credentials.
This may pose a risk for the service,
the information and the system users,
by allowing malicious users to interact
simultaneously with the system using a valid user,
leading to undetected identity thefts,
unauthorized actions in name of the user (impersonation)
and a loss of traceability of the impersonated user's actions <<r1, ^[1]^>> <<r2, ^[2]^>>.

== Implementation

. Restrict or remove concurrent sessions:
Configure in the system the option to restrain
the simultaneous connections using the same access credentials,
either from an external authentication system
or from the same system.

== Attacks

. An attacker logs in simultaneously
using the account of a valid user.

. An attacker performs actions
without traceability nor authorization.

== Attributes

. Layer: Application Layer.
. Asset: Session Management.
. Scope: Integrity.
. Phase: Operation.
. Control Type: Procedure.

== Findings

* [inner]#link:/web/findings/062/[F062. Concurrent sessions]#

== References

. [[r1]] link:https://cwe.mitre.org/data/definitions/384.html[CWE-384: Session Fixation].
Authenticating a user, or otherwise establishing a new user session,
without invalidating any existing session identifier gives an attacker the
opportunity to steal authenticated sessions.

. [[r2]] link:https://pages.nist.gov/800-63-3/sp800-63b.html[NIST 800-63B 7.1 Session Bindings]
Secrets used for session binding SHALL be generated by the session host during
an interaction,
typically immediately following authentication.

. [[r3]] link:https://owasp.org/www-project-top-ten/OWASP_Top_Ten_2017/Top_10-2017_A2-Broken_Authentication[OWASP Top 10 A2:2017-Broken Authentication].
Application functions related to authentication and session management are
often implemented incorrectly,
allowing attackers to compromise passwords, keys, or session tokens,
or to exploit other implementation flaws to assume other users' identities
temporarily or permanently.

. [[r4]] link:https://owasp.org/www-project-application-security-verification-standard/[OWASP-ASVS v4.0.1
V2.2 General Authenticator Requirements.(2.2.3)]
Verify that secure notifications are sent to users after updates to
authentication details,
such as credential resets, email or address changes, logging in from unknown or
risky locations.

. [[r5]] link:https://owasp.org/www-project-application-security-verification-standard/[OWASP-ASVS v4.0.1
V3.2 Session Binding Requirements.(3.2.1)]
Verify the application generates a new session token on user authentication.

. [[r6]] link:https://pcinetwork.org/forum/index.php?threads/pci-dss-3-0-6-5-10-broken-authentication-and-session-management.667/[[PCI DSS 3.0\] 6.5.10 Broken authentication and session management].

. [[r7]] link:https://www.pcisecuritystandards.org/documents/PCI_DSS_v3-2-1.pdf[PCI DSS v3.2.1 - Requirement 6.5.10]
Address common coding vulnerabilities in software-development processes such as
broken authentication and session management.
