:slug: rules/186/
:category: rules
:description: En el presente documento se detallan los requerimientos de seguridad relacionados a la importancia que implica establecer o utilizar el mínimo nivel de privilegios cuando un sistema requiere del acceso a otro sistema o a una base de datos en particular.
:keywords: Requerimiento, Seguridad, Acceso, Datos, Privilegios, Base de datos.
:rules: yes

= REQ.186 Utilizar el mínimo nivel de privilegios

== Requisito

El sistema debe utilizar el mínimo nivel de privilegios
cuando accede a otro sistema o a bases de datos.

== Referencias

. [[r1]] link:https://www.owasp.org/index.php/ASVS_V4_Access_Control[+OWASP-ASVS v3.1-4.1+]
Verificar que exista el principio de mínimo privilegio.
Los usuarios sólo deben tener acceso a funciones, datos, archivos, URLs,
controladores, servicios y otros recursos
para los cuales se posee autorización específica.
Esto implica protección contra +spoofing+ y elevación de privilegio.

. [[r2]] link:https://nvd.nist.gov/800-53/Rev4/control/AC-6[+NIST+ 800-53 AC-6]
La organización emplea el principio del mínimo privilegio,
permitiendo sólo accesos autorizados a los usuarios
(o procesos que actúan en nombre de los usuarios) necesarios para completar
las tareas asignadas de acuerdo a las misiones de la organización
y las funciones de negocio.
