:slug: defends/java/firmar-objeto/
:category: java
:description: Nuestros ethical hackers nos explican que son las firmas digitales y la importancia que estas tienen a la hora de compartir todo tipo de información en la red. Además, mediante un ejemplo en Java, nos enseñan como firmar adecuadamente el contenido de los objetos.
:keywords: Java, Seguridad, Firma, Digital, Objeto, Datos.
:defends: yes

= Firmar el Contenido de un Objeto

== Necesidad

Firmar el contenido de un objeto mediante el uso de una firma digital.

== Contexto

A continuación se describen las circunstancias
bajo las cuales la siguiente solución tiene sentido:

. Se dispone de un compilador estándar de +Java+.

== Solución

Hoy día y gracias a que Internet es una realidad
que beneficia a millones de personas, es posible compartir
casi cualquier tipo de información en cuestión segundos.
Pero dicha ventaja es a su vez un gran problema,
porque muchas veces la información compartida
está corrupta o posee datos maliciosos
que pueden comprometer el correcto funcionamiento
de un sistema de información.
Y es gracias a dicha problemática
que se hace necesario
contar con métodos o herramientas
que permitan verificar que la información enviada y recibida
es realmente la información que se necesita.

Entonces, el método que permite realizar tal validación
es la implementación de una firma digital.
Una firma digital no es más que un método criptográfico
que asocia una identidad a un mensaje enviado a través de la red,
es decir, es el procedimiento por el cual
se puede autenticar al emisor de un mensaje
y confirmar que dicho mensaje
no ha sido alterado desde que fue firmado.
En sí, la firma digital permite que tanto
el receptor como el emisor de un contenido
puedan identificarse mutuamente con la certeza
de que son ellos los que están interactuando,
evitando que terceras personas
intercepten dicho contenido y por tanto no pueda ser alterado.

. Java permite proteger la integridad de la información
mediante el uso de firmas digitales.
En el caso particular de está solución se firmará un objeto.

. Para firmar un objeto es necesario
crear una clave privada y una clave pública,
las cuales serán usadas
para firmar y verificar el contenido del objeto.

. Primero hay que importar las siguientes clases.
Las clases terminadas en +Exception+,
representan excepciones que podrían ocurrir durante el proceso.
+
.cli.java
[source, java, linenums]
----
import java.security.KeyPair;
import java.security.KeyPairGenerator;
import java.security.PrivateKey;
import java.security.PublicKey;
import java.security.Signature;
import java.security.SignedObject;
import java.io.IOException;
import java.security.InvalidKeyException;
import java.security.NoSuchAlgorithmException;
import java.security.SignatureException;
----

. Como segundo paso, se debe generar
la clave privada y su respectiva clave pública,
estas serán usadas para firmar y verificar
la validez de la firma.
Para hacerlo, se debe invocar
el método estático +getInstance+ de la clase +KeyPairGenerator+.
+
[source, java, linenums]
----
class CLI {
  public static void main(String[] args) throws Exception,
    NoSuchAlgorithmException, SignatureException, InvalidKeyException,
      IOException, ClassNotFoundException {
        PublicKey publicKey = null;
        PrivateKey privateKey = null;
        KeyPairGenerator keyGen = KeyPairGenerator.getInstance("DSA");
        keyGen.initialize(1024);
        KeyPair keypair = keyGen.genKeyPair();
        privateKey = keypair.getPrivate();
        publicKey = keypair.getPublic();
----

. Luego, hay que invocar
el método +getInstance+ de la clase +Signature+
con el fin de obtener
una referencia al objeto que representa la firma digital.
+
[source, java, linenums]
----
String data = "object signed";
Signature signature = Signature.getInstance(privateKey.getAlgorithm());
----

. Para verificar la integridad
y la autenticidad de la información,
se debe utilizar la clave pública
para crear la firma.
Dicha clave pública se encuentra asociada
a la clave privada con la cual
se firmó el contenido de la variable +data+.
+
[source, java, linenums]
----
Signature sigs = Signature.getInstance(publicKey.getAlgorithm());
----

. Posteriormente se debe invocar
el método +verify+ de la clase +SignedObject+
para identificar si la firma digital
asociada al objeto firmado es correcta.
+
[source, java, linenums]
----
boolean b = so.verify(publicKey, sigs);
----

. Por último, se obtiene
el contenido del objeto firmado
y se imprimen los resultados.
+
[source, java, linenums]
----
  String os = (String) so.getObject();
  System.out.println("object signed: " + os);
  System.out.println("Signature Verification: " + b);
  }
}
----

== Descargas

Puedes descargar el código fuente
pulsando en el siguiente enlace:

[button]#link:src/cli.java[CLI.java]#
Clase CLI.

== Referencias

. [[r1]] link:https://docs.oracle.com/javase/6/docs/technotes/guides/security/crypto/CryptoSpec.html#KeyFactoryEx[Java Cryptography Architecture]
. [[r2]] link:https://en.wikipedia.org/wiki/Digital_signature[Digital signature]
