# frozen_string_literal: true

source "https://rubygems.org"

gemspec

gem "rails", "~> 7.0.0"
gem "omniauth"
gem "omniauth-oauth2"
gem "rdoc", "4.2.2"
gem "mime-types", "= 3.3.1"

gem "devise", ">= 4.0.0", "< 4.6.2"

gem "draper", "~> 1.2", ">= 1.2.1"

gem "rails-controller-testing", github: "rails/rails-controller-testing"

gem "responders", "~> 3.0"

group :test do
  gem "nokogiri", "< 1.13"
  gem "omniauth-facebook"
  gem "omniauth-openid"
  gem "rexml"
  gem "timecop"
  gem "webrat", "0.7.3", require: false
  gem "mocha", "~> 1.1", require: false
end

platforms :ruby do
  gem "sqlite3", "~> 1.4"
end