:slug: rules/018/
:category: rules
:description: En el presente documento se detallan los requerimientos relacionados a la gestion adecuada en cuanto a los acuerdos por servicios se refiere. El objetivo de este requerimiento es definir la importancia de los acuerdos a nivel de servicio con terceros con los cuales se comparte información.
:keywords: Requerimiento, Seguridad, Acuerdos, Servicio, Terceros, Información.
:rules: yes

= REQ.018 Acuerdos a nivel de servicio con terceros

== Requisito

La organización debe tener un acuerdo
de nivel de servicio de disponibilidad
con todos los terceros con los cuales comparte información.

== Descripción

El objetivo primordial es asegurar que los servicios estén disponibles
y funcionen correctamente siempre que los clientes y usuarios
deseen hacer uso de ellos.
Además, establecer acuerdos de disponibilidad
implica establecer los umbrales de tiempo disponible del servicio
necesarios para el negocio.

== Implementación

. La disponibilidad es el porcentaje de tiempo sobre el total acordado
en que los servicios han sido accesibles al usuario
y han funcionado correctamente.
Es indispensable cuantificar los requisitos de disponibilidad
para la correcta elaboración de los Acuerdos de nivel de servicio.
La disponibilidad propuesta debe encontrarse en línea
tanto con las necesidades reales del negocio
como con las posibilidades de la organización.

. Aunque en principio todos estarán de acuerdo
con unas elevadas cotas de disponibilidad,
es importante tener en cuenta que la alta disponibilidad
puede generar unos costes injustificados dadas sus necesidades reales.
Quizá unas pocas horas sin un determinado servicio
pueden representar poco más allá de una pequeña inconveniencia
mientras que la certeza de un servicio prácticamente continuo
y sin interrupciones puede requerir la replicación de sistemas
u otras medidas igualmente costosas
que no van a tener una repercusión real
en la rentabilidad del negocio.

. Para llevar a cabo
la determinación de la disponibilidad necesaria se debe:

* Identificar las actividades clave del negocio.

* Cuantificar los intervalos razonables de interrupción
de los diferentes servicios
dependiendo de sus respectivos impactos.

* Determinar las franjas horarias de disponibilidad necesarias
para cada uno de los servicios (+24/7+, +12/5+, ...).

. Una vez se establezcan los porcentajes de disponibilidad,
estos se llevan a nivel contractual
definiendo las posibles multas
en caso de incumplimiento de los parámetros definidos
para la prestación del servicio.

== Ataques

. Se presentan incumplimientos en la prestación del servicio
y se afecta la producción de la organización,
no es posible aplicar multas
debido a la falta de definición de acuerdos de nivel de servicio
orientados a la disponibilidad requerida para el negocio.

== Atributos

* Capa: Capa de Negocio.
* Activo: Acuerdo de nivel de servicio.
* Alcance: Adherencia.
* Fase: Operación.
* Tipo de Control: Recomendación.

== Referencias

. link:http://es.presidencia.gov.co/dapre/DocumentosSIGEPRE/L-TI-05-Administracion-Niveles-Servicio.pdf[LINEAMIENTOS DE ADMINISTRACIÓN DE NIVELES DE SERVICIO].
