:slug: rules/336/
:category: cryptography
:description: This document contains the details of the security requirements related to the definition and management of random numbers in the organization. This requirement establishes the importance of disabling out-of-date or insecure versions of TLS and SSL protocols.
:keywords: SSL, Version, Protocol, TLS, CWE, ASVS
:rules: yes

= R336. Disable insecure TLS versions

== Requirement

The system must disable out-of-date or insecure versions of *SSL* and *TLS*
protocols, algorithms and ciphers.

== Descriptions

All communications between the client and the server should take place over
channels that are protected and encrypted.
In order to guarantee this, out-of-date or insecure protocols such as *SSLv2*,
*SSLv3*, or *TLS* 1.0 and *TLS* 1.1 should be disabled.
The latest version of TLS should be used and communications should not be
allowed to fall back to insecure or unencrypted protocols.

== Findings

* [inner]#link:/web/findings/052/[F052. Insecure encryption algorithm]#

== References

. [[r1]] link:https://cwe.mitre.org/data/definitions/319.html[CWE-319: Cleartext Transmission of Sensitive Information]
The software uses insufficiently random numbers or values in a security context
that depends on unpredictable numbers.

. [[r2]] link:https://cwe.mitre.org/data/definitions/326.html[CWE-326: Inadequate Encryption Strength]
The software stores or transmits sensitive data using an encryption scheme that
is theoretically sound,
but is not strong enough for the level of protection required.

. [[r3]] link:https://owasp.org/www-project-application-security-verification-standard/[OWASP-ASVS v4.0.1
V9.1 Communications Security Requirements.(9.1.1)]
Verify that secured TLS is used for all client connectivity,
and does not fall back to insecure or unencrypted protocols.

. [[r4]] link:https://owasp.org/www-project-application-security-verification-standard/[OWASP-ASVS v4.0.1
V9.1 Communications Security Requirements.(9.1.2)]
Verify using online or up to date TLS testing tools that only strong
algorithms, ciphers, and protocols are enabled,
with the strongest algorithms and ciphers set as preferred.

. [[r5]] link:https://owasp.org/www-project-application-security-verification-standard/[OWASP-ASVS v4.0.1
V9.1 Communications Security Requirements.(9.1.3)]
Verify that old versions of SSL and TLS protocols, algorithms, ciphers, and
configuration are disabled,
such as SSLv2, SSLv3, or TLS 1.0 and TLS 1.1.
The latest version of TLS should be the preferred cipher suite.
