:slug: services/
:description: Fluid Attacks services aim to detect and report all existing vulnerabilities and security issues within an application. Our professional team continuously develop their own tools and exploits to ensure the detection of all security findings with no false positives.
:keywords: Fluid Attacks, Services, Ethical Hacking, Pentesting, Security, Information.
:caption:

= Services

[role="tb-alt"]
[cols=3, frame="topbot"]
|====

2+a|== link:one-shot-hacking/[One-Shot Hacking]

This service aims to detect and report all the vulnerabilities
and security issues within one specific version of your application,
with no false positives.
a|image::one-shot.svg[Computer being attacked]

a|image::continuous.svg[Server being attacked]
2+a|== link:continuous-hacking/[Continuous Hacking]

This service aims to detect and report all the vulnerabilities
and security issues during the whole software development cycle.
This method allows us to detect security issues continuously
as software evolves.
This inspection is done without false positives and ensuring previous
issues were resolved before going to production.

2+a|== link:differentiators/[Differentiators]

What is the difference between a +pentest+ and a +vulnerability analysis+
using automated tools? +
These items allow us to find and report all security vulnerabilities
in your application.
a|image::differentiators.svg[Metal gear]

a|image::comparative.svg[Two plate scale]
2+a|== link:comparative/[Comparative]

What is the difference between the +One-Shot Hacking+ service
and the +Continuous Hacking+ service? +
These items allow you to decide which service
best suits your needs.

2+a|== link:certifications/[Certifications]

Our hackers have professional certifications in a variety of areas
in information security
such as Offensive Security Certified Professional (+OSCP+),
Offensive Security Wireless Professional (+OSWP+),
Certified Ethical Hacker (+CEH+),
Certified Information Systems Security Professional (+CISSP+), among others.
You can be confident that when you hire us,
you are getting a team of highly capable professionals.

a|image::certifications.svg[Certification diploma]

a|image::faq.svg[Question being answered in a conversation]
2+a|== link:faq/[FAQ]

Do you have any questions about One-Shot Hacking
or Continuous Hacking services? +
Scroll through the Frequently Asked Questions section
to find the answers to the most common questions we get about our services.

|====

Want further information about our services?
Do not hesitate to
[button]#link:../contact-us/[contact us]#.
