:slug: rules/061/
:category: rules
:description: En el presente documento se detallan los requerimientos de seguridad relacionados a la gestión de la documentación que prinda soporte en todo sistema de una organización. Por lo tanto, se recomienda que se dedique al menos un capítulo donde se traten temas de seguridad del sistema.
:keywords: Documentación, Sistema, Soporte, Capítulo, Organización, Seguridad.
:rules: yes

= REQ.061 Documentar capítulo de seguridad

== Nombre

La documentación que soporta un sistema de información
debe contener un capítulo de seguridad.

== Descripción

La documentación de un sistema
debe sustentar el diseño
y uso de las características de seguridad definidas.

== Implementación

. La seguridad de la información
es una característica no funcional de los sistemas,
la documentación del mismo
debe soportar las definiciones establecidas
para proteger la información que el sistema maneja.

. Dentro de la documentación de diseño
se debería incluir los casos de abuso diseñados,
los requisitos de seguridad necesarios
para proteger la información
y el diseño de controles establecidos.
Esta documentación ayuda en la validación
de la implementación de seguridad.

. En la documentación de usuario,
se debería los paso a paso de configuración
y uso de controles
que cada perfil de usuario puede aplicar.

== Ataques

. Los documentos de diseño
no establecieron los casos de abuso
y requisitos de seguridad
que necesita la aplicación
y por lo tanto
no fueron implementados los controles necesarios
para la protección de la información.

. Los parámetros de configuración de seguridad no fueron documentados,
los usuarios no usan los posibles controles de seguridad establecidos.

== Atributos

* Capa: Negocio.
* Activo: Arquitectura de seguridad.
* Alcance: Mantenibilidad.
* Fase: Operación.
* Tipo de Control: Recomendación.
