:slug: personas/john-gomez/
:category: personas
:description: FLUID es una compañía dedicada al ethical hacking, las pruebas de intrusión y la detección de vulnerabilidades en aplicaciones con más de 18 años de experiencia. La siguiente página tiene como propósito presentar a los miembros que conforman el equipo de trabajo de FLUID.
:keywords: FLUID, Equipo, Trabajo, Perfil, John, Gómez
//:translate: people/john-gomez/

= John Gómez

Ingeniero de Sistemas de la Universidad EAFIT, 
tiene un MBA de la misma Universidad, 
y es Especialista en Economía y Negocios Internacionales 
de la Universidad de Medellín.
Ha sido profesor de Sistemas de Información y la Gerencia,
Tendencias de la Gerencia y, Gerencia Contemporánea, 
en programas de postgrado de laUniversidad Pontificia Bolivariana.
Fue representante de +Orbitel Telecomunicaciones+ 
en el Comité Universidad-Empresa-Estado, 
miembro del comité de sistemas de la Universidad de Antioquia, 
miembro del comité de sistemas de la Alcaldía de Medellín, 
y representante de +Suramericana de Seguros+ 
en el Consejo Directivo del Centro de Ciencia y Tecnología de Antioquia.

Fue Gerente General de +Choucair Testing S.A+, 
en donde lideró y participó activamente 
en su estructuración como empresa de carácter regional 
e impulsó esquemas de gestión y gobierno 
tendientes a facilitar su perdurabilidad y sostenibilidad 
en el corto, mediano y, largo plazo.
Se desempeñó como Gerente de Tecnología y Producción 
de la Casa Editorial +El Colombiano+,
fue Director de Seguridad y Cumplimiento del +Grupo Bancolombia+.
También desempeñó el cargo de Gerente de Tecnología 
y líder del proyecto de implantación de +SAP+ 
en +Orbitel Telecomunicaciones+.
Además fue Gerente de Desarrollo de +Suramericana de Seguros+ 
y socio fundador de +VCB+ (Virtual Community Builders), 
+TICBO+ (empresa prestadora de servicios de +outsourcing+ 
en operación de tecnologías de información), 
+Dolphins Consulting+ (+BPO+ + Desarrollo Empresarial) 
y +AFTER 50+ (Desarrollo de Talento Humano y Consultoría en T.I).
Actualmente acompaña y asesora algunas empresas en la ciudad de Medellín.


