:slug: rules/320/
:category: architecture
:description: This document details the security guidelines and requirements related to logical architecture management within the organization. This requirement establishes the importance of enforcing access control on the server's side instead of on the client's.
:keywords: Control Enforcement, Client, Server, Access, ASVS, CWE
:rules: yes

= REQ.320 Avoid client-side control enforcement

== Requirement

The system must enforce access controls on trusted enforcement points,
not on the client's side.

== Description

Systems must enforce access controls on trusted enforcement points such as
access control gateways, severs and serverless functions.
Client-side access control enforcement can not be trusted because it is prone
to being bypassed and/or tampered with.

== Findings

* [inner]#link:/web/findings/032/[F032. Spoofing]#

* [inner]#link:/web/findings/039/[F039. Improper authorization control for web services]#

* [inner]#link:/web/findings/063/[F063. Lack of data validation]#

* [inner]#link:/web/findings/064/[F064. Traceability loss]#

* [inner]#link:/web/findings/075/[F075. Unauthorized access to files]#

* [inner]#link:/web/findings/093/[F093. Hidden fields manipulation]#

* [inner]#link:/web/findings/098/[F098. External control of file name or path]#

* [inner]#link:/web/findings/103/[F103. Insufficient data authenticity validation]#

== References

. [[r1]] link:https://cwe.mitre.org/data/definitions/284.html[CWE-284: Improper Access Control]
The software does not restrict or incorrectly restricts access to a resource
from an unauthorized actor.

. [[r2]] link:https://cwe.mitre.org/data/definitions/602.html[CWE-602: Client-Side Enforcement of Server-Side Security]
The software is composed of a server that relies on the client to implement a
mechanism that is intended to protect the server.

. [[r3]] link:https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:02002L0058-20091219[Directive 2002/58/EC (amended by E-privacy Directive 2009/136/EC).
Art. 4: Security of processing.(1a)]
The measures referred to in paragraph 1 shall at least ensure that personal
data can be accessed only by authorized personnel for legally authorized
purposes.

. [[r4]] link:https://owasp.org/www-project-application-security-verification-standard/[OWASP-ASVS v4.0.1
V1.4 Access Control Architectural Requirements.(1.4.1)]
Verify that trusted enforcement points such as at access control gateways,
servers, and serverless functions enforce access controls.
Never enforce access controls on the client.

. [[r5]] link:https://owasp.org/www-project-application-security-verification-standard/[OWASP-ASVS v4.0.1
V1.4 Access Control Architectural Requirements.(1.4.4)]
Verify the application uses a single and well-vetted access control mechanism
for accessing protected data and resources.
All requests must pass through this single mechanism to avoid copy and paste or
insecure alternative paths.

. [[r6]] link:https://owasp.org/www-project-application-security-verification-standard/[OWASP-ASVS v4.0.1
V1.5 Input and Output Architectural Requirements.(1.5.3)]
Verify that input validation is enforced on a trusted service layer.
