import os

FI_AWS_OPENSEARCH_HOST = os.environ["AWS_OPENSEARCH_HOST"]
FI_DYNAMODB_HOST = os.environ["DYNAMODB_HOST"]
FI_DYNAMODB_PORT = os.environ["DYNAMODB_PORT"]
FI_ENVIRONMENT = os.environ["ENVIRONMENT"]
