:slug: rules/327/
:category: architecture
:description: This requirement establishes the importance of setting a rate limit to control interaction frequency.
:keywords: Rate, Limit, Interaction, Frequency, ASVS, CWE, Rules, Ethical Hacking, Pentesting
:rules: yes

= R327. Set a rate limit

== Requirement

The server must have a rate limit to control interaction frequency.

== Description

Several attacks depend on executing a huge amount of requests from a single
host.
For instance, it is possible to exhaust a server's connection pool with a
single machine by using asynchronous requests,
effectively causing a Denial of Service (*DoS*).
These and other attacks such as the ones depending on brute force
can be thwarted, or severely hindered, by limiting the number of requests that
a single host can send to the server in a short period of time.
Therefore, server settings should include a rate limit that considers a regular
request flow between a host and the server.

== Findings

* [inner]#link:/web/findings/003/[F003. Symmetric denial of service]#

* [inner]#link:/web/findings/047/[F047. Automatic information enumeration]#

* [inner]#link:/web/findings/053/[F053. Lack of protection against brute force attacks]#

* [inner]#link:/web/findings/108/[F108. Improper control of interaction frequency]#

== References

. [[r1]] link:https://cwe.mitre.org/data/definitions/770.html[CWE-770: Allocation of Resources Without Limits or Throttling].
The software allocates a reusable resource or group of resources on behalf of
an actor without imposing any restrictions on the size or number of resources
that can be allocated,
in violation of the intended security policy for that actor.

. [[r2]] link:https://cwe.mitre.org/data/definitions/799.html[CWE-799: Improper Control of Interaction Frequency].
The software does not properly limit the number or frequency of interactions
that it has with an actor,
such as the number of incoming requests.

. [[r3]] link:https://owasp.org/www-project-application-security-verification-standard/[OWASP-ASVS v4.0.1
V2.2 General Authenticator Requirements.(2.2.1)]
Verify that anti-automation controls are effective at mitigating breached
credential testing, brute force, and account lockout attacks.
Such controls include blocking the most common breached passwords,
soft lockouts, rate limiting, CAPTCHA, ever increasing delays between attempts,
IP address restrictions,
or risk-based restrictions such as location, first login on a device,
recent attempts to unlock the account, or similar.
Verify that no more than 100 failed attempts per hour is possible on a single
account.

. [[r4]] link:https://owasp.org/www-project-application-security-verification-standard/[OWASP-ASVS v4.0.1
V8.1 General Data Protection.(8.1.4)]
Verify the application can detect and alert on abnormal numbers of requests,
such as by IP, user, total per hour or day, or whatever makes sense for the
application.

. [[r5]] link:https://owasp.org/www-project-application-security-verification-standard/[OWASP-ASVS v4.0.1
V11.1 Business Logic Security Requirements.(11.1.2)]
Verify the application will only process business logic flows with all steps
being processed in realistic human time,
i.e. transactions are not submitted too quickly.

. [[r6]] link:https://owasp.org/www-project-application-security-verification-standard/[OWASP-ASVS v4.0.1
V11.1 Business Logic Security Requirements.(11.1.3)]
Verify the application has appropriate limits for specific business actions or
transactions which are correctly enforced on a per user basis.

. [[r7]] link:https://owasp.org/www-project-application-security-verification-standard/[OWASP-ASVS v4.0.1
V11.1 Business Logic Security Requirements.(11.1.4)]
Verify the application has sufficient anti-automation controls to detect and
protect against data exfiltration, excessive business logic requests, excessive
file uploads or denial of service attacks.

. [[r8]] link:https://owasp.org/www-project-application-security-verification-standard/[OWASP-ASVS v4.0.1
V11.1 Business Logic Security Requirements.(11.1.5)]
Verify the application has business logic limits or validation to protect
against likely business risks or threats, identified using threat modelling or
similar methodologies.

. [[r9]] link:https://owasp.org/www-project-application-security-verification-standard/[OWASP-ASVS v4.0.1
V12.1 File Upload Requirements.(12.1.3)]
Verify that a file size quota and maximum number of files per user is enforced
to ensure that a single user cannot fill up the storage with too many files,
or excessively large files.
