:slug: rules/362/
:category: authentication
:description: This requirement establishes the importance of assigning MFA mechanisms to only one account.
:keywords: MFA, Authenticatino, Authenticator, Single, Account, ASVS, CWE, OWASP, PCI DSS, Rules, Ethical Hacking, Pentesting
:rules: yes

= R362. Assign MFA mechanisms to a single account

== Requirement

The system must associate each secondary authentication mechanism with a single
account.

== Description

Single-factor authentication mechanisms often offer poor security due to
the weak, common or easy-to-guess passwords that users tend to set.
Secondary authentication mechanisms,
such as physical or logical security tokens, smart cards, and certificates,
help guarantee the identity of actors trying to authenticate.
However, their value highly decreases when they are shared by multiple
accounts.

== References

. [[r1]] link:https://cwe.mitre.org/data/definitions/287.html[CWE-287: Improper Authentication]
When an actor claims to have a given identity,
the software does not prove or insufficiently proves that the claim is correct.

. [[r2]] link:https://owasp.org/www-project-top-ten/OWASP_Top_Ten_2017/Top_10-2017_A2-Broken_Authentication[OWASP Top 10 A2:2017-Broken Authentication].
Application functions related to authentication and session management are
often implemented incorrectly,
allowing attackers to compromise passwords, keys, or session tokens,
or to exploit other implementation flaws to assume other users' identities
temporarily or permanently.

. [[r3]] link:https://owasp.org/www-project-application-security-verification-standard/[OWASP-ASVS v4.0.1
V1.2 Authentication Architectural Requirements.(1.2.4)]
Verify that all authentication pathways and identity management APIs implement
consistent authentication security control strength,
such that there are no weaker alternatives per the risk of the application.

. [[r4]] link:https://www.pcisecuritystandards.org/documents/PCI_DSS_v3-2-1.pdf[PCI DSS v3.2.1 - Requirement 6.5.10]
Address common coding vulnerabilities in software-development processes such as
broken authentication and session management.

. [[r5]] link:https://www.pcisecuritystandards.org/documents/PCI_DSS_v3-2-1.pdf[PCI DSS v3.2.1 - Requirement 8.5]
Do not use group, shared, or generic IDs, passwords, or other authentication
methods.

. [[r6]] link:https://www.pcisecuritystandards.org/documents/PCI_DSS_v3-2-1.pdf[PCI DSS v3.2.1 - Requirement 8.6]
Authentication mechanisms must be assigned to an individual account and not
shared among multiple accounts.
