:slug: rules/325/
:category: architecture
:description: This document contains the details of the security requirements related to the definition and management of resources and services in the organization. This requirement establishes the importance of restricting access to WSDL files containing sensitive information.
:keywords: WSDL, File, Web, Services, ASVS, CWE
:rules: yes

= REQ.325 Protect WSDL files

== Requirement

WSDL files containing sensitive information must not be publicly accessible.


== Description

Some web services architectures require exposing a WSDL file.
If this file contains sensitive information such as deprecated methods or
administrative services,
it should not be available to a wider audience than it requires.
If it must be available on a very public network such as the internet,
then it must not contain any sensitive information.

== Findings

* [inner]#link:/web/findings/040/[F040. Exposed web services]#

== References

. [[r1]] link:https://cwe.mitre.org/data/definitions/651.html[CWE-651: Exposure of WSDL File Containing Sensitive Information]
The Web services architecture may require exposing a Web Service Definition
Language (WSDL) file that contains information on the publicly accessible
services and how callers of these services should interact with them
(e.g. what parameters they expect and what types they return).
