:slug: rules/348/
:category: architecture
:description: This requirement establishes the importance of using consistent encoding across system components.
:keywords: Consistent, Output, Encoding, Parsing, ASVS, CWE, Rules, Ethical Hacking, Pentesting
:rules: yes

= R348. Use consistent encoding

== Requirement

System components must use the same encodings and parsers.

== Description

System components use structured messages to communicate with other components.
When these messages include input from untrusted sources and this input is not
properly escaped,
they become prone to the insertion of malicious commands.
A part of the escaping process can be done by encoding the output messages.
However, all components must use consistent encoding in order to prevent
attacks that benefit from the presence of different parsing behaviors.
E.g. Server-Side Request Forgery (*SSRF*) and Remote File Inclusion (*RFI*)
attacks.

== References

. [[r1]] link:https://cwe.mitre.org/data/definitions/116.html[CWE-116: Improper Encoding or Escaping of Output].
The product does not validate or incorrectly validates input that can affect
the control flow or data flow of a program.

. [[r2]] link:https://owasp.org/www-project-application-security-verification-standard/[OWASP-ASVS v4.0.1
V13.1 Generic Web Service Security Verification Requirements.(13.1.1)]
Verify that all application components use the same encodings and parsers to
avoid parsing attacks that exploit different *URI* or file parsing behavior
that could be used in *SSRF* and *RFI* attacks.
