:slug: kb/lenguajes/javascript/implementar-estructura-condicional
:eth: no
:category: javascript
:kb: yes

= Implementar Estructura Condicional

== Necesidad

Estructura condicional en JavaScript

== Contexto

A continuación se describen las circunstancias bajo las cuales la siguiente 
solución tiene sentido:

. Se utiliza el lenguaje JavaScript.
. Se necesitan implementar estructuras condicionales de manera segura.

== Solución

. En cada estructura condicional empleada en una aplicación JavaScript, se 
recomienda contemplar todos los posibles escenarios.
* Para sentencias if debe usarse su correspondiente else [1].
* Para sentencias switch debe usarse su correspondiente default [2].
. El siguiente muestra el uso correcto de la sentencia if, primero creamos una 
función que nos retornará un número aleatorio entre un rango especificado:
[source, js, linenums]
----
function getRandomInt(min, max) {
  return Math.floor(Math.random() * (max - min + 1)) + min;
}
----

[start=3]
. Obtenemos un valor aleatorio entre 0 y 2, y comparamos este utilizando 
if/else.
[source, js, linenums]
----
var args = getRandomInt(0,2);
if (args <= 1)
{
  console.log("args is smaller than one");
} else {
   console.log("args is bigger than one ");
}
----

[start=4]
. El siguiente muestra el uso correcto de la sentencia switch, se debe incluir 
el caso default:
[source, js, linenums]
----
var val = getRandomInt(1,4);
switch(val) {
 case 1:
  console.log("val is 1");
  break;
 case 2:
  console.log("val is 2");
  break;
 default:
  console.log("val is not 1 or 2");
}
----

== Referencias

. https://developer.mozilla.org/es/docs/Web/JavaScript/Referencia/Sentencias/switch[switch - JavaScript MDN]
. https://developer.mozilla.org/es/docs/Web/JavaScript/Referencia/Sentencias/if...else[if...else - JavaScript MDN]
. REQ.0156 El código debe definir opciones por defecto seguras (ej: default en switchs).
