:slug: rules/145/
:category: cryptography
:description: This document contains the details of the security requirements related to definition and management of cryptographic systems. This requirement establishes the importance of protecting system cryptographic keys in order to prevent leakages of encrypted sensitive information.
:keywords: Asymmetric, Symmetric, Cryptography, Keys, ASVS, CWE
:rules: yes

= REQ.145 Protect system cryptographic keys

== Requirement

System private asymmetric or symmetric keys must be protected
and must not be exposed.

== Description

System cryptographic keys are essential for maintaining the confidentiality
and integrity of transactions and communications.
Their exposure may cause business information leakages, loss of data integrity
and loss of trust due to the inability to differentiate server traffic from
malicious traffic.
Therefore, these keys must be protected and managed following industry-verified
standards.

== Findings

* link:/web/findings/0016/[FIN.S.0016. Non-parameterized cryptographic key]

== References

. [[r1]] link:https://cwe.mitre.org/data/definitions/321.html[CWE-321: Use of Hard-coded Cryptographic Key]
The use of a hard-coded cryptographic key significantly increases the
possibility that encrypted data may be recovered.

. [[r2]] link:https://cwe.mitre.org/data/definitions/322.html[CWE-322: Key Exchange without Entity Authentication]
The software performs a key exchange with an actor without verifying the
identity of that actor.

. [[r3]] link:https://cwe.mitre.org/data/definitions/323.html[CWE-323: Reusing a Nonce, Key Pair in Encryption]
Nonces should be used for the present occasion and only once.

. [[r4]] link:https://cwe.mitre.org/data/definitions/324.html[CWE-324: Use of a Key Past its Expiration Date]
The product uses a cryptographic key or password past its expiration date,
which diminishes its safety significantly by increasing the timing window for
cracking attacks against that key.

. [[r5]] link:https://owasp.org/www-project-application-security-verification-standard/[OWASP-ASVS v4.0.1
V1.6 Cryptographic Architectural Requirements.(1.6.1)]
Verify that there is an explicit policy for management of cryptographic keys
and that a cryptographic key lifecycle follows a key management standard such
as **NIST SP 800-57**.

. [[r6]] link:https://owasp.org/www-project-application-security-verification-standard/[OWASP-ASVS v4.0.1
V1.6 Cryptographic Architectural Requirements.(1.6.2)]
Verify that consumers of cryptographic services protect key material and other
secrets by using key vaults or API based alternatives.

. [[r7]] link:https://owasp.org/www-project-application-security-verification-standard/[OWASP-ASVS v4.0.1
V1.6 Cryptographic Architectural Requirements.(1.6.3)]
Verify that all keys and passwords are replaceable and are part of a
well-defined process to re-encrypt sensitive data.

. [[r8]] link:https://owasp.org/www-project-application-security-verification-standard/[OWASP-ASVS v4.0.1
V1.6 Cryptographic Architectural Requirements.(1.6.4)]
Verify that symmetric keys, passwords, or API secrets generated by or shared
with clients are used only in protecting low risk secrets,
such as encrypting local storage, or temporary ephemeral uses such as parameter
obfuscation.
