:slug: rules/046/
:category: files
:description: This requirement establishes that the system must manage through logs the integrity of critical files.
:keywords: System, Log, File, Integrity, Security, ASVS, CAPEC, CWE, PCI DSS, Rules, Ethical Hacking, Pentesting
:rules: yes

= R046. Manage the integrity of critical files

== Requirement

The system must verify
and log changes in the integrity of critical system files.

== References

. [[r1]] link:http://capec.mitre.org/data/definitions/13.html[CAPEC-13: Subverting Environment Variable Values].
The attacker directly or indirectly modifies environment variables used by or
controlling the target software.

. [[r2]] link:https://cwe.mitre.org/data/definitions/778.html[CWE-778: Insufficient Logging].
When a security-critical event occurs,
the software either does not record the event or omits important details about
the event when logging it.

. [[r3]] link:https://owasp.org/www-project-application-security-verification-standard/[OWASP-ASVS v4.0.1
V14.1 Build.(14.1.5)]
Verify that authorized administrators can verify the integrity of all
security-relevant configurations to detect tampering.

. [[r4]] link:https://www.pcisecuritystandards.org/documents/PCI_DSS_v3-2-1.pdf[PCI DSS v3.2.1 - Requirement 10.2.2]
Implement automated audit trails for all system components to reconstruct all
actions taken by any individual with root or administrative privileges.

. [[r5]] link:https://www.pcisecuritystandards.org/documents/PCI_DSS_v3-2-1.pdf[PCI DSS v3.2.1 - Requirement 10.2.6]
Implement automated audit trails for all system components to reconstruct
creation and deletion of system-level objects.

. [[r6]] link:https://www.pcisecuritystandards.org/documents/PCI_DSS_v3-2-1.pdf[PCI DSS v3.2.1 - Requirement 10.4.2]
Time data is protected.

. [[r7]] link:https://www.pcisecuritystandards.org/documents/PCI_DSS_v3-2-1.pdf[PCI DSS v3.2.1 - Requirement 10.5.5]
Use file-integrity monitoring or change-detection software on logs to ensure
that existing log data cannot be changed without generating alerts.
