:slug: events/securing-device/
:category: events
:description: This page aims to inform the customer about the different talks offered by Fluid Attacks. Securing your Mobile Device conference aims to inform about the risks that smartphone users are constantly exposed and unaware of, as well as the implications and countermeasures to mitigate those risks.
:keywords: Fluid Attacks, Talks, Mobile Device, Events, Security, Smartphone

= Securing your Mobile Device

== 1. Objective

This talk was designed to show the risks
related with the information stored on your Smartphone.

== 2. Content

During the speech,
we will address a set of information risks
related to the use of smartphones
in a way that each assistant can understand them,
realize their implications
and know the necessary controls to mitigate the risks.

== 3. Experience

This conference has been presented for +5+ years
in large companies, such as:
link:https://www.grupobancolombia.com/wps/portal/personas[Bancolombia],
link:https://www.negocioleonisa.com/wps/portal/colombia[Leonisa],
link:http://www.tuya.com.co/[Tuya] and link:http://www.celsia.com/[Celsia].

== 4. Where?

The presentation can be hosted
at your company's facilities or an external venue.

The talk can be scheduled in Medellín, for a minimum audience of +10+ assistants
For other cities of Colombia, Central America, Ecuador and Perú,
the minimum audience is +20+ assistants.

== 5. Duration

The conference has a duration of +2+ hours.
(Duration may vary between 1½ hours and 2½ hours)

== 6. When?

[button]#link:../#when[When]#

== 7. Public

The conference is suitable for people
with basic or low technical knowledge, ideally smartphone users.
The maximum number of assistants is +30+.

== 8. Requirements

[button]#link:../#requirements[Requirements]#

== 9. Speaker

Licenciate in Education, with +15+ years of experience.
+Fluid Attacks+ Co-founder.
Information Security Systems Auditor.
