:slug: defends/java/fortaleza-contrasena-dic/
:category: java
:description: Nuestros ethical hackers explican cómo evitar vulnerabilidades de seguridad mediante la programación segura en Java al comprobar la fortaleza de las contraseñas con un diccionario común de palabras, ésto permite crear contraseñas seguras y resistentes a ataques de tipo fuerza bruta.
:keywords: Java, Seguridad, Comprobar, Contraseña, Diccionario, Fortaleza.
:defends: yes

= Comprobar Fortaleza de Contraseña con Diccionarios

== Necesidad

Comprobar fortaleza de contraseña por medio de diccionarios en +Java+.

== Contexto

A continuación se describen las circunstancias
bajo las cuales la siguiente solución tiene sentido:

. Se está desarrollando una aplicación en +Java+.
. Se requiere comprobar la fortaleza
de una contraseña por medio de diccionarios.
. El sistema operativo o el administrador del sistema
poseen diccionarios con palabras comunes.

== Solución

El siguiente código dará solución a la necesidad de comprobar
la fortaleza de una contraseña
al buscarla en diccionarios que contienen palabras comunes:

. Iniciamos el desarrollo de la aplicación importando las clases necesarias
y definiendo el nombre de nuestra clase.
+
.Ditionary.java
[source, java, linenums]
----
import java.io.*;

public class Dictionary {
----

. El método +main+ será el encargado de llamar
al método +isPasswordInDictionary+,
método encargado de hacer la búsqueda de la contraseña.
+
[source, java, linenums]
----
public static void main(String[] args) {
  try {
----

. Establecemos la ruta del diccionario y se imprime el resultado.
+
[source, java, linenums]
----
String diccionario = "C:\\passwords.txt";
System.out.println(isPasswordInDictionary(diccionario, "123"));
System.out.println(isPasswordInDictionary(diccionario, "hello"));
System.out.println(isPasswordInDictionary(diccionario, "admin"));
System.out.println(isPasswordInDictionary(diccionario, "SystEM"));
System.out.println(isPasswordInDictionary(diccionario, "MyStr0n6_P4assw0rd!"));
----

. Capturamos las excepciones posibles.
+
[source, java, linenums]
----
  }
  catch (FileNotFoundException e) {
    System.err.println("Diccionario no encontrado");
  }
  catch (IOException e) {
    System.err.println("Error de entrada/salida de datos");
  }
}
----

. El método principal es el encargado
de abrir el archivo de diccionario y buscar la contraseña.
Retornará falso si la contraseña no se encuentra en el diccionario,
y verdadero en cualquier otro escenario.

. Iniciamos definiendo los parámetros
+dictionaryFilePath+ que contiene la ruta al diccionario
y +password+ que es la contraseña.
El método arroja las excepciones posibles,
las cuales deben ser controladas por el método que invocó la llamada.
+
[source, java, linenums]
----
public static boolean isPasswordInDictionary(String dictionaryFilePath, String password)
   throws FileNotFoundException, IOException {
----

. Se abre el archivo del diccionario con la clase +BufferedReader+,
la cual permite leer archivos de mucho contenido
con un buen manejo de memoria.
Se define igualmente la variable que contendrá
la palabra leída del diccionario.
+
[source, java, linenums]
----
BufferedReader dictionary = new BufferedReader(new FileReader(dictionaryFilePath));
String word = "";
----

. Se itera a través de cada palabra en el archivo,
si coincide con la contraseña entonces se retorna verdadero,
en otro caso se retorna falso.
Solo probamos palabras que tengan más de dos caracteres
para evitar problemas con diccionarios que tengan letras o sílabas.
+
[source, java, linenums]
----
  while ((word = dictionary.readLine()) != null) {
    if (word.length() > 2 && password.indexOf(word) != -1) {
      return true;
    }
  }
  return false;
  }
}
----

. La siguiente es una lista de diccionarios
que se recomiendan para hacer la búsqueda
* link:http://dazzlepod.com/uniqpass/[UNIQPASS v18]
* link:http://www.openwall.com/wordlists/[Openwall wordlists collection]
* link:http://wordlist.aspell.net/[SCOWL]
* link:https://packetstormsecurity.com/Crackers/wordlists/[packet storm]
* link:http://www.deer-run.com/~hal/sysadmin/pam_cracklib.html[A Friendly Warning]

. Para +GNU/Linux+ se recomienda utilizar los diccionarios incluidos
con el sistema operativo que se encuentran en la ruta +/usr/share/dict/+.

. El resultado para la anterior aplicación es el siguiente:

[width="60%", options="header,footer", frame="topbot"]
|============================
|Palabra |Resultado
|123 |true
|hello |true
|admin |true
|SystEM |true
|My-Str0n6_P4assw0rd! |false
|===========================

== Descargas

Puedes descargar el código fuente
pulsando en el siguiente enlace:

[button]#link:src/dictionary.java[Dictionary.java >>]#
Código de Ejemplo.


== Referencias

. [[r1]] link:http://web.mit.edu/rhel-doc/4/RH-DOCS/rhel-sg-es-4/s1-wstation-pass.html[Seguridad de contraseñas]
. [[r2]] link:https://github.com/duyetdev/bruteforce-database[Bruteforce Database - Password dictionaries]
