:slug: defends/cobol/usar-condicionales/
:category: cobol
:description: Nuestros ethical hackers explican como evitar vulnerabilidades de seguridad mediante la programacion segura en COBOL al contemplar todos los escenarios posibles en una estructura condicional que pueda dar origen a comportamientos erróneos dentro de la aplicación.
:keywords: COBOL, Variables, Condicionales, Inicializar, IF, ELSE.
:defends: yes

= Usar Estructuras Condicionales

== Necesidad

Usar estructuras condicionales contemplando todos los escenarios posibles
y valores por defecto en +COBOL+.

== Contexto

A continuación se describe las circunstancias
bajo las cuales la siguiente solución tiene sentido:

. Se dispone de una aplicación desarrollada en +COBOL+.
. El código debe ser invocado en algún escenario<<r1,^[1]^>>.
. El código debe de inicializar las variables que se crean<<r2,^[2]^>>.

== Solución

. En cada estructura condicional empleada en una aplicación +COBOL+,
se recomienda contemplar todos los posibles escenarios
como se muestra en esta entrada.
A continuación, se inicia la aplicación de prueba
declarando la división +IDENTIFICATION DIVISION+:
+
.cobolcond.cbl
[source,cobol,linenums]
----
       IDENTIFICATION DIVISION.
      ******************
      * Identification *
      ******************
       PROGRAM-ID. COBOLCOND.
----
+
En el anterior bloque de código,
mediante la sentencia +PROGRAM-ID+
se estable el nombre del programa a +COBOLCOND+.

. La división de datos +DATA DIVISION+ contiene dos variables:
+PLANET-NUMBER+ de tipo numérico con dos dígitos
y +PLANET-NAME+ con soporte para ocho caracteres.
Además, en cumplimiento del requisito:
"El código debe de inicializar las variables que crea.",
se deben inicializar todos los valores de las variables
a través del uso de la palabra clave +VALUE+.
Para este caso, "3" y "Tierra"
son los valores iniciales
para las variables +PLANET-NUMBER+ y +PLANET-NAME+ respectivamente:
+
[source,cobol,linenums]
----
      ********
      * Data *
      ********
       DATA DIVISION.
       WORKING-STORAGE SECTION.
       01 PLANET.
           05 PLANET-NUMBER PIC 9(2) VALUE 3.
           05 PLANET-NAME   PIC X(8) VALUE "Tierra".
----
. En la división +PROCEDURE DIVISION+
se encuentra la lógica del programa:
+
[source,cobol,linenums]
----
      ********
      * Main *
      ********
       PROCEDURE DIVISION.
       MAIN.
----
. En un ciclo escogemos los planetas impares
(El valor inicial del número
es 3 por lo que al ir sumando 2 vemos los impares),
mostramos su número y su nombre.
En la primer visualización,
el programa debe imprimir
los valores por defecto inicializados en la división +DATA DIVISION+:
+
[source,cobol,linenums]
----
       DISPLAY PLANET-NUMBER, " - ", PLANET-NAME.

       PERFORM 3 TIMES
           COMPUTE PLANET-NUMBER = PLANET-NUMBER + 2
----
. Con la palabra clave +EVALUATE+^<<r3,[3]>>,<<r4,[4]>>^
se determina el nombre del planeta según su número,
note como se toma en cuenta el escenario por defecto
a través de la palabra clave +OTHER+
(El escenario por defecto
es cuando el número no coincide con el de algún planeta):
+
[source,cobol,linenums]
----
           EVALUATE PLANET-NUMBER
               WHEN 1 MOVE "Mercurio" TO PLANET-NAME
               WHEN 2 MOVE "Venus   " TO PLANET-NAME
               WHEN 3 MOVE "Tierra  " TO PLANET-NAME
               WHEN 4 MOVE "Marte   " TO PLANET-NAME
               WHEN 5 MOVE "Jupiter " TO PLANET-NAME
               WHEN 6 MOVE "Saturno " TO PLANET-NAME
               WHEN 7 MOVE "Urano   " TO PLANET-NAME
               WHEN 8 MOVE "Neptuno " TO PLANET-NAME
               WHEN OTHER MOVE "Invalido" TO PLANET-NAME
           END-EVALUATE

           DISPLAY PLANET-NUMBER, " - ", PLANET-NAME
       END-PERFORM.
----
. Por medio de la instrucción +ACCEPT+
se obtiene el número ingresado por el usuario:
+
[source,cobol,linenums]
----
       DISPLAY "Ingrese un numero de planeta".
       ACCEPT PLANET-NUMBER.
----
. Usando el condicional +IF+^<<r5,[5]>>,<<r6,[6]>>^
se determina el tipo de planeta,
observe nuevamente como se deben considerar
todos los escenarios por defecto
a través del uso de la sentencia +ELSE+:
+
[source,cobol,linenums]
----
       IF PLANET-NUMBER IS >= 1 AND PLANET-NUMBER IS <= 8
           IF PLANET-NUMBER IS < 5
               DISPLAY "Planeta interior"
           ELSE
               DISPLAY "Planeta exterior"
           END-IF
       ELSE
           DISPLAY "Tipo de planeta desconocido"
       END-IF

       STOP RUN.
----
. La salida para el anterior programa es la siguiente:
+
[source,cobol,linenums]
----
       03 - Tierra
       05 - Jupiter
       07 - Urano
       09 - Invalido
       Ingrese un numero de planeta
       10
       Tipo de planeta desconocido
----

== Descargas

Puedes descargar el código fuente
pulsando en el siguiente enlace:

. [button]#link:src/cobolcond.cbl[cobolcond.cbl]# contiene
la implementación del código anterior.

== Referencias

. [[r1]] link:../../../rules/161/[REQ.161 Opciones por defecto seguras].
. [[r2]] link:../../../rules/168/[REQ.168 Variables inicializadas explícitamente].
. [[r3]] link:https://www.ibm.com/support/knowledgecenter/SSQ2R2_9.1.1/com.ibm.ent.dbt.zos.doc/rmdita/rcmdeva.html[EVALUATE command (COBOL)].
. [[r4]] link:http://www.fluffycat.com/COBOL/Evaluate/[COBOL Evaluate].
. [[r5]] link:https://www.ibm.com/support/knowledgecenter/en/SS6SG3_4.2.0/com.ibm.entcobol.doc_4.2/PGandLR/tasks/tpctl05.htm[Using nested IF statements].
. [[r6]] link:http://www.fluffycat.com/COBOL/If-and-End-If/[COBOL If And End If].
