const CI_COMMIT_REF_NAME: string = "__CI_COMMIT_REF_NAME__";
const CI_COMMIT_SHA: string = "__CI_COMMIT_SHA__";
const CI_COMMIT_SHORT_SHA: string = "__CI_COMMIT_SHORT_SHA__";
const ASM_BUCKET_NAME: string = "__INTEGRATES_BUCKET_NAME__";
const ASM_DEPLOYMENT_DATE: string = "__INTEGRATES_DEPLOYMENT_DATE__";

export {
  CI_COMMIT_REF_NAME,
  CI_COMMIT_SHA,
  CI_COMMIT_SHORT_SHA,
  ASM_BUCKET_NAME,
  ASM_DEPLOYMENT_DATE,
};
