:slug: rules/039/
:category: rules
:description: En el presente documento se detallan los requerimientos de seguridad relacionados a la gestión de archivos dentro de la organización. Por lo tanto, en este requerimiento se recomienda que los archivos del sistema tengan definido un tamaño máximo permitido.
:keywords: Sistema, Tamaño, Archivo, MB, Seguridad, Usuario.
:rules: yes

= REQ.039 Establecer tamaño máximo de archivos

== Requisito

Los archivos operados en un sistema
y los manipulados por los usuarios
deben tener un tamaño máximo definido (`5MB` recomendado).

== Descripción

Cuando en un sistema se permita adjuntar archivos para ser almacenados,
se debe definir un tamaño máximo para estos,
de esta forma se evitan inconvenientes de disponibilidad del servicio
o se disminuye la posibilidad
de que se adjunten archivos que puedan tener `software` malicioso.

== Implementación

Para establecer el límite de manejo de archivos
se debe identificar las necesidades reales de información,
el tamaño de la infraestructura
y la necesidad real de almacenamiento de información.
La organización puede definir un límite por defecto de manejo de información
y en caso de ser necesario
establecer algunas excepciones para aumentar el tamaño del manejo de archivos,
pero en todo caso se debe establecer un límite claro
de forma que se eviten denegaciones del servicio
por abuso en el consumo de almacenamiento.

== Ataques

. Una aplicación cuenta con la funcionalidad de subir y almacenar archivos,
un usuario del sistema
sube archivos de gran tamaño
hasta causar una denegación de servicio
por falta de espacio de almacenamiento.

== Atributos

* Capa: Aplicación.
* Activo: Archivos.
* Alcance: Disponibilidad.
* Fase: Operación.
* Tipo de Control: Recomendación.
