:slug: kb/linux/limitar-sesiones-concurrentes/
:eth: no
:category: linux
:kb: yes

= Limitar Número de Sesiones Concurrentes por Usuario

== Necesidad

Limitar número de sesiones concurrentes por usuario en Linux

== Contexto

A continuación se describen las circunstancias bajo las cuales la siguiente 
solución tiene sentido:

. Se dispone de un servidor con un sistema operativo basado en Linux.

== Solución

. Para limitar el número de sesiones concurrentes por usuario en el sistema 
operativo y así evitar la falta de trazabilidad en el momento de ocurrencia de 
un incidente de seguridad se debe editar el archivo/etc/security/limits.conf 
agregando las siguientes líneas:
+
[source, shell, linenums]
----
# /etc/security/limits.conf 
# 
#Cada línea describe los límites para el usuario de la forma: 
# 
#<dominio> <tipo> <ítem> <valor> 
# 
#Donde: 
#<dominio>: 
# - el comodín *, para indicar cualquier usuario 
# - si la restricción aplica para el usuario root, 
# entonces se debe usar literalmente "root" 
# 
#<tipo>: 
# - "hard" para forzar el límite 
# 
#<item>: 
# - maxlogins - número máximo de sesiones por usuario 
# 
#<domain> <type> <item> <value> 
# 
# El valor indica el número de sesiones concurrentes máximas por usuario 
# requeridas por las políticas de seguridad de la organización 
* hard maxlogins 1 
root hard maxlogins 1 
----

. Al realizar una conexión a través de SSH y sobrepasar el número máximo de 
sesiones concurrentes se puede apreciar el siguiente mensaje:
+
[source, shell, linenums]
----
login as: FLUID 
FLUID@192.168.0.106's password: 

Linux FLUIDTools 3.12-kali1-686-pae #1 SMP Debian 3.12.6-2kali1 (2014-01-06) i686 
The programs included with the Kali GNU/Linux system are free software; 
the exact distribution terms for each program are described in the 
individual files in /usr/share/doc/*/copyright. 
Kali GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent 
permitted by applicable law. 
Too many logins for 'FLUID'. 
Last login: Tue Mar 18 22:35:38 2014 from 192.168.0.100
----

. El cual indica que el usuario FLUID ha sobrepasado el número de 
sesiones concurrentes el cual fue establecido en 1.

== Referencias

. REQ.0025:	Las sesiones concurrentes de un sistema se deben controlar o 
informar
