# SPDX-FileCopyrightText: 2022 Fluid Attacks <development@fluidattacks.com>
#
# SPDX-License-Identifier: MPL-2.0

FROM leafney/docker-alpine-mysql

ENV MYSQL_ROOT_PWD=iethohnei2EeSh4P

RUN apk update && apk upgrade

COPY . /scripts
