:slug: defends/csharp/proteger-csrf-token/
:category: csharp
:description: Nuestros ethical hackers explican como validar la autenticidad de una petición mediante el uso de un token, para controlar la transferencia de información mediante los formularios de la aplicación con el fin de prevenir ataques de tipo Cross-Site Request Forgery.
:keywords: C Sharp, Buenas Prácticas, Autenticación, Sesion, Token, CSRF.
:defends: yes

= Prevenir ataque CSRF haciendo uso de Tokens

== Necesidad

Prevenir ataque +CSRF+ haciendo uso de +Tokens+ en +C#+.

== Contexto

A continuación se describen las circunstancias
bajo las cuales la siguiente solución tiene sentido:

. La aplicación está construida con el lenguaje de programación +C#+.
. Se utiliza la versión de +.NET Framework 1.0+ ó superior.
. El aplicativo hace uso de métodos +GET+ ó +POST+
para la transferencia de información a través de los formularios.
. Se debe tener acceso al código fuente
para poder modificarlo y añadir la solución.

== Solución

. La naturaleza de los ataques de tipo +CSRF+,
consiste en aprovechar el exceso de confianza
que se tiene con las acciones realizadas por parte del usuario en la plataforma,
especialmente lo que respecta al ingreso de datos a través de los formularios;
ya que no siempre se evalúa la legitimidad de éstos,
y si realmente dichos actos se hicieron a conciencia,
y no generados de manera indirecta desde un aplicativo ajeno a esta.
Con el tiempo se han propuesto varias soluciones para frenar dichos ataques,
entre las que están:

.. Exigir una re-autenticación al usuario
cada vez que el realice una acción en un formulario

.. Comprobar a través del envío de un correo o +SMS+,
la validez o legitimidad de una acción.

. Estas soluciones pueden resultar
bastante exageradas e incómodas en muchos casos,
por este motivo se propuso el uso de un mecanismo,
que de manera automatizada, pudiera verificar las conexiones
realizadas por usuario legítimos,
haciendo un seguimiento a las acciones que estos realicen
en los formularios donde ingresan los datos;
tarea que se realiza haciendo uso de los llamados +Tokens+.

. A continuación, se muestra el código de una función
que describe cómo al visitar una página con un formulario para ingresar datos,
el sistema automáticamente genera un +token+,
el cuál carga en un campo oculto del formulario,
al igual que lo guarda en la sesión del usuario:
+
.ejemplo.asp
[source, csharp, linenums]
----
protected void Page_Load(object sender, EventArgs e) {
  //Se verifica que sea la primer vez que se carga el sitio
  if (!Page.IsPostBack) {
    //Se crea el token
    string CSRF_Token = System.Guid.NewGuid().ToString();

    //Se utiliza como identificador del Token dentro de la sesión, el nombre de la página en la que se encuentra  actualmente
    string page_name = System.IO.Path.GetFileName(HttpContext.Current.Request.Url.AbsolutePath);
    string page_token = page_name + "_ID";

    //Se guarda el Token generado en la sesión, con el identificador que se generó anteriormente para su futura busqueda
    HttpContext.Current.Session[page_token] = CSRF_Token;

    //Se asigna el Token al valor del campo oculto del formulario, que para efectos prácticos se le ha dado el nombre de Token
    Token.Value = CSRF_Token;
  }
}
----

. La función +Page_Load+, es propia de la plataforma +ASP.NET+ bajo código +C#+,
y siempre se ejecuta cuando se carga la página a la que esté asociada;
se verifica que sea la primer vez que se ingresa al sitio web
y que no se ha ejecutado un refresco sobre la interfaz de la página,
como ocurre cuando la página vuelve a cargar
debido a que los datos que se ingresan son procesados en esta misma.
Aunque si la interfaz actual se cierra, y vuelve a abrirse al tiempo,
el +Token+ se renovaría automáticamente.
El motivo de utilizar el nombre de la página como identificador
para la búsqueda del +Token+,
es para poder generar uno por cada formulario al que se ingrese.
A continuación se presenta el código encargado de verificar el +Token+,
una vez se haya ingresado información a través del formulario:
+
[source, csharp, linenums]
----
public void submit(object sender, EventArgs e) {
  //Se verifica que el valor del Token almacenado en sesión, sea igual al valor del campo oculto en el formulario
  string Page_Token = System.IO.Path.GetFileName(HttpContext.Current.Request.Url.AbsolutePath) + "_ID";

  if (Token.Value.ToString() != HttpContext.Current.Session[Page_Token].ToString()) {
    //De no ser los mismos, se cierra limpia y cierra la sesión, y se redirige hacia otro sitio web
    HttpContext.Current.Session.Abandon();
    HttpContext.Current.Session.Clear();
    Response.Redirect("...");
  } else {
    //De ser iguales los valores, se sigue con la ejecución de las instrucciones posteriores al envío de la información
  }
}
----

. El campo oculto en el formulario tendría la siguiente forma:
+
[source, csharp, linenums]
----
<asp:HiddenField ID="Token" runat="server" />
----
. Y el elemento que generaría la ejecución de la verificación del +Token+,
podría ser bien, un botón de las siguientes características:
+
[source, csharp, linenums]
----
<asp:Button ID="btn" Text="Submit" runat="server" OnClick="submit" />
----

. Para concluir, una característica que se podría añadir
para darle más seguridad a la implementación del +Token+,
es asignar un valor a la sesión,
que permita saber el tiempo de vigencia del elemento en cuestión,
de tal manera que al verificarlo, pasado cierto tiempo, este se descarte,
y se tenga que generar uno nuevo.
Aunque esto complicaría el hecho de generar un +Token+ por cada formulario,
pues existiría un tiempo asignado para cada uno,
ocupando bastante espacio en la sesión.
Si se piensa desarrollar un +Token+
que sirva para todos los formularios del aplicativo,
y que tenga un tiempo de vigencia, el código de asignación sería el siguiente:
+
[source, csharp, linenums]
----
  {
    string CSRF_Token = System.Guid.NewGuid().ToString();
    HttpContext.Current.Session["Token"] = CSRF_Token;
    HttpContext.Current.Session["Token_age"] = DateTime.Now;
    Token.Value = CSRF_Token;
  }
----

. Se realizaría una comparación de más, con el índice +Token_age+,
para verificar si el +Token+ ha pasado o no de cierto tiempo,
el cual ya se establece directamente
a conveniencia cuando se esté desarrollando el aplicativo.

== Descargas

Puedes descargar el código fuente
pulsando en el siguiente enlace:

. [button]#link:src/ejemplo.asp[ejemplo.asp]# contiene
todas las instrucciones +C#+ del programa.

== Referencias

. [[r1]] link:http://palpapers.plynt.com/issues/2010Apr/secure-coding-aspdotnet-p2/[Palpapers, securecodingaspdotnet]
. [[r2]] link:http://www.owasp.org/index.php/Cross-Site_Request_Forgery_(CSRF)_Prevention_Cheat_Sheet[OWASP, Cross-SiteRequestForgery(CSRF) Prevention Cheat Sheet]
. [[r3]] link:../../../rules/174/[REQ.174 Transacciones sin patrón discernible]
