:slug: kb/java/generar-aleatorio-seguro/
:eth: no
:category: java
:kb: yes

= Generar Valores Aleatorios de Manera Segura

== Necesidad

Se requiere utilizar una función de generación de números, cadenas o sales 
aleatorias en la aplicación.

== Contexto

A continuación se describen las circunstancias bajo las cuales la siguiente 
solución tiene sentido:

. Se está desarrollando una aplicación en Java 1.4 o superior.
. La aplicación necesita generar números aleatorios usados como identificadores 
que no se almacenan

== Solución

. La clase java.security.SecureRandom proporciona un generador de números 
pseudoaleatorios que cumplen por lo menos con la especificación FIPS 140-2 
sobre pruebas estadísticas para generadores de números aleatorios (Requisitos 
de seguridad de los módulos criptográficos [1]). Adicionalmente, la clase debe 
producir una salida no determinística que por lo tanto requiere que la semilla
no sea predecible y que la salida sean secuencias criptográficamente fuertes 
tal como está descrito en RFC 1750: Recomendaciones de aleatoriedad para la 
seguridad [2].
. Se debe importar la clase !SecureRandom de la biblioteca security.
+
[source, java,linenums]
----
import java.security.SecureRandom;
----

. Se define el método generateRandomNumber en conjunto con SecureRandom, para 
generar un número aleatorio de tipo entero:
. Declaramos el método, retornará un número de tipo int
+
[source, java,linenums]
----
public static int generateRandomNumber() {
----

. Se declara un array de bytes con el tamaño de un entero para sistemas 
operativos de 32 bits
+
[source, java,linenums]
----
byte[] integer = new byte[4];
----

. Se usa SecureRandom y su método nextBytes para llenar aleatoriamente el 
array
+
[source, java,linenums]
----
SecureRandom random = new SecureRandom();
random.nextBytes(integer);
----

. Hacemos uso del método toInt [3] para convertir el array de bytes a entero. 
Retornamos el valor.
+
[source, java,linenums]
----
return toInt(integer);
}

public static int toInt(byte[] bytes) {
int result = 0;
for (int i = 0; i < 4; i++) {
  result = (result << 8) - Byte.MIN_VALUE + (int) bytes[i];
}
 return result;
}
----
 
. Este es el resultado para la generación de números aleatorios
+
[source, shell, linenums]
----
-1061930007 
1168469548 
-1436156118 
1022454756
----

== Referencias

. https://www.seagate.com/files/docs/pdf/es-ES/whitepaper/fips-140-2-faq-mb605.1-1007es.pdf
. http://www.ietf.org/rfc/rfc1750.txt
. http://bethecoder.com/applications/articles/java/basics/how-to-convert-byte-array-to-integer.html
. REQ.0219: Debe usarse el mecanismo criptográfico más seguro ofrecido por la 
plataforma ej: (java.security.SecureRandom) para la generación de números 
aleatorios usados en procesos críticos (ej: generación de ID, mapeo de códigos, 
llaves) 
