:slug: rules/031/
:category: rules
:description: En el presente documento se detallan los requerimientos de seguridad relacionados al manejo de sesiones y variables de sesión de las aplicaciones. Por lo tanto, se recomienda que una vez cerrada la sesión del usuario, el sistema elimine toda la información relacionada a este.
:keywords: Sistema, Cerrar, Sesión, Descartar, Usuario, Datos.
:rules: yes

= REQ.031 Descartar datos de sesión del usuario

== Requisito

Al cerrarse la sesión de un usuario (automática o manual)
se debe descartar los datos relacionados con la sesión del usuario.

== Referencias

. [[r1]] link:https://www.owasp.org/index.php/ASVS_V2_Authentication[`OWASP-ASVS v3.1-2.12`]
Verify that all authentication decisions can be logged,
without storing sensitive session identifiers or passwords.
This should include requests with relevant metadata
needed for security investigations.

. [[r2]] link:https://www.owasp.org/index.php/ASVS_V3_Session_Management[`OWASP-ASVS v3.1-3.2`].
Verificar que la sesiones sean invalidadas
cuando el usuario cierre sesión.

. [[r3]] link:https://www.owasp.org/index.php/ASVS_V9_Data_Protection[`OWASP-ASVS v3.1-9.14`]
Verificar que los datos autenticados
sean eliminados del almacenamiento del cliente,
como el DOM del navegador
una vez finalice la sesión o el cliente.

. [[r4]] link:https://nvd.nist.gov/800-53/Rev4/control/AC-12[`NIST` 800-53 AC-12]
Cierre de sesión: El sistema de información
debe terminar la sesión del usuario cuando se presente
una condición o evento definido por la organización
que requiera la terminación de la sesión.

. [[r5]] link:https://www.bsimm.com/framework/governance/software-security-metrics-strategy.html[`BSSIM9` SM2.6:]
Requerir cierre de sesión de seguridad.
