:slug: kb/aspnet/establecer-opciones-seguras-por-defecto/
:eth: no
:category: aspnet
:kb: yes

= Establecer Opciones Seguras por Defecto en Estructuras Condicionales

== Necesidad

Establecer opciones seguras por defecto en estructuras condicionales (ASP.Net)

== Contexto

A continuación se describe las circunstancias bajo las cuales la siguiente solución tiene sentido:

. Se está desarrollando una aplicación en ASP.Net.

== Solución

En cada estructura condicional empleada en una aplicación ASP.Net, se recomienda contemplar todos los posibles escenarios.

* Para sentencias _if_ debe usarse su correspondiente _else_ [1].

* Para sentencias _switch_ debe usarse su correspondiente _default_ [2].

En el siguiente ejemplo se muestra la forma correcta de utilizar las opciones por defecto _else_ y _default_.

. Se empieza validando que haya más de un argumento al llamar al programa.
+
[source, java,linenums]
----
using System;
class Program
{
    static void Main(string[] args)
    {        
        if (args.Length < 1)
        {
            Console.WriteLine("El programa espera un argumento.");
        }
...
----

. En caso afirmativo, se verifica que el argumento tenga solo un carácter.
+
[source,java,linenums]
----
        else if (args[0].Length == 1)
        {
...
----

. En caso afirmativo, se muestra un mensaje si se eligió la opción 0 ó 1, u otro diferente si se eligió la opción 2.
+
[source,java,linenums]
----
                default:
                    Console.WriteLine("La opción ingresada no es válida.");
                    break;
            }
        }
        else
        {
            Console.WriteLine("Se espera como argumento una opción de un solo carácter.");
        }
    }
}
----

. Se manejan los casos cuando las condiciones anteriores no fueron ciertas.
+
[source,java,linenums]
----
                default:
                    Console.WriteLine("La opción ingresada no es válida.");
                    break;
            }
        }
        else
        {
            Console.WriteLine("Se espera como argumento una opción de un solo carácter.");
        }
    }
}
----

. Se compila y ejecuta el programa con diferentes entradas, comprobando que este se comporta como es esperado ante diferentes tipos de argumentos.

[source,cs,linenums]
----
\>csc DefaultOptions.cs

\>DefaultOptions
El programa espera un argumento.

\>DefaultOptions hola
Se espera como argumento una opción de un solo carácter.

\>DefaultOptions h
La opción ingresada no es válida.

\>DefaultOptions 5
La opción ingresada no es válida.

\>DefaultOptions 0
Primera opción seleccionada.

\>DefaultOptions 1
Primera opción seleccionada.

\>DefaultOptions 2
Segunda opción seleccionada.
----

== Referencias

. https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/if-else[if-else (MSDN)]
. https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/switch[switch (MSDN)]
. REQ.0156: El código debe definir opciones por defecto seguras (ej: default en switchs).
