:slug: rules/065/
:category: rules
:description: En el presente documento se detallan los requerimientos de seguridad relacionados a la gestion segura de los requisitos de seguridad definidos para un determinado sistema. Por lo tanto, dichos requisitos probados deben estar identificados luego de realizar las pruebas de caja blanca.
:keywords: Requisitos, Sistema, Probado, Caja Blanca, Identificar, Seguridad.
:rules: yes

= REQ.065 Identificar requisitos probados

== Requisito

Los requisitos de seguridad efectivamente probados
(en pruebas de caja blanca) deben estar identificados.

== Descripción

Cuando se realice la etapa de pruebas,
se debe establecer qué requisitos fueron efectivamente probados,
durante la prueba pueden existir condiciones
que no permitan probar algunos requisitos definidos para el sistema.

== Implementación

. Es importante que queden claramente definidos los requisitos probados
de forma que se tenga conocimiento de los posibles riesgos
que no fueron evaluados.

. Dentro de la documentación
de los resultados de la prueba
deben quedar establecidos los requisitos que fueron efectivamente probados
y los que no fueron revisados.

== Ataques

. Se materializa un incidente a causa de un requisito no implementado,
en la documentación de pruebas
no se estableció si efectivamente fue revisado
y por lo tanto
no se identificó preventivamente una debilidad a ser solucionada.

== Atributos

* Capa: Negocio.
* Activo: Arquitectura de seguridad.
* Alcance: Adherencia.
* Fase: Pruebas.
* Tipo de Control: Recomendación.
