:slug: products/rules/list/356/
:category: networks
:description: This requirement establishes the importance of establishing mechanisms against sub-domain takeover attacks.
:keywords: Sub-domain, Name, DNS, Takeover, ASVS, OWASP, CWE, Rules, Ethical Hacking, Pentesting
:rules: yes

= R356. Verify sub-domain names

== Requirement

The system should regularly check *DNS* names and sub-domain names in use by
the application for expiry of change.
This helps protect applications from the effects of sub-domain takeover
attacks.

== References

. [[r1]] link:https://cwe.mitre.org/data/definitions/350.html[CWE-350: Reliance on Reverse DNS Resolution for a Security-Critical Action].
The software performs reverse *DNS* resolution on an *IP* address to obtain the
hostname and make a security decision,
but it does not properly ensure that the *IP* address is truly associated with
the hostname.

. [[r2]] link:https://owasp.org/www-project-top-ten/OWASP_Top_Ten_2017/Top_10-2017_A6-Security_Misconfiguration[OWASP Top 10 A6:2017-Security Misconfiguration].
Security misconfiguration is the most commonly seen issue.
This is commonly a result of insecure default configurations,
incomplete or ad hoc configurations, open cloud storage,
misconfigured *HTTP* headers,
and verbose error messages containing sensitive information.
Not only must all operating systems, frameworks, libraries, and applications be
securely configured, but they must be patched/upgraded in a timely fashion.

. [[r3]] link:https://owasp.org/www-project-application-security-verification-standard/[OWASP-ASVS v4.0.1
V10.3 Deployed Application Integrity Controls.(10.3.3)]
Verify that the application has protection from sub-domain takeovers if the
application relies upon *DNS* entries or *DNS* sub-domains,
such as expired domain names, out of date *DNS* pointers or **CNAME**s,
expired projects at public source code repos, or transient cloud **API**s,
serverless functions, or storage buckets (autogen-bucket-id.cloud.example.com)
or similar.
Protections can include ensuring that *DNS* names used by applications are
regularly checked for expiry or change.
