:slug: kb/aspnet/evitar-codigo-fuente-duplicado
:eth: no
:category: aspnet
:kb: yes

= Evitar Código Fuente Duplicado

== Necesidad

Evitar código fuente duplicado en ASP.Net.

== Contexto

A continuación se describe las circunstancias bajo las cuales la siguiente solución tiene sentido:

. Se está desarrollando una aplicación en ASP.Net.

. Se desea evitar código fuente duplicado en la aplicación.

== Solución

. Es común encontrar código duplicado en diferentes tipos de aplicaciones, esta duplicación representa trabajo, riesgo y complejidad adicional, por lo que evitar duplicar código fuente es importante para mantener la seguridad de la aplicación. [2]
Declaramos la nueva clase y una constante para depurar los mensajes:
+
[source, java, linenums]
----
  class Reuse
    {
        private static bool DEBUG = true;
----
+
. El método main llama a dos métodos que generan errores, estos errores son imprimidos en pantalla si la constante de depuración tiene el valor verdadero:
+
[source, java, linenums]
----
        static void Main(string[] args)
        {
            divisionPorCero();
            integerParseInt();
        }
----
+
. El primer método arroja un error de división por cero, vemos que los mensajes de error son imprimidos a través de la salida _e_, con la causa y el mensaje de excepción:
+
[source, java,linenums]
----
   public static void divisionPorCero() {
        try {
            int x = 4;
            int y = x;
            Console.WriteLine("Resultado: "+(22/(x-y)));
            
        } catch (Exception e) {
            if (DEBUG) {
                Console.Error.WriteLine("Error");
                Console.Error.WriteLine("Causa "+e.Source+" "+e.Message);                   
            }
        }
    }
----
+
. Igualmente se define un segundo método que arroja la excepción la clase _Integer_. Termina el programa:
+
[source,java,linenums]
----
        public static void integerParseInt() {
            try
            {
                Console.WriteLine("Resultado: " + int.Parse("FLUID"));

            }
            catch (Exception e)
            {
                if (DEBUG)
                {
                   Console.Error.WriteLine("Error");
                   Console.Error.WriteLine("Causa " + e.Source + " " + e.Message);
                }
            }
        }
----
+
. El error consiste en duplicar el código, si las clases siguen creciendo y se continua la metodología de duplicar el código, cambios futuros en la aplicación como eliminar el mensaje causa, filtrar ciertas palabras de las excepciones, entre otros, pueden llegar a causar una fuga de información.
+
Si los mensajes de error son manejados de forma centralizada, el cambio se hace únicamente en un lugar, por lo que a un crecimiento futuro no representaría riesgo de fuga de información.
Para evitar duplicar código se debe abstraer las llamadas en común a un nuevo método: Declaramos la nueva clase y una constante para depurar los mensajes:
+
[source,java,linenums]
----
   class Reuse
    {
        private static bool DEBUG = true;
----
+
. El método main llama a dos métodos que generan errores, estos errores son imprimidos en pantalla si la constante de depuración tiene el valor verdadero:
+
[source,java, linenums]
----
        static void Main(string[] args)
        {
            divisionPorCero();
            integerParseInt();

        }
----
+
. El método showError se encargará de ahora en adelante de manejar los mensajes de error. Un cambio en este método se ve reflejado en todas sus demás llamadas:
+
[source,java,linenums]
----
        public static void showError(Exception e)
        {
            if (DEBUG)
            {
                Console.Error.WriteLine("Error");
                Console.Error.WriteLine("Causa " + e.Source + " " + e.Message);
            }
        }
----
+
. Ahora los dos métodos llaman al método _showError_:
+
[source,java,linenums]
----
        public static void divisionPorCero() {
        try {
            int x = 4;
            int y = x;
            Console.WriteLine("Resultado: "+(22/(x-y)));
            
        } catch (Exception e) {
            showError(e);
        }
    }
        public static void integerParseInt() {
            try
            {
                Console.WriteLine("Resultado: " + int.Parse("FLUID"));

            }
            catch (Exception e)
            {
                showError(e);
            }
----

== Referencias

. http://ptgmedia.pearsoncmg.com/images/9780137081073/samplepages/0137081073.pdf[The Clean Coder: A Code of Conduct for Professional Programmers]
. REQ.0157: El código fuente no debe tener funciones, métodos o clases repetidas.