:slug: rules/142/
:category: rules
:description: En el presente documento se detallan los requerimientos de seguridad relacionados a la importancia que tiene en cuanto a vulnerabilidad se refiere, la modificación de todas las credenciales de acceso por defecto con las que cuenta cualquier sistema empaquetado.
:keywords: Requerimiento, Seguridad, Sistema, Datos, Respaldo, Origen.
:rules: yes

= REQ.142 Modificar credenciales de acceso por defecto

== Requisito

La organización debe modificar
todas las credenciales de acceso por defecto de sistemas empaquetados.

== Descripción

Las organizaciones por lo general dejan por defecto
las configuraciones de los productos de terceros
ya que éstas se adaptan a la mayoría de entornos en donde se instalan
y facilitan de esta forma el despliegue a producción,
pero con esto se dejan abiertas las puertas por defecto a los productos
y en la mayoría de los casos las credenciales
se encuentran en la documentación de los proveedores
que se encuentran fácilmente en internet.
Por esta razón es importante revisar todas las configuraciones
antes del despliegue y eliminar todas las credenciales
que se encuentren por defecto,
ya que si se dejan los usuarios es posible acceder por medio de fuerza bruta.

==  Implementación

. Eliminar todas las credenciales predeterminadas
por el proveedor del producto.

. Implementar un mecanismo
para que solo las personas con permisos de administración
accedan a las consolas de accesos a los productos.

. Crear una política de credenciales fuertes
que garanticen la seguridad de todas las credenciales de la organización.

. Las contraseñas deben ser cambiadas
cada cierto tiempo para evitar el robo de estas.

. Realizar auditorías periódicamente
para detectar configuraciones incorrectas o parches faltantes.

== Ataques

. Ataques de fuerza bruta
. Fuga de información: Técnica

== Atributos

* Capa: Capa de Negocio
* ​Activo: Credenciales de acceso
* Alcance: Confidencialidad
* ​Fase: Despliegue
* ​Tipo Control: Recomendación

== Referencias

. [[r1]] link:https://www.pcisecuritystandards.org/documents/PCI_DSS_v3-2es-LA.pdf[PCI DSS - Requisito 2.2.d]
. [[r2]] link:https://www.owasp.org/index.php/Top_10_2013-A5-Security_Misconfiguration[OWASP - Top 10 2013: A5]
. [[r3]] link:http://capec.mitre.org/data/definitions/70.html[CAPEC-70 - Try Common Usernames and Passwords]
. [[r4]] link:../266/[REQ.266 Deshabilitar funciones inseguras]
. [[r5]] link:https://www.owasp.org/index.php/ASVS_V2_Authentication[+OWASP-ASVS v3.1-2.19+]
Verificar que no existan contraseñas por defecto en uso para
el framework de la aplicación o cualquier otro componente utilizado por ella
(por ejemplo: "admin/password")
