:slug: defends/scala/limitar-tiempo-vida/
:category: scala
:description: Nuestros ethical hackers explican cómo evitar vulnerabilidades de seguridad mediante la creación, manipulación y eliminación correcta de datos o recursos dentro de un programa scala, con el fin de evitar que información confidencial disponible en memoria, sea vulnerable.
:keywords: scala, datos sensibles, datos confidenciales, lectura segura, memoria, tiempo de vida.
:defends: yes

= Limitar el tiempo de vida de datos sensibles

== Necesidad

Eliminar (limpiar) datos, recursos 
y/o objetos creados por la aplicación 
cuando ya no estén en uso.

== Contexto

A continuación se describe las circunstancias 
bajo las cuales la siguiente solución tiene sentido:

. Se está desarrollando una aplicación en +Scala+.
. El código debe eliminar información sensible en memoria.
. La aplicación debe limpiar/eliminar datos, recursos 
y/o objetos creados por la misma cuando ya no estén en uso,<<r1,^[1]^>> 
limitando así su tiempo de vida.

== Solución

* *Limpiar contenido de un +ArrayBuffer+:*

. A continuación se describe un sencillo código de ejemplo demostrativo, 
donde se explica la manera de limpiar datos almacenados 
dentro de un +ArrayBuffer+<<r2,^[2]^>>:
+
.test.scala
[source, scala, linenums]
----
import scala.collection.mutable.ArrayBuffer

var mab = ArrayBuffer(1,2,3,4,5)
mab.clear
----
+
En el anterior bloque de código 
se importa en primer lugar la clase +ArrayBuffer+. 
Posterior a ello, se crea un nuevo +ArrayBuffer+ 
cuyo contenido inicial son números del 1 al 5 
y son referenciados mediante la variable +mab+. 
Luego mediante dicha variable, 
podemos acceder al método +clear+ 
cuya función es limpiar el contenido del respectivo búfer, 
evitando así, que información sensible permanezca en memoria.

* *Lectura segura de credenciales:*
+
El siguiente bloque de código 
permite la lectura segura de credenciales 
ingresadas desde la consola.

. Dado que es posible reutilizar código +Java+ dentro de +Scala+, 
en primer lugar importamos las clases requeridas:<<r3,^[3]^>>
+
.password.scala
[source, scala, linenums]
----
import scala.collection.JavaConversions._
----
. Posterior a lo anterior, 
se procede a crear un objeto tipo +Singleton+<<r4,^[4]^>> llamado +Password+. 
Dentro de este, se define el método +main+ 
el cual no retorna ningún dato 
(esto se especifica mediante +Unit =+).
+
[source, scala, linenums]
----
object Password {

  def main(args: Array[String]): Unit = {
----

. En la constante +c+ 
almacenamos una referencia a un objeto de la clase +Console+ 
mediante el método +console+<<r5,^[5]^>> de la clase +System+:
+
[source, scala, linenums]
----
val c: Console = System.console()
    if (c == null) {
      System.err.println("No console.")
      System.exit(1)
    }
----
+
De lo anterior, una vez creado dicho objeto, 
se verifica si este es nulo, 
es caso de serlo, 
se detiene la ejecución del programa 
mediante el método +exit+.

. Se lee la información del nombre de usuario 
mediante el método +readLine+<<r6,^[6]^>>, 
y, por medio del método +readPassword()+<<r7,^[7]^>> 
(el cual retorna un +array+ de caracteres) 
se lee la contraseña desde la consola 
sin imprimir los caracteres en pantalla:
+
[source, scala, linenums]
----
    val username: String = c.readLine("Ingrese su nombre de usuario: ")
    val password: Array[Char] = c.readPassword("Ingrese su contraseña: ")
----
. Mediante el método +verify+ que recibe el nombre usuario y contraseña, 
simulamos el proceso de validación del usuario 
(el lector debe implementar este método de acuerdo a sus necesidades):
+
[source, scala, linenums]
----
	val isValidUser: Boolean = verify(username, password)
    // limpiar la contraseña
    Arrays.fill(password, ' ')
    if (!isValidUser) {
      throw new SecurityException("Invalid Credentials")
    }
  }

  // Validación simulada, siempre devuelve true
  private def verify(username: String, password: Array[Char]): Boolean = true

}
----
+
Del anterior bloque de código 
se observa que una vez no es necesaria la contraseña, 
esta es eliminada o sobrescrita de memoria 
mediante el método +fill+<<r8,^[8]^>> de la clase +Arrays+.

* *Lectura segura de ficheros:*

. El siguiente bloque de código +Scala+ 
especifica el método +readData+:
+
.readdata.scala
[source, scala, linenums]
----
def readData(): Unit = {
----
. En dicho método, se declara un búfer de +bytes+ directo 
mediante el método +ByteBuffer.allocateDirect()+ 
especificando el tamaño del mismo:
+
[source, scala, linenums]
----
    val bufferSize: Int = 16 * 1024
    val zeroes: Byte = Array.ofDim[Byte](bufferSize)
    val buffer: ByteBuffer = ByteBuffer.allocateDirect(bufferSize)
----
. Posterior a ello, a través de un objeto de la clase +FileInputStream+, 
se llama al método +getChannel+ 
para obtener el flujo de datos 
asociado a la entrada o fichero actual:
+
[source, scala, linenums]
----
    try {
      for (rdr <- managed((new FileInputStream("file")).getChannel))
----
. Por último, mediante un ciclo +while+ se lee el contenido 
de dicho archivo almacenado en el búfer:
+
[source, scala, linenums]
----
        while (rdr.read(buffer) > 0) {

          // Hacer algo con el búfer

          buffer.clear()
          buffer.put(zeroes) // sobrescribir el búfer con ceros
          buffer.clear()
        }

    } catch {
      case e: Throwable => {}

    }
}
----
+
Note que dentro del ciclo +while+ 
se lleva a cabo la eliminación manual de los datos del búfer, 
limpiándolos o sobrescribiendo su contenido con ceros.

Puedes encontrar soluciones similares 
para los siguientes lenguajes: <<r9,C#>>, <<r10,Java>>.


== Descargas

Puedes descargar el código fuente 
pulsando en el siguiente enlace:

. [button]#link:src/password.scala[password.scala >>]# contiene 
las instrucciones +scala+ para el manejo de credenciales de manera segura.

. [button]#link:src/readdata.scala[readdata.scala >>]# contiene 
las instrucciones +scala+ para la lectura de un fichero desde un búfer.

== Referencias

. [[r1]] REQ.999: La aplicación debe 
limpiar/eliminar datos, recursos y/o objetos creados por la misma 
cuando ya no estén en uso.
. [[r2]] link:http://www.scala-lang.org/api/2.8.1/scala/collection/mutable/ArrayBuffer.html[ArrayBuffer].
. [[r3]] link:http://www.scala-lang.org/api/2.9.3/scala/collection/JavaConversions$.html[JavaConversions].
. [[r4]] link:https://en.wikipedia.org/wiki/Singleton_pattern[Singleton pattern].
. [[r5]] link:https://docs.oracle.com/javase/7/docs/api/java/lang/System.html#console()[Class System-console].
. [[r6]] link:https://docs.oracle.com/javase/7/docs/api/java/io/Console.html#readLine()[Class Console-readLine].
. [[r7]] link:https://docs.oracle.com/javase/7/docs/api/java/io/Console.html#readPassword()[Class Console-readPassword].
. [[r8]] link:https://docs.oracle.com/javase/7/docs/api/java/util/Arrays.html[Class Arrays].
. [[r9]] link:../../csharp/limitar-tiempo-vida/[C#-Limitar el tiempo de vida de datos sensibles].
. [[r10]] link:../../java/limitar-vida-datos-sensibles/[Java-Limitar el tiempo de vida de datos sensibles].