:slug: careers/knowledge-test
:category: careers
:eth: no

= Knowledge Test

The next step to continue with your selection process is to submit our knowledge exam. This exam contains questions focused on several areas of knowledge, some that apply to your profile, and some other ones that don’t, nevertheless you must answer all of them in a conscious way because that is how we will be able to validate if the exam is effective determining that who knows - actually knows and who doesn’t, just doesn't.

The steps to submit the exam are the following:

== Create an account
. Browse to the following link: https://fluid.la/courses/login/index.php[Click here].
. Click in “CREATE NEW ACCOUNT” button and fill the form with your information.Please consider that the user name field only admits lowercase letters , and the password must have at least 8 characters, at least 1 digit(s), at least 1 lower case letter(s), at least 1 upper case letter(s), and at least 1 non-alphanumeric character(s) such as as *, -, or #
. Confirm your email direction following the instructions. Check your inbox and in case you can’t find it there, check the spam folder.

== Install SafeExamBrowser
. Download the following security software to present the exam: link:../../files/fluidexams.zip[Click here].

 IMPORTANT: Please finish reading all the steps before you execute the program.
 
. Decompress the .ZIP file downloaded and then install “SafeExamBrowserInstaller.exe”. The keyboard may change its configuration and set its language to English, so you may need to check if its necessary to change it back to Spanish.
. Verify your internet connection and make sure it is stable.
. You can close the program in any moment by using the button located in the bottom right side of the screen.
. To present the exam, you must go to the folder and execute the “fluidexams” file. From this moment, the only program active in the computer will be the exam.

== Present the exam
. You will have to log in with the credentials you just registered back in the step 2.
. After succeessfully logging in, go to the left side navigation bar and look for the “Sites home” tab”, click it.
. Scroll down to the end of the page and select “General Knowlegde Exam”.
. Click the "Enroll me" button next to the course name, then, on the next page, click the "ATTEMPT QUIZ NOW" button to begin.

 IMPORTANT: Please keep in mind that once you answer or skip a question, you won't be able to go back to it so you can't modify the answer

. Once you have finished, look for the “FINISH ATTEMPT” button in the bottom of the page and click it to validate if you answered all the questions.
. Click the “Submit all and finish” button located in the bottom of the page.
. To exit the program, use the button located in the bottom right side of the screen.
. Send an e-mail letting us know that you have finished.

From the moment you signed up in the exam platform, you have 24 hours to submit it and only 1 attempt. In case of not being able to present the exam in that time please let us now in a mail proposing a new date to submit it. The exam has an approximated duration time of three hours and a twenty minutes, so you need to make sure have enough time to do it without any interruptions.

Have Fun!  ... and good luck, but you don't need it.
