:slug: rules/158/
:category: source
:description: This requirement establishes the importance of developing applications in an adequately updated and free of known vulnerabilities programming language.
:keywords: Security, Source Code, Updates, Vulnerabilities, Programming, ASVS, Rules, Ethical Hacking, Pentesting
:rules: yes

= R158. Use a secure programming language

== Requirement

System source code must be implemented
in a stable, updated, tested, and free of known vulnerabilities
version of the chosen programming language.

== Findings

* [inner]#link:/web/findings/067/[F067. Improper resource allocation]#

* [inner]#link:/web/findings/070/[F070. Inappropriate coding practices]#

== References

. [[r1]] link:https://www.owasp.org/index.php/ASVS_V1_Architecture[OWASP-ASVS v3.1-1.9]
A mechanism for enforcing updates of the application exists.

. [[r2]] link:https://www.owasp.org/index.php/ASVS_V1_Architecture[OWASP-ASVS v3.1-1.11]
All application components, libraries, modules, frameworks, platform,
and operating systems are free from known vulnerabilities.

. [[r3]] link:https://owasp.org/www-project-application-security-verification-standard/[OWASP-ASVS v4.0.1
Appendix C: Internet of Things Verification Requirements.(C.11)]
Verify that any use of banned *C* functions are replaced with the appropriate
safe equivalent functions.

. [[r4]] link:https://owasp.org/www-project-application-security-verification-standard/[OWASP-ASVS v4.0.1
V5.4 Memory, String, and Unmanaged Code Requirements.(5.4.1)]
Verify that the application uses memory-safe string, safer memory copy and
pointer arithmetic to detect or prevent stack, buffer, or heap overflows.
