:slug: defends/cobol/evitar-msg-autenticacion/
:category: cobol
:description: Nuestros ethical hackers explican cómo evitar vulnerabilidades de seguridad mediante la programación segura en COBOL al evitar emitir mensajes de error en autenticación. Los mensajes de error pueden contener información que puede ser aprovechada por un atacante para vulnerar la aplicación.
:keywords: Cobol, Seguridad, Evitar, Autenticación, Error, Mensajes.
:defends: yes

= Evitar Emitir Mensajes de Errores en Autenticación

== Necesidad

No emitir mensajes de error identificables en la autenticación en +COBOL+.

== Contexto

A continuación se describe las circunstancias
bajo las cuales la siguiente solución tiene sentido:

. Se está desarrollando una aplicación en +COBOL+.
. La aplicación maneja autenticación de usuarios.
. El proceso de autenticación
no debe emitir mensajes de error que permitan distinguir
si es un error de usuario o de contraseña<<r1,^[1]^>>.

== Solución

. Se da inicio a la aplicación de ejemplo
declarando la división +IDENTIFICATION DIVISION+<<r2,^[2]^>>:
+
.cobolauth.cbl
[source,cobol,linenums]
----
      ******************
      * Identification *
      ******************
       IDENTIFICATION DIVISION.
       PROGRAM-ID. COBOLAUTH.
----
+
En el anterior bloque de código,
se establece el nombre del programa a +COBOLAUTH+
mediante la sentencia +PROGRAM-ID+.
Cabe resaltar que el uso de +IDENTIFICATION DIVISION+
no se limita a establecer el nombre de un programa en +COBOL+.
Al final del presente escrito^<<r2,[2]>>,<<r3,[3]>>^
puede encontrar mayor información
sobre otros usos dados a dicha división.

. Se declaran los datos a usar en la división +DATA DIVISION+<<r4,^[4]^>>:
+
[source,cobol,linenums]
----
      ********
      * Data *
      ********
       DATA DIVISION.
----
. En esta ocasión, se declaran las variables +W01-USERNAME+
y +W02-PASSWORD+, las cuales serán ingresadas por el usuario:
+
[source,cobol,linenums]
----
       WORKING-STORAGE SECTION.
       01 W01-USERNAME PIC X(16) VALUE "".
       01 W02-PASSWORD PIC X(16) VALUE "".
----
. Se establece como prueba los datos de autenticación.
Hay que recordar que estos datos deben ir centralizados en una base de datos,
y la contraseña resumida con una función hash:
+
[source,cobol,linenums]
----
       01 W03-USERAPP  PIC X(16) VALUE "administrator".
       01 W04-PASSAPP  PIC X(16) VALUE "Admin_123456!".
----
. Se declara la división +PROCEDURE DIVISION+
y dentro de ella mediante la sentencia +ACCEPT+,
se captura el usuario
y contraseña ingresados desde la entrada estándar:
+
[source,cobol,linenums]
----
      ********
      * Main *
      ********
       PROCEDURE DIVISION.
           DISPLAY "Username: ".
           ACCEPT W01-USERNAME.

           DISPLAY "Password: ".
           ACCEPT W02-PASSWORD.
----
+
Como se mencionó anteriormente,
luego de que se ejecuta el anterior bloque de código,
las variables +W01-USERNAME+ y +W02-PASSWORD+
contendrán los valores ingresados por el usuario.

. Comparamos los datos ingresados
con los establecidos en las variables +W03-USERAPP+ y +W04-PASSAPP+,
declaradas (e inicializadas) dentro de la división +DATA DIVISION+:
+
[source,cobol,linenums]
----
       IF W01-USERNAME = W03-USERAPP THEN
           IF W02-PASSWORD = W04-PASSAPP THEN
----
. Si la combinación es válida,
se despliega en pantalla un mensaje de notificación de ingreso válido
y se procede a realizar las acciones para el usuario autenticado:
+
[source,cobol,linenums]
----
       DISPLAY "Combinacion valida"
----
. Si el usuario o contraseña no corresponden con los establecidos,
se despliega en pantalla un mensaje genérico para ambos (Combinación no válida).
Esto evita que un atacante infiera datos sobre los usuarios en la base de datos,
además de posibles ataques de fuerza bruta:
+
[source,cobol,linenums]
----
           ELSE
               DISPLAY "Combinacion no valida"
           END-IF
       ELSE
           DISPLAY "Combinacion no valida"
       END-IF.

       STOP RUN.
----

== Descargas

Puedes descargar el código fuente
pulsando en el siguiente enlace:

. [button]#link:src/cobolauth.cbl[cobolauth.cbl]# contiene
todas las instrucciones +COBOL+ del programa explicado anteriormente.

== Referencias

. [[r1]] link:../../../rules/225/[REQ.225 Respuestas de autenticación adecuadas].
. [[r2]] link:https://www.ibm.com/support/knowledgecenter/en/ssw_ibm_i_73/rzasb/iddiv.htm[IBM - Identification Division].
. [[r3]] link:http://www.escobol.com/modules.php?name=Sections&op=viewarticle&artid=11[Identification Division].
. [[r4]] link:https://www.ibm.com/support/knowledgecenter/en/ssw_ibm_i_73/rzasb/datdivs.htm[Data Division Structure].
