:slug: careers/reverse-references/
:category: careers
:description: The main goal of the following page is to inform potential talents and people interested in working with us about our selection process. This stage of the selection process aims to validate the provided references of the candidate from his/her previous jobs.
:keywords: Fluid Attacks, Careers, Reverse, References, Selection, Process.

= References

In this stage of the process
we validate the references
from your previous employer
in the following manner:
Two of your direct bosses (your boss’ superior and/or family does not apply)
from the previous jobs you listed in our application
must give us a call at the number given below.

This is all about doing everything that is needed
to get two of your bosses to give us a call
in order to have a short conversation with them
regarding your performance
so that we can get an idea of
how you worked in said company.

* Cellphone: *+57 300 496 3851*

Please send us an email
confirming the names and contact information
of the two bosses that are going to call us.

Don’t hesitate to contact us
with any doubts regarding the process.

The person that will contact you is: Santiago Vélez Robledo.
