:slug: events/
:description: This page aims to inform the customer about the different talks offered by Fluid Attacks. These talks are all related to the field of Information Security and are prepared by experienced professionals. Learn how to book one of our speakers to give a talk in your own facilities.
:keywords: Fluid Attacks, Talk, Security, Experience, Information, Service

= Conference Event Topics Available from Fluid Attacks

+Fluid Attacks+ can help you with your next conference.
We are happy to provide professional conference presentations
on a variety of topics.
Pick a topic below and contact us.
Let's explore what we can do together.

. link:burn-the-datacenter/[Burn the Datacenter: from Pets to Cattle.]

. link:breaking-the-build/[Breaking the Build: Our +SecDevOps+ Habits.]

. link:securing-device/[Securing Your Mobile Device.]

. link:live-hacking/[Live Hacking.]

== When?

You choose +3+ possible dates
for your event that will work the best for you.
We will then select +1+ of those dates
and confirm that date with you.

== Details

. *Cost:* You are responsible for the conference venue cost
and the registration fees for conference attendees.
+Fluid Attacks+ will cover all other conference-related expenses.
However, we do require approximately +20+ registered attendees
for a conference to proceed.
If you are unable to provide at least +20+ attendees,
then call us immediately.
We can obtain up to 4 additional conference attendees for you,
but you will be billed to cover their registration fees.

. *Event Materials:* Conference attendees
who complete the customer satisfaction survey
within +1+ day after the conference ends
will be sent all conference materials.

== Requirements

Listed below are the minimum requirements
necessary for us to provide you with a setback-free conference event.

*Note:* You are responsible for making sure all items
are in place and ready before we arrive at the conference venue.
If you have any questions about or problems with,
any of these items do not hesitate to contact us immediately.

. All the assistants MUST complete an online satisfaction survey (+2+ minutes)
before leaving the auditorium.

. +Fluid Attacks+ CAN invite up to +4+ additional assistants
to the event.

. Event assistants MUST NOT use cellphones nor laptops
during the time of the conference.

. All assistants MUST be previously notified about the event,
so they can voluntary decide whether to assist or not.

. The speaker MUST enter the auditorium +30+ minutes before
the beginning of the event to connect the equipment,
test +WiFi+ connectivity and start the conference
at the scheduled time.

. *Access to +Google Drive+ via WiFi:*
The presentation has animations and videos
that can only be accessed if the laptop is connected
to a network that allows access to +Google Drive+.

. Video beam with aspect ratio +16:9+.

. +HDMI+ cable connected directly to the video beam
from the speaker laptop (without +VGA+ adapters).

. Do not include assistants remotely.
The conference is very dynamic and hence,
it depends on the face to face interaction with the attendance.

. If the conference is part of an event with more speakers,
it must be scheduled before the last speaker of the morning session.
