:slug: events/
:category: about-us
:description: As cybersecurity experts, we offer talks related to the security information field. Fluid Attacks can help you with your next conference. Check our options.
:keywords: Fluid Attacks, Talk, Security, Experts, Cybersecurity, Conference, Events, Pentesting, Ethical Hacking
:banner: events-bg

= Events

== Conference Event Topics Available from Fluid Attacks

`Fluid Attacks` can help you with your next conference.
We are happy to provide professional conference presentations
on a variety of topics.
Pick a topic below and contact us.
Let's explore what we can do together.

. link:burn-the-datacenter/[Burn the Datacenter: from Pets to Cattle.,role=link-4]

. link:breaking-the-build/[Breaking the Build: Our `SecDevOps` Habits.,role=link-4]

. link:securing-device/[Securing Your Mobile Device.,role=link-4]

. link:live-hacking/[Live Hacking.,role=link-4]

== When?

You choose `3` possible dates
for your event that will work the best for you.
We will then select `1` of those dates
and confirm that date with you.

== Details

. *Cost:* You are responsible for the conference venue cost
and the registration fees for conference attendees.
`Fluid Attacks` will cover all other conference-related expenses.
However, we do require approximately `20` registered attendees
for a conference to proceed.
If you are unable to provide at least `20` attendees,
then call us immediately.
We can obtain up to 4 additional conference attendees for you,
but you will be billed to cover their registration fees.

. *Event Materials:* Conference attendees
who complete the customer satisfaction survey
within `1` day after the conference ends
will be sent all conference materials.
