:slug: kb/lenguajes/cobol/manejar-error-operacion-aritmetica
:eth: no
:category: cobol
:kb: yes

= Manejar Errores en Operaciones Aritméticas

== Necesidad

Manejar errores en operaciones aritméticas en COBOL

== Contexto

A continuación se describe las circunstancias bajo las cuales la siguiente 
solución tiene sentido:

. Se está desarrollando una aplicación en COBOL.
. La aplicación realiza operaciones aritméticas con las instrucciones ADD, 
SUBTRACT, MULTIPLY, DIVIDE, o COMPUTE.
. El código sólo debe realizar las funciones para las cuales fue diseñado y no 
acciones colaterales. [1]
. El sistema debe evitar difundir información sensible al momento de ocurrir un 
evento excepcional. [2]

== Solución

. Las operaciones aritméticas pueden causar ciertos tipos de error que 
generalmente resultan en mensajes MCH. Al usar las instrucciones ADD, SUBTRACT, 
MULTIPLY, DIVIDE, o COMPUTE, podemos controlar estos errores mediante el uso
de la instrucción ON SIZE ERROR.
.  Las siguientes condiciones son manejadas a través de la instrucción ON SIZE
ERROR:
* La longitud del resultado de la operación aritmética es mayor a la longitud 
del número que lo contiene.
* División por cero.
* Cero elevado a la cero.
* Cero elevado a un número negativo.
* Número negativo elevado a un fraccionario.
* Desbordamiento de números flotantes.
. A continuación podrá evidenciar el uso de la instrucción ON SIZE ERROR
. Definimos la división de identificación
[source, cobol,linenums]
-----------------------
IDENTIFICATION DIVISION.
 ******************
 * Identification *
 ******************
 PROGRAM-ID. COBOLONSZ.
-----------------------

[start=5]
. La división de datos contendrá la variable W01-TOTALAMOUNT, la cual tiene 
como propósito almacenar el monto total de una persona en el banco (Note como 
la longitud del dato es de 6 dígitos)
[source, cobol,linenums]
-------------------------
********
* Data *
********
DATA DIVISION.
WORKING-STORAGE SECTION.
01 W01-TOTALAMOUNT PIC 9(06) VALUE 0.
--------------------------
 
[start=6]
. Definimos la división de procedimiento donde inicia nuestro programa
[source, cobol,linenums]
-----------------------
********
* Main *
********
PROCEDURE DIVISION.
MAIN.
-----------------------

[start=7]
. Sumamos los montos $500.000, $400.000 y $300.000, el resultado es almacenado 
en W01-TOTALAMOUNT (Si ocurre una excepción, CALC-ERROR es el encargado de 
manejar el problema)
[source, cobol,linenums]
------------------------
ADD 500000 400000 300000 TO W01-TOTALAMOUNT
 ON SIZE ERROR PERFORM CALC-ERROR.
------------------------

[start=8]
. Mostramos el monto total
[source, cobol,linenums]
------------------------
DISPLAY W01-TOTALAMOUNT.
 STOP RUN.
------------------------

[start=9]
. En esta sección podemos tratar el desbordamiento como un error, para el 
ejemplo mostraremos una advertencia
[source, cobol,linenums]
------------------------
CALC-ERROR.
 DISPLAY "Arithmetic overflow".
 STOP RUN.
------------------------

[start=10]
. En este caso es mostrada la excepción debido a que la suma total de los montos 
($1.200.000) supera la longitud esperada en la variable W01-TOTALAMOUNT.
. Se debe redefinir la variable con el objetivo de almacenar números más grandes
[source, cobol,linenums]
------------------------
********
* Data *
********
DATA DIVISION.
WORKING-STORAGE SECTION.
01 W01-TOTALAMOUNT PIC 9(63) VALUE 0.
-------------------------
 
== Referencias
. REQ.0149 El código fuente de un sistema no debe realizar funciones 
diferentes a las que han sido especificadas en los requisitos 
funcionales (puertas traseras).
. REQ.0077: El sistema no debe registrar información sensible en un evento 
excepcional de una bitácora.
