:slug: products/rules/list/008/
:category: assets
:description: It's crucial to set a system threat model covering STRIDE (Spoofing, Tampering, Repudiation, Information Disclosure, Denial of Service, Elevation of Privilege).
:keywords: Requirement, Security, Information, Assets, Threat Model, STRIDE, Rules, Ethical Hacking, Pentesting
:rules: yes
:extended: yes

= R008. Generate system threat model

== Requirement

The organization must generate a threat model for the system,
identifying all potential threats and covering +STRIDE+
(Spoofing, Tampering, Repudiation, Information Disclosure,
Denial of Service, Elevation of Privilege).

== References

. [[r1]] link:https://gdpr-info.eu/recitals/no-76/[GDPR. Recital 76: Risk assessment].

. [[r2]] link:https://www.law.cornell.edu/cfr/text/45/164.308[+HIPAA Security Rules+ 164.308(a)(1)(ii)(A):]
Risk Analysis: Conduct an accurate and thorough assessment
of the potential risks and vulnerabilities to the confidentiality,
integrity, and availability of electronic protected health information
held by the covered entity.

. [[r3]] link:https://www.law.cornell.edu/cfr/text/45/164.310[+HIPAA Security Rules+ 164.310(a)(2)(ii):]
Facility Security Plan: Implement policies and procedures
to safeguard the facility and the equipment therein
from unauthorized physical access, tampering, and theft.
