:slug: kb/glassfish/revisar-bitacora
:eth: no
:category: glassfish
:kb: yes

= Revisar Bitácoras

== Necesidad

Revisar bitácoras en servidor de aplicaciones GlassFish

== Contexto

A continuación se describen las circunstancias bajo las cuales la siguiente 
solución tiene sentido:

. Se utiliza el servidor de aplicaciones GlassFish.
. Se desea revisar la bitácora.

== Solución

. Abrimos la consola de administración web de GlassFish.
. Seleccionamos la opción server y hacemos clic en el botón View LogFiles.
. Se abrirá una nueva ventana emergente en la cual podremos ver la bitácora del 
servidor de aplicaciones.
. La bitácora está clasificada por severidad, y pueden usarse las opciones de 
la parte superior para filtrar los resultados.
. Es posible también revisar manualmente el archivo server.log ubicado en la 
carpeta logs dentro de nuestro dominio. 
. A continuación se puede ver un ejemplo extraído de la bitácora, se observa 
que se incluye fecha, hora, segundos, milisegundos y zona horaria de manera 
predeterminada.
[source, conf, linenums]
----
[#|2012-10-26T15:06:48.176-0500|INFO|glassfish3.1.2| 
javax.enterprise.system.std.com.sun.enterprise.server.logging| 
_ThreadID=188;_ThreadName=Thread-2;|Attempting to load ESAPI.properties via file io.|#]
----

== Referencias

. REQ.0070: El sistema debe registrar el nivel de severidad para cada evento 
excepcional y de seguridad.
. REQ.0073: El sistema debe registrar el momento exacto de ocurrencia (Fecha, 
hora, segundos, milisegundos y zona horaria) para cada evento excepcional y de 
seguridad.