:slug: careers/reasons/
:category: careers
:description: If you are someone who is talented and passionate about software development, information technology and are eager to learn, you should consider being a part of our team here at +Fluid Attacks+. Here are some reasons why +Fluid Attacks+ is a great place to work.
:keywords: Fluid Attacks, Career, Reasons, Work, Projects, Clients.
:translate: empleos/razones/

= Reasons to work with us

+Fluid Attacks+ is a great place to work.
This is due to:

== Hackers that develop their own tools

When we have projects we hack applications or corporate networks,
when we do not have any, we develop our own software tools.
For this reason we are looking for hackers
that are passionate about programming.
Our favorite technologies are Linux, Git, Python, Docker,
Ansible and Amazon Web Services.
If you do not master these tools yet, it doesn’t matter,
in +Fluid Attacks+ what matters is your capacity to be self taught
and learn about the various challenges we face on a daily basis,
the discipline with which you face them,
the honesty to say what needs to be said
and collaboration without pretending to be better than anyone.

If you want to take part in the most challenging selection process there is,
where no matter the result, you will learn more than in any other company,
we invite you to participate and see for yourself
that in +Fluid Attacks+ it is better to do then to know.
Our selection process is guided using +Git+,
provides feedback through continuous integration and
allows you to improve your world ranking in programming and hacking
as well as your +GitLab+ profile.
You don’t need to have graduated,
don’t need to be enrolled in a specific career,
nor have any specific work experience.
The only thing that matters is that you show us you can learn
on your own at an expected rate.

== Short projects and high rotations

+70%+ of the company’s projects are small (less than +1+ month)
and medium (+1+ to +6+ months).
This allows you to constantly get to know new organizations,
different problems, different method and broaden your knowledge.

== Continuous improvement based on International Standards

+Fluid Attacks+ was the first company in Colombia
to obtain an +ISO/IEC 27001+ (Information Security) certification
at the same time they obtained the +ISO 9001+.
Also, our continuous improvement process
uses the +ISO/IEC 17025+ and Common Criteria standards
as a reference for all security test.

== Work with the great ones

+Fluid Attacks+ provides information security services
to some of the biggest organizations in Colombia.
This means that there will always be challenging projects
in which you can participate.
link:../../customers/financial/#bancolombia[Bancolombia],
link:../../customers/financial/#colpatria[Colpatria],
link:../../customers/financial/#davivienda[Davivienda],
the biggest banks in the country;
link:../../customers/communications/#tigo-une[+UNE+],
link:../../customers/communications/#etb[+ETB+],
link:../../customers/communications/#edatel[+EDATEL+],
link:../../customers/communications/#claro[Claro],
the biggest ISP in the country; and many more.
To see a complete list of our clients
go to our link:../../customers/[Clients Section].

== Great talents working together

Our most valuable component is people and
We feel proud of our amazing team.
In fact, It is a very young team
with an average age of 25.
We believe the talents in our team
make +Fluid Attacks+ a competitive place to work and
at the same time a great place to learn and
develop your skills.
The first three Debian developers in Colombia work with +Fluid Attacks+,
the greatest percentage of Colombians certified in
link:../../services/certifications/#certified-ethical-hacker-(ceh)[+CEH+] and
link:../../services/certifications/#offensive-security-wireless-professional-(oswp)[+OSCP+]
are in our company and
the majority of the team members
of the latin american security wargames champion work with us.
On top of this,
our employees have important certifications such as
link:../../services/certifications/#certified-ethical-hacker-(ceh)[+CEH+],
link:../../services/certifications/#offensive-security-wireless-professional-(oswp)[+OSCP+],
link:../../services/certifications/#certified-information-systems-auditor-(cisa)[+CISA+],
link:../../services/certifications/#certified-information-security-manager-(cism)[+CISM+],
link:../../services/certifications/#giac-information-security-professional-(gisp)[+GISP+],
link:../../services/certifications/#certified-information-systems-security-professional-(cissp)[+CISSP+]
link:../../services/certifications/#comptia-security+[+CompTIA Security++] and
link:../../services/certifications/#information-technology-infrastructure-library-certification-(itil)[+ITIL+].

== Socially responsible

+Fluid Attacks+ also believes that companies,
No matter their size or sector,
must permanently give back to the society.
This is why +Fluid Attacks+ participates as a company and
actively encourages their talents to support education
through the organization “Dividendo por Colombia”.
+Fluid Attacks+ also recycles and
separates their waste in
glass, paper, plastic and ordinary
for the benefit of the community.

== Former employees

We are also proud of our former employees
who are now studying or working
in mayor universities and companies
all over the world.
Here is a short list:

  . Rafael: Masters in Math at the Royal Institute of Technology in Sweden,
currently Ph.D in Math at the University of Miami.
  . Miguel: Masters in Computer Science at the Max-Plank Institute in Germany,
Currently Ph.D in the same institute.
  . Diego: Masters in Information Security in Australia.
  . Juan: Masters in Innovation in Switzerland.
  . Manuel: Masters in Innovation in England.
  . Jorge: Masters in Math in the University of Miami.
  . Julian: Yahoo Taiwan.
  . Luis: SAP Security consultant in England.
  . Sebastian and Juan: Founders of Coffee Grid.
  . Jaime: Entrepreneur in our cloud services allie Nuva.

== Bond with the academia

For us it is very important to maintain a close relationship with the academia.
This is why some of our employees teach or have taught courses and lectures
in different universities in Medellin.

Courses in topics such as:

* Information Security.
* Secure Development Life Cycle.
* Programming.
* Networks.
* Operating Systems.
* Distributed systems.

In addition to this, we are part of Business Lecture group at EAFIT University,
University of Medellin, La Salle University Corporation and
The university of Antioquia.

This is a program in which our employees teach
short courses on specific topics completely free
for students in different universities.
So far, we have offered courses in Basics of Linux,
Information Security Principles and Hacking through wargames.
