:slug: services/
:description: Fluid Attacks services aim to detect and report all existing vulnerabilities and security issues within an application. Our professional team continuously develop their own tools and exploits to ensure the detection of all security findings with no false positives.
:keywords: Fluid Attacks, Services, Ethical Hacking, Pentesting, Security, Information.
:translate: servicios/
:caption:

= Services

[role="tb-alt tb-services"]
[cols=2, frame="topbot"]
|====

a|== link:one-shot-hacking/[One-Shot Hacking]

This service aims to detect and report all the vulnerabilities
and security issues within one specific version of your application,
with no false positives.
a|image::one-shot.svg[Computer being attacked]

a|image::continuous.svg[Server being attacked]
a|== link:continuous-hacking/[Continuous Hacking]

This service aims to detect and report all the vulnerabilities
and security issues during the whole software development cycle.
This method allows us to detect security issues continuously
as software evolves.
This inspection is done without false positives and ensuring previous
issues were resolved before going to production.

a|== link:differentiators/[Differentiators]

What is the difference between a +pen test+ and a +vulnerability analysis+
using automated tools? +
These items alow us to find and report all security vulnerabilities
in your application.
a|image::differentiators.svg[Metal gear]

a|image::comparative.svg[Two plate scale]
a|== link:comparative/[Comparative]

What is the difference between the +One-Shot Hacking+ service
and the +Continuous Hacking+ service? +
These items allow you to decide which service
best suits your needs.

a|== link:certifications/[Certifications]

Our hackers have certifications in different areas
of the Security of Information, like +OSCP+, +OSWP+,
+CEH+, +CISSP+, among others.
This to ensure that you are hiring a team of capable professionals.
a|image::certifications.svg[Certification diploma]

a|image::faq.svg[Question being answered in a conversation]
a|== link:faq/[FAQ]

Do you have any question about the +Continuous Hacking+ service? +
Read these Frequently Asked Questions to solve
some of the most common doubts regarding our service.

|====
