:slug: customers/
:description: Fluid Attacks is a company focused on information security, ethical hacking, penetration testing and vulnerabilities detection in applications with over 18 years of experience in the Colombian market. In this page we present our contributions to the sectors we work with.
:keywords: Fluid Attacks, Information, Solutions, Sectors, Security, Ethical Hacking.
:caption:

= Customers

[role="tb-alt"]
[cols=3, frame="topbot"]
|====
2+a|== link:financial/[Financial]

In the financial sector, +Fluid Attacks'+ customers
comprise some of the most important banks in Latin America.
Some of our customers are +Bancolombia+, +BBVA+,
+Davivienda+, +Sura+, +Protección+, +Colpatria+ among others.

a|image::financial.svg[Dollar sign]


a|image::communications.svg[Smartphone]
2+a|== link:communications/[Communications]

+Fluid Attacks+ has provided innovative problem-solving
to some of the largest communication services companies in Colombia,
such as +Claro+, +Tigo UNE+, +ETB+, +Edatel+, among others.

2+a|== link:consumer/[Consumer]

+Fluid Attacks+ has worked with a wide variety of companies
involved in retail activities, +E-Commerce+, textiles,
and technology solutions whose shared goal
is providing excellent customer service to their consumers.
Some of these companies are +Grupo Éxito+, +Grupo Uribe+, +Rappi+, +Semana+,
and the Australian company, +The Missing Link+.

a|image::consumer.svg[Customers with different reactions]

a|image::technology.svg[Server and database]
2+a|== link:technology/[Technology]

+Fluid Attacks+ has worked with companies that offer software,
infrastructure, and other technology solutions to their customers,
in a wide range of applications.
Some of our customers in this area have been +PSL+, +S4N+, +Arus+, +Ceiba+,
the American companies +Cre8tive+, +KometSales+ and +VM2020+,
and the Spanish company +Indra+.

2+a|== link:utilities/[Utilities]

In the energy sector, +Fluid Attacks+ has executed projects
in companies involved in generation, distribution, and selling
such as +Celsia+, as well as, planning, designing
and managing transactional systems, such as +XM+.

a|image::utilities.svg[Ligthning symbol]

a|image::industrial.svg[Factory]
2+a|== link:industrial/[Industrial]

+Fluid Attacks+ has assisted several manufacturers
and other companies in the industrial sector
in their software security and infrastructure security needs.
Some of these customers are +Grupo Argos+, +Manuelita+,
+Corona+, +Cadena+ and +Odinsa+.

2+a|== link:transportation/[Transportation]

+Fluid Attacks+ has worked with transportation giants
like +Avianca+ and +F2X+ to ensure that their applications and web platforms
provide the best in security protection for their users.

a|image::transportation.svg[Bus frontal view]

|====
