:slug: defends/java/personalizar-error/
:category: java
:description: Nuestros ethical hackers explican la importancia de utilizar páginas de error en la aplicaciones web. Además, explican la forma de personalizar dichas páginas con el fin de evitar exponer información técnica y/o sensible de la aplicación o el servidor que la almacena.
:keywords: Java, Seguridad, Error, Web, Información, Fuga.
:defends: yes

= Personalizar Páginas de Error

== Necesidad

Personalizar páginas de error
en un servidor de aplicaciones +Java EE+.

== Contexto

A continuación se describen las circunstancias
bajo las cuales la siguiente solución tiene sentido:

. La aplicación está desarrollada
en +Java EE+ versión +1.4+ o superior.
. Se requiere evitar revelar información sobre rutas,
código fuente y versión de las herramientas de desarrollo
cuando se genere un error en la aplicación.

== Solución

Hoy en día, y debido a la gran masificación que ha tenido Internet,
es más que probable que en este preciso momento
millones de personas alrededor del mundo
estén accediendo a un sitio web.
Sea por cuestión de negocios, educación, entretenimiento,
o simplemente por pasar el rato,
prácticamente es inconcebible pensar en el día a día
sin este poderoso medio de comunicación.

Pero así como hay millones de personas
que visitan millones de sitios web,
existe la posibilidad de que se presenten
millones de errores al intentar acceder
a la información almacenada en los diversos sitios web.
Estos errores se pueden dar por múltiples razones,
pero sin duda, la más recurrente es que el contenido buscado
no se encuentra alojado en dicho servidor.

Si bien es normal que esto suceda,
es absolutamente necesario que un sitio web
tenga una página por defecto para informar los errores.
Eso se debe hacer por diversos motivos,
pero el que concierne a este articulo,
es para evitar exponer información técnica de la aplicación
que pueda ser utilizada posteriormente
por un atacante con el fin de comprometer
el correcto desempeño del sitio web.

En esta solución, se explicará
la manera de generar páginas de error personalizadas
en las aplicaciones desarrolladas en +Java EE+.

. Se debe utilizar el archivo
de configuración de la aplicación +web.xml+.
En dicho archivo se puede mapear los errores
a +URLs+ especificas utilizando el elemento +<errorpage>+.

. El elemento crea un enlace
entre el código del error o el tipo de error
con la ubicación del recurso o página de la aplicación.

. Dentro de la sección +<error-page>+
se pueden utilizar los siguientes subelementos:

* *error-code:* Es un entero que identifica el código del error.
* *Exception-type:* Nombre completo de la clase
del tipo de excepción +Java+.
* *Location:* Ubicación del recurso dentro del +root+ de la aplicación.

. Personalizar la pagina mediante el código de error.
+
.web.xml
[source, xml, linenums]
----
<error-page>
  <error-code>401</error-code>
  <location>/ejemplo/ERROR/401.html</location>
</error-page>
<error-page>
  <error-code>404</error-code>
  <location>/ejemplo/ERROR/404.html</location>
</error-page>
<error-page>
  <error-code>500</error-code>
  <location>/ejemplo/ERROR/500.html</location>
</error-page>
----

. Personalizar la pagina mediante el tipo de excepción.
+
[source, xml, linenums]
----
<error-page>
  <exception-type>java.io.FileNotFoundException</exception-type>
  <location>/ejemplo/ERROR/FileNotFound.html</location>
</error-page>
----

. Para establecer una página genérica
para cualquier tipo de error que ocurra en la aplicación
se debe considerar la siguiente configuración.
+
[source, xml, linenums]
----
<error-page>
  <exception-type>java.lang.Exception</exception-type>
  <location>/ejemplo/ERROR/exception.html</location>
</error-page>
----

== Referencias

. [[r1]] link:http://www.adobepress.com/articles/article.asp?p=25445&seqNum=4[Customizing the Look of Error Messages in JSP]
. [[r2]] link:../../../rules/083/[REQ.083 No registrar datos sensibles en bitácoras]
