:slug: rules/137/
:category: credentials
:description: This requirement establishes the importance of forcing the change of all the temporary passwords generated by a third party after their first use.
:keywords: Requirement, Password, Temporary, Force, Change, System, ASVS, CWE, NIST, PCI DSS, Rules, Ethical Hacking, Pentesting
:rules: yes

= R137. Change temporary passwords of third parties

== Requirement

The system must force the change of temporary passwords,
generated by a third party,
after their first use.

== Description

Temporary passwords are often harder to remember and shared over systems whose
future integrity may not be guaranteed by the system that created them.
Furthermore, there is no control over who has access to the secret besides
the third party.
Therefore, they should be changed after their first use.

== References

. [[r1]] link:https://cwe.mitre.org/data/definitions/263.html[CWE-263: Password Aging with Long Expiration].
Allowing password aging to occur unchecked can result in the possibility of
diminished password integrity.

. [[r2]] link:https://pages.nist.gov/800-63-3/sp800-63b.html[NIST 800-63B 6.1.1 Binding at Enrollment]
Temporary secrets SHALL NOT be reused.

. [[r3]] link:https://owasp.org/www-project-application-security-verification-standard/[OWASP-ASVS v4.0.1
V2.3 Authenticator Lifecycle Requirements.(2.3.1)]
Verify system generated initial passwords or activation codes SHOULD be
securely randomly generated, SHOULD be at least 6 characters long,
and MAY contain letters and numbers,
and expire after a short period of time.
These initial secrets must not be permitted to become the long term password.

. [[r4]] link:https://www.pcisecuritystandards.org/documents/PCI_DSS_v3-2-1.pdf[PCI DSS v3.2.1 - Requirement 8.2.6]
Set passwords/passphrases for first-time use and upon reset to a unique value
for each user,
and change immediately after the first use.
