:slug: rules/332/
:category: credentials
:description: This documents contains the details of the security requirements related to the definition and management of access credentials in the organization. This requirement establishes the importance of checking passwords against a set of breached passwords.
:keywords: Breached, Leaked, Password, Account, ASVS, CWE
:rules: yes

= R332. Prevent the use of breached passwords

== Requirement

The system must check new passwords against a list of 1000 to 10000 breached
passwords.

== Description

There exist various mechanisms for cracking passwords that use public lists
containing breached credentials.
Systems must check submitted passwords against some of these lists and prevent
account creation and password update operations that use passwords contained in
them.

== References

. [[r1]] link:https://cwe.mitre.org/data/definitions/521.html[CWE-521: Weak Password Requirements]
The product does not require that users should have strong passwords,
which makes it easier for attackers to compromise user accounts.

. [[r2]] link:https://pages.nist.gov/800-63-3/sp800-63b.html[NIST 800-63B 5.1.1.2 Memorized Secret Verifiers]
Verifiers SHALL compare the prospective secrets against a list that contains
values known to be commonly-used, expected, or compromised.

. [[r3]] link:https://owasp.org/www-project-application-security-verification-standard/[OWASP-ASVS v4.0.1
V2.1 Password Security Requirements.(2.1.7)]
Verify that passwords submitted during account registration, login, and
password change are checked against a set of breached passwords either locally
or using an external API.
