:slug: rules/181/
:category: rules
:description: En el presente documento se detallan los requerimientos de seguridad relacionados a la importancia de transmitir información o ejecutar funciones cuyo contenido sea sensible mediante un protocolo o canal seguro que cumpla con todos los estándares de seguridad requeridos para dicho sistema.
:keywords: Requerimiento, Seguridad, Protocolo, Transmisión, Funciones, Información sensible.
:rules: yes

= REQ.181 Transmitir por medio de protocolos seguros

== Requisito

La transmisión de información sensible
o la ejecución de funciones sensibles
debe hacerse a través de protocolos seguros.

== Descripción

Un sistema puede enviar información por un canal no cifrado
utilizando protocolos no seguros,
el uso de este tipo de protocolos genera un riesgo que puede ser explotado
mediante la interceptación de información y modificación de la misma
al efectuar un ataque de hombre en el medio,
ejemplos típicos de este riesgo se ven en el uso de protocolos no seguros
como +HTTP+, +FTP+, +POP3+, +Telnet+, etc.

== Implementación

. Desplegar las aplicaciones utilizando +HTTPS+ en el servidor de aplicaciones:
Al utilizar este protocolo se cifra el canal utilizado
para el despliegue de aplicaciones web,
para esto será necesario contar con certificados
emitidos por una entidad certificadora válida.

. Utilizar servicios seguros en vez de estándar:
Cuando se requiera transmitir información sensible por un canal inseguro
utilizando servicios como +FTP+, +POP3+ y otros
se pueden habilitar las versiones seguras de cada protocolo
o implementar protocolos con las mismas funciones
pero que cuentan con cifrado de la comunicación
tales como +SSH+, +FTPS+, +POP3S+, +TLS+, etc.

== Ataques

. Atacante con acceso al canal no cifrado realiza ataques de hombre
en el medio (+MitM+) sobre los activos vulnerables
para interceptar y ver la información que se transmite.

== Atributos

* Capa: Capa de Recursos
* Activo: Datos
* Alcance: Confidencialidad
* Fase: Operación
* Tipo de Control: Recomendación

== Referencias

. [[r1]] link:https://pcinetwork.org/forum/index.php?threads/pci-dss-3-0-6-5-4-insecure-communications.660/[PCI 6.5.4 Insecure communications/transport layer protection]
. [[r2]] link:https://www.owasp.org/index.php/Top_10_2014-I4_Lack_of_Transport_Encryption[OWASP Top 10 2014: I4 Top 10 2014-I4 Lack of Transport Encryption]
. [[r3]] link:https://www.owasp.org/index.php/Mobile_Top_10_2014-M3[OWASP Top 10 2014: M3 Insufficient Transport Layer Protection]
. [[r4]] link:https://www.owasp.org/index.php/ASVS_V2_Authentication[+OWASP-ASVS v3.1-2.16+]
Verificar que todos los datos de la aplicación
sean transmitidos por un canal cifrado (por ejemplo +TLS+).
. [[r5]] link:https://www.owasp.org/index.php/ASVS_V9_Data_Protection[+OWASP-ASVS v3.1-9.3+]
Verificar que toda la información sensible
es enviada en el cuerpo del mensaje HTTP o sus encabezados
(Los parámetros URL nunca deben enviar información sensible).
