:slug: kb/aspnet/configurar-tiempo-sesion
:eth: no
:category: aspnet
:kb: yes

= Configurar tiempo de sesión

== Necesidad

Se requiere controlar el tiempo de sesión para una aplicación desarrollada en ASP.NET.

== Contexto

A continuación se describe las circunstancias bajo las cuales la siguiente solución tiene sentido:

. Se desarrolla una aplicación en ASP.NET

== Solución

. Para controlar el tiempo de sesión de las aplicaciones desarrolladas en ASP.NET, se debe configurar el valor para el atributo timeout en el subelemento < sessionState>, del elemento < system.web> dentro del archivo de configuración web.config. El archivo debe tener las siguientes líneas:

[source,xml,linenums]
----
<?xml version="1.0" encoding="utf-8" ?>
<configuration>
    <system.web>
         <sessionState timeout="# de minutos" />
    </system.web>
</configuration
---- 

* *NOTA:* El valor establecido en el atributo timeout representa los MINUTOS antes de que la sesión expire. El valor máximo que se puede configurar es de 525.601 minutos (1 año).

== Referencias

. https://msdn.microsoft.com/es-es/library/h6bb9cz9(VS.80).aspx[Elemento sessionState (Esquema de configuración de ASP.NET)]