:slug: products/forces/
:description: Forces makes use of human skills for the creation of exploits to break your build and force remediation of vulnerabilities performing DAST - SAST tests.
:keywords: Fluid Attacks, Products, Forces, Ethical Hacking, Pentesting, Security
:template: products/forces

= Forces

=== Break the Build for Confirmed Vulnerabilities

Through Forces, you can interrupt your deployment processes
— aka break the build — in cases where the detected vulnerabilities
(without false positives) that you do not accept in your systems
are still open, in other words, have not yet been remediated.

=== Easy Integration With Any CI System

Forces can be easily incorporated into any
Continuous Integration/Continuous Deployment (CI/CD) system
to act as a security gate, allowing everything that goes into production
to be free of the vulnerabilities you decide to remediate.

=== SAST, DAST and DXST

Forces can perform Dynamic and Static Application Security Testing
(DAST - SAST), as well as dynamic testing of many protocols (DXST),
directly in your CI environment,
all this without increasing the integration times in your systems.
