:slug: products/forces/
:description: Forces allows you to have DevSecOps in your company and breaks the build every time it is necessary to force the remediation of unaccepted vulnerabilities.
:keywords: Fluid Attacks, Products, Forces, Ethical Hacking, Pentesting, Security
:template: products/forces

= Forces

=== Break the Build for Confirmed Vulnerabilities

Through Forces, you can interrupt your deployment processes
— aka break the build — in cases where the detected vulnerabilities
in your systems that you do not accept are still open,
in other words, have not yet been remediated.

=== Easy Integration With Any CI System

Forces can be easily incorporated into any
Continuous Integration/Continuous Deployment (CI/CD) system
to act as a security gate, allowing everything that goes into production
to be free of the vulnerabilities you decide to remediate.

=== Force Vulnerability Remediation Processes

The activity of Forces in your pipelines
lives up to its name by leading you to promptly remedy the vulnerabilities
you decide not to have in your IT systems.
We have demonstrated that this significantly increases
your remediation effectiveness rates.
