:slug: rules/132/
:category: credentials
:description: This requirement establishes the importance of defining passphrases with at least 4 words and allowing them to be more than 64 characters long.
:keywords: Password, Length, Passphrase, ASVS, CWE, NIST, Rules, Ethical Hacking, Pentesting
:rules: yes

= R132. Passphrases with at least 4 words

== Requirement

The system must require passphrases to be at least 4 words long
and allow them to have 64 characters or more.

== Description

Passwords are identity assertion elements that can be easily forgotten.
Passphrases are sequences of words that are longer than passwords but are also
easier to remember.
Thus, systems should enforce the usage of passphrases at least 4 words long
and allow them to have 64 characters or more.

== Findings

* [inner]#link:/web/findings/035/[F035. Weak credential policy]#

* [inner]#link:/web/findings/050/[F050. Guessed weak credentials]#

== References

. [[r1]] link:https://cwe.mitre.org/data/definitions/521.html[CWE-521: Weak Password Requirements]
The product does not require that users should have strong passwords,
which makes it easier for attackers to compromise user accounts.

. [[r2]] link:https://pages.nist.gov/800-63-3/sp800-63b.html[NIST 800-63B 5.1.1.2 Memorized Secret Verifiers]
Verifiers SHOULD permit subscriber-chosen memorized secrets at least 64
characters in length.

. [[r3]] link:https://owasp.org/www-project-application-security-verification-standard/[OWASP-ASVS v4.0.1
V2.1 Password Security Requirements.(2.1.2)]
Verify that passwords 64 characters or longer are permitted.
