:slug: rules/083/
:category: rules
:description: En el presente documento se detallan los requerimientos de seguridad relacionados con las bitácoras que registran eventos relevantes. En este requerimiento se establece la importancia de evitar filtrar información sensible a través de eventos excepcionales almacenados en una bitácora.
:keywords: Requerimiento, Seguridad, Bitácoras, Información, Eventos, Almacenamiento.
:rules: yes

= REQ.083 No registrar datos sensibles en bitácoras

== Requisito

El sistema no debe registrar información sensible
en un evento excepcional de una bitácora.

== Descripción

Mientras registrar en bitácoras es una buena práctica en general,
la organización debe considerar que utilizar niveles muy altos
de registro de bitácoras son apropiados solo para ambientes de desarrollo,
pues al tener demasiada información de registro en etapas de producción
puede entorpecer la habilidad de un administrador de sistema
para detectar condiciones anómalas.
Esto puede significar que un atacante y un ataque
queden ocultos mientras intentan penetrar un sistema,
atrofiar el rastro de auditoría en un análisis forense,
o hacer más difícil depurar problemas en ambientes de producción.

== Implementación

. Suprimir grandes volúmenes de registros en bitácoras duplicados
y reemplazarlos con resúmenes periódicos.
Por ejemplo, +syslog+ puede registrar un evento de repetición
que indique "el último mensaje se ha repetido +X+ veces"
para evitar registrar muchas veces el mismo evento.

. Configurar un tamaño máximo para los archivos de bitácoras.
Sí se alcanza el tamaño máximo, el administrador debe ser notificado.
También considere reducir las funcionalidades de los subsistemas.
Esto puede resultar en una denegación de servicios para los usuarios,
pero previene que los subsistemas
impacten negativamente el sistema completo en general.

. Ajuste apropiadamente la configuración de los sistemas
cuando se pase de un estado de de depuración a producción.

== Soluciones

. +COBOL+ link:../../defends/cobol/error-operacion-aritmetica/[Manejar Errores en Operaciones Aritméticas].
. +COBOL+ link:../../defends/cobol/error-operacion-texto/[Manejar Errores en Operaciones de Texto].
. +Exchange 2010+ link:../../defends/exchange/activar-bitacoras-smtp/[Activar Bitácoras de Conectores SMTP].
. +Programación+ link:../../defends/programacion/bitacoras-cond/[Generar Bitácoras Condicionales].
. +Scala+ link:../../defends/scala/registrar-eventos-bitacoras/[Registrar Eventos en Bitácoras].
. +SharePoint 2010+ link:../../defends/sharepoint/registro-bitacoras/[Configurar Registro en Bitácoras].

== Ataques

. El sistema puede sufrir en cuanto a rendimiento
cuando los archivos de bitácoras se vuelven excesivamente grandes
y consumen recursos en exceso.

. Al almacenar demasiada información en las bitácoras
se pierde valor en lo registrado en caso de hacer diagnósticos de problemas
para recuperarse de un ataque o hacer un análisis forense.

. Si los administradores son incapaces
de efectivamente procesar archivos en bitácoras,
los ataques que hayan sido intentados pueden pasar desapercibidos,
lo que eventualmente termine con el sistema comprometido.

== Atributos

* Capa: Capa de Aplicación
* Activo: Bitácoras
* Alcance: Confidencialidad
* Fase: Operación
* Tipo de Control: Procedimiento

== Referencias

. [[r1]] link:https://www.owasp.org/index.php/Exception_Handling#Logging_Exception_Details[OWASP - Exception Handling]
. [[r2]] link:https://msdn.microsoft.com/en-us/library/ed577840(v=vs.100).aspx[Microsoft: How to: Handle Page-Level Errors]
. [[r3]] link:https://cwe.mitre.org/data/definitions/779.html[CWE-779: Logging of Excessive Data]
