:slug: rules/329/
:category: data
:description: This requirement establishes the importance of avoiding the storage of sensitive information in the client-side storage.
:keywords: Local, Session, Storage, ASVS, GDPR, ISO, NIST, OWASP, Rules, Ethical Hacking, Pentesting
:rules: yes

= R329. Keep client-side storage without sensitive data

== Requirement

Personal, sensitive and session data must not be stored in the client-side
storage
(*localStorage*, *sessionStorage*, cookies without security attributes, mobile
device unencrypted storage, etc.).

== Description

Data placed in the *localStorage* persists after a session is closed;
thus, any actor with access to the browser will be able to obtain it.
Furthermore, data in the *localStorage* or in the *sessionStorage* is visible to
scripts that are running on the browser,
and these scripts could belong to malicious third-parties.
Therefore, no sensitive or session information should be stored in the
client-side storage.

== Findings

* [inner]#link:/web/findings/085/[F085. Sensitive data stored in the client-side storage]#

== Rereferences

. [[r1]] link:https://cwe.mitre.org/data/definitions/922.html[CWE-922: Insecure Storage of Sensitive Information]
The software stores sensitive information without properly limiting read or
write access by unauthorized actors.

. [[r2]] link:https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:02002L0058-20091219[Directive 2002/58/EC (amended by E-privacy Directive 2009/136/EC).
Art. 4: Security of processing.(1a)]
The measures referred to in paragraph 1 shall at least protect personal data
stored or transmitted against accidental or unlawful destruction,
accidental loss or alteration,
and unauthorized or unlawful storage, processing, access or disclosure.

. [[r3]] link:https://gdpr-info.eu/art-5-gdpr/[GDPR. Art. 5: Principles relating to processing of personal data.(1)(f).]
Personal data shall be processed in a manner that ensures appropriate security
of the personal data,
including protection against unauthorized or unlawful processing and against
accidental loss, destruction or damage.

. [[r4]] link:https://gdpr-info.eu/recitals/no-51/[GDPR. Recital 51: Protecting sensitive personal data].
Personal data which are, by their nature, particularly sensitive in relation to
fundamental rights and freedoms merit specific protection as the context of
their processing could create significant risks to the fundamental rights and
freedoms.

. [[r5]] link:https://www.iso.org/obp/ui/#iso:std:54534:en[ISO 27001:2013. Annex A - 18.1.3]
Protect records against loss, destruction, forgery, unauthorized access and
unauthorized release,
in accordance with legal, regulatory, contractual and business requirements.

. [[r6]] link:https://pages.nist.gov/800-63-3/sp800-63b.html[NIST 800-63B 7.1 Session Bindings]
Secrets used for session binding SHOULD NOT be placed in insecure locations
such as *HTML5* Local Storage due to the potential exposure of local storage to
cross-site scripting (*XSS*) attacks.

. [[r7]] link:https://owasp.org/www-project-top-ten/OWASP_Top_Ten_2017/Top_10-2017_A3-Sensitive_Data_Exposure[OWASP Top 10 A3:2017-Sensitive Data Exposure].
Many web applications and **API**s do not properly protect sensitive data,
such as financial, healthcare, and *PII*.
Attackers may steal or modify such weakly protected data to conduct credit card
fraud, identity theft, or other crimes.
Sensitive data may be compromised without extra protection,
such as encryption at rest or in transit, and requires special precautions when
exchanged with the browser.

. [[r8]] link:https://owasp.org/www-project-application-security-verification-standard/[OWASP-ASVS v4.0.1
V8.2 Client-side Data Protection.(8.2.2)]
Verify that data stored in client side storage (such as *HTML5* local storage,
session storage, **IndexedDB**, regular cookies or *Flash* cookies) does not
contain sensitive data or *PII*.
