:slug: rules/095/
:category: rules
:description: En el presente documento se detallan los requerimientos de seguridad relacionados a la gestión segura en cuanto al control de acceso en una organización. Por lo tanto, se recomienda que todo usuario que acceda al sistema con privilegios de administrador, esté previamente definido.
:keywords: Sistema, Seguridad, Usuario, Acceso, Administrador, Definir.
:rules: yes
:translate: rules/095/

= REQ.095 Definir usuarios con privilegios

== Requisito

Los usuarios que accederán al sistema con cuentas de administrador
o super administrador deben estar definidos.

== Referencias

. [[r1]] link:https://www.law.cornell.edu/cfr/text/45/164.308[+HIPAA Security Rules+ 164.308(a)(3)(i):]
Implementar políticas y procedimientos para asegurarse
que todos los empleados tengan acceso apropiado a la información sensible
como se especifica en el párrafo (a)(4) de esta sección,
y para prevenir que los empleados no autorizados
obtengan acceso a esta información.

. [[r2]] link:https://www.law.cornell.edu/cfr/text/45/164.310[+HIPAA Security Rules+ 164.310(a)(2)(iii):]
Procedimientos de control de acceso y validación:
Implementar procedimientos para controlar y validar
el acceso de una persona a las instalaciones basándose
en su rol o función, incluyendo control de visitantes
y control de acceso a software de la compañía
para pruebas o revisión.
