:slug: rules/050/
:category: architecture
:description: This requirement establishes the importance of controlling the calls to interpreted code in order to avoid malicious code injections.
:keywords: Code, System, ASVS, CWE, Interpreted, JavaScript, Rules, Ethical Hacking, Pentesting
:rules: yes

= R050. Control calls to interpreted code

== Requirement

Interpreted code (e.g. *Javascript*, *CSS*) must be loaded from domains
controlled by the organization.

== Description

Applications often use resources or have dependencies that are hosted on
other servers.
These resources should be hosted on domains controlled by the organization
in order to prevent several types of injection attacks.

== References

. [[r1]] link:https://cwe.mitre.org/data/definitions/829.html[CWE-829: Inclusion of Functionality from Untrusted Control Sphere].
The software imports, requires, or includes executable functionality
(such as a library) from a source that is outside of the intended control
sphere.

. [[r2]] link:https://cwe.mitre.org/data/definitions/830.html[CWE-830: Inclusion of Web Functionality from an Untrusted Source].
The software includes web functionality (such as a web widget) from another
domain,
potentially granting total access and control of the software to the untrusted
source.

. [[r3]] link:https://owasp.org/www-project-application-security-verification-standard/[OWASP-ASVS v4.0.1
V5.3 Output encoding and Injection Prevention Requirements.(5.3.6)]
Verify that the application projects against *JavaScript* or *JSON* injection
attacks,
including for eval attacks, remote *JavaScript* includes, *CSP* bypasses,
**DOM XSS**, and *JavaScript* expression evaluation.

. [[r4]] link:https://owasp.org/www-project-top-ten/OWASP_Top_Ten_2017/Top_10-2017_A1-Injection[OWASP Top 10 A1:2017-Injection].
Injection flaws, such as **SQL**, **NoSQL**, **OS**, and *LDAP* injection,
occur when untrusted data is sent to an interpreter as part of a command or
query.
The attacker’s hostile data can trick the interpreter into executing unintended
commands or accessing data without proper authorization.

. [[r5]] link:https://owasp.org/www-project-application-security-verification-standard/[OWASP-ASVS v4.0.1
V10.3 Deployed Application Integrity Controls.(10.3.2)]
The application must not load or execute code from untrusted sources,
such as loading includes, modules, plugins, code, or libraries from untrusted
sources or the Internet.

. [[r6]] link:https://owasp.org/www-project-application-security-verification-standard/[OWASP-ASVS v4.0.1
V10.3 Deployed Application Integrity Controls.(10.3.3)]
Verify that the application has protection from sub-domain takeovers if the
application relies upon *DNS* entries or *DNS* sub-domains.

. [[r7]] link:https://owasp.org/www-project-application-security-verification-standard/[OWASP-ASVS v4.0.1
V12.3 File execution Requirements.(12.3.6)]
Verify that the application does not include and execute functionality from
untrusted sources,
such as unverified content distribution networks, *JavaScript* libraries,
or **node npm** libraries.
