from syntax_cfg.dispatchers import (
    connect_to_block,
    connect_to_next,
    end_node,
    if_node,
    multi_path,
    step_by_step,
)
from syntax_cfg.types import (
    Dispatcher,
    Dispatchers,
)

DISPATCHERS: Dispatchers = (
    Dispatcher(
        applicable_types={
            "Class",
            "MethodDeclaration",
            "Namespace",
        },
        cfg_builder=connect_to_block.build,
    ),
    Dispatcher(
        applicable_types={
            "DeclarationBlock",
            "File",
        },
        cfg_builder=multi_path.build,
    ),
    Dispatcher(
        applicable_types={
            "ExecutionBlock",
        },
        cfg_builder=step_by_step.build,
    ),
    Dispatcher(
        applicable_types={
            "If",
        },
        cfg_builder=if_node.build,
    ),
    Dispatcher(
        applicable_types={
            "Comment",
            "MethodInvocation",
            "ThrowStatement",
            "VariableDeclaration",
        },
        cfg_builder=connect_to_next.build,
    ),
    Dispatcher(
        applicable_types={
            "Import",
            "Return",
        },
        cfg_builder=end_node.build,
    ),
)
