:slug: products/rules/list/158/
:category: source
:description: This requirement establishes the importance of developing applications in an adequately updated and free of known vulnerabilities programming language.
:keywords: Security, Source Code, Updates, Vulnerabilities, Programming, ASVS, CAPEC, CWE, PCI DSS, Rules, Ethical Hacking, Pentesting
:rules: yes

= R158. Use a secure programming language

== Requirement

System source code must be implemented
in a stable, updated, tested, and free of known vulnerabilities
version of the chosen programming language.

== Findings

* [inner]#link:/findings/067/[F067. Improper resource allocation]#

* [inner]#link:/findings/070/[F070. Inappropriate coding practices]#

== References

. [[r1]] link:http://capec.mitre.org/data/definitions/123.html[CAPEC-123: Buffer Manipulation].
An adversary manipulates an application's interaction with a buffer in an
attempt to read or modify data they shouldn't have access to.
Buffer attacks are distinguished in that it is the buffer space itself that is
the target of the attack rather than any code responsible for interpreting the
content of the buffer.

. [[r2]] link:https://cwe.mitre.org/data/definitions/120.html[CWE-120: Classic Buffer Overflow].
The program copies an input buffer to an output buffer without verifying that
the size of the input buffer is less than the size of the output buffer,
leading to a buffer overflow.

. [[r3]] link:https://owasp.org/www-project-top-ten/OWASP_Top_Ten_2017/Top_10-2017_A9-Using_Components_with_Known_Vulnerabilities[OWASP Top 10 A9:2017-Using Components with Known Vulnerabilities].
Components, such as libraries, frameworks, and other software modules,
run with the same privileges as the application.
If a vulnerable component is exploited,
such an attack can facilitate serious data loss or server takeover.
Applications and **API**s using components with known vulnerabilities may
undermine application defenses and enable various attacks and impacts.

. [[r4]] link:https://owasp.org/www-project-application-security-verification-standard/[OWASP-ASVS v4.0.1
Appendix C: Internet of Things Verification Requirements.(C.11)]
Verify that any use of banned *C* functions are replaced with the appropriate
safe equivalent functions.

. [[r5]] link:https://owasp.org/www-project-application-security-verification-standard/[OWASP-ASVS v4.0.1
V5.4 Memory, String, and Unmanaged Code Requirements.(5.4.1)]
Verify that the application uses memory-safe string, safer memory copy and
pointer arithmetic to detect or prevent stack, buffer, or heap overflows.

. [[r6]] link:https://owasp.org/www-project-application-security-verification-standard/[OWASP-ASVS v4.0.1
V14.2 Dependency.(14.2.1)]
Verify that all components are up to date, preferably using a dependency
checker during build or compile time.

. [[r7]] link:https://owasp.org/www-project-application-security-verification-standard/[OWASP-ASVS v4.0.1
V14.2 Dependency.(14.2.4)]
Verify that third party components come from pre-defined, trusted and
continually maintained repositories.

. [[r8]] link:https://www.pcisecuritystandards.org/documents/PCI_DSS_v3-2-1.pdf[PCI DSS v3.2.1 - Requirement 6.2]
Ensure that all system components and software are protected from known
vulnerabilities by installing applicable vendor-supplied security patches.
