:slug: careers/character-test/
:category: careers
:description: The main goal of the following page is to inform potential talents and people interested in working with us about our selection process. The character test evaluates your strengths and temperament in order to determine whether the candidate matches the required profile.
:keywords: Fluid Attacks, Careers, Selection, Character, Test, Strengths.

= Character Evaluation

The next step in the selection process
to become a part of the +Fluid Attacks+ team
is taking a test
that looks to quantify the 4 main strengths
that we look for in a candidate.
Our philosophy is based on
putting together a very talented team
in which ethics and
respect are a priority,
where we will work to better your strengths
instead of trying to correct your weaknesses.

To continue with this step,
we ask that you please follow the following instructions:

. Follow the link that will be sent to you via email
once you finish the previous states.
+
Or follow this [inner]#link:https://fluidattacks.com/forms/profile[link]#
. Follow the instructions on screen,
. Once you are registered
you can take the test in 8 minutes.
There are 24 questions
with a maximum of 20 seconds per question,
. Once you have finished the test
we will be able to see your 4 main strengths.
Here are some suggestions for the test:
. Once you start the test
it can not be paused
nor repeated,
. Make sure no interruptions occur during the test,
. Trust your instinct,
. There are no wrong answers,
. The test results are always your 4 main strengths,
. If you have any doubts
don’t hesitate to contact us at careers@autonomicmind.com

Remember the agility with which you finish each stage
Will be a variable taken into account
When making our decision.
