:slug: careers/reasons/
:category: careers
:description: If you are someone who is talented and passionate about software development, information technology and are eager to learn, you should consider being a part of our team here at `Fluid Attacks`. Here are some reasons why `Fluid Attacks` is a great place to work.
:keywords: Fluid Attacks, Career, Reasons, Work, Projects, Clients.

= Reasons to work with us

`Fluid Attacks` is a great place to work.
This is due to:

== Hackers that develop their own tools

When we have projects we hack applications or corporate networks.
When we do not have projects,
we develop our own software tools.
This is why we are looking for hackers that are passionate about programming.
Our favorite technologies are `Linux`, `Git`, `Python`,
`Docker`, `Ansible`, and `Amazon Web Services`.
It does not matter if you have not yet mastered these tools.
With `Fluid Attacks`, what matters is your capacity to self-teach
and learn new skills to address challenges we face on a daily basis,
the discipline with which you face challenges,
the honesty to say what needs to be said,
and the ability to listen and communicate
in a manner that fosters respectful and equal collaboration
with other team members.

Do you want to take part in the most challenging selection process there is?
A selection process where no matter the result,
you will learn more than with any other company?
If so, then we invite you to participate
and see for yourself that with `Fluid Attacks`,
it is better to do, then to know.
Our selection process is guided using `Git`,
provides feedback through continuous integration
and allows you to improve your world-ranking in programming and hacking,
as well as your `GitLab` profile.
You don’t need to have graduated,
don’t need to be enrolled in a college or university,
nor have any specific work experience.
The only thing that matters, is that you show us you can learn,
on your own, at an expected rate.

== Short projects and high rotations

`70%` of the company’s projects are small (less than `1` month)
and medium (`1` to `6` months).
This allows you to constantly become familiar with new organizations,
different problems, different methods,
and to broaden your knowledge.

== Continuous improvement based on International Standards

`Fluid Attacks` was the first company in Colombia
to obtain an `ISO/IEC 27001` (Information Security) certification
at the same time we obtained the `ISO 9001` certificate.
Also, our continuous improvement process
uses the `ISO/IEC 17025` and Common Criteria standards
as a reference for all security tests.

== Work with the great ones

`Fluid Attacks` provides information security services
to some of the biggest organizations in Colombia.
This means that there will always be challenging projects
in which you can participate.
Bancolombia, Colpatria, Davivienda,
-- the biggest banks in the country;
`UNE`, `ETB`, `EDATEL`, Claro,
-- the biggest ISP in the country; and many more.

== Great talent working together

Our most valuable asset is our people
and we are proud of our amazing team.
In fact, it is a very young team with an average age of `25`.
We believe our talented team makes `Fluid Attacks`
a competitive place to work and, at the same time,
a great place to learn and develop your skills.
The first three `Debian` developers in Colombia work with `Fluid Attacks`.
Compared to other companies,
`Fluid Attacks` has the highest percentage
of employees certified in
link:../../services/certifications/#certified-ethical-hacker-(ceh)[`CEH`] and
link:../../services/certifications/#offensive-security-wireless-professional-(oswp)[`OSCP`]
The majority of the team members
of the Latin American Security Wargames Championship work with us.
Additionally, our employees have important certifications such as
link:../../services/certifications/#certified-ethical-hacker-(ceh)[`CEH`],
link:../../services/certifications/#offensive-security-wireless-professional-(oswp)[`OSCP`],
link:../../services/certifications/#certified-information-systems-auditor-(cisa)[`CISA`],
link:../../services/certifications/#certified-information-security-manager-(cism)[`CISM`],
link:../../services/certifications/#giac-information-security-professional-(gisp)[`GISP`],
link:../../services/certifications/#certified-information-systems-security-professional-(cissp)[`CISSP`]
link:../../services/certifications/#comptia-security`[`CompTIA Security``] and
link:../../services/certifications/#information-technology-infrastructure-library-certification-(itil)[`ITIL`].

== Socially responsible

`Fluid Attacks` also believes that companies,
no matter their size or sector,
must contribute to  society's welfare.
This is why `Fluid Attacks` participates, as a company,
and actively encourages our employees to support education
through the organization _“Dividendo por Colombia”_.
At `Fluid Attacks` we also recycle and separate our waste
into glass, paper, plastic, and ordinary
for the benefit of the community.

== Former employees

We are also proud of our former employees
who are now studying or working
in major universities and companies all over the world.
Here is a short list:

  .  Rafael: Masters in Math from the Royal Institute of Technology in Sweden,
currently `PhD` in Math at the University of Miami.
  . Miguel: Masters in Computer Science from the Max-Plank Institute in Germany,
  currently PhD at the same institute.
  . Diego: Masters in Information Security, Australia.
  . Juan: Masters in Innovation, Switzerland.
  . Manuel: Masters in Innovation, England.
  . Jorge: Masters in Math from the University of Miami.
  . Julian: Yahoo Taiwan.
  . Luis: SAP Security consultant in England.
  . Sebastian and Juan: Founders of Coffee Grid.
  . Jaime: Entrepreneur with our cloud services ally (associate), `Nuva`.

== Maintaining contact in academia

To us, it is very important to maintain close relationships in academia.
This is why some of our employees teach
or have taught courses and lectures
at different universities in Medellin.

Courses in topics such as:

* Information Security.
* Secure Development Life Cycle.
* Programming.
* Networks.
* Operating Systems.
* Distributed Systems.

In addition,
we are part of the Business Lecture group at `EAFIT` University,
University of Medellin,
La Salle University Corporation,
and the University of Antioquia.

In this program our employees teach short courses on specific topics,
free of charge, for students at a variety of universities.
So far, we have offered courses in Basics of `Linux`,
Information Security Principles,
and Hacking through Wargames.
