:slug: services/continuous-hacking/
:category: services
:description: In this page we describe our Continuous Hacking service, which aims to detect and report all the vulnerabilities in your application as soon as possible. Our participation in the development life cycle allow us to continuously detect security findings in a development environment.
:keywords: Fluid Attacks, Services, Continuous Hacking, Ethical Hacking, Pentesting, Security.
:template: salesforce

= Continuous Hacking

We detect and report all vulnerabilities
and security issues during the entire software development cycle.
Our participation during the entire development period
allows us to detect security issues continuously as the software evolves.
There's no need to have a working environment
to start hacking since we are able to analyze source code
published on a project’s +GIT+ repository.
The rigorous inspection carried out by our team
allows us to detect all security issues
with no false positives and to check if issues were properly repaired
before the system goes into the production phase.

[role="tb-alt"]
[cols=3, frame="topbot"]
|====

a|image::hacking-techniques.svg[alt="Source code symbol"]

2+a|== Hacking techniques

* Integral continuous hacking
is achieved through application and infrastructure ethical hacking,
as well as source code analysis.
We require access to both, the +GIT+ repository and integration environment,
in order to perform integral continuous hacking.

* In limited continuous ethical hacking,
you can choose between application ethical hacking
or source code analysis.
Access to the +GIT+ repository or the integration environment
is required to perform limited continuous hacking.

2+a|== Healthcheck

When a new continuous ethical hacking subscription starts,
if there were any previous issues
it is necessary to perform a healthcheck.
This means we will attack all versions of the existing code
up to the subscription start point in addition to the monthly test limit
to catch up with the development team
within the first +3+ subscription months.
Then we’ll continue hacking simultaneously as development continues
(healthcheck will have additional fees).

a|image::healthchecks.svg[alt="Source code with successful checks"]

a|image::severity.svg[alt="Checklist"]

2+a|== Severity and Hacking Environments

You are able to decide which security requirements will be tested
on each Ethical Hacking (Profiling) through our
[inner]#link:../../products/rules/[Rules]# product.
You will know the exact severity for each hacking
(for inspected and non-inspected profiled requirements).
Basic service allows customers to choose a single environment
from production, testing or integration.
Customers can also add additional testing environments
for validation at an additional charge.

2+a|==  Duration of Service and Attack Cycles

The minimum subscription time for continuous ethical hacking is one year.
The selected system will be attacked multiple times
to test all versions generated during the development phase.

a|image::duration.svg[alt="Calendar"]

a|image::agile-communication.svg[alt="Two persons having a conversation"]

2+a|== Integrates

Our platform for communication,
follow up and reporting of your project.
You can use [inner]#link:../../products/integrates/[Integrates]#
to access general information about each finding,
check its remediation status,
classify it according to age,
visualize real-time project statistics and progress,
as well as other functionalities.

You can also use chat and comments for any project or finding question.
Integrates provides a Technical Report,
which contains detailed information on all security vulnerabilities.
It gives technical personnel
a road map for a technical remediation plan.
Also, you can find an Executive Report for use of all  project’s stakeholders.
It includes an in-depth findings analysis
and a projected business impact statement,
as well as a summary of the project scope,
methodology used, conclusions and recommendations.

2+a|== Remediation

Multiple finding validation cycles
are performed during the subscription period
to ensure findings have been properly repaired.
We can check if any finding has been successfully closed
as many times as a customer wants us to.
In order to perform this remediation validation,
a customer must first define the treatment
used to remediate the vulnerability
and then request, through Integrates,
a finding validation.
You can request clarification on any issue
by directly contacting our hackers through our platform [inner]#link:../../products/integrates/[Integrates]#.

a|image::validate-remediation.svg[alt="Checklist"]

a|image::exploitation.svg[alt="Computer with an open lock symbol"]

2+a|== Reproduce mock attacks

We can reproduce mock attacks with [inner]#link:../../products/asserts/[Asserts]#,
an automated closing engine which closes security findings
over execution environments (+DAST+ and +SAST+).
+Asserts+ breaks the build if finds out that a vulnerability is open,
either because it reopened or has not been closed.

2+a|== Critical information extraction

Whenever findings indicate the need to obtain information,
information extraction is done to maximize finding impacts
without compromising sensitive information.
[inner]#link:../../products/integrates/#compromised-records[Example]#.

a|image::critical-info.svg[alt="Arrows flowing out of a lock"]

a|image::secure-deletion.svg[alt="Trash can with a cloud behind"]

2+a|== Information gets deleted securely

+7+ days after a customer approves their final report
all information gathered during Ethical Hacking
is deleted securely from all of our systems.

2+a|== Highly trained hacking team

Our hackers have practical certifications and academic backgrounds
related to security testing.
They perform manual testing and use tools
to guarantee that our reporting includes insecure programming practices,
standard alignment and security regulation compliance,
and findings with specific business impacts.
This enables us to detect Zero Day findings
with no false positive reports.

a|image::trained-team.svg[alt="Team"]

|====

* To check on differences between our services
and other providers take a look at our differentiators
[inner]#link:../differentiators/[here]#.

* To check on differences between our One-shot hacking
and Continuous hacking take a look at our comparative
[inner]#link:../comparative/[here]#.
