:slug: empleos/portafolio/
:category: empleos
:description: La siguiente página tiene como objetivo informar a los interesados en ser parte del equipo de trabajo de FLUID sobre el proceso de selección realizado. El portafolio es un documento que contiene tus principales logros académicos, muestras y resultados de tus proyectos más destacables.
:keywords: FLUID, Empleo, Proceso, Selección, Portafolio, Candidato.
:translate: careers/portfolio/

= Portafolio

Con respecto al portafolio, estamos a la espera de un documento que se ajuste a lo descrito a continuación. Este entregable es indispensable en nuestro proceso de selección

Pretendemos que en ese documento el candidato pueda mostrar sus mejores resultados académicos y/o profesionales.

Le recordamos que los objetivos del portafolio son:

* Evidenciar la capacidad del candidato de alcanzar resultados concretos y sobresalientes
* Demostrar el interés del candidato por pertenecer a la organización
* Detectar la alineación entre los resultados esperados por la organización y los resultados que puede dar el aspirante.

Los requisitos que se esperan del documento son los siguientes:

. El portafolio debe entregarse en formato PDF a través del formulario de aplicación. Sin embargo, en este caso puedes construirlo y enviarlo vía e-mail a careers@autonomicmind.co.
. Es un documento diferente a la hoja de vida.
. El portafolio debe tener mínimo 5 resultados entre personales, profesionales y académicos cada uno de ellos explicado en máximo 1 página
* Diseños (de red, de datos, de clases, de circuitos, etc)
* Porciones de código.
* Documentación.

. El portafolio puede presentar resultados de diferentes categorías (código fuente, diseños, documentación, estadísticas, etc)
. El portafolio debe preservar los derechos de autor:
* Citando las fuentes pertinentes.
* Impidiendo la asociación entre el resultado y la organización para la cual fue creado.
* Reproduciendo sólo parte del resultado de forma que se limite su uso inadecuado.
. El portafolio puede seguir las recomendaciones de los portafolios de diseño que apliquen a trabajos de ingeniería:
* Simple
* Interesante
* Fácil de leer
* Sólo sus mejores resultados

El propósito de este documento es ver su capacidad de expresarse sobre si mismo, sintetizar ideas y llamar la atención.

No seguir estas indicaciones evidenciará dificultad para seguir instrucciones o poco interés para el proceso en FLUID y por tal motivo sera finalizado el proceso de forma inmediata.

