:slug: kb/lenguajes/cobol/compilar-programa-de-forma-estricta
:eth: no
:category: cobol
:kb: yes

= Compilar Programa de Forma Estricta

== Necesidad

Compilar programa en COBOL de forma estricta

== Contexto

A continuación se describe las circunstancias bajo las cuales la siguiente
solución tiene sentido:

. Se está desarrollando una aplicación en COBOL.
. El código debe compilarse o interpretarse de forma estricta. [1]

== Solución

. A través del parámetro GENLVL del comando CRTBNDCBL se especifica el nivel
de severidad que determina si un objeto es creado. La severidad corresponde al
nivel de severidad de los mensajes producidos durante la compilación. Este
parámetro aplica individualmente a cada unidad dentro del miembro del archivo
fuente.
. Se debe especificar un número de uno o dos dígitos, desde 0 hasta 30, el cual
es el nivel de severidad que usted desea para determinar si el objeto es creado
o no. Ningún programa es creado si algún error ocurre con una severidad igual o
mayor a la especificada.
. La siguiente tabla muestra los niveles de severidad para diferentes tipos
mensajes:
|===
|Severidad |Tipo de mensaje

|00 - 04
|Información

|05 - 19
|Advertencia

|20 - 29
|Error

|30 - 39
|Severo

|40 - 99
|Terminal
|===
[start=4]
. Para compilar un programa en COBOL de forma estricta se debe usar "0" como
argumento en el parámetro GENLVL. Para crear el programa COBOLSTR de la
biblioteca FLUID con un nivel de severidad 0 (Compilación estricta) se usa el
siguiente comando:
[source,cobol,linenums]
----
CRTBNDCBL
PGM(FLUID/COBOLSTR)
SRCFILE(FLUID/SOURCE)
SRCMBR(COBOLSTR)
GENLVL(0)
REPLACE(*YES)
----
[start=5]
. El anterior programa es creado exitosamente, el código fuente utilizado para
esta solución y que contiene la estructura básica de un programa en COBOL es el
que puede observar a continuación:
[source,cobol,linenums]
----
       IDENTIFICATION DIVISION.
       PROGRAM-ID. COBOLSTR.
       ENVIRONMENT DIVISION.
       DATA DIVISION.
       PROCEDURE DIVISION.
       MAIN.
           DISPLAY "Programa estricto".
           STOP RUN.
----

== Referencias
 	
. REQ.0152: El código debe compilarse o interpretarse de forma estricta.
