:slug: defends/sharepoint/configurar-bitacoras/
:category: sharepoint
:description: Nuestros ethical hackers explican cómo evitar vulnerabilidades de seguridad mediante la programación segura en Microsoft SharePoint 2010 al configurar el registro en bitácoras. Las bitácoras facilitan el seguimiento y detección de anomalías al registrar eventos relevantes.
:keywords: Sharepoint 2010, Bitácoras, Registro, Eventos, Writetrace, Seguimiento
:defends: yes

= Configurar Registro en Bitácoras

== Necesidad

Registrar en bitácoras información de eventos excepcionales
en +Microsoft Sharepoint 2010+

== Contexto

A continuación se describe las circunstancias
bajo las cuales la siguiente solución tiene sentido:

. Se cuenta con una implementación de +Microsoft Sharepoint 2010+.

== Solución

Ninguna aplicación está exenta de fallas o anomalías.
Incluso las aplicaciones más robustas
pueden presentar comportamientos inesperados,
ya sea por un ataque ejecutado por un usuario malicioso,
un error humano, o un escenario no contemplado.
Cuando ocurren estas situaciones lo más recomendable
es llevar un seguimiento exhaustivo
para encontrar la causa de este comportamiento,
y tomar las medidas preventivas y/o correctivas necesarias
para solucionarlo, o evitar que el daño se propague a más información.
Aquí es donde resultan útiles las bitácoras.
Una bitácora permite registrar eventos excepcionales
y relevantes de la aplicación,
facilitando el seguimiento en caso de una anomalía en la aplicación.
En este artículo abordaremos la configuración de bitácoras
utilizando +Microsoft Sharepoint 2010+
para facilitar el monitoreo y registro de eventos excepcionales.

En +Microsoft Sharepoint 2010+,
+Microsoft+ adicionó capacidades de depuración y registro
para ayudar a los desarrolladores
a implementar monitoreo y depuración en las aplicaciones.
Adicionalmente se introdujo una base de datos
que contiene toda la información de registros de los servidores.

Para escribir en los registros de +Microsoft 2010+
se puede hacer uso de la clase +SPDIagnosticsService+,
el miembro +Local+ y el método +WriteTrace+.
A continuación se muestran los parámetros del método +WriteTrace+:

.Método WriteTrace
[source, java, linenums]
----
public void WriteTrace(
  uint id,
  SPDiagnosticsCategory category,
  TraceSeverity severity,
  string output,
  params Object[] data
)
----

Los parámetros del método mencionado anteriormente
se detallan a continuación:

* +id+: El identificador de la plataforma para la traza.

* +category+: La categoría de la traza (ver +SPDiagnosticsCategory+).

* +severity+: La severidad de la traza.

* +output+: El mensaje de salida. Puede ser una cadena de formato.

* +data+: Los datos de la cadena de formato.

Cabe mencionar que al utilizar el parámetro +category+
se debe enviar una categoría reconocida por el servicio,
En caso contrario arrojará un error.

Un ejemplo de implementación de la clase +SPDiagnosticsService+
se puede apreciar a continuación:

[source, java, linenums]
----
SPDiagnosticsService diagnosticsService = SPDiagnosticsService.Local;
SPDiagnosticsCategory cat = diagnosticsService.Areas["SharePoint Foundation"].Categories["Unknown"];

string format = "Ocurrio un evento excepcional {0} ";
diagnosticsService.WriteTrace(1, cat, TraceSeverity.Medium, format, DateTime.Today);
----

Si se envía un valor al parámetro +severity+ menor
al valor definido en la propiedad  +TraceSeverity+,
éste no es registrado en la bitácora.

== Referencias

. [[r1]] link:https://msdn.microsoft.com/en-us/library/microsoft.sharepoint.administration.spdiagnosticsservicebase.writetrace.aspx[SPDiagnosticsServiceBase.WriteTrace method].
. [[r2]] link:https://msdn.microsoft.com/en-us/library/microsoft.sharepoint.administration.spdiagnosticsservicebase.aspx[SPDiagnosticsServiceBase class].
. [[r3]] link:https://msdn.microsoft.com/en-us/library/microsoft.sharepoint.administration.spdiagnosticsservicebase_members.aspx[SPDiagnosticsServiceBase members].
. [[r4]] link:../../../rules/075/[REQ.075 Registrar eventos en bitácoras].
. [[r5]] link:../../../rules/079/[REQ.079 Registrar momento de ocurrencia de eventos].
. [[r6]] link:../../../rules/083/[REQ.083 No registrar datos sensibles en bitácoras].
