:slug: rules/264/
:category: authentication
:description: This document details the security requirements and guidelines related to secure user authentication management in the organization. In this case, it is recommended that the system require authentication for all resources not explicitly classified as public.
:keywords: Private Resources, Authentication, Public Resources, Access, ASVS, CWE
:rules: yes

= REQ.264 Request authentication

== Requirement

The system must require authentication for all resources,
except for the consultation or visualization of those specifically classified
as public.

== Description

Sometimes systems have information and other resources that are not considered
public.
These resources should be protected by a secure authentication mechanism that
prevents unauthorized actors from accessing them.

== Findings

* link:/web/findings/012/[F012. Unauthenticated access to protected resources]

* link:/web/findings/075/[F075. Unauthorized access to files]

== References

. [[r1]] link:https://cwe.mitre.org/data/definitions/287.html[CWE-287: Improper Authentication]
When an actor claims to have a given identity,
the software does not prove or insufficiently proves that the claim is correct.

. [[r2]] link:https://cwe.mitre.org/data/definitions/306.html[CWE-306: Missing Authentication for Critical Function]
The software does not perform any authentication for functionality that
requires a provable user identity or consumes a significant amount of
resources.

. [[r3]] link:https://owasp.org/www-project-application-security-verification-standard/[OWASP-ASVS v4.0.1
V1.2 Authentication Architectural Requirements.(1.2.2)]
Verify that communications between application components,
including APIs, middleware and data layers, are authenticated.
Components should have the least necessary privileges needed.

. [[r4]] link:https://owasp.org/www-project-application-security-verification-standard/[OWASP-ASVS v4.0.1
V1.2 Authentication Architectural Requirements.(1.2.3)]
Verify that the application uses a single vetted authentication mechanism that
is known to be secure,
can be extended to include strong authentication,
and has sufficient logging and monitoring to detect account abuse or breaches.
