:slug: rules/264/
:category: authentication
:description: This requirement states that the system must request authentication for all resources not explicitly classified as public.
:keywords: Private Resources, Authentication, Public Resources, Access, ASVS, CWE, Rules, Ethical Hacking, Pentesting
:rules: yes

= R264. Request authentication

== Requirement

The system must require authentication for all resources,
except for the consultation or visualization
of those specifically classified as public.

== Description

Sometimes systems have information and other resources that are not considered
public.
These resources should be protected by a secure authentication mechanism that
prevents unauthorized actors from accessing them.

== Findings

* [inner]#link:/web/findings/006/[F006. Authentication mechanism absence or evasion]#

* [inner]#link:/web/findings/018/[F018. Improper authentication for shared folders]#

* [inner]#link:/web/findings/056/[F056. Anonymous connection]#

* [inner]#link:/web/findings/075/[F075. Unauthorized access to files]#

* [inner]#link:/web/findings/081/[F081. Lack of two-factor authentication]#

== References

. [[r1]] link:https://cwe.mitre.org/data/definitions/287.html[CWE-287: Improper Authentication].
When an actor claims to have a given identity,
the software does not prove or insufficiently proves that the claim is correct.

. [[r2]] link:https://cwe.mitre.org/data/definitions/306.html[CWE-306: Missing Authentication for Critical Function].
The software does not perform any authentication for functionality that
requires a provable user identity or consumes a significant amount of
resources.

. [[r3]] link:https://owasp.org/www-project-top-ten/OWASP_Top_Ten_2017/Top_10-2017_A2-Broken_Authentication[OWASP Top 10 A2:2017-Broken Authentication].
Application functions related to authentication and session management are
often implemented incorrectly,
allowing attackers to compromise passwords, keys, or session tokens,
or to exploit other implementation flaws to assume other users’ identities
temporarily or permanently.

. [[r4]] link:https://owasp.org/www-project-top-ten/OWASP_Top_Ten_2017/Top_10-2017_A3-Sensitive_Data_Exposure[OWASP Top 10 A3:2017-Sensitive Data Exposure].
Many web applications and **API**s do not properly protect sensitive data,
such as financial, healthcare, and *PII*.
Attackers may steal or modify such weakly protected data to conduct credit card
fraud, identity theft, or other crimes.
Sensitive data may be compromised without extra protection,
such as encryption at rest or in transit, and requires special precautions when
exchanged with the browser.

. [[r5]] link:https://owasp.org/www-project-application-security-verification-standard/[OWASP-ASVS v4.0.1
Appendix C: Internet of Things Verification Requirements.(C.9)]
Verify that wireless communications are mutually authenticated.

. [[r6]] link:https://owasp.org/www-project-application-security-verification-standard/[OWASP-ASVS v4.0.1
V1.2 Authentication Architectural Requirements.(1.2.2)]
Verify that communications between application components,
including APIs, middleware and data layers, are authenticated.
Components should have the least necessary privileges needed.

. [[r7]] link:https://owasp.org/www-project-application-security-verification-standard/[OWASP-ASVS v4.0.1
V1.2 Authentication Architectural Requirements.(1.2.3)]
Verify that the application uses a single vetted authentication mechanism that
is known to be secure,
can be extended to include strong authentication,
and has sufficient logging and monitoring to detect account abuse or breaches.

. [[r8]] link:https://owasp.org/www-project-application-security-verification-standard/[OWASP-ASVS v4.0.1
V3.7 Defenses Against Session Management Exploits.(3.7.1)]
Verify the application ensures a valid login session or requires
re-authentication or secondary verification before allowing any sensitive
transactions or account modifications.

. [[r9]] link:https://owasp.org/www-project-application-security-verification-standard/[OWASP-ASVS v4.0.1
V9.2 Server Communications Security Requirements.(9.2.3)]
Verify that all encrypted connections to external systems that involve
sensitive information or functions are authenticated.

. [[r10]] link:https://owasp.org/www-project-application-security-verification-standard/[OWASP-ASVS v4.0.1
V14.5 Validate HTTP Request Header Requirements.(14.5.4)]
Verify that *HTTP* headers added by a trusted proxy or *SSO* devices,
such as a bearer token, are authenticated by the application.
