:slug: rules/333/
:category: credentials
:description: This requirement establishes the importance of storing the salt values used in the hashing process separately from hashed passwords.
:keywords: Salt, Store, Separately, ASVS, CWE, NIST, Rules, Ethical Hacking, Pentesting
:rules: yes

= R333. Store salt values separately

== Requirement

The salt values used during the password hashing process must be stored
separately from the hashed passwords.

== Description

Adding random salt to a password as part of the hashing process
drastically increases the time required to crack that password.
Salt values should be stored in a system different from the one in which
hashed passwords are stored so that if the hashes are breached,
an attacker still has to test every possible salt value in order to crack
a single password.

== References

. [[r1]] link:https://cwe.mitre.org/data/definitions/916.html[CWE-916: Use of Password Hash With Insufficient Computational Effort].
The software generates a hash for a password,
but it uses a scheme that does not provide a sufficient level of computational
effort that would make password cracking attacks infeasible or expensive.

. [[r2]] link:https://pages.nist.gov/800-63-3/sp800-63b.html[NIST 800-63B 5.1.1.2 Memorized Secret Verifiers]
The secret salt value SHALL be stored separately from the hashed memorized
secrets (e.g., in a specialized device like a hardware security module).

. [[r3]] link:https://owasp.org/www-project-application-security-verification-standard/[OWASP-ASVS v4.0.1
V2.4 Credential Storage Requirements.(2.4.5)]
The secret salt value SHALL be stored separately from the hashed passwords
(e.g., in a specialized device like a hardware security module).

. [[r4]] link:https://owasp.org/www-project-application-security-verification-standard/[OWASP-ASVS v4.0.1
V6.4 Secret Management.(6.4.2)]
Verify that key material is not exposed to the application but instead uses an
isolated security module like a vault for cryptographic operations.
