:slug: kb/aspnet/generar-numeros-aleatorios-seguros/
:eth: no
:category: aspnet
:kb: yes

= Generar Números Aleatorios Seguros

== Necesidad

Generar números aleatorios seguros en ASP.Net.

== Contexto

A continuación se describen las circunstancias 
bajo las cuales la siguiente solución tiene sentido:

. Se está desarrollando una aplicación en ASP.Net.
. Se desean generar números aleatorios seguros.

== Solución

Los números aleatorios generalmente son utilizados 
para generar llaves criptográficas 
que sirven para asegurar archivos y documentos.
Es por eso que es de vital importancia 
que los números aleatorios sean siempre seguros
para resistir posibles predicciones 
o ataques de criptoanalistas [1]. 

Existen diversas formas de generar números aleatorios, 
un ejemplo es utilizando generadores físicos, 
los cuales toman señales aleatorias del ambiente, 
tales como: el ruido generado por una fuga de corriente 
desde un diodo a un transistor,
el ruido generado al presionar una tecla,
señales perceptibles provenientes de alguna fuente de audio, 
tiempos entre interrupciones, entre muchos otros. 
Después de obtener la señal aleatoria,
ésta es procesada a través 
de una función criptográfica Hash
para obtener el número aleatorio.
Este tipo de generadores poseen la ventaja 
de ser verdaderamente aleatorios,
a diferencia de los generadores pseudo-aleatorios,
los cuales utilizan algoritmos aleatorios estáticos
que pueden ser generados a partir de código. 
De esta manera los números aleatorios 
generados con un generador físico
no pueden ser recreados 
por ningún tipo de software.

Otra forma de generar números aleatorios 
es utilizando generadores basados en código,
los cuales toman un valor semilla inicial
para generar una secuencia pseudo aleatoria de números.
El problema de esta práctica,
es que los resultados pueden ser reproducibles,
es decir, con las mismas condiciones iniciales
y el mismo valor semilla
es posible generar la misma secuencia de números.

Para el caso de este artículo, 
se hará uso de la clase _RNGCryptoServiceProvider_
para generar números aleatorios
criptográficamente seguros.
Para ello debemos seguir los siguientes pasos:

. La clase _RNGCryptoServiceProvider_ proporciona 
un generador de números pseudoaleatorios 
usando la implementación de un proveedor de servicios criptográficos. 
Esta clase no puede heredarse.
Inicialmente se usan los siguientes componentes:
+
[source, java, linenums]
----
using System;
using System.IO;
using System.Text;
using System.Security.Cryptography;
class RNGCSP
{
    public static void Main()
    {
----

. Luego se crea el objeto 
generador de números pseudoaleatorios.
+
[source, java, linenums]
----
RandomNumberGenerator rng = new _RNGCryptoServiceProvider()_;
----

. El método _GetBytes_ llena un arreglo de bytes 
con una secuencia de valores aleatorios criptográficamente seguros.
+
[source,java,linenums]
----
byte[] tokenData = new byte[32];
rng.GetBytes(tokenData);
----

. Finalmente, convertimos a Base64 para facilitar su impresión.
+
[source,java,linenums]
----
string token = Convert.ToBase64String(tokenData);
----

== Referencias

. https://www.segu-info.com.ar/proyectos/p1_generador-numeros.htm[Generadores de números aleatorios]
. https://msdn.microsoft.com/en-us/library/system.security.cryptography.rngcryptoserviceprovider.aspx[Microsoft, RNGCryptosServiceProvider]
. REQ.0143: Debe utilizarse como mecanismo de cifrado asimétrico 
un tamaño de clave mínimo de 2048 bits.
. REQ.0219: Debe usarse el mecanismo criptográfico 
más seguro ofrecido por la plataforma 
(ej: java.security.SecureRandom) 
para la generación de números aleatorios 
usados en procesos críticos 
(ej: generación de ID, mapeo de códigos, llaves).