:slug: kb/lenguajes/java/importar-certificado-digital
:eth: no
:category: java
:kb: yes

= Importar Certificado Digital

== Necesidad

Importar un certificado digital o confiar en uno autofirmado (Java)

== Contexto

A continuación se describen las circunstancias bajo las cuales la siguiente 
solución tiene sentido:

. Se desarrolla una aplicación en el lenguaje Java
. Se posee acceso al keystore de la máquina virtual de Java.

== Solución

. A continuación se describe el procedimiento para importar un certificado 
digital en el keystore de la máquina virtual de JAVA, con el objetivo que se 
pueda realizar una conexión SSL/TLS desde una aplicación que corre bajo esta. 
Para realizar el procedimiento se utiliza la herramienta keytool que se incluye 
dentro del JDK de JAVA.
. Keystore de JAVA:  se encuentra ubicado en $JAVA_HOME/jre/lib/security/cacerts 
y la contraseña predeterminada es changeit
. Verificar Certificados Instalados que se encuentran instalados en el keystore 
de la máquina virtual, se utiliza el comando keytool -list -keystore 
<keystorefile>, este solicitará el password del keystore para poder acceder a 
este.
+
[source, bash, linenums]
----
% keytool -list -keystore cacerts

% Enter keystore password:

Keystore type: JKS
Keystore provider: SUN

Your keystore contains 5 entries

aolrootca2, Mar 26, 2008, trustedCertEntry,
Certificate fingerprint (MD5): D6:ED:3C:CA:E2:66:0F:AF:10:43:0D:77:9B:04:09:BF
deutschetelekomrootca2, Nov 6, 2008, trustedCertEntry,
Certificate fingerprint (MD5): 74:01:4A:91:B1:08:C4:58:CE:47:CD:F0:DD:11:53:08
aolrootca1, Jan 17, 2008, trustedCertEntry,
Certificate fingerprint (MD5): 14:F1:08:AD:9D:FA:64:E2:89:E7:1C:CF:A8:AD:7D:5E
secomscrootca1, May 1, 2008, trustedCertEntry,
Certificate fingerprint (MD5): F1:BC:63:6A:54:E0:B5:27:F5:CD:E7:1A:E3:4D:6E:4A
verisignclass3g2ca, Mar 25, 2004, trustedCertEntry,
Certificate fingerprint (MD5): A2:33:9B:4C:74:78:73:D4:6C:E7:C1:F3:8D:CB:5C:E9
----

. Para importar un certificado al keystore se utiliza el comando 'keytool 
-import -alias <nombre alias del certificado> -keystore <keystorefile> -file 
<certfile>', este pedirá el password del keystore para poder acceder a este.
[source, bash, linenums]
----
% keytool -import -alias cabco -keystore cacerts -file /tmp/ca.cer

Enter keystore password:

Owner: CN=VERISIGN, OU=Engineering Team,
O=FLUID S.A., L=MEDELLIN, ST=ANTIOQUIA, C=CO
Issuer: CN=VERISIGN, OU=Engineering Team,
O=FLUID S.A., L=MEDELLIN, ST=ANTIOQUIA, C=CO
Serial number: 3f817305
Valid from: Sun Oct 05 08:49:57 COT 2003 until: Wed Jun 14 08:49:57 COT 2017
Certificate fingerprints:
 MD5: 3D:C3:23:80:20:79:72:58:F9:4B:C7:B5:5D:A9:86:FE
 SHA1: BF:5D:E4:5C:F5:37:BD:22:35:65:48:EA:64:AD:08:BB:15:A9:1E:AC
 Signature algorithm name: MD5withRSA
 Version: 3
Trust this certificate? [no]: yes
Certificate was added to keystore
----

== Referencias

. https://docs.microsoft.com/en-us/azure/java-add-certificate-ca-store[Adding a Certificate to the Java CA] 
. https://docs.oracle.com/javase/7/docs/technotes/tools/windows/keytool.html[Key and Certificate Management Tool]
. REQ.0142: Las funciones de criptografía del sistema deben ser implementadas 
con mecanismos criptográficos pre-existentes.