:slug: conferencias/
:description: La presente página tiene como objetivo informar a los clientes sobre el servicio de conferencias ofrecido por FLUID. Las conferencias tratan temas relacionados con la Seguridad de la Información y son preparadas por profesionales experimentados en el campo.
:keywords: FLUID, Conferencia, Seguridad, Experiencia, Información, Servicio
:translate: talks/

= Conferencias

. link:quemar-el-datacenter/[Quemar el Datacenter - De Mascotas a Ganado]

. link:aseguramiento-moviles/[Aseguramiento de Dispositivos Móviles]

== ¿Cuándo?

Acordaremos la fecha en que se dictará,
es cuestión de que nos indiques 3 posibles horarios para realizarla
y nosotros seleccionamos 1.

== Detalles

. *Inversión:* $0 COP, FLUID se encarga de todos los costos correspondientes excepto el lugar y el tiempo de los asistentes. Si no se pueden cumplir los requisitos mínimos de número de asistentes y perfil de los mismos, la inversión de la conferencia en Medellín es de $1.025.324 COP, en otras ciudades del país 2X, y 3X fuera de Colombia.

. *Material:* El material se le envia solo a los asistentes que diligencien la evaluación de satisfacción 1 día después de la conferencia.

== Requisitos

A continuación describimos los aspectos que requerimos se cumplan en su totalidad para poder dictar la conferencia sin ningún contratiempo:

. Todos los asistentes antes de retirarse DEBEN diligenciar por Internet una evaluación de satisfacción de 2 minutos.

. FLUID PODRÁ invitar hasta 4 asistentes adicionales a los de su organización.

. Los asistentes NO DEBEN usar celulares ni portátiles durante todo el tiempo de la conferencia.

. Todos los asistentes DEBEN tener previamente acceso a la totalidad de esta invitación de forma que puedan decidir voluntariamente si asistir o no.

. El expositor DEBE poder ingresar 30 minutos antes al lugar de la conferencia a conectar equipos, hacer pruebas de conectividad WiFi y así empezar a la hora en punto la conferencia.

. *Conexión HDMI física:*  La presentación se hace desde un portatil Linux con animaciones, por ende no son soportados conectores inalámbricos HDMI que requieren instalación de Drivers Windows.

. *Acceso a Google Drive via WiFi:* La presentación dispone de animaciones y videos solo disponibles si el portatil de presentación puede conectarse a Internet mediante una WiFi que permita conexión a Google Drive.

. No incluir personas remotamente.  La conferencia es muy dinámica y por ende depende mucho de la interacción cara a cara con el público.
