:slug: defends/suse/eliminar-metadatos/
:category: suse
:description: Nuestros ethical hackers explican cómo evitar vulnerabilidades de seguridad mediante la programación segura en Suse 11.3 al remover los metadatos presentes en los archivos. Se recomienda realizar esto para evitar la filtración de información sensible al momento de subir los archivos a Internet.
:keywords: Suse 11.3, Remover, Metadatos, Imágenes, PDF, Linux.
:defends: yes

= Eliminar Metadatos

== Necesidad

Eliminar metadatos en sistemas tipo +Linux+.

== Contexto

A continuación se describen las circunstancias
bajo las cuales la siguiente solución tiene sentido:

. Se dispone de un sistema +Linux Red Hat+ o +Suse+.
. Es necesario hacer un filtro de metadatos en los archivos
que están contenidos dentro de un sistema,
antes de que sean compartidos a terceros o sean expuestos en sitios públicos.
. Se esta realizando el proceso de aseguramiento de un sistema tipo +Linux+.

== Solución

Debemos seguir diferentes pasos para lograr eliminar datos
en diferentes extensiones de archivos.

=== Metadatos en Imágenes

Para el caso de las imágenes
vamos a usar un paquete llamado +EXIV2+.
Este paquete que permite borrar metadatos
de imágenes en formatos +JPEG+, +TIFF+, +PNG+, +JP2+, +Adobe DNG+,
+Canon CRW+, +Canon THM+, +Nikon NEF+, +Pentax PEF+ y +XMP+.
Para ello debemos seguir los siguientes pasos:

. Instalar el paquete +exiv2+ con el comando:
+
.Instalación exiv2
[source, bash, linenums]
----
$ sudo zypper install exiv2
----

. Luego si queremos eliminar los metadatos de un archivo en especial
con formato .JPG, debemos ejecutar el siguiente comando:
+
[source, bash, linenums]
----
$ sudo exiv2 rm archivo.JPG
----

. Además si queremos eliminar los metadatos de varias imágenes
dentro de un mismo directorio,
podemos usar un comodín de la siguiente forma:
+
[source, bash, linenums]
----
$ sudo exiv2 rm *.JPG
----

. Si queremos confirmar que los metadatos han sido borrados
podemos verificarlo dando clic derecho sobre la imagen e ingresando a
+propiedades+ y luego a la pestaña +imagen+.

=== Metadatos en archivos PDF

Ahora vamos a usar +pdftk+ para eliminar metadatos en archivos +PDF+.
Para ello seguimos los siguientes pasos:

. Primero debemos instalar el paquete +pdftk+ a través del siguiente comando:
+
[source, bash, linenums]
----
$ sudo zypper install pdftk
----

. Luego creamos un archivo nuevo en +Open office+ o +Libre Office+
con una pagina en blanco y lo exportamos a archivo +PDF+.

. A continuación fusionamos los dos archivos,
borrando los metadatos del archivo principal
con los metadatos del archivo en blanco:
+
[source, bash, linenums]
----
$ pdftk borrarmetadatos.pdf paginaenblanco.pdf cat output limpiodemetadata.pdf keep_final_id
----

. El documento +borrarmetadatos.pdf+ como su nombre lo dice,
es a quien le vamos a eliminar los metadatos.
El documento +paginaenblanco.pdf+ es el que creamos con +Open Office+,
y el documento +limpiodemetadata.pdf+ es el documento final.

. Por ultimo si queremos eliminar la página en blanco que nos quedó
dentro de nuestro documento, podemos hacerlo,
teniendo en cuenta que nuestro documento tenga +252+ páginas:
+
[source, bash, linenums]
----
$ pdftk limpiodemetadata.pdf cat 1-252 output limpiodemetadata1.pdf
----

=== Metadatos en archivos Office

Para eliminar metadatos en documentos +Open Office/Libre Office+
debemos tener en cuenta que los documentos con extensión +.odt+
son una serie de archivos empaquetados como un +tar.gz+ o un +.zip+.

. Para verificar los archivos empaquetados dentro de un documento +.odt+
ejecutamos el siguiente comando:
+
[source, bash, linenums]
----
file-roller nombredelarchivo.odt
----

. Una vez allí encontramos un fichero llamado +meta.xml+,
podemos ingresar con un editor de texto y modificarlo o borrarlo.
Es importante tener en cuenta
que si abrimos el documento nuevamente y guardamos,
los metadatos son creados nuevamente.

. Tanto +Open Office+ como +Libre Office+
tienen una función llamada +Control de versiones+.
Ésta se encarga de guardar información
de todos los cambios realizados en un documento,
además del autor de dichos cambios,
como también el texto que ha sido borrado previamente.
Para verificar si esta función esta habilitada vamos a la sección +editar+
luego a +modificaciones+ y nos fijamos si la casilla +Grabar+ esta habilitada.

== Referencias

. [[r1]] link:../../../rules/045/[REQ.045 Eliminar metadatos al compartir archivos].
. [[r2]] link:http://www.exiv2.org/[EXIV2 C++ metadata library and tools].
. [[r3]] link:https://www.pdflabs.com/tools/pdftk-the-pdf-toolkit/[PDFTK Tools].
