:slug: rules/237/
:category: rules
:description: En el presente documento se detallan los requerimientos de seguridad relacionados a la gestion segura de autenticacion de usuarios. Por lo tanto, el sistema debe garantizar que todas las acciones de usuario sean ejecutadas por un humano y no por robots que ejecutan tareas automatizadas.
:keywords: Autenticación, Tiempo, Seguridad, Segundos, Usuarios, Límite.
:rules: yes

= REQ.237 Establecer acciones de usuario seguras

== Requisito

El sistema debe garantizar
que quien realiza las acciones de registro, autenticación
y restablecimiento de contraseña es un humano
(usando `CAPTCHA` o retrasos incrementales).

== Descripción

Un sistema debe reconocer que tipo de usuario está interactuando con él,
sobretodo cuando se están realizando acciones
que pueden comprometer la confidencialidad de la información que gestiona;
como es el caso de la autenticación, registro y cambio de contraseña.
Es por eso que se deben implementar mecanismos
que eviten ataques automatizados a este tipo de entradas.

== Implementación

Desde el diseño y desarrollo debe un sistema
se deben tener en cuenta políticas que prevengan ataques automatizados,
las cuales deben garantizar la confidencialidad
y disponibilidad de la información.
Por lo que el tipo de control se debe elegir pensando en eso,
ya que muchas veces se tiene la idea errónea
de que al bloquear al usuario después de varios intentos fallidos
evitamos este tipo de ataque que aunque funciona no es recomendable;
ya que se genera un riesgo adicional al tener la posibilidad
de denegar aleatoriamente el servicio a los usuarios
aprovechando este tipo de controles.
Es por esto que se recomiendan bloqueos temporales
o el uso de mecanismos contra robots como lo es el `captcha`.

* *Retrasos Incrementales:*
Este control consiste en crear bloqueos temporales al acceso del sistema
después de un número de intentos fallidos,
el tiempo debe ser corto y puede ir aumentando si el comportamiento se repite.
Con esto bloqueas ataques de fuerza bruta,
ya que el robot se detendrá
cada vez que se bloquee temporalmente el usuario
con el que está intentando ingresar.

* Captcha (Completely Automated Public Turing test
to tell Computers and Humans Apart):
Como lo describe la sigla es un control
para diferenciar entre un computador y un humano
de esta forma bloquear ataques automatizados
siempre y cuando se utilicen `captchas` seguros
que no sean predecibles o se puedan descifrar
con `scripts` diseñados para ese fin.

== Ataques

. Ataques de fuerza bruta.

. Enumeración de usuarios.

== Atributos

* Capa: Capa de Aplicación
* ​Activo: Proceso de autenticación
* ​Alcance: Responsabilidad
* ​Fase: Operación
* ​Tipo Control: Recomendación

== Referencias

. [[r1]] link:https://www.owasp.org/index.php/Authentication_Cheat_Sheet#Prevent_Brute-Force_Attacks[OWASP - Authentication Cheat Sheet].
. [[r2]] link:https://cwe.mitre.org/data/definitions/307.html[CWE-307 - Improper Restriction of Excessive Authentication Attempts].
. [[r3]] link:https://cwe.mitre.org/data/definitions/799.html[CWE-799 - Improper Control of Interaction Frequency].
