:slug: careers/portfolio/
:category: careers
:description: The following page is meant to inform everyone interested in being part of the Fluid Attacks team about the selection process. The portfolio is a document that describes your biggest personal, professional and academic achievements, examples and results of your best projects.
:keywords: Fluid Attacks, Career, Process, Selection, Portfolio, Candidate.

= Portfolio

The items we expect to see in your portfolio are described below.
Through these, you can present your best academic
and/or your professional achievements.
We also use your portfolio to assess your ability to express yourself,
synthesize ideas, and capture our attention.
Your portfolio is of utmost importance in the selection process.

The objectives of the portfolio are:

* To present examples of a candidate's ability
to achieve concrete and outstanding results.
* To demonstrate a candidate's interest in joining the company.
*  To see if the results expected by the company
align with the demonstrated results of what a candidate can achieve.

Requirements for the portfolio:

. The portfolio must be delivered in a `PDF` format
through the application form.
In case you experience any trouble,
you can also submit it via email to careers@autonomicmind.com.
. The portfolio is not a `CV`.
Do not use your `CV` as a substitute for the portfolio.
. The portfolio must contain your top `5` achievements,
including personal, professional and academic achievements.
Each one must be explained in at most `1` page.
* Designs/Diagrams (network, data, class, circuits, etc).
* Code examples.
* Documentation.
. The portfolio must respect copyrights:
* Quote relevant sources.
* For business confidentiality, do not link a specific result
to the organization it was created for.
* Reproduce only part of the achievement
in order to prevent its misuse.
. The portfolio must follow the guidelines for design portfolios
that apply to simple engineering assignments:
* Simple.
* Interesting.
* Easy to read.
* Only your best results.

. The portfolio must be delivered in a slideshow format,
in high resolution (aspect ratio `16:9`).

[CAUTION]
Failure to submit a portfolio
or to follow these instructions in completing your portfolio
will result in the immediate termination of your participation
in the selection process.
