:slug: products/rules/list/149/
:category: cryptography
:description: This requirement establishes the importance of setting symmetric encryption of minimum size in the cryptographic functions of the system.
:keywords: Symmetric, Encryption, Cryptographic, Size, ASVS, CAPEC, HIPAA, Rules, Ethical Hacking, Pentesting
:rules: yes

= R149. Set minimum size of symmetric encryption

== Requirement

The symmetric encryption mechanism must use a minimum key size of **128 bits**.

== Findings

* [inner]#link:/products/rules/findings/052/[F052. Insecure encryption algorithm]#

== References

. [[r1]] link:http://capec.mitre.org/data/definitions/20.html[CAPEC-20: Encryption Brute Forcing].
An attacker, armed with the cipher text and the encryption algorithm used,
performs an exhaustive (brute force) search on the key space to determine the
key that decrypts the cipher text to obtain the plaintext.

. [[r2]] link:https://www.law.cornell.edu/cfr/text/45/164.312[HIPAA Security Rules 164.312(a)(2)(iv):]
Encryption and Decryption: Implement a mechanism to encrypt and decrypt
electronic protected health information.

. [[r3]] link:https://owasp.org/www-project-application-security-verification-standard/[OWASP-ASVS v4.0.1
V1.6 Cryptographic Architectural Requirements.(1.6.1)]
Verify that there is an explicit policy for management of cryptographic keys
and that a cryptographic key lifecycle follows a key management standard such
as **NIST SP 800-57**.
