:slug: rules/083/
:category: logs
:description: This document contains the details of the security requirements related to the definition and management of logs and events in the organization. This requirement establishes the importance of preventing logs from registering sensitive data in exceptional events.
:keywords: Logs, Data, Events, Information, CWE, ASVS
:rules: yes

= REQ.083 Avoid sensitive data logging

== Requirement

The system must not register sensitive information
when logging exceptional events.

== Description

While event logging is generally a good security practice,
the organization must consider that using high logging levels
is only appropriate for development environments,
since having too much log information in production stages
may hinder the performance of a system administrator
to detect abnormal conditions.
This may imply that both attacker and attack
can remain hidden while trying to penetrate the system,
reduce the audit trail in a forensic analysis,
or difficult the debugging of issues in production environments.
Furthermore, if sensitive information is recorded in the logs,
an attacker that gets access to these can also obtain the information.

== Implementation

. Delete big volumes of records in duplicated logs
and replace them with periodic summary messages.
For example, *syslog* may register a repetition event
saying "the last message was repeated *X* times",
to avoid multiple logging of the same event.

. Set a maximum size for log files.
If the maximum size is reached,
the system administrator must be notified.
You may also consider to reduce subsystem functionalities.
This may cause a denial of service for all users,
but prevent subsystems from negatively impact the overall system.

. Properly adjust system settings
when changing from debugging to production stage.

== Attacks

. The system may suffer in terms of performance when log files
become excessively large and consume excessive resources.

. By storing too much information in logs, they lose their value
in case of performing a troubleshoot diagnosis to recover from an attack,
or a forensic analysis.

. If administrators are not able to effectively process files in logs,
attack attempts may remain unnoticed,
which eventually will compromise the system security.

. If an attacker gets access to the logs,
he might be able to compromise other systems using the sensitive information.

== Attributes

* Layer: Application Layer
* Asset: Logs
* Scope: Confidentiality
* Phase: Operation
* Type of Control: Procedure

== References

. [[r1]] link:https://cwe.mitre.org/data/definitions/779.html[CWE-779: Logging of Excessive Data]
The software logs too much information,
making log files hard to process and possibly hindering recovery efforts or
orensic analysis after an attack.

. [[r2]] link:https://cwe.mitre.org/data/definitions/532.html[CWE-532: Logging of Excessive Data]
Information written to log files can be of a sensitive nature and give valuable
guidance to an attacker or expose sensitive user information.

. [[r3]] link:https://www.owasp.org/index.php/ASVS_V8_Error_Handling[OWASP-ASVS v3.1-8.7]
Verify that the application does not log sensitive data
as defined under local privacy laws or regulations,
organizational sensitive data as defined by a risk assessment,
or sensitive authentication data that could assist an attacker,
including user’s session identifiers, passwords, hashes, or *API* tokens.

. [[r4]] link:https://owasp.org/www-project-application-security-verification-standard/[OWASP-ASVS v4.0.1
V1.7 Errors, Logging and Auditing Architectural Requirements.(1.7.1)]
Verify that a common logging format and approach is used across the system.
