:slug: rules/072/
:category: architecture
:description: This document details the security guidelines and requirements related to logical architecture management within the organization. This requirement establishes the importance of defining an adequate maximum response time with the maximum expected concurrence.
:keywords: Time, Response, Concurrency, GDPR, Requirement, Security
:rules: yes

= REQ.072 Set maximum response time

== Requirement

The response time with the maximum expected concurrence
must be no more than 5 seconds.

== Description

Response time is a relevant measure of a system's availability and
adaptability to stress.
It is also important when it comes to usability and reliance.
For these reasons the response time must not surpass 5 seconds when the
number of concurrent users reaches its peak.

== Findings

* link:/web/findings/002/[F002. Asymmetric denial of service]

* link:/web/findings/003/[F003. Symmetric denial of service]

* link:/web/findings/092/[F092. Improper resource allocation]

* link:/web/findings/108/[F108. Improper control of interaction frequency]

== References

. [[r1]] link:https://gdpr-info.eu/art-32-gdpr/[GDPR. Art. 32: Security of processing.(1)(c).]
The controller and the processor shall implement appropriate technical and
organizational measures to ensure an appropriate level of security,
including the the ability to restore the availability and access to personal
data in a timely manner in the event of a physical or technical incident.
