:slug: defends/apache/restringir-metodo-http/
:category: apache
:description: Nuestros ethical hackers explican cómo evitar vulnerabilidades de seguridad mediante la configuración segura en Apache al restringir los métodos HTTP inseguros. Éstos métodos son potencialmente peligrosos, debido a que pueden ser utilizados de forma maliciosa como un medio de ataque.
:keywords: Apache, Seguridad, Métodos, HTTP, Configurar, Petición.
:defends: yes

= Restringir Métodos HTTP

== Necesidad

Se requiere restringir métodos inseguros
como +PUT+ o +DELETE+ en un servidor web.

== Contexto

A continuación se describen las circunstancias
bajo las cuales la siguiente solución tiene sentido:

. Se tiene un servidor +Apache 2.x+ en la máquina
. Se tienen permisos para modificar los archivos de configuración.

== Solución

El Protocolo de transferencia de hipertexto
(en inglés: +Hypertext Transfer Protocol+ o +HTTP+)
es el protocolo de comunicación que permite
las transferencias de información en la +World Wide Web+ (+WWW+).
+HTTP+ es un protocolo orientado a transacciones
y sigue el esquema petición-respuesta entre un cliente y un servidor.
El cliente realiza una petición enviando un mensaje,
con cierto formato al servidor.
El servidor le envía un mensaje de respuesta.^<<r1,[1]>>^

Para realizar estas peticiones +HTTP+
define un conjunto de métodos de petición
para indicar la acción que se desea realizar para un recurso determinado.

Algunos de los métodos más usados son:

* +GET+: El método +GET+  solicita
una representación de un recurso específico.
Las peticiones que usan el método +GET+ sólo deben recuperar datos.
* +HEAD+: El método +HEAD+ pide
una respuesta idéntica a la de una petición +GET+,
pero sin el cuerpo de la respuesta.
* +POST+: El método +POST+ se utiliza
para enviar una entidad a un recurso en específico,
causando a menudo un cambio en el estado
o efectos secundarios en el servidor.
* +PUT+: El método +PUT+ reemplaza todas las representaciones actuales
del recurso de destino con la carga útil de la petición.
* +DELETE+: El método +DELETE+ borra un recurso en específico.
* +CONNECT+: El método +CONNECT+ establece
un tunel hacia el servidor identificado por el recurso.
* +OPTIONS+: El método +OPTIONS+ es utilizado para describir
as opciones de comunicación para el recurso de destino.
* +TRACE+: El método +TRACE+  realiza una prueba de bucle
de retorno de mensaje a lo largo de la ruta al recurso de destino.^<<r2,[2]>>^

Para restringir los métodos considerados inseguros
en +HTTP+ se debe tener en cuenta:

. Los controles de acceso se aplican normalmente
a todos los métodos de acceso,
y este es el comportamiento que se busca casi siempre.

. En general, las directivas de control de acceso
no deben estar dentro de una sección +Limit+.

. El propósito de las secciones es restringir
el efecto de los controles de acceso
a los métodos +HTTP+ que se especifiquen.

. Para los demás métodos, las restricciones de acceso
que estén incluidas en la sección correspondiente no tendrán efecto.

. Los siguientes ejemplos aplican el control de acceso
solo a los métodos +POST+, +PUT+, y +DELETE+,
no afectando al resto de métodos:
+
.ejemplo.html
[source, html, linenums]
----
<Limit POST PUT DELETE>
 Require valid-user
</Limit>
----

. Los métodos incluidos en la lista pueden ser uno o más de los siguientes:
+GET+, +POST+, +PUT+, +DELETE+, +CONNECT+,
+OPTIONS+, +PATCH+, +PROPFIND+, +PROPPATCH+,
+MKCOL+, +COPY+, +MOVE+, +LOCK+, y +UNLOCK+.

. Los nombres de los métodos
diferencian mayúsculas de minúsculas (+case-sensitive+).

. Si se usa +GET+ también se restringirán las peticiones +HEAD+.

. El método +TRACE+ no puede limitarse,
para tal fin bastará con seguir la solución ^<<r4,[4]>>^

== Referencias

. [[r1]] link:https://es.wikipedia.org/wiki/Protocolo_de_transferencia_de_hipertexto[Protocolo de transferencia de hipertexto]
. [[r2]] link:https://developer.mozilla.org/es/docs/Web/HTTP/Methods[Métodos de petición HTTP]
. [[r3]] link:http://httpd.apache.org/docs/2.0/en/mod/core.html[AcceptPathInfo Directive]
. [[r4]] link:../desactivar-http-trace/[No TRACE Apache2]
