:slug: rules/345/
:category: source
:description: This requirement establishes the importance of establishing protection mechanisms against overflow attacks.
:keywords: Overflow, Buffer, Mechanism, Protection, ASVS, CWE
:rules: yes

= R345. Establish protections against overflows

== Requirement

The system must have protection mechanisms against the different types of
overflow (stack, buffer, heap, integer, etc.).

== Description

A overflow occurs when an application receives a value outside of the range
that it is prepared to handle.
It can happen when a program tries to process an excessively big number or if
it attempts to read a memory address outside of its assigned buffer.
An overflow can cause a program to stop working,
which can lead to a Denial of Service (*DoS*).
Therefore, systems should use data structures and mechanisms that help reduce
the chances that an overflow will arise,
such as memory-safe strings, and safe memory copy and pointer arithmetic.

== Rereferences

. [[r1]] link:https://cwe.mitre.org/data/definitions/120.html[CWE-120: Classic Buffer Overflow].
The program copies an input buffer to an output buffer without verifying that
the size of the input buffer is less than the size of the output buffer,
leading to a buffer overflow.

. [[r2]] link:https://cwe.mitre.org/data/definitions/134.html[CWE-134: Use of Externally-Controlled Format String].
The software uses a function that accepts a format string as an argument,
but the format string originates from an external source.

. [[r3]] link:https://cwe.mitre.org/data/definitions/190.html[CWE-190: Integer Overflow or Wraparound].
The software performs a calculation that can produce an integer overflow or
wraparound,
when the logic assumes that the resulting value will always be larger than the
original value.

. [[r4]] link:https://owasp.org/www-project-application-security-verification-standard/[OWASP-ASVS v4.0.1
V5.4 Memory, String, and Unmanaged Code Requirements.(5.4.1)]
Verify that the application uses memory-safe string, safer memory copy and
pointer arithmetic to detect or prevent *stack*, *buffer*, or *heap* overflows.

. [[r5]] link:https://owasp.org/www-project-application-security-verification-standard/[OWASP-ASVS v4.0.1
V5.4 Memory, String, and Unmanaged Code Requirements.(5.4.2)]
Verify that format strings do not take potentially hostile input,
and are constant.

. [[r6]] link:https://owasp.org/www-project-application-security-verification-standard/[OWASP-ASVS v4.0.1
V5.4 Memory, String, and Unmanaged Code Requirements.(5.4.3)]
Verify that sign, range, and input validation techniques are used to prevent
integer overflows.
