:slug: compliance/nist/
:category: compliance
:description: At Fluid Attacks, through comprehensive analysis, we can help you comply with a variety of security standards for information technology, including NIST.
:keywords: Fluid Attacks, NIST, 800-53, Continuous Hacking, Security, Standards, Ethical Hacking, Pentesting
:banner: bg-compliance-internal
:template: compliance

= NIST

=== How can Fluid Attacks help with the NIST 800-53 compliance?

[role="fw3 f3 lh-2"]
Ensuring compliance with up-to-date security standards may become a complicated
issue for diverse organizations that use continually evolving information
technology for their businesses. Fluid Attacks recognizes this and offers you
comprehensive testing and analysis to determine whether your company is
effectively complying with all corresponding security requirements.

[role="fw3 f3 lh-2"]
Although Fluid Attacks’ link:../../services/continuous-hacking/[Continuous Hacking, role=basic-link] service goes beyond the NIST 800-53,
testing around 200 technical security requirements in each of your projects,
we can guarantee the detection of all vulnerabilities in your software
associated with this standard. In addition, we provide you with reliable
reports so that your team can take the necessary steps to adjust and maintain
your information systems in line with such requirements.

[role="fw3 f3 lh-2"]
All our security testing is based on link:../../products/rules/[​Rules, role=basic-link], which is a set of security
requirements written by us in a comprehensible manner, using several
international standards as a reference. It allows you to parameterize the
assessments we make to your systems and determine what your company agrees to
comply with and what would be considered a vulnerability.

=== What is the NIST?

[role="fw3 f3 lh-2"]
NIST is the National Institute of Standards and Technology from the U.S. that
has been in operation for more than a century, supporting a multiplicity of
science-based products and services. Within NIST is the Information Technology
Laboratory (link:https://www.nist.gov/itl/about-itl[ITL, role=basic-link]), and linked to it is the National Vulnerability Database (link:https://nvd.nist.gov/general[NVD, role=basic-link]),
where the link:https://nvd.nist.gov/800-53/Rev4[NIST Special Publication 800-53 (Rev. 4), role=basic-link] appears.

=== What is the NIST SP 800-53?

[role="fw3 f3 lh-2"]
The NIST SP 800-53, a database related to security and privacy controls for
federal information systems and organizations, serves as a guide for security
policies and the protection of private information
of both agencies and citizens against cyberattacks, errors and disasters.
It provides administrative, operational and technical controls
for developing secure IT systems and maintaining the availability,
integrity and confidentiality of information assets.
The NIST SP 800-53, which applies to any system storing, processing or
transmitting federal data, is divided into three Minimum Security Controls
(High, Moderate and Low-Impact Baseline) that apply to the following 18 Control
Families, each one with the corresponding and variable security controls
(follow the links below):

[role="fw3 f3 lh-2"]
1. AC - link:https://nvd.nist.gov/800-53/Rev4/family/Access%20Control[Access Control, role=basic-link]
2. AT - link:https://nvd.nist.gov/800-53/Rev4/family/Awareness%20and%20Training[Awareness and Training, role=basic-link]
3. AU - link:https://nvd.nist.gov/800-53/Rev4/family/Audit%20and%20Accountability[Audit and Accountability, role=basic-link]
4. CA - link:https://nvd.nist.gov/800-53/Rev4/family/Security%20Assessment%20and%20Authorization[Security Assessment and Authorization, role=basic-link]
5. CM - link:https://nvd.nist.gov/800-53/Rev4/family/Configuration%20Management[Configuration Management, role=basic-link]
6. CP - link:https://nvd.nist.gov/800-53/Rev4/family/Contingency%20Planning[Contingency Planning, role=basic-link]
7. IA - link:https://nvd.nist.gov/800-53/Rev4/family/Identification%20and%20Authentication[Identification and Authentication, role=basic-link]
8. IR - link:https://nvd.nist.gov/800-53/Rev4/family/Incident%20Response[Incident Response, role=basic-link]
9. MA - link:https://nvd.nist.gov/800-53/Rev4/family/Maintenance[Maintenance, role=basic-link]
10. MP - link:https://nvd.nist.gov/800-53/Rev4/family/Media%20Protection[Media Protection, role=basic-link]
11. PE - link:https://nvd.nist.gov/800-53/Rev4/family/Physical%20and%20Environmental%20Protection[Physical and Environmental Protection, role=basic-link]
12. PL - link:https://nvd.nist.gov/800-53/Rev4/family/Planning[Planning, role=basic-link]
13. PM - link:https://nvd.nist.gov/800-53/Rev4/family/Program%20Management[Program Management, role=basic-link]
14. PS - link:https://nvd.nist.gov/800-53/Rev4/family/Personnel%20Security[Personnel Security, role=basic-link]
15. RA - link:https://nvd.nist.gov/800-53/Rev4/family/Risk%20Assessment[Risk Assessment, role=basic-link]
16. SA - link:https://nvd.nist.gov/800-53/Rev4/family/System%20and%20Services%20Acquisition[System and Services Acquisition, role=basic-link]
17. SC - link:https://nvd.nist.gov/800-53/Rev4/family/System%20and%20Communications%20Protection[System and Communications Protection, role=basic-link]
18. SI - link:https://nvd.nist.gov/800-53/Rev4/family/System%20and%20Information%20Integrity[System and Information Integrity, role=basic-link]

[role="fw3 f3 lh-2"]
It is relevant to mention that in September 2020
a final version of the link:https://csrc.nist.gov/publications/detail/sp/800-53/rev-5/final[NIST SP 800-53 (Rev. 5), role=basic-link] was completed,
which eliminated the word ‘federal’ from the title,
changing it to ‘Security and Privacy Controls for Information Systems and
Organizations’, thus indicating that it is not limited to federal agencies and
can serve as a guide for any organization for the compliance of multiple
security standards. In this revision there are now 20 Control Families, with
the CA now called ‘Assessment, Authorization and Monitoring’, and the new ones
‘PT - PII Processing and Transparency’ and ‘SR - Supply Chain Risk Management’.

[role="fw3 f3 lh-2"]
The NIST 800-53 is not a regulation but a standard
of best practices in security and privacy,
so there are no penalties or fines for non-compliance. The official
documents by NIST can be quite useful for organizations, providing them with
guidance according to their security objectives and including suggested
practices for data protection and breach avoidance, such as:

[role="fw3 f3 lh-2"]
* Identification of all sensitive information used,
users and access permissions.
* Removal of inactive users.
* Privilege management.
* Monitoring of suspicious activity and potential threats.
* Detection and remediation of security vulnerabilities in the systems.
