:slug: rules/353/
:category: devices
:description: This requirement establishes the importance of scheduling automatic firmware updates.
:keywords: Schedule, Firmware, Update, Automatic, IoT, ASVS, CWE, Rules, Ethical Hacking, Pentesting
:rules: yes

= R353. Schedule firmware updates

== Requirement

Devices should update their own firmware upon a predefined schedule.

== References

. [[r1]] link:https://cwe.mitre.org/data/definitions/362.html[CWE-367: Time-of-check Time-of-use (TOCTOU) Race Condition.]
The software checks the state of a resource before using that resource,
but the resource's state can change between the check and the use in a way that
invalidates the results of the check.
This can cause the software to perform invalid actions when the resource is in
an unexpected state.

. [[r2]] link:https://owasp.org/www-project-application-security-verification-standard/[OWASP-ASVS v4.0.1
Appendix C: Internet of Things Verification Requirements.(C.20)]
Verify that the firmware update process is not vulnerable to time-of-check vs
time-of-use attacks.

. [[r3]] link:https://owasp.org/www-project-application-security-verification-standard/[OWASP-ASVS v4.0.1
Appendix C: Internet of Things Verification Requirements.(C.24)]
Verify that firmware can perform automatic firmware updates upon a predefined
schedule.

. [[r4]] link:https://owasp.org/www-project-application-security-verification-standard/[OWASP-ASVS v4.0.1
V1.11 Business Logic Architectural Requirements.(1.11.3)]
Verify that all high-value business logic flows,
including authentication, session management and access control,
are thread safe and resistant to time-of-check and time-of-use race conditions.

. [[r5]] link:https://owasp.org/www-project-application-security-verification-standard/[OWASP-ASVS v4.0.1
V11.1 Business Logic Security Requirements.(11.1.6)]
Verify the application does not suffer from "time of check to time of use"
(*TOCTOU*) issues or other race conditions for sensitive operations.
