:slug: products/rules/list/041/
:category: files
:description: This requirement establishes that the files transferred or uploaded to the system must be scanned for possible malicious code.
:keywords: Validate, File, Code, ASVS, CAPEC, CWE, Malicious, NERC, PCI DSS, Rules, Ethical Hacking, Pentesting
:rules: yes

= R041. Scan files for malicious code

== Requirement

The system must validate that
the content of the files transferred to it is free of malicious code.

== Findings

* [inner]#link:/products/rules/findings/027/[F027. Insecure file upload]#

== References

. [[r1]] link:http://capec.mitre.org/data/definitions/17.html[CAPEC-17: Using Malicious Files].
An attack of this type exploits a system's configuration that allows an
attacker to either directly access an executable file,
for example through shell access;
or in a possible worst case allows an attacker to upload a file and then
execute it.

. [[r2]] link:http://capec.mitre.org/data/definitions/23.html[CAPEC-23: File Content Injection].
An attack of this type exploits the host's trust in executing remote content,
including binary files.
The files are poisoned with a malicious payload
(targeting the file systems accessible by the target software)
by the adversary and may be passed through standard channels such as via email,
and standard web content like PDF and multimedia files.

. [[r3]] link:http://capec.mitre.org/data/definitions/165.html[CAPEC-165: File Manipulation].
An attacker modifies file contents or attributes (such as extensions or names)
of files in a manner to cause incorrect processing by an application.

. [[r4]] link:http://capec.mitre.org/data/definitions/549.html[CAPEC-549: Local Execution of Code].
An adversary installs and executes malicious code on the target system in an
effort to achieve a negative technical impact.

. [[r4]] link:https://cwe.mitre.org/data/definitions/509.html[CWE-509: Replicating Malicious Code (Virus or Worm)].
Replicating malicious code, including viruses and worms, will attempt to attack
other systems once it has successfully compromised the target system or
software.

. [[r5]] link:https://cwe.mitre.org/data/definitions/749.html[CWE-749: Exposed Dangerous Method or Function].
The software provides an Applications Programming Interface (*API*) or similar
interface for interaction with external actors,
but the interface includes a dangerous method or function that is not properly
restricted.

. [[r6]] link:https://www.nerc.com/pa/Stand/Reliability%20Standards/CIP-003-8.pdf[NERC CIP-003-8. Attachment 1. Section 5 - 5.1]
Each Responsible Entity shall implement,
except under CIP Exceptional Circumstances,
one or more plan(s) to achieve the objective of mitigating the risk of the
introduction of malicious code to low impact BES Cyber Systems.
The plan(s) shall include antivirus software,
or other method(s) to mitigate the introduction of malicious code.

. [[r7]] link:https://owasp.org/www-project-application-security-verification-standard/[OWASP-ASVS v4.0.1
V10.1 Code Integrity Controls.(10.1.1)]
Verify that a code analysis tool is in use that can detect potentially
malicious code, such as time functions, unsafe file operations and network
connections.

. [[r8]] link:https://owasp.org/www-project-application-security-verification-standard/[OWASP-ASVS v4.0.1
V12.4 File Storage Requirements.(12.4.2)]
Verify that files obtained from untrusted sources are scanned by antivirus
scanners to prevent upload of known malicious content.

. [[r9]] link:https://www.pcisecuritystandards.org/documents/PCI_DSS_v3-2-1.pdf[PCI DSS v3.2.1 - Requirement 5.1.1]
Ensure that anti-virus programs are capable of detecting, removing, and
protecting against all known types of malicious software.
