:slug: products/rules/list/042/
:category: files
:description: This requirement establishes that every system validates the format of the files defined for the business operation.
:keywords: System, Validate, File, Format, ASVS, CAPEC, CWE, Business, Rules, Ethical Hacking, Pentesting
:rules: yes

= R042. Validate file format

== Requirement

The system must only accept files
whose format (structure) is required by the business operation.

== References

. [[r1]] link:http://capec.mitre.org/data/definitions/165.html[CAPEC-165: File Manipulation].
An attacker modifies file contents or attributes (such as extensions or names)
of files in a manner to cause incorrect processing by an application.

. [[r2]] link:https://cwe.mitre.org/data/definitions/646.html[CWE-646: Reliance on File Name or Extension of Externally-Supplied File].
The software allows a file to be uploaded,
but it relies on the file name or extension of the file to determine the
appropriate behaviors.
This could be used by attackers to cause the file to be misclassified and
processed in a dangerous fashion.

. [[r3]] link:https://owasp.org/www-project-application-security-verification-standard/[OWASP-ASVS v4.0.1
V12.2 File Integrity Requirements.(12.2.1)]
Verify that files obtained from untrusted sources are validated to be of
expected type based on the file's content.
