:slug: rules/032/
:category: session
:description: This requirement establishes the importance of managing session IDs securely to avoid session hijacking attacks.
:keywords: Session ID, Leakage, URL, Messages, ASVS, CWE, OWASP, PCI DSS, Rules, Ethical Hacking, Pentesting
:rules: yes

= R032. Avoid session ID leakages

== Requirement

The system must not expose session **ID**s in **URL**s
and messages presented to the user.

== Description

Session **ID**s are sensitive information that may allow an attacker to steal,
modify and/or destroy information once they get one.
Information sent via URL parameters is:

* stored in clear text in the browser history.
* sent to external sites via the referrer *HTTP* header.
* sent to external sites via the search bar if the browser interprets the
*URL* as query.
* visible to scripts running on the browser that may belong to
third-parties.

Therefore, session **ID**s should neither be sent via *URL* parameters,
nor be displayed as messages presented to the user nor stored in logs.

== Findings

* [inner]#link:/web/findings/017/[F017. Sensitive information sent insecurely]#

* [inner]#link:/web/findings/030/[F030. Sensitive information sent via URL parameters]#

== Reference

. [[r1]] link:https://cwe.mitre.org/data/definitions/200.html[CWE-200: Exposure of Sensitive Information to an Unauthorized Actor].
The product exposes sensitive information to an actor that is not explicitly
authorized to have access to that information.

. [[r2]] link:https://cwe.mitre.org/data/definitions/319.html[CWE-319: Cleartext Transmission of Sensitive Information].
The software transmits sensitive or security-critical data in cleartext in a
communication channel that can be sniffed by unauthorized actors.

. [[r3]] link:https://cwe.mitre.org/data/definitions/598.html[CWE-598: Use of GET Request Method With Sensitive Query Strings]
The web application uses the *HTTP* *GET* method to process a request and
includes sensitive information in the query string of that request.

. [[r4]] link:https://owasp.org/www-project-top-ten/OWASP_Top_Ten_2017/Top_10-2017_A2-Broken_Authentication[OWASP Top 10 A2:2017-Broken Authentication].
Application functions related to authentication and session management are
often implemented incorrectly,
allowing attackers to compromise passwords, keys, or session tokens,
or to exploit other implementation flaws to assume other users’ identities
temporarily or permanently.

. [[r5]] link:https://owasp.org/www-project-top-ten/OWASP_Top_Ten_2017/Top_10-2017_A3-Sensitive_Data_Exposure[OWASP Top 10 A3:2017-Sensitive Data Exposure].
Many web applications and **API**s do not properly protect sensitive data,
such as financial, healthcare, and *PII*.
Attackers may steal or modify such weakly protected data to conduct credit card
fraud, identity theft, or other crimes.
Sensitive data may be compromised without extra protection,
such as encryption at rest or in transit, and requires special precautions when
exchanged with the browser.

. [[r6]] link:https://owasp.org/www-project-application-security-verification-standard/[OWASP-ASVS v4.0.1
V3.1 Client-side Data Protection.(3.1.1)]
Verify the application never reveals session tokens in *URL* parameters or error
messages.

. [[r7]] link:https://owasp.org/www-project-application-security-verification-standard/[OWASP-ASVS v4.0.1
V8.3 Sensitive Private Data.(8.3.1)]
Verify that sensitive data is sent to the server in the *HTTP* message body or
headers,
and that query string parameters from any *HTTP* verb do not contain sensitive
data.

. [[r8]] link:https://owasp.org/www-project-application-security-verification-standard/[OWASP-ASVS v4.0.1
V13.1 Generic Web Service Security Verification Requirements.(13.1.3)]
Verify *API* **URL**s do not expose sensitive information,
such as the *API* key, session tokens etc.

. [[r9]] link:https://www.pcisecuritystandards.org/documents/PCI_DSS_v3-2-1.pdf[PCI DSS v3.2.1 - Requirement 6.5.10]
Address common coding vulnerabilities in software-development processes such as
broken authentication and session management.
