:slug: kb/java/firmar-archivo-jar/
:category: java
:description: TODO
:keywords: TODO
:kb: yes

= Firmar Archivos JAR

== Necesidad

Firmar archivos JAR (firmar código móvil)

== Contexto

A continuación se describen las circunstancias 
bajo las cuales la siguiente solución tiene sentido:

. Se tiene código Java empaquetado en archivos JAR.

== Solución

. Un archivo JAR (por sus siglas en inglés, Java ARchive) 
es un tipo de archivo que permite ejecutar aplicaciones escritas 
en el lenguaje de programación Java. 

. La firma de un archivo JAR tiene como objetivo 
permitir a la persona que lo ejecuta 
la verificación de la identidad de su creador 
con el fin de que ella pueda discernir si la aplicación es confiable o no, 
y por tanto hacer uso de la misma. 
En pocas palabras, El firmado digital de un JAR 
permite garantizar la integridad y el no repudio del software 
por parte de la persona que lo utilizará.

. La firma del archivo JAR se hace a través de un certificado digital, 
este se define como un fichero informático 
generado por una entidad de servicios de certificación 
que asocia unos datos de identidad a una persona física, organismo o empresa, 
confirmando de esta manera su identidad digital. 

. Además, los certificados se deben almacenar en keystores 
y para un mejor uso, cada certificado puede ser referenciado mediante un alias, 
que, por lo general, suele ser el nombre de la persona que firma la clave.    

. Para cuestiones de ejemplo, 
se utilizará la siguiente clase que será empaquetada en un JAR 
y que además contiene un método sensible:
+
.test.py
[source, java, linenums]
----
package com.FLUID;

class CLI
{
  public static void main(String[] argumentos)
  {
    System.out.println("public static void main");
  }
  protected static void metodoProtegido()
  {
    System.out.println("protected static void metodoProtegido");
  }
}
----

. Lo primero que se debe hacer 
es generar un par de certificados (llave pública y privada) 
y almacenarlos en un keystore:
+
[source, shell, linenums]
----
keytool -keystore keystore -alias FLUID -genkey \  -dname "cn=Technology, ou=Engineering, 
  o=FLUIDsignal Group, c=CO" \ -keypass keypass -storepass storepass
----

. Luego, se procede a compilar la clase:
+
[source, shell, linenums]
----
export CLASSPATH=src
javac src/com/FLUID/CLI.java
----

. Se crea el archivo MANIFEST.MF requerido al momento de crear el .jar:
+
[source, shell, linenums]
----
$ cat META-INF/MANIFEST.MF

Main-Class: com.FLUID.CLI
Name: com/FLUID/
Sealed: true
----

. Se empaqueta entonces el programa compilado en un archivo JAR, 
paquete-1.0.jar el cual usaremos para firmar:
+
[source, shell, linenums]
----
$ jar -cvfm paquete-1.0.jar META-INF/MANIFEST.MF -C src .added manifest

adding: com/(in = 0) (out= 0)(stored 0%)
adding: com/FLUID/(in = 0) (out= 0)(stored 0%)
adding: com/FLUID/CLI.java(in = 262) (out= 144)(deflated 45%)
adding: com/FLUID/CLI.class(in = 551) (out= 348)(deflated 36%)
----

. Finalmente, procedemos a firmar el paquete generado 
paquete-1.0.jar con el alias FLUID alojado en el keystore previamente creado:
+
[source, shell, linenums]
----
jarsigner -keystore keystore -storepass storepass -keypass keypass \ 
   -signedjar paquete-firmado-1.0.jar paquete-1.0.jar FLUID
----

. Se procede a ejecutar el programa para verificar su funcionamiento:
+
[source, shell, linenums]
----
$ java -jar paquete-1.0.jar
public static void main
----

. Adicionalmente, es posible utilizar la herramienta jarsigner 
para verificar la firma de un paquete. 
Para el ejemplo, se verificará la firma de paquete paquete-1.0.jar:
+
[source, shell, linenums]
----
$ jarsigner -keystore keystore -certs -verbose -verify paquete-firmado-1.0.jar

 297 Thu Nov 24 10:45:14 COT 2011 META-INF/MANIFEST.MF
 347 Thu Nov 24 10:45:14 COT 2011 META-INF/FLUIDSIG.SF
 978 Thu Nov 24 10:45:14 COT 2011 META-INF/FLUIDSIG.DSA
 0 Thu Nov 24 10:45:12 COT 2011 META-INF/
 0 Fri Sep 17 11:18:22 COT 2010 com/
 0 Fri Sep 17 11:18:22 COT 2010 com/FLUID/
 smk 262 Tue Nov 11 11:31:06 COT 2008 com/FLUID/CLI.java
 X.509, CN=Technology, OU=Engineering, O=FLUIDsignal Group, C=CO (FLUID)
 [certificate will expire on 2/22/12 10:45 AM]
 smk 551 Thu Nov 24 10:45:10 COT 2011 com/FLUID/CLI.class
 X.509, CN=Technology, OU=Engineering, O=FLUID Group, C=CO (FLUID)
 [certificate will expire on 2/22/12 10:45 AM]
 s = signature was verified
 m = entry is listed in manifest
 k = at least one certificate was found in keystore
 i = at least one certificate was found in identity scope
 jar verified.
----

== Referencias

. https://docs.oracle.com/javase/tutorial/security/toolsign/signer.html[Steps for the Code Signer]
. https://docs.oracle.com/javase/tutorial/deployment/jar/signing.html[Signing JAR Files]
. https://es.wikipedia.org/wiki/Java_Archive[Java Archive]
. https://es.wikipedia.org/wiki/Certificado_digital[Certificado digital]
. REQ.0173: Debe utilizarse firmas digitales para garantizar la autenticidad de 
información sensible.