:slug: eventos/hacking-en-vivo/
:description: Observa de primera mano los pasos que sigue un hacker a la hora de buscar y explotar las vulnerabilidades que se encuentran presentes en una aplicación o en la infraestructura subyacente. Uno de nuestros hackers te guiará en las diferentes etapas, utilizando una aplicación vulnerable, bWAPP.
:keywords: Fluid Attacks, Conferencia, Seguridad, Experiencia, Información, Hacking

= Hacking en Vivo

== 1. Objetivo

¿Alguna vez te has preguntado qué tan seguras
son las aplicaciones que usas a diario?
¿Aquellas que tienen acceso a tu información personal y, en algunos casos,
a tu información financiera?
¿Será que son tan seguras que los únicos que pueden tener una oportunidad
de comprometerlas son esos +hackers+ que vemos en televisión y en cine,
que se sientan en frente de una pantalla negra con letras verdes,
utilizan el teclado a una velocidad descomunal,
y probablemente hablan binario como segunda lengua?

Lamento decírtelo, pero probablemente la realidad no sea así,
y tal vez no se necesita de un personaje tan extraordinario
como el que describimos anteriormente para vulnerar tu información.
Esto debido a que el mayor porcentaje de las vulnerabilidades
que se encuentra en una aplicación son del tipo
+_XSS (Cross-Site Scripting)_+, +_SQLi (SQL Injection)_+,
+_CSRF (Cross-Site Request Forgery)_+, _Manejo de sesión_,
_Configuraciones inseguras_, entre otras;
las cuales se encuentran extensivamente documentadas
y su explotación en algunos casos puede llegar a ser extremadamente simple,
e incluso puedes ni necesitar conocimientos profundos
de computación o de programación para lograrlo.

Acompáñanos para ver cómo uno de nuestros +ethical hackers+
se aprovecha de estas vulnerabilidades para obtener información sensible,
robar una sesión o hasta adueñarse de la máquina
donde se encuentra ejecutando la aplicación.

== 2. Contenido

Esta conferencia utiliza una aplicación llamada
link:http://www.itsecgames.com/[bWAPP], la cual tiene la particularidad
de que fue diseñada con vulnerabilidades a propósito,
con el fin de que aquellos que tienen conocimientos de seguridad,
puedan ponerlos en práctica y mejorarlos,
y aquellos que apenas se encuentran empezando,
tengan un lugar donde puedan aprender a encontrar y explotar vulnerabilidades.

Se atacará la aplicación desde dos frentes, la interfaz Web
y los diferentes servicios que se ejecutan dentro del servidor que la soporta,
empezando por una etapa de reconocimiento, y siguiendo con la explotación
y el escalamiento de privilegios.

Se visualizarán también los errores de programación
que ocasionan estas vulnerabilidades,
todo manteniéndolo en términos simples
para que todos los asistentes, sin importar su ocupación,
puedan apreciar y tener en cuenta la seguridad informática
en un mundo donde el número de aplicaciones y dispositivos
está incrementando exponencialmente.

== 3. Experiecia

Esta conferencia se presentó en el Workshop de seguridad informática
llevado a cabo por link:https://www.tigo.com.co/[+TigoUne+].

== 4. ¿Dónde?

La conferencia se puede dictar a domicilio en las instalaciones del cliente.

Las charlas pueden ser en Medellín con un público de mínimo 10 personas.
Para otras ciudades en Colombia, Centroamérica, Ecuador y Perú
se debe contar con 20 asistentes

== 5. Duración

La duración de este evento es de 1 hora.

== 8. Público

La conferencia es apta para personas con básico o poco conocimiento técnico.
El límite de asistentes es 30 personas.

== 9. Requisitos

[button]#link:../#requisitos[Requisitos]#

== 10. Expositores

* [button]#link:../../personas/acuberos[Andrés Cuberos]#

* [button]#link:../../personas/jarmas[Jonathan Armas]#
