:slug: defends/java/crear-contenedores-no-sync/
:category: java
:description: Nuestros ethical hackers explican que son las clases contenedoras y en que circunstancias es recomendable usarlas dentro del código. Por último, muestran un ejemplo de su implementación en el lenguaje de programación Java usando las clases StringBuilder y ArrayList...
:keywords: Java, Hilos, Contenedor, Sincronizadas, StringBuilder, ArrayList.
:defends: yes

= Crear Contenedores No Sincronizados

== Necesidad

Crear contenedores de objetos optimizados
cuando no se requieren hilos en +Java+.

== Contexto

A continuación se describen las circunstancias
bajo las cuales la siguiente solución tiene sentido:

.  No es una variable compartida que pueda ser accedida
por diferentes hilos (no se requiere sincronización).

== Solución

Los contenedores son clases o estructuras de datos
cuyas instancias son colecciones de otros objetos.
Es decir, almacenan objetos de manera ordenada
siguiendo determinadas reglas de acceso y control.
El tamaño de dichos contenedores es determinado
por la cantidad de elementos que contiene, además,
proporcionan flexibilidad para elegir
la implementación correcta para cualquier escenario dado.

+Java+ ofrece dos tipos de implementaciones para clases contenedoras:

* *Sincronizada:* Varios hilos pueden modificar el contenedor
y esta quedará en estado consistente.
* *No sincronizada:* Varios hilos, al modificar el contenedor,
pueden afectar la consistencia del mismo.

Normalmente siempre debería utilizarse la implementación sincronizada,
pero esta siempre implica un rendimiento menor
dado que internamente implementa mecanismos de control y concurrencia
como son los semáforos y/o monitores ^<<r1,[1]>>^.

Por lo tanto, se puede determinar que la decisión óptima de rendimiento,
cuando un contenedor puede no ser modificado por varios hilos,
es utilizar implementaciones no sincronizadas.

Una implementación de clase contenedora sincronizada
es la clase +Vector+ ^<<r2,[2]>>^
y de clase no sincronizada es +ArrayList+ ^<<r3,[3]>>^.
De igual modo ocurre con +StringBuffer+ ^<<r4,[4]>>^
y +StringBuilder+ ^<<r5,[5]>>^ respectivamente.

. En esta solución se mostrará la creación de un contenedor
usando las clases no sincronizadas +StringBuilder+ y +ArrayList+.

. Se importan las clases del paquete java.util.
La clases +StringBuilder+ no requiere ser importada
porque pertenece al paquete +java.lang+.
+
.Main.java
[source, java, linenums]
----
import java.util.List;
import java.util.ArrayList;
----

. Definimos una clase que simplemente creará los contenedores
y les asignará los String +fluidattacks+ y después +Group+.
+
[source, java, linenums]
----
public class Main {
  public static void main(String[] args) {
    StringBuilder sb = new StringBuilder();
    sb.append("fluidattacks");
    sb.append("Group");
    System.out.println(sb);
    List<String> lista = new ArrayList<String>();
    lista.add("fluidattacks");
    lista.add("Group");
    System.out.println(lista);
  }
}
----

. Debido a que la aplicación anterior no hace uso de hilos,
se usaron las versiones no sincronizadas de los contenedores.

. Siempre que se pueda usar una Interfaz para definir una variable,
es preferible definirla usando el nombre de la clase,
lo cual permitirá cambiar a la versión sincronizada más fácilmente
si en algún momento llegase a ser necesario.
En el código anterior esto se puede observar
durante la creación de la lista.

. Por último, se compila y se ejecuta la aplicación.
+
[source, shell, linenums]
----
% javac Main.java
% java Main
fluidattacksGroup
[fluidattacks, Group]
----

== Descargas

Puedes descargar el código fuente
pulsando en el siguiente enlace:

[button]#link:src/main.java[Main.java]#
Uso de clases no sincronizadas.

== Referencias

. [[r1]] link:https://www.javaworld.com/article/2077425/java-se/vector-or-arraylist-which-is-better.html[Vector or ArrayList]
. [[r2]] link:https://docs.oracle.com/javase/6/docs/api/java/util/Vector.html[Class Vector]
. [[r3]] link:https://docs.oracle.com/javase/6/docs/api/java/util/ArrayList.html[Class ArrayList]
. [[r4]] link:https://docs.oracle.com/javase/6/docs/api/java/lang/StringBuffer.html[Class StringBuffer]
. [[r5]] link:https://docs.oracle.com/javase/6/docs/api/java/lang/StringBuilder.html[Class StringBuilder]
. [[r6]] link:../../../rules/164/[REQ.164 Utilizar estructuras optimizadas]
