:slug: conferencias/quemar-el-datacenter/
:category: conferencias
:description: Ésta página tiene como objetivo informar a los clientes sobre el servicio de conferencias ofrecido por FLUID. La presente conferencia tiene por objetivo socializar el futuro de la tecnología y el desarrollo de software en los próximos 10 años según la opinión de nuestros expertos.
:keywords: FLUID, Conferencia, Datacenter, Seguridad, Software, Tecnología.

= Quemar el datacenter - De mascotas a ganado

== 1. Objetivo

En este espacio queremos socializar nuestras convicciones sobre lo que creemos será el futuro de la tecnología, el desarrollo de software y la gestión de su ciclo de vida en los próximos 10 años y por ende como se tendrá que adaptar todo el ecosistema de gestión, incluido el que nos compete a nosotros: Pruebas de Seguridad.

== 2. Contenido

El mundo del desarrollo de aplicaciones y la administración de infraestructura han sido típicamente dos mundos separados y antagonistas.  Existe una dicotomía entre la apertura al cambio que se pide en el desarrollo y la estabilidad que se les pide a las áreas de infraestructura.  Recientemente vemos como emergen frases extrañas (tecnorrea) como DevOps, perfiles DevOps, como las empresas crean áreas de transformación DevOps pero más allá del ámbito de gobierno (roles, responsabilidades y procesos), ¿cómo esto se traduce en conceptos técnicos simples en espacios adicionales a las aplicaciones?.

En este universo metodológico estamos perdiendo de vista que existe desde hace más de 20 años, y con más criticidad hace 10, una emergencia en lenguajes de programación específicos para infraestructura y redes, que si los dominamos desde el principio, hacen que las prácticas de programación desarrolladas durante medio siglo comiencen a aplicar a la infraestructura:

* ¿Podemos compilar un servidor?
* ¿Hacer linting de infraestructura?
* ¿Hacer análisis estático de redes?
* ¿Podemos integrar continuamente la infraestructura?
* ¿Podemos hacer despliegue continuo de infraestructura?
* ¿La infraestructura puede ser inmutable y por ende desechable?.

En esta conferencia veremos como el mundo le pertenece a los programadores y como los ambientes son infinitos.


== 3. Experiencia

Esta conferencia académica gratuita la hemos estado dando ya hace 9 meses en:

* *Grandes empresas de la región:* link:https://www.segurossura.com.co/Paginas/default.aspx[Sura], 
link:https://www.grupobancolombia.com/wps/portal/personas[Bancolombia], 
link:https://www.grupoexito.com.co/es/[Grupo Éxito], 
link:https://www.tigoune.com.co/[Tigo Une], 
link:http://www.celsia.com/[Celsia-EPSA], 
link:https://www.comfama.com/webinicio/default.asp[Comfama], 
link:https://www.banistmo.com/[Banistmo], 
link:https://www.stgeorgesbank.com/[St. Georges Bank], 
link:https://www.bcp.com.bo/[Banco de Credito del Peru], 
link:https://www.gnbsudameris.com.co/[GNB Sudameris], 
link:https://www.velez.com.co/[Cueros Velez]

* *Universidades:* link:http://www.eafit.edu.co/[EAFIT], 
link:https://www.udem.edu.co/[UdeM], 
link:https://www.udea.edu.co/[UdeA], 
link:https://medellin.unal.edu.co/[UNALMed], 
link:http://www.politecnicojic.edu.co/[Politécnico Jaime Isaza Cadavid], 
link:https://www.upb.edu.co/es/home[UPB], 
link:http://www.uniminuto.edu/[Uniminuto Bogotá]

* *Empresas proveedoras de TI:* link:https://www.kometsales.com/[Komet Sales], 
link:http://perceptio.co/[Perceptio], 
link:http://www.internexa.com/Paginas/Home.aspx[Internexa], 
link:http://gluky.co/[Gluky], 
link:https://outsourcing.cidenet.com.co/home/[Cidenet], 
link:https://www.choucairtesting.com/[Choucair Testing], 
link:http://www.cadena.com.co/es/home.aspx[Cadena], 
link:http://www.seti.com.co/sitios/seti/Paginas/HomePageSeti.aspx[SETI], 
link:http://novit.pe/[NovitIT Peru], 
link:http://flypass.com.co/[Flypass], 
link:http://www.cognox.co/sitios/Cognox/default.aspx[Cognox], 
link:https://www.todo1services.com/[Todo1], 
link:http://www.mareigua.com/[Mareigua]

* *Otros espacios abiertos:* link:https://www.rutanmedellin.org/es/[RutaN], 
link:https://www.meetup.com/es/mde-devops[MeetUp-Medellin-DevOps].

En total se han dictado más de *35 charlas* con un total de *878 asistentes* y una *satisfacción global de 165%.*

== 4. ¿Dónde?

Podemos dictar la conferencia a domicilio en sus instalaciones.

Las charlas pueden ser en Medellín con un público de mínimo 20 personas y uno de ellos con más de 10 personas a cargo. Para otras ciudades en Colombia, Centro América, Ecuador y Perú se debe contar entre los asistentes 1 persona con más de 20 personas a cargo.

== 5. Duración

La conferencia tiene una duración de 2 horas (no es posible reducir su duración).

== 6. Público

La conferencia es apta para personal técnico y personal gerencial de tecnología.  Ambos perfiles son bienvenidos y su satisfacción es alta indistintamente.  Sin embargo si desea disparar cambios y experimentos dentro de su organización es importante considerar la presencia de personas con poder de decisión.

El límite de asistentes está determinado según el espacio del que se disponga.  Se ha realizado en grupos de 20 personas y en auditorios con más de 80 personas.

== 7. Expositor

[button]#link:../../personas/ralvarez[Rafael Alvarez]#




