:slug: kb/cobol/evitar-elementos-obsoletos/
:eth: no
:category: cobol
:kb: yes

= Evitar Elementos Obsoletos

== Necesidad

Conocer elementos obsoletos del lenguaje COBOL.

== Contexto

A continuación se describe las circunstancias 
bajo las cuales la siguiente solución tiene sentido:

. Se está desarrollando una aplicación en COBOL.
. Se debe evitar el uso de funciones 
o elementos obsoletos del lenguaje
que puedan afectar la seguridad de la aplicación.
. El código solo debe usar funciones seguras 
y actualizadas del lenguaje [1]. 
. Se desea implementar un sistema
lo más estable posible.
. Es necesario llevar a cabo tareas de actualización 
y mantenimiento a una estructura existente basada en COBOL.

== Solución

. Los elementos en desuso del lenguaje
son elementos categorizados como obsoletos
en el estándar ANSI X3.23-1985 COBOL [3].
Estos elementos no forman parte del estándar COBOL de 2002 [2]
y por lo tanto no son mejorados, modificados o mantenidos.

. En COBOL, los elementos del lenguaje listados aquí 
serán eliminados en futuras especificaciones de COBOL.
Por lo cual, no deberían ser usados en un programa de código abierto.

. COBOL es un lenguaje de programación 
que ofrece compatibilidad con versiones anteriores, 
sin embargo, el uso de elementos obsoletos, 
podría afectar la seguridad 
y estabilidad dentro de la aplicación.

. Además de la versiones ANSI del lenguaje,
IBM tiene su propia versión conocida como: 
IBM Enterprise Cobol, lanzada en 1991 
y que cuenta con actualizaciones periódicas, 
siendo ampliamente usada en sistemas host (Mainframe) bajo z/OS.

. A continuación se da a conocer 
una tabla con los elementos 
considerados obsoletos dentro de COBOL, 
tanto en su versión estándar, 
como para la versión de IBM:

|===
|Elemento |Localización

|ALL.
|En los literales mayores a un caracter 
con un tipo de dato numérico o numérico editado.

|AUTHOR, INSTALLATION, DATE-WRITTEN, DATE-COMPILED y SECURITY.
|División de Identificación.

|MEMORY SIZE.
|Apartado de OBJECT-COMPUTER.

|RERUN.
.2+|Apartado de I-O-CONTROL.

|MULTIPLE FILE TAPE.

|LABEL RECORD.
.3+|Entrada de descripción del archivo.

|VALUE OF.

|DATA RECORDS.

|ALTER.
.4+|Instrucción.

|ENTER.

|STOP.

|USE FOR DEBUGGING.

|KEY.
|Instrucción DISABLE o ENABLE.

|REVERSED.
|Instrucción OPEN.

|GO TO.
|Al excluir el nombre del procedimiento.

|Módulo de segmentación.
|
|===

== Referencias

. REQ.0153: La codificación del sistema 
debe estar implementada en una versión de un lenguaje de programación
estable, actualizada, probada y libre de vulnerabilidades conocidas.
. https://www.ibm.com/support/knowledgecenter/SS6SG3_4.2.0/com.ibm.entcobol.doc_4.2/PGandLR/rlpreobs.htm[Obsolete language elements.]
. https://supportline.microfocus.com/documentation/books/sx20books/atobsl.htm[Summary of obsolete language elements.]