# pylint: disable=invalid-name
"""
This migration removes duplicate vulns, generated by error:
https://gitlab.com/fluidattacks/product/-/issues/5068

Execution Time:    2021-07-26 at 16:02:49 UTC-05
Finalization Time: 2021-07-26 at 16:03:50 UTC-05

New execution deleting unneeded vulns:

Execution Time:    2021-08-11 at 17:28:00 UTC-05
Finalization Time: 2021-08-11 at 17:28:01 UTC-05
"""

from aioextensions import (
    collect,
    run,
)
import csv
import time
from vulnerabilities import (
    dal as vulns_dal,
)

PROD: bool = True


async def main() -> None:
    # Read file with deletion info
    with open("0105.csv", mode="r", encoding="utf8") as f:
        reader = csv.reader(f)
        vulns_to_delete = [
            {
                "finding_id": row[0],
                "vuln_uuid": row[1],
            }
            for row in reader
        ]
    print(f"    === vulns to delete: {len(vulns_to_delete)}")
    print(f"    === sample: {vulns_to_delete[:3]}")

    success = False
    if PROD:
        success = all(
            await collect(
                vulns_dal.delete(
                    vuln["vuln_uuid"],
                    vuln["finding_id"],
                )
                for vuln in vulns_to_delete
            )
        )

    print(f"    === success: {success}")


if __name__ == "__main__":
    execution_time = time.strftime(
        "Execution Time:    %Y-%m-%d at %H:%M:%S UTC%Z"
    )
    run(main())
    finalization_time = time.strftime(
        "Finalization Time: %Y-%m-%d at %H:%M:%S UTC%Z"
    )
    print(f"{execution_time}\n{finalization_time}")
