# pylint: disable=invalid-name
"""
This migration removes duplicate vulns, generated by error:
https://gitlab.com/fluidattacks/product/-/issues/5068

Execution Time:
Finalization Time:
"""

from aioextensions import (
    collect,
    run,
)
import csv
import time
from vulnerabilities import (
    dal as vulns_dal,
)

PROD: bool = False


async def main() -> None:
    # Read file with deletion info
    with open("0105_vulns_to_delete.csv", mode="r") as f:
        reader = csv.reader(f)
        vulns_to_delete = [
            {
                "finding_id": row[2],
                "vuln_uuid": row[4],
            }
            for row in reader
        ]
    print(f"    === vulns to delete: {len(vulns_to_delete)}")

    success = False
    if PROD:
        success = all(
            await collect(
                vulns_dal.delete(
                    vuln["vuln_uuid"],
                    vuln["finding_id"],
                )
                for vuln in vulns_to_delete
            )
        )

    print(f"    === success: {success}")


if __name__ == "__main__":
    execution_time = time.strftime(
        "Execution Time:    %Y-%m-%d at %H:%M:%S UTC%Z"
    )
    run(main())
    finalization_time = time.strftime(
        "Finalization Time: %Y-%m-%d at %H:%M:%S UTC%Z"
    )
    print(f"{execution_time}\n{finalization_time}")
