:slug: defends/java/registrar-eventos-clases/
:category: java
:description: Nuestros ethical hackers explican que son las bitácoras, por que es importante utilizarlas y cual es la manera adecuada de generar dichos informes usando clases de Java y así, poder conocer los acontecimientos relevantes que han afectado la ejecución del programa.
:keywords: Java, Seguridad, Bitacoras, Logs, Clases, Logger.
:defends: yes

= Personalizar Registro de Eventos con Clases

== Necesidad

Personalizar el registro de eventos con clases.

== Contexto

A continuación se describen las circunstancias
bajo las cuales la siguiente solución tiene sentido.

. Se dispone de una aplicación en +Java+
conforme con la especificación del lenguaje +1.4.2+ o superior.

== Solución

Una bitácora o +log+ es una grabación secuencial
en un archivo o en una base de datos
de todos los acontecimientos (eventos o acciones)
que afectan a un proceso particular
(aplicación, actividad de una red informática, entre otros).
De esta forma constituye una evidencia
del comportamiento del sistema.

El uso de bitácoras puede servir para:

* Análisis forense.
* Detección de intrusos.
* Depuración de errores.
* Motorización.
* Cumplir con las leyes establecidas.
* Auditoría.

Por otro lado, cada evento
que desea grabarse en la bitácora tiene un nivel.
Este nivel indica la prioridad o urgencia de dicho evento.
Los niveles en orden descendente de urgencia son:

* +SEVERE+.
* +WARNING+.
* +INFO+.
* +CONFIG+.
* +FINE+.
* +FINER+.
* +FINEST+.

. En +Java+ es posible realizar la configuración del +logger+
especificando una clase donde se establezcan las propiedades
que este debe de tener.
Para lo cual es necesario
utilizar el parámetro +Djava.util.logging.config.class+
cuyo valor será usado por la clase +java.util.logging.LogManager+.
La clase +LogManager+ es la encargada de crear
el +logger+ con las propiedades que se definan.

. Se debe crear una clase
que se encargue de inicializar
la configuración del +logger+
donde se obtenga una referencia a +root logger+
y se le asigne el manejador de eventos +ConsoleHandler+
con el fin de que los eventos
sean registrados en una salida estándar.
+
.config.java
[source, java, linenums]
----
import java.util.logging.ConsoleHandler;
import java.util.logging.Level;
import java.util.logging.Logger;

public class Config {
  public Config() {
    System.out.println("Configuring...");
    Logger logger = Logger.getLogger("");
    ConsoleHandler ch = new ConsoleHandler();
    ch.setLevel(Level.INFO);
    logger.addHandler(ch);
    logger.setLevel(Level.ALL);
  }
}
----

. Después, se debe crear una clase
encargada de solicitarle al +logger+
el registro de algunos eventos de diferentes niveles.
En esta nueva clase,
es necesario invocar el método estático +Logger.getLogger+
pasándole como parámetro el nombre del +logger+.
+
.cli.java
[source, cli, linenums]
----
import java.util.logging.Level;
import java.util.logging.Logger;

class CLI {
  public static void main(String argv[]) throws Exception {
    Logger logger = Logger.getLogger("");
----

. Por último, se registran algunos eventos de diferentes niveles.
+
[source, cli, linenums]
----
    logger.info("Procesing...");
    try {
      throw(new Exception());
    }
    catch (Exception e) {
      logger.log(Level.WARNING, "Hello... we've got a problem", e);
    }
    logger.fine("Done!");
  }
}
----

. Se compilan las clases.
+
.compile.bash
[source, bash, linenums]
----
$ javac CLI.java
$ javac Config.java
----

. Para finalizar, se ejecuta la clase +CLI+
utilizando el parámetro +Djava.util.logging.config.class+
pasándole como valor la clase +Config+.
Una vez ejecutada la clase
se obtiene como salida
la información de los eventos registrados.
+
[source, bash, linenums]
----
$ java -Djava.util.logging.config.class=Config CLI

Configuring...
Nov 6, 2018 9:29:05 AM CLI main
INFO: Procesing...
Nov 6, 2018 9:29:05 AM CLI main
WARNING: Hello... we've got a problem
java.lang.Exception at CLI.main(CLI.java:14)
----

== Descargas

Puedes descargar el código fuente
pulsando en los siguientes enlaces:

[button]#link:src/config.java[Config.java]#
Clase Config.

[button]#link:src/cli.java[CLI.java]#
Clase CLI.

== Referencias

. [[r1]] link:https://docs.oracle.com/javase/7/docs/api/java/util/logging/LogManager.html[Class LogManager]
. [[r2]] link:https://es.wikipedia.org/wiki/Log_(inform%C3%A1tica)[Log]
. [[r3]] link:../../../rules/075/[REQ.075 Registrar eventos en bitácoras]
