:slug: rules/316/
:category: privacy
:description: This document contains the details of the security requirements related to the management and protection of data privacy in the organization. This requirement establishes the importance of allowing the users to request rectification of data belonging to them.
:keywords: Requirement, Security, Data, GDPR, Rectification, Personal
:rules: yes

= REQ.316 Allow rectification requests

== Requirement

The system must allow users to request rectification of data belonging to them
that it is managing.

== Description

Systems usually request information from the users,
obtain it from third parties or collect it based on their interactions with the
application.
They should have a mechanism that allows users to find out about this
information and request rectification if they consider it is necessary.

== Exceptions

. If the system is able to demonstrate that it is not possible to individually
identify the users based on the information collected from them,
this requirement is not applicable.

. The processing of the personal information might have scientific or
historical research purposes or statistical purposes.
If the system properly safeguards this information and if complying with this
requirement seriously impairs those purposes,
this requirement is not applicable.

. The processing of the personal information might have archiving purposes
in the public interest.
If the system properly safeguards this information and if complying with this
requirement seriously impairs those purposes,
this requirement is not applicable.

== Findings

* [inner]#link:/web/findings/088/[F088. Privacy violation]#

== References

. [[r1]] link:https://gdpr-info.eu/art-11-gdpr/[GDPR. Art. 11: Processing which does not require identification.(2).]
Where the controller is able to demonstrate that it is not in a position to
identify the data subject,
articles 15 to 20 shall not apply.

. [[r2]] link:https://gdpr-info.eu/art-16-gdpr/[GDPR. Art. 16: Right to rectification.(1).]
The data subject shall have the right to obtain from the controller without
undue delay the rectification of inaccurate personal data concerning him or
her.

. [[r3]] link:https://gdpr-info.eu/art-89-gdpr/[GDPR. Art. 89: Safeguards and derogations relating to processing
for archiving purposes in the public interest,
scientific or historical research purposes or statistical purposes.(2).]
Where personal data are processed for scientific or historical research
purposes or statistical purposes,
Union or Member State law may provide for derogations from the rights referred
to in Articles 15, 16, 18 and 21.

. [[r4]] link:https://gdpr-info.eu/art-89-gdpr/[GDPR. Art. 89: Safeguards and derogations relating to processing
for archiving purposes in the public interest,
scientific or historical research purposes or statistical purposes.(3).]
Where personal data are processed for archiving purposes in the public
interest,
Union or Member State law may provide for derogations from the rights referred
to in Articles 15, 16, 18, 19, 20 and 21.
