:slug: rules/173/
:category: source
:description: This document contains the details of the security requirements related to the definition and management of source code in the organization. This requirement establishes the importance of validating the application inputs and discarding harmful information to avoid common injection attacks.
:keywords: Inputs, Application, Validation, Discard, ASVS, CWE
:rules: yes

= REQ.173 Discard unsafe inputs

== Requirement

The system must discard all potentially harmful information
obtained via data inputs.

== Description

Technological devices and, in particular, applications
must be able to notice if the received information
that does not correspond to its operational purposes,
in order to treat it properly
(for example, rejecting and/or generating timely alerts)
and so that it does not impact the operation negatively.
Typical examples of this are: *SQL* queries, *JavaScript* code,
*OS* commands or *LDAP* queries
in fields and application parameters;
text with undesired special characters
and their possible combinations in fields and parameters;
files manipulated in structure and extension
to be loaded in an application or technology artifact,
and in general any type of information
that does not correspond to the requested format.
A large amount of the incoming traffic
(which does not correspond to operational purposes)
of a technological artifact must also be considered
and controls and proper treatment must be applied.

== Implementation

. Perform whitelisting instead of blacklisting:
By using this principle, the control implementation
will be configured to reject all inputs
that are not explicitly approved
discarding all possible scenarios
and forcing enumeration of strictly allowed inputs.
E.g. allow only *a-z*, *A-Z* y *0-9*.

. Use variable highlight:
If supported, language and compiler
can detect foreign variables
that are not validated by a filter.
To this end, you may use techniques to highlight those variables
and compilers or pre-processors
to detect that they are not validated.

. No only user validation but also input validation:
Any input from outside the application
must be considered malicious,
that is to say, the user can enter incorrect information
as well as potentially harmful inputs
that may also compromise external systems,
therefore this information must be validated.

== Attacks

. Inject malicious software or code.
. Denial of service caused by register overload.
. Cross-Site Scripting (*XSS*).
. *OS* command injection.
. *SQL* injection.
. *LDAP* injection.
. Redirect to untrusted pages.

== Attributes

* Layer: Application Layer
* Asset: Source code
* Scope: Matureness
* Phase: Building
* Type of Control: Recommendation

== Findings

* link:/web/findings/001/[F001. SQL injection]

* link:/web/findings/004/[F004. Remote command execution]

* link:/web/findings/008/[F008. Reflected cross-site scripting (XSS)]

* link:/web/findings/010/[F010. Stored cross-site scripting (XSS)]

* link:/web/findings/021/[F021. XPath Injection]

* link:/web/findings/023/[F023. Uncontrolled external site redirect]

* link:/web/findings/045/[F045. HTML code injection]

* link:/web/findings/063/[F063. Lack of data validation]

* link:/web/findings/083/[F083. XML Injection (XXE)]

* link:/web/findings/090/[F090. Code injection (CSV)]

* link:/web/findings/091/[F091. Log injection]

* link:/web/findings/092/[F092. Improper resource allocation]

* link:/web/findings/093/[F093. Hidden fields manipulation]

* link:/web/findings/094/[F094. System impersonation]

* link:/web/findings/096/[F096. Insecure deserialization]

* link:/web/findings/097/[F097. Reverse tabnabbing]

* link:/web/findings/100/[F100. Server-side request forgery (SSRF)]

* link:/web/findings/103/[F103. Insufficient data authenticity validation]

* link:/web/findings/105/[F105. Apache Lucene query injection]

* link:/web/findings/106/[F106. NoSQL injection]

* link:/web/findings/107/[F107. LDAP injection]

* link:/web/findings/110/[F110. HTTP request smuggling]

== Referencias

. [[r1]] link:https://www.owasp.org/index.php/Top_10_2013-A1-Injection[A1 Injection OWASP - Top 10 2013]

. [[r2]] link:https://www.owasp.org/index.php/Top_10_2013-A3-Cross-Site_Scripting_(XSS)[A3 Cross-site Scripting (XSS) OWASP - TOP 10 2013].

. [[r3]] link:https://www.owasp.org/index.php/Top_10_2013-A10-Unvalidated_Redirects_and_Forwards[A10 Unvalidated Redirects and Forwards OWASP - TOP 10 2013].

. [[r4]] link:https://cwe.mitre.org/data/definitions/20.html[CWE-20: Improper Input Validation].
The product does not validate or incorrectly validates input that can affect
the control flow or data flow of a program.

. [[r5]] link:https://cwe.mitre.org/data/definitions/74.html[CWE-74: Injection].
The software constructs all or part of a command, data structure, or record
using externally-influenced input from an upstream component,
but it does not neutralize or incorrectly neutralizes special elements.

. [[r6]] link:https://cwe.mitre.org/data/definitions/78.html[CWE-78: OS Command Injection].
The software constructs all or part of an OS command using
externally-influenced input from an upstream component,
but it does not neutralize or incorrectly neutralizes special elements that
could modify the intended OS command.

. [[r7]] link:https://cwe.mitre.org/data/definitions/79.html[​CWE-79: Cross-site Scripting].
The software does not neutralize or incorrectly neutralizes user-controllable
input before it is placed in output that is used as a web page that is served
  to other users.

. [[r8]] link:https://cwe.mitre.org/data/definitions/80.html[CWE-80: Basic XSS].
The software receives input from an upstream component,
but it does not neutralize or incorrectly neutralizes special characters such
as "<", ">", and "&" that could be interpreted as web-scripting elements.

. [[r9]] link:https://cwe.mitre.org/data/definitions/89.html[CWE-89: SQL Injection].
The software constructs all or part of an SQL command using
externally-influenced input from an upstream component,
but it does not neutralize or incorrectly neutralizes special elements that
could modify the intended SQL command.

. [[r10]] link:https://cwe.mitre.org/data/definitions/116.html[CWE-116: SQL Injection].
The software prepares a structured message for communication with another
component,
but encoding or escaping of the data is either missing or done incorrectly.
As a result, the intended structure of the message is not preserved.

. [[r11]] link:https://cwe.mitre.org/data/definitions/602.html[CWE-602: Client-Side Enforcement of Server-Side Security]
The software is composed of a server that relies on the client to implement a
mechanism that is intended to protect the server.

. [[r12]] link:https://www.owasp.org/index.php/ASVS_V5_Input_validation_and_output_encoding[OWASP-ASVS v3.1-5.10]
Verify that all database queries are protected
by the use of parameterized queries
or proper *ORM* usage to avoid *SQL* injection.

. [[r13]] link:https://www.owasp.org/index.php/ASVS_V5_Input_validation_and_output_encoding[OWASP-ASVS v3.1-5.11]
Verify that the application is not susceptible to *LDAP* Injection,
or that security controls prevent *LDAP* Injection.

. [[r14]] link:https://www.owasp.org/index.php/ASVS_V5_Input_validation_and_output_encoding[OWASP-ASVS v3.1-5.12]
Verify that the application is not susceptible to *OS* Command Injection,
or that security controls prevent *OS* Command Injection.

. [[r15]] link:https://www.owasp.org/index.php/ASVS_V5_Input_validation_and_output_encoding[OWASP-ASVS v3.1-5.13]
Verify that the application is not susceptible
to Remote File Inclusion (*RFI*) or Local File Inclusion (*LFI*)
when content is used that is a path to a file.

. [[r16]] link:https://www.owasp.org/index.php/ASVS_V5_Input_validation_and_output_encoding[OWASP-ASVS v3.1-5.14]
Verify that the application is not susceptible
to XPath injection or *XML* injection attacks.

. [[r17]] link:https://www.owasp.org/index.php/ASVS_V5_Input_validation_and_output_encoding[OWASP-ASVS v3.1-5.15]
Verify that all string variables placed into *HTML*
or other web client code are either properly contextually encoded manually,
or utilize templates that automatically contextually encode
to ensure the application is not susceptible to reflected,
stored or *DOM* Cross-Site Scripting (*XSS*) attacks.

. [[r18]] link:https://www.owasp.org/index.php/ASVS_V5_Input_validation_and_output_encoding[OWASP-ASVS v3.1-5.17]
Verify that the application has defenses
against *HTTP* parameter pollution attacks,
particularly if the application framework makes no distinction
about the source of request parameters
(*GET*, *POST*, cookies, headers, environment, etc.)

. [[r19]] link:https://www.owasp.org/index.php/ASVS_V5_Input_validation_and_output_encoding[OWASP-ASVS v3.1-5.19]
Verify that all input data is validated,
not only *HTML* form fields but all sources of input such as *REST* calls,
query parameters, *HTTP* headers, cookies, batch files, *RSS* feeds, etc;
using positive validation (whitelisting),
then lesser forms of validation such as grey listing
(eliminating known bad strings),
or rejecting bad inputs (blacklisting).

. [[r20]] link:https://www.owasp.org/index.php/ASVS_V5_Input_validation_and_output_encoding[OWASP-ASVS v3.1-5.20]
Verify that structured data is strongly typed
and validated against a defined schema including allowed characters,
length and pattern (e.g. credit card numbers or telephone,
or validating that two related fields are reasonable,
such as validating suburbs and zip or post codes match).

. [[r21]] link:https://www.owasp.org/index.php/ASVS_V5_Input_validation_and_output_encoding[OWASP-ASVS v3.1-5.21]
Verify that unstructured data is sanitized to enforce generic safety measures
such as allowed characters and length,
and characters potentially harmful in given context should be escaped
(e.g. natural names with Unicode or apostrophes, such as ねこ or O'Hara).

. [[r22]] link:https://www.owasp.org/index.php/ASVS_V5_Input_validation_and_output_encoding[OWASP-ASVS v3.1-5.22]
Verify that all untrusted *HTML* input from *WYSIWYG* editors or similar
is properly sanitized with an *HTML* sanitizer library or framework feature.

. [[r23]] link:https://owasp.org/www-project-application-security-verification-standard/[OWASP-ASVS v4.0.1
V1.5 Input and Output Architectural Requirements.(1.5.3)]
Verify that input validation is enforced on a trusted service layer.

. [[r24]] link:https://owasp.org/www-project-application-security-verification-standard/[OWASP-ASVS v4.0.1
V1.5 Input and Output Architectural Requirements.(1.5.4)]
Verify that output encoding occurs close to or by the interpreter for which it
is intended.
