:slug: rules/173/
:category: source
:description: This requirement establishes the importance of validating the application inputs and discarding harmful information to avoid frequent injection attacks.
:keywords: Inputs, Application, Validation, Discard, ASVS, CWE, Rules, Ethical Hacking, Pentesting
:rules: yes

= R173. Discard unsafe inputs

== Requirement

The system must discard all potentially harmful information
received via data inputs.

== Description

Technological devices and, in particular, applications
must be able to notice if the received information
that does not correspond to its operational purposes,
in order to treat it properly
(for example, rejecting and/or generating timely alerts)
and so that it does not impact the operation negatively.
Typical examples of this are: *SQL* queries, *JavaScript* code,
*OS* commands or *LDAP* queries
in fields and application parameters;
text with undesired special characters
and their possible combinations in fields and parameters;
files manipulated in structure and extension
to be loaded in an application or technology artifact,
and in general any type of information
that does not correspond to the requested format.
A large amount of the incoming traffic
(which does not correspond to operational purposes)
of a technological artifact must also be considered
and controls and proper treatment must be applied.

== Implementation

. Perform whitelisting instead of blacklisting:
By using this principle, the control implementation
will be configured to reject all inputs
that are not explicitly approved
discarding all possible scenarios
and forcing enumeration of strictly allowed inputs.
E.g. allow only *a-z*, *A-Z* y *0-9*.

. Use variable highlight:
If supported, language and compiler
can detect foreign variables
that are not validated by a filter.
To this end, you may use techniques to highlight those variables
and compilers or pre-processors
to detect that they are not validated.

. No only user validation but also input validation:
Any input from outside the application
must be considered malicious,
that is to say, the user can enter incorrect information
as well as potentially harmful inputs
that may also compromise external systems,
therefore this information must be validated.

== Attacks

. Inject malicious software or code.
. Denial of service caused by register overload.
. Cross-Site Scripting (*XSS*).
. *OS* command injection.
. *SQL* injection.
. *LDAP* injection.
. Redirect to untrusted pages.

== Attributes

* Layer: Application Layer
* Asset: Source code
* Scope: Maturity
* Phase: Building
* Type of Control: Recommendation

== Findings

* [inner]#link:/web/findings/001/[F001. SQL injection]#

* [inner]#link:/web/findings/004/[F004. Remote command execution]#

* [inner]#link:/web/findings/008/[F008. Reflected cross-site scripting (XSS)]#

* [inner]#link:/web/findings/010/[F010. Stored cross-site scripting (XSS)]#

* [inner]#link:/web/findings/021/[F021. XPath Injection]#

* [inner]#link:/web/findings/023/[F023. Uncontrolled external site redirect]#

* [inner]#link:/web/findings/032/[F032. Spoofing]#

* [inner]#link:/web/findings/045/[F045. HTML code injection]#

* [inner]#link:/web/findings/063/[F063. Lack of data validation]#

* [inner]#link:/web/findings/067/[F067. Improper resource allocation]#

* [inner]#link:/web/findings/083/[F083. XML Injection (XXE)]#

* [inner]#link:/web/findings/090/[F090. Code injection (CSV)]#

* [inner]#link:/web/findings/091/[F091. Log injection]#

* [inner]#link:/web/findings/093/[F093. Hidden fields manipulation]#

* [inner]#link:/web/findings/096/[F096. Insecure deserialization]#

* [inner]#link:/web/findings/097/[F097. Reverse tabnabbing]#

* [inner]#link:/web/findings/100/[F100. Server-side request forgery (SSRF)]#

* [inner]#link:/web/findings/103/[F103. Insufficient data authenticity validation]#

* [inner]#link:/web/findings/105/[F105. Apache Lucene query injection]#

* [inner]#link:/web/findings/106/[F106. NoSQL injection]#

* [inner]#link:/web/findings/107/[F107. LDAP injection]#

* [inner]#link:/web/findings/110/[F110. HTTP request smuggling]#

== References

. [[r1]] link:https://www.owasp.org/index.php/Top_10_2013-A1-Injection[A1 Injection OWASP - Top 10 2013]

. [[r2]] link:https://www.owasp.org/index.php/Top_10_2013-A3-Cross-Site_Scripting_(XSS)[A3 Cross-site Scripting (XSS) OWASP - TOP 10 2013].

. [[r3]] link:https://www.owasp.org/index.php/Top_10_2013-A10-Unvalidated_Redirects_and_Forwards[A10 Unvalidated Redirects and Forwards OWASP - TOP 10 2013].

. [[r4]] link:https://cwe.mitre.org/data/definitions/20.html[CWE-20: Improper Input Validation].
The product does not validate or incorrectly validates input that can affect
the control flow or data flow of a program.

. [[r5]] link:https://cwe.mitre.org/data/definitions/74.html[CWE-74: Injection].
The software constructs all or part of a command, data structure, or record
using externally-influenced input from an upstream component,
but it does not neutralize or incorrectly neutralizes special elements.

. [[r6]] link:https://cwe.mitre.org/data/definitions/78.html[CWE-78: OS Command Injection].
The software constructs all or part of an OS command using
externally-influenced input from an upstream component,
but it does not neutralize or incorrectly neutralizes special elements that
could modify the intended OS command.

. [[r7]] link:https://cwe.mitre.org/data/definitions/79.html[​CWE-79: Cross-site Scripting].
The software does not neutralize or incorrectly neutralizes user-controllable
input before it is placed in output that is used as a web page that is served
 to other users.

. [[r8]] link:https://cwe.mitre.org/data/definitions/80.html[CWE-80: Basic XSS].
The software receives input from an upstream component,
but it does not neutralize or incorrectly neutralizes special characters such
as "<", ">", and "&" that could be interpreted as web-scripting elements.

. [[r9]] link:https://cwe.mitre.org/data/definitions/89.html[CWE-89: SQL Injection].
The software constructs all or part of an SQL command using
externally-influenced input from an upstream component,
but it does not neutralize or incorrectly neutralizes special elements that
could modify the intended SQL command.

. [[r10]] link:https://cwe.mitre.org/data/definitions/94.html[CWE-94: Code Injection].
The software constructs all or part of a code segment using
externally-influenced input from an upstream component,
but it does not neutralize or incorrectly neutralizes special elements that
could modify the syntax or behavior of the intended code segment.

. [[r11]] link:https://cwe.mitre.org/data/definitions/116.html[CWE-116: Improper Encoding or Escaping of Output].
The software prepares a structured message for communication with another
component,
but encoding or escaping of the data is either missing or done incorrectly.
As a result, the intended structure of the message is not preserved.

. [[r12]] link:https://cwe.mitre.org/data/definitions/138.html[CWE-138: Improper Neutralization of Special Elements].
The software receives input from an upstream component,
but it does not neutralize or incorrectly neutralizes special elements that
could be interpreted as control elements or syntactic markers when they are
sent to a downstream component.

. [[r13]] link:https://cwe.mitre.org/data/definitions/147.html[CWE-147: Improper Neutralization of Input Terminators].
The software receives input from an upstream component,
but it does not neutralize or incorrectly neutralizes special elements that
could be interpreted as input terminators when they are sent to a downstream
component.

. [[r14]] link:https://cwe.mitre.org/data/definitions/159.html[CWE-159: Improper Handling of Invalid Use of Special Elements].
The product does not properly filter, remove, quote, or otherwise manage the
invalid use of special elements in user-controlled input,
which could cause adverse effect on its behavior and integrity.

. [[r15]] link:https://cwe.mitre.org/data/definitions/602.html[CWE-602: Client-Side Enforcement of Server-Side Security].
The software is composed of a server that relies on the client to implement a
mechanism that is intended to protect the server.

. [[r16]] link:https://cwe.mitre.org/data/definitions/643.html[CWE-643: XPath Injection].
The software uses external input to dynamically construct an *XPath* expression
used to retrieve data from an *XML* database,
but it does not neutralize or incorrectly neutralizes that input.

. [[r17]] link:https://cwe.mitre.org/data/definitions/943.html[CWE-943: Improper Neutralization of Special Elements in Data Query Logic].
The application generates a query intended to access or manipulate data in a
data store such as a database,
but it does not neutralize or incorrectly neutralizes special elements that can
modify the intended logic of the query.

. [[r18]] link:https://owasp.org/www-project-application-security-verification-standard/[OWASP-ASVS v4.0.1
V1.5 Input and Output Architectural Requirements.(1.5.3)]
Verify that input validation is enforced on a trusted service layer.

. [[r19]] link:https://owasp.org/www-project-application-security-verification-standard/[OWASP-ASVS v4.0.1
V1.5 Input and Output Architectural Requirements.(1.5.4)]
Verify that output encoding occurs close to or by the interpreter for which it
is intended.

. [[r20]] link:https://owasp.org/www-project-application-security-verification-standard/[OWASP-ASVS v4.0.1
V5.1 Input Validation Requirements.(5.1.1)]
Verify that the application has defenses against HTTP parameter pollution
attacks,
particularly if the application framework makes no distinction about the source
of request parameters (*GET*, *POST*, cookies, headers,
or environment variables).

. [[r21]] link:https://owasp.org/www-project-application-security-verification-standard/[OWASP-ASVS v4.0.1
V5.1 Input Validation Requirements.(5.1.3)]
Verify that all input (*HTML* form fields, *REST* requests, *URL* parameters,
*HTTP* headers, cookies, batch files, *RSS* feeds, etc) is validated using
positive validation (*whitelisting*).

. [[r22]] link:https://owasp.org/www-project-application-security-verification-standard/[OWASP-ASVS v4.0.1
V5.1 Input Validation Requirements.(5.1.4)]
Verify that structured data is strongly typed and validated against a defined
schema including allowed characters, length and pattern
(e.g. credit card numbers or telephone, or validating that two related fields
are reasonable, such as checking that suburb and zip/postcode match).

. [[r23]] link:https://owasp.org/www-project-application-security-verification-standard/[OWASP-ASVS v4.0.1
V5.2 Sanitization and Sandboxing Requirements.(5.2.1)]
Verify that all untrusted *HTML* input from *WYSIWYG* editors or similar is
properly sanitized with an *HTML* sanitizer library or framework feature.

. [[r24]] link:https://owasp.org/www-project-application-security-verification-standard/[OWASP-ASVS v4.0.1
V5.2 Sanitization and Sandboxing Requirements.(5.2.2)]
Verify that unstructured data is sanitized to enforce safety measures such as
allowed characters and length.

. [[r25]] link:https://owasp.org/www-project-application-security-verification-standard/[OWASP-ASVS v4.0.1
V5.2 Sanitization and Sandboxing Requirements.(5.2.3)]
Verify that the application sanitizes user input before passing to mail systems
to protect against *SMTP* or *IMAP* injection.

. [[r26]] link:https://owasp.org/www-project-application-security-verification-standard/[OWASP-ASVS v4.0.1
V5.2 Sanitization and Sandboxing Requirements.(5.2.4)]
Verify that the application avoids the use of **eval()** or other dynamic code
execution features.
Where there is no alternative,
any user input being included must be sanitized or sandboxed before being
executed.

. [[r27]] link:https://owasp.org/www-project-application-security-verification-standard/[OWASP-ASVS v4.0.1
V5.2 Sanitization and Sandboxing Requirements.(5.2.5)]
Verify that the application protects against template injection attacks by
ensuring that any user input being included is sanitized or sandboxed.

. [[r28]] link:https://owasp.org/www-project-application-security-verification-standard/[OWASP-ASVS v4.0.1
V5.2 Sanitization and Sandboxing Requirements.(5.2.6)]
Verify that the application protects against *SSRF* attacks,
by validating or sanitizing untrusted data or *HTTP* file metadata,
such as filenames and URL input fields,
or using whitelisting of protocols, domains, paths and ports.

. [[r29]] link:https://owasp.org/www-project-application-security-verification-standard/[OWASP-ASVS v4.0.1
V5.2 Sanitization and Sandboxing Requirements.(5.2.7)]
Verify that the application sanitizes, disables, or sandboxes user-supplied
*SVG* scriptable content,
especially as they relate to *XSS* resulting from inline scripts, and
*foreignObject*.

. [[r30]] link:https://owasp.org/www-project-application-security-verification-standard/[OWASP-ASVS v4.0.1
V5.2 Sanitization and Sandboxing Requirements.(5.2.8)]
Verify that the application sanitizes, disables, or sandboxes user-supplied
scriptable or expression template language content,
such as Markdown, *CSS* or *XSL* stylesheets, *BBCode*, or similar.

. [[31]] link:https://owasp.org/www-project-application-security-verification-standard/[OWASP-ASVS v4.0.1
V5.3 Output encoding and Injection Prevention Requirements.(5.3.4)]
Verify that data selection or database queries
(e.g. *SQL*, *HQL*, *ORM*, *NoSQL*) use parameterized queries, *ORMs*,
entity frameworks, or are otherwise protected from database injection attacks.

. [[r32]] link:https://owasp.org/www-project-application-security-verification-standard/[OWASP-ASVS v4.0.1
V5.3 Output encoding and Injection Prevention Requirements.(5.3.5)]
Verify that where parameterized or safer mechanisms are not present,
context-specific output encoding is used to protect against injection attacks,
such as the use of *SQL* escaping to protect against *SQL* injection.

. [[r33]] link:https://owasp.org/www-project-application-security-verification-standard/[OWASP-ASVS v4.0.1
V5.3 Output encoding and Injection Prevention Requirements.(5.3.7)]
Verify that the application protects against *LDAP* Injection vulnerabilities,
or that specific security controls to prevent *LDAP* Injection have been
implemented.

. [[r34]] link:https://owasp.org/www-project-application-security-verification-standard/[OWASP-ASVS v4.0.1
V5.3 Output encoding and Injection Prevention Requirements.(5.3.8)]
Verify that the application protects against *OS* command injection and that
operating system calls use parameterized *OS* queries or use contextual command
line output encoding.

. [[r35]] link:https://owasp.org/www-project-application-security-verification-standard/[OWASP-ASVS v4.0.1
V5.3 Output encoding and Injection Prevention Requirements.(5.3.9)]
Verify that the application protects against Local File Inclusion (*LFI*) or
Remote File Inclusion (*RFI*) attacks.

. [[r36]] link:https://owasp.org/www-project-application-security-verification-standard/[OWASP-ASVS v4.0.1
V5.3 Output encoding and Injection Prevention Requirements.(5.3.10)]
Verify that the application protects against *XPath* injection or *XML*
injection attacks.

. [[r37]] link:https://owasp.org/www-project-application-security-verification-standard/[OWASP-ASVS v4.0.1
V5.4 Memory, String, and Unmanaged Code Requirements.(5.4.2)]
Verify that format strings do not take potentially hostile input,
and are constant.

. [[r38]] link:https://owasp.org/www-project-application-security-verification-standard/[OWASP-ASVS v4.0.1
V5.4 Memory, String, and Unmanaged Code Requirements.(5.4.3)]
Verify that sign, range, and input validation techniques are used to prevent
integer overflows.

. [[r39]] link:https://owasp.org/www-project-application-security-verification-standard/[OWASP-ASVS v4.0.1
V5.5 Deserialization Prevention Requirements.(5.5.2)]
Verify that the application correctly restricts *XML* parsers to only use the
most restrictive configuration possible and to ensure that unsafe features such
as resolving external entities are disabled to prevent *XXE*.

. [[r40]] link:https://owasp.org/www-project-application-security-verification-standard/[OWASP-ASVS v4.0.1
V7.3 Log Protection Requirements.(7.3.1)]
Verify that the application appropriately encodes user-supplied data to prevent
log injection.

. [[r41]] link:https://owasp.org/www-project-application-security-verification-standard/[OWASP-ASVS v4.0.1
V12.1 File Upload Requirements.(12.1.2)]
Verify that compressed files are checked for "zip bombs" - small input files
that will decompress into huge files thus exhausting file storage limits.

. [[r42]] link:https://owasp.org/www-project-application-security-verification-standard/[OWASP-ASVS v4.0.1
V13.1 Generic Web Service Security Verification Requirements.(13.1.5)]
Verify that requests containing unexpected or missing content types are
rejected with appropriate headers
(*HTTP* response status **406 Unacceptable** or
**415 Unsupported Media Type**).

. [[r43]] link:https://owasp.org/www-project-application-security-verification-standard/[OWASP-ASVS v4.0.1
V13.2 RESTful Web Service Verification Requirements.(13.2.2)]
Verify that *JSON* schema validation is in place and verified before accepting
input.

. [[r44]] link:https://owasp.org/www-project-application-security-verification-standard/[OWASP-ASVS v4.0.1
V13.3 SOAP Web Service Verification Requirements.(13.3.1)]
Verify that *XSD* schema validation takes place to ensure a properly formed
*XML* document,
followed by validation of each input field before any processing of that data
takes place.
