:slug: kb/yii/validar-datos-entrada/
:eth: no
:category: yii
:kb: yes

= Validar Datos de Entrada

== Necesidad

Validar los datos de entrada a la aplicación

== Contexto

A continuación se describen las circunstancias bajo las cuales la siguiente 
solución tiene sentido:

. Se utiliza el lenguaje de programación PHP.
. Se utiliza el framework de desarrollo Yii [1].

== Solución

. Se cuenta con un formulario del cual se desean validar sus datos.
. Para validar datos con Yii se hace uso del método rules() en los modelos 
definidos para el uso de la aplicación, un ejemplo se muestra a continuación:
+
[source, php, linenums]
----
/**
  * @return array validation rules for model attributes.
*/

public function rules()
{
  // NOTE: you should only define rules for those attributes that
  // will receive user inputs.
  return array(
    array('ciudad_id, nombres, identificacion, email, genero','required',
	  'message'=>'Este campo es requerido'),
    array('nombres', 'match', 'pattern'=>'[\w\s]*', 'allowEmpty'=>false),
    array('email', 'email'),
    array('id, ciudad_id, nombres, identificacion, email, estado, genero', 
	  'safe','on'=>'search'), );
}
----

. En el ejemplo anterior se puede apreciar el uso de diferentes validaciones 
del tipo required, email o incluso el uso de expresiones regulares como se 
aprecia en array('nombres','match', 'pattern'=>'[\w\s]{3,}', 
'allowEmpty'=>false), con el cual podemos evitar que los datos contengan 
caracteres innecesarios tales como ', -, ", etc., previniendo ciertos vectores
de ataque. El validador safe nos permite evitar que un usuario malintencionado 
pueda alterar los valores del modelo que no necesariamente tengan una 
representación en una base de datos, y a la vez proteger que estos datos puedan 
explotar funciones del método CActiveRecord.
. Esta validación se realiza cuando el método validate() es llamado desde el 
objeto modelo, generalmente en respuesta a una acción por parte del usuario, 
ejemplo:
[source, php, linenums]
----
$model->attributes=$_POST['Usuarios'];
if ($model->validate())
{
  //todo correcto
}
else
{
  //hubo un error en la validación
}
----

== Referencias

. http://www.yiiframework.com/wiki/56/[YII]
. REQ.0168 El sistema debe descartar toda la información potencialmente 
insegura que sea recibida por entradas de datos.