:slug: rules/046/
:category: rules
:description: En el presente documento se detallan los requerimientos de seguridad relacionados a la gestion de archivos dentro de la organización. Por lo tanto, en este requerimiento se recomienda que el sistema gestione por medio de bitácoras la integridad de los archivos.
:keywords: Sistema, Bitácora, Archivo, Integridad, Seguridad, Requerimiento.
:rules: yes

= REQ.046 Gestionar integridad de archivos críticos

== Requisito

El sistema debe verificar y reportar en bitácora
cambios en integridad de los archivos críticos del sistema.

== Descripción

El sistema debería tener un monitoreo
sobre los archivos identificados como críticos para su funcionamiento,
cuando se detecte alguna modificación
se debe registrar la actividad realizada
con los detalles necesarios para un análisis
como, quien ocasionó evento y el momento de cambio.<<r1,^[1]^>>

== Implementación

. Una vez definidos cuáles serán los archivos críticos del sistema,
se debe establecer una herramienta
que permita generar el registro de las actividades realizadas
sobre los archivos críticos
y configurarla para registrar todos los posibles eventos
que modifiquen estos archivos
y lograr identificar el usuario responsable
y el momento de modificación.

. Es importante que la herramienta usada
genere alertas en cuanto sucedan modificaciones en estos archivos
con el fin de identificar de forma temprana posibles incidentes.

== Ataques

. Ocurre un incidente en el cual
se identifica una modificación de archivos críticos,
sin embargo no se logró detectar con anticipación
al no contar con una herramienta
que registre las modificaciones
en los archivos comprometidos.

== Atributos

* Capa: Aplicación.
* Activo: Archivos.
* Alcance: Integridad.
* Fase: Operación.
* Tipo de Control: Procedimiento.

== Referencias

. [[r1]] link:../079/[REQ.079 Registrar momento de ocurrencia de eventos].
