:slug: defends/csharp/proteger-aplicacion-xss/
:category: csharp
:description: Nuestros ethical hackers explican como evitar vulnerabilidades de seguridad mediante la programacion segura en C Sharp al proteger nuestra aplicación contra ataques de tipo cross site scripting. Éste es un tipo común de ataque que consiste en inyectar scripts en las entradas de la aplicación.
:keywords: C Sharp, Seguridad, Desarrollo, Depuración, Protección, Buenas Prácticas.
:defends: yes

= Proteger Aplicación de Ataques de XSS

== Necesidad

Codificar el código según el lenguaje correspondiente en +C#+

== Contexto

A continuación se describen las circunstancias bajo las cuales la siguiente
solución tiene sentido:

. Se está desarrollando una aplicación en +C#+ y se deben
agregar mensajes de depuración.
. La salida de información del sistema
debe estar codificada en el lenguaje correspondiente.<<r1,^[1]^>>

== Solución

Los ataques por +Cross Site Scripting+ explotan las vulnerabilidades de las
aplicaciones +Web+ que fallan en validar y/o codificar las entradas embebidas
en los datos de respuesta.
Los usuarios maliciosos pueden inyectar +scripts+ al lado del cliente a los
datos de respuesta causando que el navegador de la victima
ejecute códigos posiblemente maliciosos.<<r2,^[2]^>>

La biblioteca +Anti Cross Site Scripting+ de +Microsoft+<<r3,^[3]^>>
puede usarse para proteger a los usuarios
de este tipo de ataques.
Puede descargarse gratis en +Microsoft Anti Cross Site Scripting+.

Antes de comenzar a explicar como proteger una aplicación de los ataques de
+XSS+ es importante resaltar los vectores de ataque que un usuario malicioso
puede usar para lanzar dichos ataques.

Idealmente, se deben ejecutar estas tareas en la etapa de diseño; sin embargo,
aún es posible realizar el trabajo en las aplicaciones que ya se encuentren
implementadas de esta forma:

. Revisar todo el código que produce salidas
. Determinar si la salida incluye parámetros no confiables de salida.
. Determinar si el contexto en el que se usa la entrada no confiable.
. Codificar la salida de manera apropiada.

El mejor criterio para determinar si la entrada es confiable es asumir
que no lo es.

Ejemplos de entradas no confiables incluyen:

. Campos de formulario.
. Cadenas +"Query"+.
. Contenidos de +cookies+.
. Encabezados +HTTP+.

Cuando se identifique que una entrada es no confiable, es importante determinar
el método de codificación más apropiado.
La siguiente tabla muestra los métodos de codificación asociados:

[width="100%"]
|===
|Método de codificación | Cuando se debe usar
|+HtmlEncode+ | Entrada no confiable usada en salida +HTML+ excepto cuando se
asigna a un atributo +HTML+
|+HtmlAttributeEncode+ | Entrada no confiable se usa en atributos +HTML+
|+XmlEncode+ | Entrada no confiable usada en salida +XML+ excepto cuando se
asigne a un atributo +XML+
|+XmlAttributeEncode+ | Salida no confiable usada en los atributos +XML+
|+UrlEncode+ | Entrada no confiable usada como un argumento +URL+
|+UrlPathEncode+ | Entrada no confiable usada como parte de un path +URL+
|+JavaScriptEncode+ | Entrada no confiable usada dentro
de un contexto +JavaScript+
|===

Para usarlo se requiere:

. Clic derecho en el explorador de soluciones en +Visual Studio+.
. Seleccionar "Add Reference"
. Seleccionar la pestaña "+browse+" y luego adicione +AntiXSSLibrary.dll+.
. Adicionar una directiva +using Microsoft.Security.Application+;
. Cambiar la forma en que se asigna la salida, por ejemplo de:
+
.ejemplo.cs.
[source, csharp]
----
string out_Name = Request.QueryString["Name"];
----

. pasar a
+
[source, csharp]
----
string out_Name = Encoder.HtmlEncode(Request.QueryString["Name"]);
----

== Descargas

Puedes descargar el código fuente
pulsando en el siguiente enlace:

. [button]#link:src/default.aspx[default.asp]# contiene
todas las instrucciones +Asp+ del programa.
. [button]#link:src/default.aspx.cs[default.aspx.cs]# contiene
todas las instrucciones +C#+ del programa.

== Referencias

. [[r1]] link:../../../rules/160/[REQ.160 Salidas codificadas].
. [[r2]] link:http://msdn.microsoft.com/en-us/library/aa973813.aspx[Microsoft, Anti- Cross Site Scripting Library].
. [[r3]] link:http://www.microsoft.com/download/en/search.aspx?q=antixss[Microsoft, Antixss].
