:slug: rules/118/
:category: emails
:description: This requirement establishes that email attachments must be inspected employing anti-malware software to avoid virus propagation.
:keywords: Files, Email, Attachment, Malware, Analyze, ASVS, Rules, Ethical Hacking, Pentesting
:rules: yes

= R118. Inspect attachments

== Requirement

An anti-malware tool must scan files that are attached to an email.

== Findings

* [inner]#link:/web/findings/114/[F114. Phishing]#

== References

. [[r1]] link:https://cwe.mitre.org/data/definitions/509.html[CWE-509: Replicating Malicious Code (Virus or Worm)].
Replicating malicious code, including viruses and worms, will attempt to attack
other systems once it has successfully compromised the target system or
software.

. [[r2]] link:https://owasp.org/www-project-application-security-verification-standard/[OWASP-ASVS v4.0.1
V10.1 Code Integrity Controls.(10.1.1)]
Verify that a code analysis tool is in use that can detect potentially
malicious code, such as time functions, unsafe file operations and network
connections.

. [[r3]] link:https://owasp.org/www-project-application-security-verification-standard/[OWASP-ASVS v4.0.1
V12.4 File Storage Requirements.(12.4.2)]
Verify that files obtained from untrusted sources are scanned by antivirus
scanners to prevent upload of known malicious content.
