:slug: rules/266/
:category: architecture
:description: This requirement establishes the importance of disabling or controlling system functions that could be harmful to the application.
:keywords: Insecure, Functionality, System, Hardening, ASVS, CWE, Rules, Ethical Hacking, Pentesting
:rules: yes

= R266. Disable insecure functionalities

== Requirement

The organization must disable or carefully control the insecure functions of a
system (system hardening).

== Description

Sometimes platforms include functionalities that are not required or could be
harmful for some applications built on top of or residing in them.
Other times, applications are developed including functionalities that allow
actions that could be considered insecure.
All these functionalities should be disabled or otherwise controlled to prevent
them from compromising the system's security.
Furthermore, the system must enforce those controls on trusted enforcement
points such as access control gateways, severs and serverless functions.

== Findings

* [inner]#link:/web/findings/014/[F014. Insecure functionality]#

* [inner]#link:/web/findings/044/[F044. Insecure HTTP methods enabled]#

* [inner]#link:/web/findings/047/[F047. Automatic information enumeration]#

* [inner]#link:/web/findings/055/[F055. Insecure service configuration]#

* [inner]#link:/web/findings/056/[F056. Anonymous connection]#

* [inner]#link:/web/findings/101/[F101. Lack of protection against deletion]#

* [inner]#link:/web/findings/110/[F110. HTTP request smuggling]#

* [inner]#link:/web/findings/111/[F111. Out-of-bounds Read]#

* [inner]#link:/web/findings/115/[F115. Security controls bypass]#

* [inner]#link:/web/findings/116/[F116. XS-Leaks]#

== References

. [[r1]] link:https://cwe.mitre.org/data/definitions/284.html[CWE-284: Improper Access Control]
The software does not restrict or incorrectly restricts access to a resource
from an unauthorized actor.

. [[r2]] link:https://cwe.mitre.org/data/definitions/602.html[CWE-602: Client-Side Enforcement of Server-Side Security]
The software is composed of a server that relies on the client to implement a
mechanism that is intended to protect the server.

. [[r3]] link:https://cwe.mitre.org/data/definitions/749.html[CWE-749: Exposed Dangerous Method or Function]
The software provides an Applications Programming Interface (API) or similar
interface for interaction with external actors,
but the interface includes a dangerous method or function that is not properly
restricted.

. [[r4]] link:https://owasp.org/www-project-application-security-verification-standard/[OWASP-ASVS v4.0.1
Appendix C: Internet of Things Verification Requirements.(C.1)]
Verify that application layer debugging interfaces such *USB*, *UART*,
and other serial variants are disabled or protected by a complex password.

. [[r5]] link:https://owasp.org/www-project-application-security-verification-standard/[OWASP-ASVS v4.0.1
Appendix C: Internet of Things Verification Requirements.(C.4)]
Verify that on-chip debugging interfaces such as *JTAG* or *SWD* are disabled
or that an available protection mechanism is enabled and configured
appropriately.

. [[r6]] link:https://owasp.org/www-project-application-security-verification-standard/[OWASP-ASVS v4.0.1
V1.4 Access Control Architectural Requirements.(1.4.1)]
Verify that trusted enforcement points such as at access control gateways,
servers, and serverless functions enforce access controls.
Never enforce access controls on the client.

. [[r7]] link:https://owasp.org/www-project-application-security-verification-standard/[OWASP-ASVS v4.0.1
V4.1 General Access Control Design.(4.1.1)]
Verify that the application enforces access control rules on a trusted service
layer,
especially if client-side access control is present and could be bypassed.

. [[r8]] link:https://owasp.org/www-project-application-security-verification-standard/[OWASP-ASVS v4.0.1
V6.2 Algorithms.(6.2.5)]
Verify that known insecure block modes (i.e. *ECB*, etc.), padding modes
(i.e. **PKCS#1** v1.5, etc.), ciphers with small block sizes
(i.e. **Triple-DES**, *Blowfish*, etc.), and weak hashing algorithms
(i.e. *MD5*, *SHA1*, etc.) are not used unless required for backwards
compatibility.

. [[r9]] link:https://owasp.org/www-project-application-security-verification-standard/[OWASP-ASVS v4.0.1
V9.1 Communications Security Requirements.(9.1.3)]
Verify that old versions of *SSL* and *TLS* protocols, algorithms, ciphers, and
configuration are disabled,
such as *SSLv2*, *SSLv3*, or *TLS* 1.0 and *TLS* 1.1.
The latest version of *TLS* should be the preferred cipher suite.

. [[r10]] link:https://owasp.org/www-project-application-security-verification-standard/[OWASP-ASVS v4.0.1
V14.2 Dependency.(14.2.2)]
Verify that all unneeded features, documentation, samples, configurations are
removed,
such as sample applications, platform documentation, and default or example
users.

. [[r11]] link:https://owasp.org/www-project-application-security-verification-standard/[OWASP-ASVS v4.0.1
V14.5 Validate HTTP Request Header Requirements.(14.5.1)]
Verify that the application server only accepts the *HTTP* methods in use by
the application or *API*, including pre-flight *OPTIONS*.
