:slug: rules/153/
:category: authentication
:description: This requirement establishes the importance of offering secure out of band authenticators, such as push notifications, as secondary authentication factors.
:keywords: Out-of-band, Transaction, Band, Push notification, ASVS, CWE, Rules, Ethical Hacking, Pentesting
:rules: yes

= R153. Out of band transactions

== Requirement

The system must offer secure out of band authenticators, such as **push
notifications**.
Clear text options such as *SMS*, mailing or *PSTN* may be offered but should
not be the default option.

== Description

Secure out of band authenticators are physical devices that can communicate
with an authentication verifier over a secure secondary channel.
They serve as an additional security measure for identity assertion during
authentication processes or sensitive transactions.
Systems should offer at least one out of band authenticator and the default
option should not be a clear text one.

== References

. [[r1]] link:https://cwe.mitre.org/data/definitions/287.html[CWE-287: Improper Authentication]
When an actor claims to have a given identity,
the software does not prove or insufficiently proves that the claim is correct.

. [[r2]] link:https://cwe.mitre.org/data/definitions/319.html[CWE-319: Cleartext Transmission of Sensitive Information]
The software transmits sensitive or security-critical data in clear text in a
communication channel that can be sniffed by unauthorized actors.

. [[r3]] link:https://cwe.mitre.org/data/definitions/523.html[CWE-523: Unprotected Transport of Credentials]
Login pages do not use adequate measures to protect the user name and password
while they are in transit from the client to the server.

. [[r4]] link:https://owasp.org/www-project-top-ten/OWASP_Top_Ten_2017/Top_10-2017_A2-Broken_Authentication[OWASP Top 10 A2:2017-Broken Authentication].
Application functions related to authentication and session management are
often implemented incorrectly,
allowing attackers to compromise passwords, keys, or session tokens,
or to exploit other implementation flaws to assume other users’ identities
temporarily or permanently.

. [[r5]] link:https://owasp.org/www-project-application-security-verification-standard/[OWASP-ASVS v4.0.1
V2.7 Out of Band Verifier Requirements.(2.7.1)]
Verify that clear text out of band (NIST "restricted") authenticators,
such as *SMS* or *PSTN*, are not offered by default,
and stronger alternatives such as push notifications are offered first.

. [[r6]] link:https://owasp.org/www-project-application-security-verification-standard/[OWASP-ASVS v4.0.1
V2.7 Out of Band Verifier Requirements.(2.7.4)]
Verify that the out of band authenticator and verifier communicates over a
secure independent channel.
