:slug: rules/030/
:category: session
:description: This requirement establishes the importance of defining controls to manage object sessions securely to avoid reuse and replay attacks.
:keywords: Replay, Reuse, Session, ASVS, CWE, NIST, Rules, Ethical Hacking, Pentesting
:rules: yes

= R030. Avoid object reutilization

== Requirement

The system must guarantee that objects (session id, cookies, etc.)
used in the authentication process can not be reused (**replay resistance**).

== Description

In a system, it is necessary to prevent transmitted information from
being reused by an attacker to impersonate an authorized user
or server responses.
Thus, it is essential to verify the communications between the users and the
system,
avoiding in this way a replay of any request that could affect
the confidentiality, integrity and/or availability of the system.

== Implementation

In order to prevent this type of impersonation,
there are several options to considerate
depending on the context and implementation method.
Some good practices to avoid data reutilization
are listed below:

. **Cryptographic nonce**:
It consists of numbers that expire after their first use or after a small lapse
of time,
with which the authenticity of a message can be verified.
They are often randomized and used in authentication protocols
to ensure that past communications can not be reused.

. *Timestamping*:
In order to implement this method
there must be a clock synchronization between the client and the server.
The server will only accept messages with a date and an hour
within a tolerance range.
Thus, it minimizes the risk of potential attacks
by providing small time windows for exploitation.

. **Session Token**:
In this method, the server sends a *token* code
which is used by the client to transform a key
(e.g. applying hash functions to the key and token combination)
before sending it again to the server as part of the authentication process.
The server then processes this value, compares it with the initial token,
and rejects the request if they do not match.
Thus, an attacker cannot perform replay attacks
because the token sent by the server will be different
(token generation must be random).

. **Session Time-out**:
Session objects are invalidated when the user terminates a session or when
the user surpasses a certain time limit without posting new requests.

== Attacks

. Session hijacking
. Identity impersonation
. Man in the middle (*MitM*).
. Replay attack

== Attributes

. Layer: Application Layer
. Asset: Session management
. Scope: Authenticity
. Phase: Construction
. Type of Control: Recommendation

== Findings

* [inner]#link:/web/findings/015/[F015. Insecure authentication method]#

* [inner]#link:/web/findings/076/[F076. Insecure session management]#

== References

. [[r1]] link:http://capec.mitre.org/data/definitions/60.html[CAPEC-60: Reusing Session IDs (aka Session Replay)].
This attack targets the reuse of a valid session ID to spoof the target system
in order to gain privileges.

. [[r2]] link:https://cwe.mitre.org/data/definitions/287.html[CWE-287: Improper Authentication].
When an actor claims to have a given identity,
the software does not prove or insufficiently proves that the claim is correct.

. [[r3]] link:https://cwe.mitre.org/data/definitions/294.html[CWE-294: Authentication Bypass by Capture-replay].
A capture-replay flaw exists when the design of the software makes it possible
for a malicious user to sniff network traffic and bypass authentication by
replaying it to the server in question to the same effect as the original
message (or with minor changes).

. [[r4]] link:https://cwe.mitre.org/data/definitions/308.html[CWE-308: Use of Single-factor Authentication].
The use of single-factor authentication can lead to unnecessary risk of
compromise when compared with the benefits of a dual-factor authentication
scheme.

. [[r5]] link:https://cwe.mitre.org/data/definitions/345.html[CWE-345: Insufficient Verification of Data Authenticity]
The software does not sufficiently verify the origin or authenticity of data,
in a way that causes it to accept invalid data.

. [[r6]] link:http://www.ietf.org/rfc/rfc2617.txt[HTTP Authentication: Basic and Digest Access Authentication].

. [[r7]] link:https://pages.nist.gov/800-63-3/sp800-63b.html[NIST 800-63B 5.2.8 Replay Resistance]
An authentication process resists replay attacks if it is impractical to
achieve a successful authentication by recording and replaying a previous
authentication message.

. [[r8]] link:https://pages.nist.gov/800-63-3/sp800-63b.html[NIST 800-63B 7.1 Session Bindings]
Secrets used for session binding SHALL be generated by the session host during
an interaction,
typically immediately following authentication.

. [[r9]] link:https://owasp.org/www-project-top-ten/OWASP_Top_Ten_2017/Top_10-2017_A2-Broken_Authentication[OWASP Top 10 A2:2017-Broken Authentication].
Application functions related to authentication and session management are
often implemented incorrectly,
allowing attackers to compromise passwords, keys, or session tokens,
or to exploit other implementation flaws to assume other users’ identities
temporarily or permanently.

. [[r10]] link:https://owasp.org/www-project-application-security-verification-standard/[OWASP-ASVS v4.0.1
V2.2 General Authenticator Requirements.(2.2.6)]
Verify replay resistance through the mandated use of *OTP* devices,
cryptographic authenticators, or lookup codes.

. [[r11]] link:https://owasp.org/www-project-application-security-verification-standard/[OWASP-ASVS v4.0.1
V3.2 Session Binding Requirements.(3.2.1)]
Verify the application generates a new session token on user authentication.
