:slug: rules/030/
:category: session
:description: This document contains the details of the security requirements related to the definition and management of sessions and session variables the organization. This requirement establishes the importance of defining controls to manage object sessions securely to avoid common attacks.
:keywords: Requirement, Security, Session, Authentication, Objects, Control
:rules: yes

= REQ.030 Avoid object reutilization

== Requirement

System must control that objects
(session id, cookies, etc)
used in authentication process can't be reused.

== Description

In a system it is necessary to control if the transmitted information
is being reused by an attacker to impersonate an authorized user
or the server response, so it is essential to verify the communications
between the users and the system, avoiding in this way
the reinjection of any type of information
that affects the confidentiality and/or availability of the same.

== Implementation

In order to prevent this type of impersonation
there are several options to considerate
depending on the context and implementation method.
Some good practices to avoid data reutilization
are listed below:

. *Cryptographic nonce*:
It consists of numbers that expire after their first use
or after a small lapse of time, with which you can verify
the authenticity of a message.
They are often randomized and used in authentication protocols
to ensure that past communications can not be reused.

. *Timestamping*:
In order to implement this method
there must be a clock synchronization between client and server.
Server will only accept messages with date and hour
within a tolerance range.
Thus, it minimizes the risk of potential attacks
by providing a small time windows for exploitation.

. Session Token :
In this method, the server sends a +token+ code
which is used by the client to transform the key
(e.g applying hash functions to key and token combination)
before sending it again to the server.
This value is compared with the client side authentication.
Thus, an attacker cannot perform replay attacks
because the token sent by the server will be different
(token generation must be random).

. Session Time-out:
Allow users to exit the application and clean session data,
say, when an user exits the application his session
must be invalidated in client and server side.

== Attacks

. Session hijacking
. Identity impersonation
. Man in the middle (+MiM+).
. Replay attack

== Attributes

. Layer: Application Layer
. Asset: Session management
. Scope: Authenticity
. Phase: Construction
. Type of Control: Recommendation


== References

. [[r1]] link:http://capec.mitre.org/data/definitions/60.html[CAPEC-60: Reusing Session IDs (aka Session Replay)].

. [[r2]] link:https://cwe.mitre.org/data/definitions/287.html[CWE-287: Improper Authentication].

. [[r3]] link:https://cwe.mitre.org/data/definitions/294.html[CWE-294: Authentication Bypass by Capture-replay].

. [[r4]] link:http://www.ietf.org/rfc/rfc2617.txt[HTTP Authentication: Basic and Digest Access Authentication].

. [[r5]] link:https://www.owasp.org/index.php/ASVS_V2_Authentication[+OWASP-ASVS v3.1-2.12+]
Verify that all authentication decisions can be logged,
without storing sensitive session identifiers or passwords.
This should include requests with relevant metadata
needed for security investigations.

. [[r6]] link:https://www.owasp.org/index.php/ASVS_V3_Session_Management[+OWASP-ASVS v3.1-3.7+]
Verify that all successful authentication and re-authentication
generates a new session and session id.
