:slug: rules/363/
:category: system
:description: This requirement establishes the importance of synchronizing system clocks.
:keywords: Synchronize, System, Clock, Time, Settings, PCI DSS, Security, Requirement, Rules, Ethical Hacking, Pentesting
:rules: yes

= R363. Synchronize system clocks

== Requirement

Critical systems must have synchronized clocks whose configuration is protected
and comes from industry-accepted sources.

== Description

Systems must properly record exceptional and security events in protected logs.
This allows administrators to find bugs and makes it easier for forensics teams
to determine how a system was compromised.
However, if clocks are not properly synchronized,
it can be very difficult to compare log files from different systems in order
to establish the event sequence that led the security incident.

== References

. [[r1]] link:https://www.pcisecuritystandards.org/documents/PCI_DSS_v3-2-1.pdf[PCI DSS v3.2.1 - Requirement 10.4.1]
Critical systems have the correct and consistent time.

. [[r2]] link:https://www.pcisecuritystandards.org/documents/PCI_DSS_v3-2-1.pdf[PCI DSS v3.2.1 - Requirement 10.4.2]
Time data is protected.

. [[r3]] link:https://www.pcisecuritystandards.org/documents/PCI_DSS_v3-2-1.pdf[PCI DSS v3.2.1 - Requirement 10.4.3]
Time settings are received from industry-accepted time sources.
