:slug: defends/php/establecer-opciones-seguras/
:category: php
:description: Nuestros ethical hackers explican cómo evitar vulnerabilidades de seguridad mediante la programación segura en PHP al establecer opciones seguras por defecto en estructuras condicionales. Para mejorar la seguridad de la aplicación es necesario considerar todos los posibles escenarios.
:keywords:   PHP, Opciones, Seguras, Condicionales, Seguridad, Default
:defends: yes

= Establecer Opciones Seguras por Defecto

== Necesidad

Usar estructuras condicionales contemplando todos los escenarios posibles.

== Contexto

A continuación se describen las circunstancias
bajo las cuales la siguiente solución tiene sentido:

. Se dispone de una aplicación +PHP+
conforme con la especificación del lenguaje +PHP 4 o+ superior.

. La aplicación utiliza estructuras condicionales,
tales como +if - then+ o +switch - case+.

. No se han definido casos por defecto para los condicionales.

== Solución

Cuando se desarrollan aplicaciones,
es muy importante pensar en la seguridad general de las mismas.
Existen muchos criterios de programación segura
que se pueden aplicar para evitar ataques malintencionados.
La validación de entradas es uno de ellos,
y constituye un proceso esencial para crear
aplicaciones seguras.
Gracias a ella que es posible proteger el sistema
contra ataques comunes de inyección de código y similares.

Las estructuras condicionales por lo general se utilizan
para definir la respuesta del sistema ante una entrada del usuario.
En otras palabras, permite la toma de decisiones.
La definición de opciones por defecto en condicionales
hace parte de la validación de entradas.
Esto es debido a que permite abarcar todos los casos,
terminando la aplicación en un escenario seguro y controlado
ante una entrada inválida.

Esta validación es aplicable a cualquier lenguaje de programación.
Para el caso de +PHP+ podemos mejorar la seguridad de nuestra aplicación,
al agregar escenarios por defecto para cada uno de los casos posibles.
Para ello utilizamos los condicionales propios del lenguaje.
Esto lo realizamos definiendo siguientes criterios <<r1, ^[1]^>>:

* Cada sentencia +if+ debe tener su respectiva sentencia +else+.

* Cada estructura condicional +switch - case+
debe poseer su respectivo caso por defecto +default+.

. A continuación presentamos un ejemplo del uso adecuado
de la sentencia +if - then - else+  en +PHP+:
+
.ifexample.php
[source, php, linenums]
----
if (condition){
  body-code
}

else {
  else-code
}
----
+
Dentro del bloque de la sentencia +else+,
colocaremos el procedimiento a realizar en caso de no cumplirse la condición.
Es decir, definimos una opción por defecto segura y controlada
para terminar el condicional.

Para el caso de la sentencia +switch+,
realizamos un procedimiento similar.
Para ello seguimos los siguientes pasos:

. Se definen los escenarios contemplados por la aplicación.
+
.swtichexample.php
[source, php, linenums]
----
switch (expression) {

case condition_1:
      code_block_1;
      break;

case condition_2:
     code_block_2;
     break;

...

case condition_n:
     code_block_n;
     break;
----
+
Nótese el uso de la sentencia +break+.
Esta es utilizada para finalizar las instrucciones ejecutadas
en un determinado caso.

. En este caso el escenario por defecto es descrito por el caso +default+.
Aquí es donde debemos colocar el código que se ejecutará
en caso de que ninguna de las condiciones
contempladas por la aplicación se cumpla.
+
[source, php, linenums]
----
default:
     code_block_default;
}
----

== Referencias

. [[r1]] link:http://php.net/manual/en/language.control-structures.php[Manual de PHP: Estructuras de control].

. [[r2]] link:../../../rules/161/[REQ.161 Opciones por defecto seguras].
