:slug: rules/075/
:category: rules
:description: En el presente documento se detallan los requerimientos de seguridad relacionados con las bitácoras que registran eventos relevantes. En este requerimiento se establece la importancia de registrar todos los eventos excepcionales en una o varias bitácoras.
:keywords: Requerimiento, Seguridad, Bitácoras, Registrar, Eventos, Información.
:rules: yes

= REQ.075 Registrar eventos en bitácoras

== Requisito

El sistema debe registrar todos los eventos excepcionales
y de seguridad en bitácoras.

== Descripción

La organización debe registrar apropiadamente los eventos excepcionales
y de seguridad en bitácoras debidamente protegidas (confidencialidad),
pensando que un evento de este tipo
no debe mostrar información confidencial o detallada
del problema en mensajes de error
para prevenir el uso de esa información
de parte de un atacante o usuario malintencionado.
Registrar eventos permiten que las páginas de error
muestren mensajes genéricos simples,
alertando a los usuarios finales que un error ha ocurrido,
con alguna opción de contactar a soporte.
El detalle de cómo atender estos problemas
debe mantenerse seguramente almacenado
en un almacenamiento de bitácoras previamente definido.
Cuando un evento de estos tipos no es apropiadamente registrado
un comportamiento malicioso puede probarse difícil de detectarse
o se puede llegar a entorpecer un análisis forense
en caso tal que un ataque sea exitoso.

== Implementación

. Utilizar un mecanismo de registro en bitácoras centralizado
que soporte varios niveles de detalle.
Asegúrese que todos los eventos
relacionados a éxitos y fallos sean registrados.

. Asegúrese que el nivel de registro en bitácoras
sea configurado apropiadamente para los ambientes de producción.
Debe registrarse suficiente información
como para permitir a un administrador de sistema detectar ataques,
diagnosticar errores y recuperarse de ataques.
Al mismo tiempo registrar demasiada información
puede causar los mismos problemas (+CWE-779+).

== Ataques

. En el caso que la información crítica de seguridad no sea registrada,
un atacante puede realizar un ataque
que no dejará rastro durante un análisis forense,
por lo tanto descubrir la causa del problema
o el origen de uno o varios ataques puede probar ser muy difícil o imposible.

== Atributos

* Capa: Capa de Aplicación
* Activo: Bitácoras
* Alcance: Responsabilidad
* Fase: Operación
* Tipo de Control: Procedimiento

== Referencias

. [[r1]] link:https://www.owasp.org/index.php/Codereview-Error-Handling[OWASP - CodeReview-Error-Handling].

. [[r2]] link:https://www.owasp.org/index.php/OWASP_Proactive_Controls[OWASP - Proactive Controls].

. [[r3]] link:https://www.owasp.org/index.php/Exception_Handling#Logging_Exception_Details[OWASP - Exception Handling].

. [[r4]] link:https://cwe.mitre.org/data/definitions/778.html[CWE - Insufficient logging].

. [[r5]] link:https://www.law.cornell.edu/cfr/text/45/164.312[+HIPAA Security Rules+ 164.312(b):]
Auditorías de Control: Implementar hardware, software
y/o mecanismos procedimentales que registren y examinen la actividad
en sistemas de información que contienen o utilizan información sensible
protegida electrónicamente.

. [[r6]] link:https://www.owasp.org/index.php/ASVS_V7_Cryptography[+OWASP-ASVS v3.1-8.3+]
Verificar que los controles de registro de seguridad
registren eventos exitosos y fallidos
identificables como relevantes para la seguridad del sistema.
