:slug: rules/075/
:category: rules
:description: En el presente documento se detallan los requerimientos de seguridad relacionados con las bitácoras que registran eventos relevantes. En este requerimiento se establece la importancia de registrar todos los eventos excepcionales en una o varias bitácoras.
:keywords: Requerimiento, Seguridad, Bitácoras, Registrar, Eventos, Información.
:rules: yes

= REQ.075 Registrar eventos en bitácoras

== Requisito

El sistema debe registrar todos los eventos excepcionales
y de seguridad en bitácoras.

== Descripción

La organización debe registrar apropiadamente los eventos excepcionales
y de seguridad en bitácoras debidamente protegidas (confidencialidad),
pensando que un evento de este tipo
no debe mostrar información confidencial o detallada
del problema en mensajes de error
para prevenir el uso de esa información
de parte de un atacante o usuario malintencionado.
Registrar eventos permiten que las páginas de error
muestren mensajes genéricos simple,
alertando a los usuarios finales que un error a ocurrido,
con alguna opción de contactar a soporte.
El detalle de cómo atender estos problemas
debe mantenerse seguramente almacenado
en un almacenamiento de bitácoras previamente definido.
Cuando un evento de estos tipos no es apropiadamente registrado
un comportamiento malicioso puede probarse difícil de detectarse
o se puede llegar a entorpecer un análisis forense
en caso tal que un ataque sea exitoso.

== Implementación

. Utilizar un mecanismo de registro en bitácoras centralizado
que soporte varios niveles de detalle.
Asegúrese que todos los eventos
relacionados a éxitos y fallos sean registrados.

. Asegúrese que el nivel de registro en bitácoras
sea configurado apropiadamente para los ambientes de producción.
Debe registrarse suficiente información
como para permitir a un administrador de sistema detectar ataques,
diagnosticar errores y recuperarse de ataques.
Al mismo tiempo registrar demasiada información
puede causar los mismos problemas (+CWE-779+).

== Soluciones

. +COBOL+ link:../../defends/cobol/registrar-excepciones-ile/[Registrar Excepciones ILE].
. +COBOL+ link:../../defends/cobol/registrar-excepciones-opm/[Registrar Excepciones OPM].
. +Exchange 2010+ link:../../defends/exchange/activar-bitacoras-smtp/[Activar Bitácoras de Conectores SMTP].
. +Programación+ link:../../defends/programacion/bitacoras-cond/[Generar Bitácoras Condicionales].
. +Scala+ link:../../defends/scala/registrar-eventos-bitacoras/[Registrar Eventos en Bitácoras].
. +SharePoint 2010+ link:../../defends/sharepoint/registro-bitacoras/[Configurar Registro en Bitácoras].

== Ataques

. En el caso que la información crítica de seguridad no sea registrada,
un atacante puede realizar un ataque
que no dejará rastro durante un análisis forense,
por lo tanto descubrir la causa del problema
o el origen de uno o varios ataques puede probar ser muy difícil o imposible.

== Atributos)

* Capa: Capa de Aplicación
* Activo: Bitácoras
* Alcance: Responsabilidad
* Fase: Operación
* Tipo de Control: Procedimiento

== Referencias

. link:https://www.owasp.org/index.php/Codereview-Error-Handling[OWASP - CodeReview-Error-Handling].
. link:https://www.owasp.org/index.php/OWASP_Proactive_Controls[OWASP - Proactive Controls].
. link:https://www.owasp.org/index.php/Exception_Handling#Logging_Exception_Details[OWASP - Exception Handling].
. link:https://cwe.mitre.org/data/definitions/778.html[CWE - Insufficient logging].
