:slug: defends/programacion/crear-bitacoras-cond/
:category: programacion
:description: Nuestros ethical hackers explican como evitar vulnerabilidades de seguridad mediante la programacion segura al generar bitácoras condicionales. Las bitácoras permiten registrar eventos relevantes facilitando el seguimiento de la información afectada en caso de un ataque informático.
:keywords: Programación, Bitácoras, Condicionales, Registro, Seguridad, Eventos.
:defends: yes

= Crear Bitácoras Condicionales

== Necesidad

Generar bitácoras condicionales desde una aplicación.

== Contexto

A continuación se describe las circunstancias
bajo las cuales la siguiente solución tiene sentido:

. Una aplicación presenta problemas de rendimiento.

. Se requieren generar bitácoras con mayor nivel de detalle
según el ambiente donde está desplegado.

== Solución

Las bitácoras son registros que guardan
eventos importantes que afectan a la aplicación.
Los eventos registrados pueden cambiar
dependiendo del ambiente en que ésta se encuentre.
Una bitácora normalmente almacena la fecha, horas,
minutos, segundos, milisegundos y zona horaria
del momento en que se presenta un evento,
así como la severidad de dicho evento.
Esto permite mantener un seguimiento continuo de la aplicación
en los distintos ambientes,
permitiendo rastrear posibles ataques
o accesos no autorizados.
A continuación presentamos una guía
acerca de cómo definir el nivel de las bitácoras
dependiendo del ambiente en el cual se esté trabajando:

. Las aplicaciones dependiendo del ambiente donde están desplegadas
y el estado en su ciclo de vida,
requieren diferente nivel de detalle en las bitácoras que generan:

* *Ambiente y estado de producción:*
El nivel de detalle de las bitácoras se debe limitar a condiciones anormales.

* *Ambientes y estados de desarrollo y pruebas:*
El nivel de detalle de las bitácoras puede estar en su máximo nivel.

. Estos principios básicos para la configuración
del nivel de detalle de las bitácoras de una aplicación
se basan en las siguientes premisas:

* Las operaciones de entrada y salida son altamente costosas,
pues requieren acceso a dispositivos.
Debido a ello se colocan a los hilos de la aplicación en estado suspendido
hasta que finalice la operación.

* Las bitácoras de un sistema en producción deben facilitar la auditoria,
tanto desde la perspectiva de la longitud como la relevancia de las bitácoras.

. Considerando entonces los aspectos anteriores, la necesidad y el contexto,
se recomienda siempre disponer de un mecanismo
que permita la generación de bitácoras condicionales.
Esto se realiza para que durante el despliegue a producción de la aplicación
se parametrice el nivel de detalle mínimo.
Lo anterior permite optimizar la relevancia y el rendimiento,
y pueda seguirse manteniendo durante el desarrollo
y las pruebas el nivel de detalle máximo para depurar la aplicación.

. A continuación se relacionan algunas herramientas
que pueden utilizarse para generar bitácoras con detalle condicional:

* +Log4J+ <<r1, ^[1]^>>.
* +Log4Net+ <<r2, ^[2]^>>.
* +Syslog+ <<r3, ^[3]^>>.

== Referencias

. [[r1]] link:http://logging.apache.org/log4j/1.2/index.html[Apache Log4J].
. [[r2]] link:http://logging.apache.org/log4net/index.html[Apache Log4Net].
. [[r3]] link:https://linux.die.net/man/3/syslog[SYSLOG].
. [[r4]] link:../../../rules/076/[REQ.076 Registrar niveles de severidad de eventos].
