:slug: products/rules/list/044/
:category: files
:description: This requirement establishes the importance of defining an explicit Character set for all system files dynamically generated.
:keywords: Character Set, Encoding, Files, ASVS, CWE, Dynamic, Rules, Ethical Hacking, Pentesting
:rules: yes

= R044. Define a explicit charset

== Requirement

All system files generated dynamically
must have a explicitly defined character set (*charset*).

== References

. [[r1]] link:http://capec.mitre.org/data/definitions/242.html[CAPEC-242: Code Injection].
An adversary exploits a weakness in input validation on the target to inject
new code into that which is currently executing.

. [[r2]] link:https://cwe.mitre.org/data/definitions/116.html[CWE-116: Improper Encoding or Escaping of Output].
The product does not validate or incorrectly validates input that can affect
the control flow or data flow of a program.

. [[r3]] link:https://cwe.mitre.org/data/definitions/173.html[CWE-173: Improper Handling of Alternate Encoding].
The software does not properly handle when an input uses an alternate encoding
that is valid for the control sphere to which the input is being sent.

. [[r4]] link:https://owasp.org/www-project-application-security-verification-standard/[OWASP-ASVS v4.0.1
V5.3 Output encoding and Injection Prevention Requirements.(5.3.1)]
Verify that output encoding is relevant for the interpreter and context
required.
For example, use encoders specifically for *HTML* values, *HTML* attributes,
JavaScript, URL Parameters, *HTTP* headers, *SMTP*, and others as the context
requires, especially from untrusted inputs
(e.g., names with Unicode or apostrophes, such as ねこ or O'Hara).

. [[r5]] link:https://owasp.org/www-project-application-security-verification-standard/[OWASP-ASVS v4.0.1
V14.4 HTTP Security Headers Requirements.(14.4.1)]
Verify that every *HTTP* response contains a content type header specifying a
safe character set (e.g., *UTF-8*, **ISO 8859-1**).
