:slug: careers/technical-challenges/
:category: careers
:description: The main goal of the following page is to inform potential talents and people interested in working with us about our selection process. The technical challenges stage intends to assess the competences of the candidate through programming and hacking exercises.
:keywords: Fluid Attacks, Careers, Selection, Process, Technical Challenges, Training.
//:toc: yes

= Technical Challenges

Because this stage parallels the other stages of the process,
you can work on this at the same time you are completing previous stages.
The more progress you make on it now,
the greater the probability that you may be evaluated before other participants
who finish their work in a linear fashion.

This stage can also function as a kind of lifesaver for you.
If you have not yet graduated, perhaps have no previous work experience,
or maybe got a low score on the knowledge test,
but were able to successfully finish this stage, you have the most valuable
competence of all: The ability to learn new things on the fly and apply them to
solve real problems.
This, along with a good personality and strong
[inner]#link:../../values[values]#, mean more to us and our customers than
anything else.

== 1. Philosophy

In this stage, we want you to demonstrate, through practical exercises,
your technical skills by solving problems similar to the ones you will face in
your work with +Fluid Attacks+.

The technical challenges are divided into
+vbd-hacking+, +ctf-hacking+, and +programming+.
With the first,
you demonstrate your skill to bypass security controls.
With the second,
you demonstrate your adaptation skill when it comes to problem-solving
in unknown environments.
With the third,
you demonstrate your proficiency and speed in understanding source code.

By solving challenges we:

. Promote the solution of unresolved challenges.

. Encourage self-directed and independent learning.

By uploading your solutions to +GitLab+, you will be able to:

. Use the +GitLab+ infrastructure to analyze
your efficiency and work quality as you adapt to the process.

. Familiarize yourself with the tools
(+Git+, +AsciiDoc+, +Python+, +Gherkin+, etc) and
concepts (automation, unit tests, continuous integration, +linting+, etc.) that
you will use in your daily work with +Fluid Attacks+.

. Allow the community and the team to view your results.

== 2. Objectives

. Solve +3+ unique +programming+ challenges.

. Solve +3+ unique +ctf-hacking+ challenges.

. Solve +3+ unique +vbd-hacking+ challenges.

== 3. Recommendations

. When solving +programming+ challenges,
we recommend [inner]#link:https://www.codeabbey.com/[Codeabbey]#.
Also, we suggest using a language that is not widely used.

. When solving +ctf-hacking+ challenges,
we recommend [inner]#link:https://www.root-me.org/?lang=en[Root Me]#.

. After solving a challenge, immediately submit your answer.
Do not save your answers to send later as a larger group submission.
When you send them individually and immediately you will receive feedback
that will tell you what,
if anything, you did incorrectly and may help you with upcoming questions.

== 4. Stage steps

To successfully finish this stage, you must:

. Register on +GitLab+ using your personal email
and the username of your choice.
Your username must not exceed *12* characters in length
and only contain lowercase letters and numbers.

. Join our link:https://community.fluidattacks.com/[Forum],
where you can interact with +Fluid Attacks+ personnel and other candidates,
who are working in the same stage that you are,
to discuss questions or issues you may have.

. Request permission to access the +Git Training+ repository by filling out this
[inner]#link:https://fluidattacks.com/forms/access[form]#.

. In the +Repo Access Message+ field, paste the following message:
+
[quote]
____________________________________________________________________
I have read and understood all documentation pertaining to technical challenges,
I agree to all of the terms and
therefore request access to the +git+ +training+ repository
with my +GitLab+ username.
____________________________________________________________________

. Complete +three (3)+ +programming+ challenges

. Complete +three (3)+ +ctf-hacking+ challenges

. Request permission to access the +Writeups+ repository by filling out this
[inner]#link:https://fluidattacks.com/forms/access[form]#.
This time around, the Repo Access Message field should have the following:
Request developer permissions to the +Writeups+ repository through this
.
+
This time around, the +Repo Access Message+ field should have the following:
+
[quote]
____________________________________________________________________
I have completed three (3) +programming+ and three (3) +ctf-hacking+
unique challenges
in the training repo and
therefore request access to the +git+ +writeups+ repository
with my +GitLab+ username.
____________________________________________________________________

. Complete +three (3)+ +vbd-hacking+ challenges in the writeups repository.

== 5. Conditions

The challenge stage ends under any of the following conditions:

. You have met all link:#objectives[objectives] and
sent an +email+ with the links to your solutions in the +master+ branch.
. If there has been no activity
(+push+ to the +git+ repos) within 14 calendar days.
. If you clearly state,
via email,
that you are no longer interested in continuing the process.
. If you present someone else’s complete or
partial solutions as your own (plagiarism).
. If you solve a challenge with the help of others.

In all cases, the email address for these steps is: careers@autonomicmind.com

If you were removed from the challenge due to circumstances 1, 2 or 3,
you may apply again, at any time, and start the process over by clicking
[inner]#link:../../../../forms/aplicacion[here]#
If your removal was a result of circumstance 4 or 5
you are not eligible for any future retry.

== 6. Questions

* Before you email us with a question,
please re-read this document carefully,
and pay particular attention to our link:../faq/[Frequently Asked Questions].

* You can contact us with your issues or concerns,
and any questions you may have in our
link:https://community.fluidattacks.com/[Forum].

== 7. Property

* The proprietary rights of all content
in the repositories are defined in the files:

** link:https://gitlab.com/fluidattacks/writeups/blob/master/COPYRIGHT.txt[writeups COPYRIGHT].
** link:https://gitlab.com/autonomicmind/training/blob/master/COPYRIGHT.txt[training COPYRIGHT].

* The license and privileges that users of the repositories have
are defined in the files:

** link:https://gitlab.com/fluidattacks/writeups/blob/master/LICENSE.txt[writeups LICENSE].
** link:https://gitlab.com/autonomicmind/training/blob/master/LICENSE.txt[training LICENSE].

* Carrying out a +merge request+ implies the transfer of copyrights.
Therefore, all information contained herein may be used
by +Fluid Attacks+ for any commercial purpose,
always preserving the moral rights of their authors.

== 8. Plagiarism

Making solutions easily available to everyone
presents an opportunity for plagiarism.
How do we show the solution and avoid plagiarism at the same time?
Plagiarism is not a technical problem.
Plagiarism is copying another's work and then presenting it as your own.

To discourage plagiarism we require that the author of each algorithm
is clearly stated in a centralized place.
This provides clear author attribution
and allows for public scrutiny in case of plagiarism.

In other words, the current model avoids plagiarism
through total transparency.

+Fluid Attacks+ applies algorithmic similarity detection techniques
to all solutions submitted. We use:

* link:https://theory.stanford.edu/~aiken/moss/[MOSS]
* link:https://en.wikipedia.org/wiki/Plagiarism_detection[Plagiarism Detection Theory]
* link:https://www.plagaware.com/[PlagAware]
* link:https://www.safe-corp.com/products_codematch.htm[Code Match]

== 9. Submission

Now that you know all the rules
and have a general understanding
of why these challenges are important,
you can proceed to the [inner]#link:https://gitlab.com/fluidattacks/writeups/wikis/Submission[Submission guide]#
and start posting your solutions. Good luck!

== 10. keywords

. +ToE+: link:https://docs.marklogic.com/6.0/guide/cc/toe[Target Of Evaluation]
. +VBD+: Vulnerable by design
. +CTF+: link:https://ctftime.org/ctf-wtf/[Capture The Flag]
