:slug: rules/224/
:category: numbers
:description: This document contains the details of the security requirements related to the definition and management of random number in the organization. This requirement establishes the importance of using secure cryptographic mechanisms to generate random numbers used in data encryption.
:keywords: Requirement, Security, Logical, Network, Segment, Areas
:rules: yes

= REQ.224 Use secure cryptographic mechanisms

== Requirement

System must use the most secure cryptographic mechanism
provided by the platform (e.g +java.security.SecureRandom+)
for random number generation used in critical processes
(e.g +ID generation, code mapping, cryptographic keys+)

== References

. [[r1]] link:https://www.owasp.org/index.php/ASVS_V1_Architecture[+OWASP-ASVS v3.1-1.12+]
There is an explicit policy for how cryptographic keys (if any) are managed,
and the lifecycle of cryptographic keys is enforced.
Ideally, follow a key management standard such as +NIST SP 800-57+.

. [[r2]] link:https://www.owasp.org/index.php/ASVS_V7_Cryptography[+OWASP-ASVS v3.1-7.6+]
Verify that all random numbers, random file names, random GUIDs,
and random strings are generated using the cryptographic module’s
approved random number generator
when these random values are intended to be not guessable by an attacker.

. [[r3]] link:https://www.owasp.org/index.php/ASVS_V7_Cryptography[+OWASP-ASVS v3.1-7.15+]
Verify that random numbers are created with proper entropy
even when the application is under heavy load,
or that the application degrades gracefully in such circumstances.

. [[r4]] link:https://nvd.nist.gov/800-53/Rev4/control/IA-7[+NIST+ 800-53 IA-7]
Cryptographic module authentication:
The information system implements mechanisms for authentication
to a cryptographic module that meet the requirements
of applicable federal laws, Executive Orders, directives, policies,
regulations, standards, and guidance for such authentication.
