:slug: rules/199/
:category: rules
:description: En el presente documento se detallan los requerimientos de seguridad relacionados a la gestion adecuada de dispositivos foraneos de la organizacion. En este requerimiento, se recomienda que la organizacion determine quienes y en qué momento podrán acceder con dichos dispositivos.
:keywords: Sistema, Organización, Servicios, Foráneos, Dispositivos, Acceder.
:rules: yes

= REQ.199 Determinar acceso con dispositivos foráneos

== Requisito

La organización debe determinar
qué servicios, en qué momento
y quién puede acceder con dispositivos foráneos.

== Referencias

. [[r1]] link:https://www.law.cornell.edu/cfr/text/45/164.310[`HIPAA Security Rules` 164.310(d)(1):]
Control de dispositivos y medios: Implementar políticas y procedimientos
para la recepción y remoción de hardware y medios electrónicos
que contengan información sensible dentro y fuera de las instalaciones,
y el movimiento de dichos objetos dentro de las instalaciones.

. [[r2]] link:https://nvd.nist.gov/800-53/Rev4/control/IA-3[`NIST` 800-53 IA-3]
Identificación y autenticación en dispositivos:
El sistema de información únicamente identifica y autentica
a los dispositivos especificados por la organización
a la hora de establecer una conexión a una red local y/o remota.
