:slug: careers/immersion/
:category: careers
:description: The main goal of the following page is to inform potential talents and people interested in working with us about our selection process. The immersion stage is a paid training period focused on acquiring the necessary knowledge and skills to solve everyday tasks.
:keywords: Fluid Attacks, Careers, Immersion, Selection, Process, Training
//:toc: yes

= Immersion

Welcome to *Immersion*.
At this point,
you have already been selected from among more than +6000+ candidates,
and you have only a few more steps to go.
*Immersion* is an intensive self-training involving a variety
of assignments in +programming+ and +hacking+.
*Immersion* is funded by +Fluid Attacks+.

== 1. Philosophy

Your goal in this stage is to reach the highest
levels of technical proficiency before you execute real pentests
on financial and telecommunications systems.
This stage also serves to substantiate your interpersonal
communication and teamwork skills.

Because this is a lengthy and time-consuming process,
+Fluid Attacks+,
regardless of your progress in points and ranking,
provides monetary compensation for the time you invest
in completing the assignments.

== 2. Objectives

. Solve +30+ unique +programming+ challenges.
. Solve +30+ unique +ctf-hacking+ challenges.
. Solve +30+ unique +vbd-hacking+ challenges.
. Publish +3+ blog articles.
. Finish +3+ training projects.

== 3. Terms

. All [button]#link:../technical-challenges/#terms[terms]#
from the technical challenge stage apply.
. Use the assigned tool in automatic mode
to report all your work time.
. Your training day begins at *7:00 AM*
in +Fluid Attacks+ office.
. By *6:00 PM* of each training day,
you must have sent at least one accepted-into-master +MR+,
or a standard progress report if the +MR+ has been rejected.
. You may then continue training and reporting your work time,
done outside of the office,
from a location of your choice,
as long as you comply with the 2 previous rules.
. If for some exceptional reason,
you are not able to complete the training in person,
a weekly training schedule to work remotely,
will be established.
. Training must always be done using your own personal laptop.
. Your daily dedication to your work
will be evaluated based on a reference time of *48 hours/week*.
. +Fluid Attacks+ expectation is that you will be present in person,
at the company's office, each business day.
. If for personal or health reasons,
you are unable to come to work in person,
you will not be allowed to complete any challenges or report any training time
for that day.
. On the third business day of each week,
you are required to work at your maximum level of productivity and commitment.

== 4. Criteria

. For the challenges,
use the same [button]#link:../technical-challenges/#criteria[criteria]#
listed in the challenge stage.
. For the articles,
use the same criteria defined in the [button]#link:../../style/[style guide]#.

== 5. Cycles

. Training is done in weekly cycles.
. Initially, you are offered *one cycle* of training.
. At the end of each cycle, one of the following will happen:
.. You do not receive any notification,
which means the training cycle continues for *one more week*.
.. You receive a notification
that we do not want to continue with another cycle,
which means we are terminating the training process.
.. You receive a formal notification
that we do not want to continue with another training
cycle because we want you to advance to the next stage.
. Usually *12 to 36 cycles* are required to finish this stage.
.. This is an estimate,
it depends entirely on your productivity,
perseverance, and performance.

== 6. Training sequence

Hacking, programming challenges, and blog entries
must be completed in the following order:

. Complete *five (5)* challenge cycles.

.. A challenge cycle consists of the following steps.
Remember, these steps must be completed in the order listed below.

... *One (1)* approved +MR+ solving a +programming+ challenge in the
link:https://gitlab.com/autonomicmind/training/[training repository].

... *One (1)* approved +MR+ solving a +ctf-hacking+ challenge in the
link:https://gitlab.com/autonomicmind/training/[training repository].

... *One (1)* approved +MR+ solving a +vbd-hacking+ challenge in the
link:https://gitlab.com/fluidattacks/writeups[writeups repository].
An +MR+ is considered approved when it’s merged to the +master+ branch
of each repository.

.. Do *NOT* do the following:
+
* Do *NOT* send consecutive +MR+ solving challenges of the same type.
* Do *NOT* change the cycle order in any way.
* Do *NOT* skip any challenge type in the cycle.

. After you have completed *five (5)* challenge cycles
write *one (1)* article for the blog by sending an +MR+
to the link:https://gitlab.com/fluidattacks/web[web repository].

. Repeat the previous steps until you complete the
[button]#link:../immersion/#objectives[objectives]#.

. Read carefully the programming challenge requirements below:

.. Each programming challenge completed
must be *one (1)* score point greater than the previous one.

.. If no challenges with greater score exist,
start again solving a challenge of lower score.

.. If you reach a point where the need to obtain a higher score
makes it hard for you to advance:

... Read about the topics you haven't mastered yet
(graphs, trees, modular arithmetic, etc).

... Try different approaches,
(Recursion, Heuristics, Dynamic Programming, Greedy, Divide and Conquer, etc).

... *Persevere!* We are interested in disciplined programmers.

.. If you reach a point where you definitely cannot advance:

... Remember that the process is more important than the goal.

... Start again solving a different challenge, the new difficulty is up to you.

== 7. Payment

. The time reported to training will be paid at *$9,468 COP* an hour.
. We expect a minimum dedication of *80%*
(based on the reference time).
. If the total dedication is greater or lower than what is expected,
that time will be paid accordingly.
. The first *96 hours* of training time reported will not be compensated and
If you continue in the training stage,
we will guarantee the payment of the next *96 hours*.
. The contract is a contract for services with monthly payments.
. You must pay your social security corresponding to these services
as an independent worker.
. You must present, in the *1st business day* of the following month,
the documents that allow us to make payments to your account:
.. A bill for the hours worked in the previous month.
.. Payment stub of your social security for the previous period.

If you live in the outskirts of Bogotá or Medellín,
you can initially perform the immersion process remotely
with all the other unalterable terms, *if and only if*:

. When we ask you to continue the immersion process in person
you accept to come to our facilities in maximum +7+
calendar days after the request.

. When you start the immersion process in person,
the hourly pay rate will be twice as much as indicated
(so you can cover transportation and accommodation costs).

. We guarantee minimum +4+ immersion cycles in this stage.

. We clarify that, in case of hiring, the job will be performed in person
in our facilities located in Medellín or Bogotá.
The immersion is still a stage of the selection process,
where we seek to improve the interaction with our team
and deepen other training topics.

If you are currently working somewhere else,
you can perform the immersion under the following conditions:

. Indicate the weekly dedication that you are willing to train
(minimum +8+ hours).

. Perform it remotely without moving to our facilities.

== 8. Get Started

This stage begins when:

. You finish the link:../technical-challenges/[technical challenge stage]
. Send us an email (careers@autonomicmind.com) with the following:
.
[quote]
____________________________________________________________________
I have read and understood all the documentation and
terms of the immersion stage.
I accept the offer and confirm that I can start on AAAA/MM/DD.

Attached:

* ProfessionalCard.pdf (If it applies in your country and are an undergraduate)
* PaymentReceiptProfessionalCard.pdf
(If it applies in your country and are an undergraduate but don’t yet have it)
* Neither (If you have not graduated yet).
____________________________________________________________________

[IMPORTANT]
Other procedural details of how the every day training will be carried out,
the programming languages,
the documentation format and
the required tools, among others,
will be revealed on the first day of Immersion and
when you have finished all the items mentioned in this section.

== 9. End

The immersion stage ends under any of the following circumstances:

. You have successfully completed link:#objectives[the objectives]

. You are not meeting all link:#terms[terms] and
link:#criteria[criteria] defined in this stage.

If you have any doubts,
don’t hesitate to contact us at careers@autonomicmind.com
