:slug: careers/immersion/
:category: careers
:description: The main goal of the following page is to inform potential talents and people interested in working with us about our selection process. The immersion stage is a paid training period focused on acquiring the necessary knowledge and skills to solve everyday tasks.
:keywords: Fluid Attacks, Careers, Immersion, Selection, Process, Training

= Immersion

Welcome to *Immersion*.
At this point,
you have already been selected from among more than +6000+ candidates,
and you have only a few more steps to go.
*Immersion* is an intensive self-training involving a variety
of assignments in +programming+ and +hacking+.
*Immersion* is funded by +Fluid Attacks+.

== 1. Philosophy

Your goal in this stage is to reach the highest
levels of technical proficiency before you execute real pentests
on financial and telecommunications systems.
This stage also serves to substantiate your interpersonal
communication and teamwork skills.

Because this is a lengthy and time-consuming process,
+Fluid Attacks+,
regardless of your progress in points and ranking,
provides monetary compensation for the time you invest
in completing the assignments.

== 2. Objectives

. Solve +30+ unique +programming+ challenges.
. Solve +30+ unique +ctf-hacking+ challenges.
. Solve +30+ unique +vbd-hacking+ challenges.
. Publish +3+ blog articles.
. Finish +3+ training projects.

== 3. Terms

. All [inner]#link:../technical-challenges/#terms[terms]#
from the technical challenge stage apply.
. Use the assigned tool in automatic mode
to report all your work time.
. Your training day begins at *7:00 AM*
in +Fluid Attacks+ office.
. By *6:00 PM* of each training day,
you must have sent at least one accepted-into-master +MR+,
or a standard progress report if the +MR+ has been rejected.
. You may then continue training and reporting your work time,
done outside of the office,
from a location of your choice,
as long as you comply with the 2 previous rules.
. If for some exceptional reason,
you are not able to complete the training in person,
a weekly training schedule to work remotely,
will be established.
. Training must always be done using your own personal laptop.
. Your daily dedication to your work
will be evaluated based on a reference time of *48 hours/week*.
. +Fluid Attacks+ expectation is that you will be present in person,
at the company's office, each business day.
. If for personal or health reasons,
you are unable to come to work in person,
you will not be allowed to complete any challenges or report any training time
for that day.
. On the third business day of each week,
you are required to work at your maximum level of productivity and commitment.

== 4. Criteria

. For the challenges,
use the same [inner]#link:../technical-challenges/#criteria[criteria]#
listed in the challenge stage.
. For the articles,
use the same criteria defined in the [inner]#link:../../style/[style guide]#.

== 5. Cycles

. Training is done in weekly cycles.
. Initially, you are offered *one cycle* of training.
. At the end of each cycle, one of the following will happen:
.. You do not receive any notification,
which means the training cycle continues for *one more week*.
.. You receive a notification
that we do not want to continue with another cycle,
which means we are terminating the training process.
.. You receive a formal notification
that we do not want to continue with another training
cycle because we want you to advance to the next stage.
. Usually *12 to 36 cycles* are required to finish this stage.
.. This is an estimate,
it depends entirely on your productivity,
perseverance, and performance.

== 6. Training sequence

Hacking, programming challenges, and blog entries
must be completed in the following order:

. Complete *five (5)* challenge cycles.

.. A challenge cycle consists of the following steps.
Remember, these steps must be completed in the order listed below.

... *One (1)* approved +MR+ solving a +programming+ challenge in the
link:https://gitlab.com/autonomicmind/training/[training repository].

... *One (1)* approved +MR+ solving a +ctf-hacking+ challenge in the
link:https://gitlab.com/autonomicmind/training/[training repository].

... *One (1)* approved +MR+ solving a +vbd-hacking+ challenge in the
link:https://gitlab.com/fluidattacks/writeups[writeups repository].
An +MR+ is considered approved when it’s merged to the +master+ branch
of each repository.

.. Do *NOT* do the following:
+
* Do *NOT* send consecutive +MR+ solving challenges of the same type.
* Do *NOT* change the cycle order in any way.
* Do *NOT* skip any challenge type in the cycle.

. After you have completed *five (5)* challenge cycles
write *one (1)* article for the blog by sending an +MR+
to the link:https://gitlab.com/fluidattacks/web[web repository].

. Repeat the previous steps until you complete the
[inner]#link:../immersion/#objectives[objectives]#.

. Read carefully the programming challenge requirements below:

.. Each programming challenge completed
must be *one (1)* score point greater than the previous one.

.. If no challenges with greater score exist,
start again solving a challenge of lower score.

.. If you reach a point where the need to obtain a higher score
makes it hard for you to advance:

... Read about the topics you haven't mastered yet
(graphs, trees, modular arithmetic, etc).

... Try different approaches,
(Recursion, Heuristics, Dynamic Programming, Greedy, Divide and Conquer, etc).

... *Persevere!* We are interested in disciplined programmers.

.. If you reach a point where you definitely cannot advance:

... Remember that in the challenge,
the process is just as important as the goal.

... Pick a different challenge,
the new difficulty is up to you, and try to solve it.

== 7. Payment

. The time you spend that is reported as training
will be paid at *$9,468 COP* (Colombian pesos) an hour.
. Based on the previously stated reference time of *48 hours/week*
(see link:#terms[item 3], sentence *8* above),
we expect an *80%* minimum level of work time.
. Regardless of expectation,
you will be paid only for the actual time worked.
. The first *96 hours* of reported training time will not be compensated.
However, if you continue in the training stage,
we will guarantee your payment for the next *96 hours*.
. Your contract is for services with monthly payments.
. During your training stage, you are considered an independent contractor.
As such, you are responsible for paying any withholding
and social security taxes.
. On the *first business day* of the following month,
we must have, in addition to your direct deposit account information:
.. An invoice for the hours you worked in the previous month.
.. Payment stub of your social security for the previous period.

If you live on the outskirts of Bogotá or Medellín,
you can begin the immersion process remotely; no other terms can be changed.
If you choose to begin remotely, you may do so *if and only if*:

. When we ask you to come into the office to continue the immersion process,
you comply within *7 calendar days* of the request.

. When you continue the immersion process in person,
the hourly pay rate will be increased.
It will be twice as much as previously indicated
(see link:#payment[item 7], number 1) in order to compensate you
for any transportation and accommodation costs you may incur.

. At this stage of the selection process
we guarantee you a minimum of +4+ immersion cycles.

. To be clear; if you are hired,
you are required to work in person at our facilities
located in Medellín or Bogotá.
Immersion is one stage of the selection process.
In this stage, we improve your interaction with our team
and expand your training into other topics.

If you are currently employed,
you can participate in the immersion process
under the following conditions:

. Indicate how many hours per week you are willing to train.
Your training minimum is +8+ hours per week.

. Work remotely without coming to our facilities.

== 8. Get Started

This stage begins when:

. You finish the link:../technical-challenges/[technical challenge stage]
. Send us an email (careers@autonomicmind.com) with the following:
.
[quote]
____________________________________________________________________
I have read and understood all the documentation and
terms of the immersion stage.
I accept the offer and confirm that I can start on AAAA/MM/DD.

Attached:

* ProfessionalCard.pdf if it applies in your country
and you are an undergraduate.
*  PaymentReceiptProfessionalCard.pdf if it applies in your country
and you are an undergraduate, but don’t yet have it.
* Neither, if you have not yet graduated from secondary school.
____________________________________________________________________

[IMPORTANT]
When you have finished all the items mentioned in this section
and you begin the immersion stage, other procedural details such as,
how you do the everyday training, the programming languages used,
documentation format, and the required tools,
among others, will be disclosed.

== 9. End

The immersion stage ends if:

. You have successfully completed link:#objectives[the objectives].

. You are not meeting all link:#terms[terms] and
link:#criteria[criteria] defined in this stage.

If you have any questions,
don’t hesitate to contact us at careers@autonomicmind.com.
