:slug: rules/062/
:category: architecture
<<<<<<< Updated upstream
:description: This requirement establishes the importance of using standard industry-approved configurations.
:keywords: Configuration, Vulnerability, Standard, Industry, ASVS, GDPR
=======
:description: This requirement establishes that the organization must define standard configurations that correct all known vulnerabilities.
:keywords: Configuration, Vulnerability, Standard, Industry, GDPR, Security, Rules, Ethical Hacking, Pentesting
>>>>>>> Stashed changes
:rules: yes

= R062. Define standard configurations

== Requirement

The organization must define standard configurations that correct all known
vulnerabilities.
These configurations must also be consistent with industry standards.

== Description

System configuration is essential when it comes to security issues.
The system must follow the industry's standard configurations that prevent
all known vulnerabilities.
These settings also contribute to ensuring the ongoing confidentiality,
integrity, availability and resilience of systems and services.

== Findings

* [inner]#link:/web/findings/043/[F043. Improperly set HTTP headers]#

* [inner]#link:/web/findings/077/[F077. ARP spoofing]#

* [inner]#link:/web/findings/084/[F084. MDNS spoofing]#

* [inner]#link:/web/findings/110/[F110. HTTP request smuggling]#

* [inner]#link:/web/findings/111/[F111. Out-of-bounds Read]#

* [inner]#link:/web/findings/115/[F115. Security controls bypass]#

* [inner]#link:/web/findings/116/[F116. XS-Leaks]#

== References

. [[r1]] link:https://gdpr-info.eu/art-32-gdpr/[GDPR. Art. 32: Security of processing.(1)(b).]
The controller and the processor shall implement appropriate technical and
organizational measures to ensure an appropriate level of security,
including the ability to ensure the ongoing confidentiality, integrity,
availability and resilience of processing systems and services.

. [[r2]] link:https://owasp.org/www-project-application-security-verification-standard/[OWASP-ASVS v4.0.1
V5.5 Deserialization Prevention Requirements.(5.5.2)]
Verify that the application correctly restricts *XML* parsers to only use the
most restrictive configuration possible and to ensure that unsafe features such
as resolving external entities are disabled to prevent *XXE*.
