:slug: rules/062/
:category: architecture
:description: This requirement establishes the importance of using standard industry-approved configurations.
:keywords: Configuration, Vulnerability, Standard, Industry, ASVS, GDPR
:rules: yes

= R062. Define standard configurations

== Requirement

The organization must define standard configurations that correct all known
vulnerabilities.
These configurations must also be consistent with industry standards.

== Description

System configuration is essential when it comes to security issues.
The system must follow the industry's standard configurations that prevent
all known vulnerabilities.
These settings also contribute to ensuring the ongoing confidentiality,
integrity, availability and resilience of systems and services.

== Findings

* [inner]#link:/web/findings/043/[F043. Improperly set HTTP headers]#

* [inner]#link:/web/findings/077/[F077. ARP spoofing]#

* [inner]#link:/web/findings/084/[F084. MDNS spoofing]#

* [inner]#link:/web/findings/110/[F110. HTTP request smuggling]#

* [inner]#link:/web/findings/111/[F111. Out-of-bounds Read]#

* [inner]#link:/web/findings/115/[F115. Security controls bypass]#

* [inner]#link:/web/findings/116/[F116. XS-Leaks]#

== References

. [[r1]] link:https://gdpr-info.eu/art-32-gdpr/[GDPR. Art. 32: Security of processing.(1)(b).]
The controller and the processor shall implement appropriate technical and
organizational measures to ensure an appropriate level of security,
including the ability to ensure the ongoing confidentiality, integrity,
availability and resilience of processing systems and services.

. [[r2]] link:https://owasp.org/www-project-top-ten/OWASP_Top_Ten_2017/Top_10-2017_A4-XML_External_Entities_(XXE)[OWASP Top 10 A4:2017-XML External Entities (XXE)].
Many older or poorly configured *XML* processors evaluate external entity
references within *XML* documents.
External entities can be used to disclose internal files using the file *URI*
handler, internal file shares, internal port scanning, remote code execution,
and denial of service attacks.

. [[r3]] link:https://owasp.org/www-project-top-ten/OWASP_Top_Ten_2017/Top_10-2017_A6-Security_Misconfiguration[OWASP Top 10 A6:2017-Security Misconfiguration].
Security misconfiguration is the most commonly seen issue.
This is commonly a result of insecure default configurations,
incomplete or ad hoc configurations, open cloud storage,
misconfigured *HTTP* headers,
and verbose error messages containing sensitive information.
Not only must all operating systems, frameworks, libraries, and applications be
securely configured, but they must be patched/upgraded in a timely fashion.

. [[r4]] link:https://owasp.org/www-project-application-security-verification-standard/[OWASP-ASVS v4.0.1
Appendix C: Internet of Things Verification Requirements.(C.17)]
Verify that any available Intellectual Property protection technologies
provided by the chip manufacturer are enabled.

. [[r5]] link:https://owasp.org/www-project-application-security-verification-standard/[OWASP-ASVS v4.0.1
Appendix C: Internet of Things Verification Requirements.(C.32)]
Verify that the firmware apps utilize kernel containers for isolation between
apps.

. [[r6]] link:https://owasp.org/www-project-application-security-verification-standard/[OWASP-ASVS v4.0.1
Appendix C: Internet of Things Verification Requirements.(C.33)]
Verify that secure compiler flags such as **-fPIE**, **-fstack-protector-all**,
**-Wl**, **-z,noexecstack**, **-Wl**, **-z,noexecheap** are configured for
firmware builds.

. [[r7]] link:https://owasp.org/www-project-application-security-verification-standard/[OWASP-ASVS v4.0.1
Appendix C: Internet of Things Verification Requirements.(C.34)]
Verify that micro controllers are configured with code protection
(if applicable).

. [[r8]] link:https://owasp.org/www-project-application-security-verification-standard/[OWASP-ASVS v4.0.1
V5.5 Deserialization Prevention Requirements.(5.5.2)]
Verify that the application correctly restricts *XML* parsers to only use the
most restrictive configuration possible and to ensure that unsafe features such
as resolving external entities are disabled to prevent *XXE*.

. [[r9]] link:https://owasp.org/www-project-application-security-verification-standard/[OWASP-ASVS v4.0.1
V6.2 Algorithms.(6.2.2)]
Verify that industry proven or government approved cryptographic algorithms,
modes, and libraries are used, instead of custom coded cryptography.

. [[r10]] link:https://owasp.org/www-project-application-security-verification-standard/[OWASP-ASVS v4.0.1
V6.2 Algorithms.(6.2.3)]
Verify that encryption initialization vector, cipher configuration,
and block modes are configured securely using the latest advice.

. [[r11]] link:https://owasp.org/www-project-application-security-verification-standard/[OWASP-ASVS v4.0.1
V9.2 Server Communications Security Requirements.(9.2.4)]
Verify that proper certification revocation, such as Online Certificate Status
Protocol (**OCSP**) Stapling, is enabled and configured.

. [[r12]] link:https://owasp.org/www-project-application-security-verification-standard/[OWASP-ASVS v4.0.1
V10.3 Deployed Application Integrity Controls.(10.3.2)]
Verify that the application employs integrity protections,
such as code signing or sub-resource integrity.
The application must not load or execute code from untrusted sources,
such as loading includes, modules, plugins, code, or libraries from untrusted
sources or the Internet.

. [[r13]] link:https://owasp.org/www-project-application-security-verification-standard/[OWASP-ASVS v4.0.1
V13.2 RESTful Web Service Verification Requirements.(13.2.2)]
Verify that *JSON* schema validation is in place and verified before accepting
input.

. [[r14]] link:https://owasp.org/www-project-application-security-verification-standard/[OWASP-ASVS v4.0.1
V13.3 SOAP Web Service Verification Requirements.(13.3.1)]
Verify that *XSD* schema validation takes place to ensure a properly formed
*XML* document,
followed by validation of each input field before any processing of that data
takes place.

. [[r15]] link:https://owasp.org/www-project-application-security-verification-standard/[OWASP-ASVS v4.0.1
V14.1 Build.(14.1.1)]
Verify that the application build and deployment processes are performed in a
secure and repeatable way, such as *CI* / *CD* automation,
automated configuration management, and automated deployment scripts.

. [[r16]] link:https://owasp.org/www-project-application-security-verification-standard/[OWASP-ASVS v4.0.1
V14.1 Build.(14.1.2)]
Verify that compiler flags are configured to enable all available buffer
overflow protections and warnings,
including stack randomization, data execution prevention,
and to break the build if an unsafe pointer, memory, format string, integer,
or string operations are found.

. [[r17]] link:https://owasp.org/www-project-application-security-verification-standard/[OWASP-ASVS v4.0.1
V14.1 Build.(14.1.3)]
Verify that server configuration is hardened as per the recommendations of the
application server and frameworks in use.
