:slug: kb/aspnet/evitar-codigo-muerto
:eth: no
:category: aspnet
:kb: yes

= Evitar Código Muerto

== Necesidad

Evitar código muerto en ASP.Net

== Contexto

A continuación se describe las circunstancias 
bajo las cuales la siguiente solución tiene sentido:

. Se está desarrollando en ASP.Net.

== Solución

. El código muerto se refiere a secciones de código 
que son cargadas en memoria o interpretadas 
pero que nunca son usadas,
se refiere también a secciones de código olvidadas 
que si no son eliminadas 
pueden ocasionar problemas de seguridad. 
En el siguiente código se muestra un ejemplo de código muerto:
Definimos la nueva clase e
importamos las clases necesarias desde la biblioteca IO:
+
[source,java,linenums]
----
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.IO;
using System.Diagnostics;

...

    class dead
    {
----

. En el método main encontramos el llamado al método _listarArchivos_, 
el cual retorna la lista de archivos según el parámetro de la ruta. 
Entre comentarios podemos ver 
una forma antigua de retornar los archivos a través del método _ejecutar_, 
el cual hace el llamado al sistema operativo del comando especificado.
+
[source,java,linenums]
----
 static void Main(string[] args)
        {
        // método viejo
        // ejecutar("dir");
        
        // método nuevo
        listarArchivos("c:\\");
        }
----

. El método seguro para listar los archivos es 
a través del uso de la clase _Directory.GetFile_:
+
[source,java,linenums]
----
     public static void listarArchivos(String ruta) {
         
           string[] archivos = Directory.GetFiles("c:\MyDir\"");
           if (archivos != null) {
            for (int i = 0; i < archivos.Length; i++) {
                Console.WriteLine(archivos[i]);
            }
            } else {
            Console.Error.WriteLine("La ruta no existe");
            }
       }
----

. El antiguo método y que no ha sido comentado, 
 hace un llamado a Process,
 el cual invoca al sistema operativo 
 y ejecuta el comando especificado. 
 Si este método no es eliminado del código, 
 al compilarlo, 
 se mantiene 
 y puede ser usado por clases externas con contenido malicioso. 
 La misma funcionalidad del código
 podría permitir a un atacante escalar privilegios en el servidor.
+
[source,java,linenums]
----
      public static void ejecutar(String comando)
        {        
        String linea = "";
        String resultado = "";
        Process p;
        p.StartInfo.UseShellExecute = false;
        p.StartInfo.RedirectStandardOutput = true;
        p.StartInfo.FileName = comando;
        p.Start();            
        String output = p.StandardOutput.ReadToEnd();
        Console.WriteLine(output); 
        p.WaitForExit();
    }
----

== Referencias

. REQ.0158: Las funciones, métodos o clases deben ser invocadas en algún escenario funcional del sistema.
