:slug: rules/033/
:category: authorization
:description: This document contains the details of the security requirements related to the definition and management of systems in the organization. This requirement establishes the importance of limiting administrative access to applications to authorized users only, in order to avoid several common attacks.
:keywords: Requirement, Security, Restrict, Administrative, Access Control, Network
:rules: yes

= REQ.033 Restrict administrative access

== Requirement

If the system has an administration mechanism,
it must only be accessible from administrative network segments.

== Description

Network access to modules or system management mechanisms
must only be limited to the parties
that require access to them (administrators).
Personnel that does not have administrative needs, tasks or obligations
must not have access to these mechanisms.
Following this recommendation fulfills the objective
of reducing the attack surface of the above mentioned systems
(since malicious third parties can not attempt
to directly access the system administration settings)
and increases the level of confidentiality and availability of the system.

== Implementation

. Principle of least privilege:
For each system in the organization
it must be guaranteed that each module
(process, user or program) can access
only to the information and resources required
to accomplish its legitimate purpose.

== Attacks

. An anonymous attacker attempts to access to an exposed administrator
interface by brute force,
which may cause a denial of service, account lockouts or a
interface/system lockout.

. An anonymous attacker and/or registered user
exploits a known vulnerability in the management system
which may allow the access to the system settings,
a denial of service or privileges elevation for system users or processes.

. An anonymous attacker obtains system technical information
through data analysis of the administrator interface
in order to perform deeper and more detailed attacks.

== Attributes

* Layer: Application Layer
* Asset: System management
* Scope: Confidentiality
* Phase: Operation
* Type of Control: Recommendation

== References

. [[r1]] link:https://cwe.mitre.org/data/definitions/419.html[CWE-419: Unprotected Primary Channel].
. [[r2]] link:https://cwe.mitre.org/data/definitions/264.html[CWE CATEGORY: Permissions, Privileges, and Access Controls].
. [[r3]] link:https://www.owasp.org/index.php/Category:Access_Control[Category:Access Control].
. [[r4]] link:https://www.owasp.org/index.php/Top_10_2013-A5-Security_Misconfiguration[Top 10 2013-A5-Security Misconfiguration].
. [[r5]] link:https://www.owasp.org/index.php/ASVS_V2_Authentication[+OWASP-ASVS v3.1-2.32+]
Verify that access to administrative interfaces
is strictly controlled and not allowed for untrusted parties.
