:slug: security/
:description: This page summarizes all the best practices and technology Fluid Attacks implements in order to keep internal products and customer data secure. It goes from philosophies as having open source code, to particular ciphering algorithms used and internal behavioral policies.
:keywords: Fluid Attacks, Security, Data, Policy, Breach, Best practices
:subtitle: How we keep things secure

= Security

As a security company,
Fluid Attacks is aware of the importance of:

. Having honesty, team work and discipline
  as immovable principles.
  Our full manifest can be found
  [inner]#link:../values/[here]#
. Developing products
  that comply with the highest worldwide
  [inner]#link:../products/rules/[security standards]#.
. Aquiring only
  [inner]#link:../rules/262/[compliant services and products for internal use]#.
. Implementing best security practices within our organization.
. Being completely transparent with our clients,
  especially regarding their data:
  [inner]#link:../rules/315/[how we use it, and what we do to protect it]#.

These concerns,
concieved since the early days of the company,
have allowed us to implement
a big number of measures
throughout the years.
In this page we will mention
the ones that provide the highest
value to our customers in
terms of security.

== 1. Transparency

This section focuses on what we do to keep our client informed
about the status of all our services
and their data.

=== 1.1 Open Source

The source code of all our applications
is available to the entire Internet.
There are no backdoors or exposed sensitive data.
The code is transparent and can be reviewed by anyone.
All our source code can be found
link:https://gitlab.com/fluidattacks[here].

Commit history of all repositories:

- link:https://gitlab.com/fluidattacks/web/-/commits/master[Web]
- link:https://gitlab.com/fluidattacks/integrates/-/commits/master[Integrates]
- link:https://gitlab.com/fluidattacks/asserts/-/commits/master[Asserts]
- link:https://gitlab.com/fluidattacks/public/-/commits/master[Public]
- link:https://gitlab.com/fluidattacks/writeups/-/commits/master[Writeups]

=== 1.2 Public incidents

Every public incident is reported in our
link:https://community.fluidattacks.com/c/announce/[Community Site]
with details like *_what happened_*, *_what we've done_*,
*_what's the impact_* and *_what are we doing to help_*.

=== 1.3 Data leakeage policy

In case Fluid Attacks detects a breach,
emails notyifing the involved parties will be sent.
Emails will contain information on what data was leaked or compromised,
when and for how long (to the extent this information is available).
For a breach that exposes private data for a large number of users,
the public will also be informed via email.leaked or compromised,
when and for how long (to the extent this information is available).
For a breach that exposes private data for a large number of users,
the public will also be informed via email.

=== 1.4 Status page

We continuous monitor
[inner]#link:../products/integrates[Integrates]#,
its [inner]#link:../../integrates/api[API]#
and [inner]#link:../[Web]#.
This information is real-time and available on our
link:http://status.fluidattacks.com/[Status Site].

== 2. Encryption

We offer both
[inner]#link:../rules/224/[encryption at rest and encryption in transit]#
with cutting-edge industry standards.

=== 2.1 Encryption at rest

All our applications and services have
industry-standard encryption at rest.

- All the sesitive data provided by our clients
  (Repo access keys, vpn credentials, etc)
  is ciphered using key management system KMS
  symmetric algorithm
  based on Advanced Encryption Standard (AES)
  in Galois Counter Mode (GCM)
  with
  [inner]#link:../rules/150/[256-bit]#
  [inner]#link:../rules/145/[private keys]#.
- All our clients repositories are
  stored in a private,
  [inner]#link:../rules/185/[AES256 ciphered]#
  cloud storage system.
- Forces exploits are stored encrypted using AES256 keys.
- All
  [inner]#link:../products/integrates[Integrates]#
  data is stored in a AES256 encrypted
  non-relational database.
- All our products use our KMS
  for both development and production secrets.
- All our Windows laptops
  have their hard drives encrypted
  using Bitlocker.
  Adherence to this policy is continuously checked
  by a domain controller.
- All our Linux laptos
  have their hard drives encrypted
  from bootloader using LUKS.

=== 2.2 Encryption in transit

All our applications and services have
industry-standard encryption in transit.

- The [inner]#link:../../[Fluid Attacks]# domain
  uses the latest
  [inner]#link:../rules/181/[TLSv1.3]#
  cryptographic protocol for maximum in transit protection.
- [inner]#link:../products/integrates[Integrates]#'s
  DynamoDB database uses TLSv1.2
  for in transit protection.
- We possess fully dedicated channels with some of our biggest clients,
  allowing us to isolate all unwanted traffic. This is especially useful
  for running secure dynamic application hacking.
- For the rest of our clients, we use fully encrypted VPNs.
- We use a messaging system with
  link:https://en.wikipedia.org/wiki/Off-the-Record_Messaging[OTR]
  and
  link:https://en.wikipedia.org/wiki/End-to-end_encryption[E2EE]
  for communication within the organization.
  Also, all chat histories
  [inner]#link:../rules/183/[reset on a weekly basis]#
  as an extra measure to avoid leaks.
- Instead of having long-term development environments like
  staging, we use testing environments that get created
  during a pipeline. We call them ephemeral environments,
  as they only exist in pipeline time. These environments
  get created on demand and always bring a digital certificate,
  validated with ACME protocol and
  [inner]#link:../rules/092/[not self-signed]#.
  Once a change reaches production, its ephemeral environment
  is destroyed forever.

== 3. Authentication

Authentication refers to the process
of validating your identity within a service or platform.
In this context,
we talk about our own services
and other third party services we use.

=== 3.1 For Clients

As
[inner]#link:../products/integrates[Integrates]#
uses SSO with Google and Microsoft Accounts,
we do not store any account passwords.
The only personal information we store of our clients are:

- Full name (Provided by Google or Microsoft).
- Company and cellphone (Only if shared, user can decide).

It is also worth noting that once users lose their
corporate email,
[inner]#link:../rules/114/[they also lose access]#
to their
[inner]#link:../products/integrates[Integrates]#
account. Allowing clients to
[inner]#link:../rules/034/[easily manage]#
who has and who does not have access to
their projects.

=== 3.2 Internal

Our IAM is a centralized authentication platform,
allowing us to manage all the applications
we internally use from just one place. Our employees do
not know any of the passwords of the managed applications,
they only know their own IAM passphrase.
Once they log in to IAM,
they can access applications
[inner]#link:../rules/096/[assigned to them]#.

Some of our IAM specifications and requirements are:

- [inner]#link:../rules/132/[Passphrases instead of passwords]#
  (More information [inner]#link:../blog/requiem-password/[here]#).
- [inner]#link:../rules/130/[Passphrases expire every 30 days]#.
- Previous passphrases can only be reused after a
  [inner]#link:../rules/129/[24 reset cycle]#.
- [inner]#link:../rules/328/[Multi-factor authentication]#
  from a mobile device must be set.
  Our MFA uses
  [inner]#link:../rules/153/[OOB]#,
  which reduces risk in case a comunnication channel becomes compromised.
- In case a mobile phone supports
  [inner]#link:../rules/231/[biometric authentication]#,
  our IAM enforces its usage.
- All successful sessions have a duration of 9 hours.

== 4. Authorization

Authorization refers to the ability of giving
users within an application,
the
[inner]#link:../rules/186/[minimum privileges]#
they need to do
their work. No users should have the ability
to do what they should not.

=== 4.1 For Clients

[inner]#link:../products/integrates[Integrates]#
has a set of
[inner]#link:../rules/096/[roles]#
that are necessary on every hacking project,
providing project managers with the
[inner]#link:../rules/035/[ability to assign]#
the
[inner]#link:../rules/186/[minimum required permissions]#
to each team member.
Some of these roles are:
hacker, admin, releaser, escaper,
user, project manager, etc.

=== 4.2 Internal

Every application we use must have user-granular authorization settings
in order to grant minimum-privilege policy at all times.
Some examples are:

- *IAM and KMS:*
  These two tools are widely used within Fluid Attacks.
  They allow us to ensure
  that hackers can only access source code,
  environments, exploits and secrets
  from projects they have access to.
  Access can be easily removed
  should the need arise,
  with no users/passwords leaked.
  These tools also let us keep application
  production secrets hidden from developers
  (Production-Development secrets separation).
- *IAM:*
  we can grant application access on a user level.
  Granting us the ability to give employees access
  [inner]#link:../rules/176/[only to what they need]#
  to execute their tasks.
  [inner]#link:../rules/034/[Giving or removing access to applications]#
  is simple, and no users/passwords are leaked.

== 5. Privacy

=== 5.1 Client and project pseudonymization

Both clients and projects have a pseudonym within our systems,
briging with it advantages like:

- Employees without direct access to the project do not
  know the client's name or any other information
  that can help them
  [inner]#link:../rules/313/[vinculate a project with the client]#.
- Internal analytics charts and other documents
  never use the clients name, they user their pseudonym.

Generally speaking, only the people who need to know
whose whose client a pseudonym is and
whose client a project is, do actually know it.

=== 5.2 Secure delivery of sensitive data

We use an information sharing system with
link:https://en.wikipedia.org/wiki/Data_loss_prevention_software[DPL]
when sending any sensitive information to our clients.
This includes contracts, portfolios and other sensitive documents.

=== 5.3 Transparent cookie usage

Both [inner]#link:../products/integrates[Integrates]#
and [inner]#link:../[Web]#
utilize a GDPR cookie plugin that:

- Informs the user about
  every cookie the page creates
- Lets users specify
  which ones to allow,
  thus giving them full control
  over what information we're creating
  and manipulating within their browser

By doing this, we become compliant with
security rules like:

- [inner]#link:../rules/310/[Request user consent]#
- [inner]#link:../rules/312/[Allow user consent revocation]#
- [inner]#link:../rules/315/[Provide processed data information]#

=== 5.4 Data policies

The following policies apply to all the information
provided by a client in a project context.

==== 5.4.1 Data use policy

We are commited to use our clients data
exclusively for vulnerability seeking
in the context of the service we are providing.
No other activities will be executed
over the provided information.

==== 5.4.2 Data retention policy

All the data related to a project
can be deleted from
[inner]#link:../products/integrates[Integrates]#
by a user with a project manager role.
Once this action is triggered,
a [inner]#link:../rules/317/[deletion window]# of 30 days begins.
Any project manager can undo the deletion action.
After the 30 days waiting period, the project,
source code, secrets, metadata and any other project related
[inner]#link:../rules/183/[data is completely removed]#
from all our infrastructure.

=== 5.5 Secret rotation

[inner]#link:../rules/130/[Key rotation]#
is of the essence when dealing with
sensitive data. The best way to prevent a key leakage is by
regularily changing it. We continuously rotate:

- KMS keys change on a yearly basis or before in case it is needed.
- JWT Tokens change on a daily basis.
- Digital Certificates
  [inner]#link:../rules/089/[change every three months]#.
- IAM passphrases change every three months.

=== 5.6 Employee time tracking software

We use a time tracking system that takes periodical
screnshots from laptop screens when
employees are working. Only managers have access to such
screenshots in case an incident happens. Employees
have control over the software, which means once they
stop working, no screen recording occurs.

=== 5.7 Poligraph tests

We continuously run poligraph checks on all
employees with access to sensitive information.
The test fully focuses on identifying
if an employee disclosed such data
to a third party,
and personal questions are never aksed.

== 6. Non-repudiation

Non-repudiation refers to the capability
of keeping a log of every action
taken in a system.
What was done, who did it and when.
By knowing this,
no one can deny their actions.

We implement this in several ways
depending of the context.

=== 6.1 Everything as code

At Fluid Attacks we try to keep everything we can
versioned in a Git repository.
By doing so, we are capable of having
comprenhensive logs of:

- What was exactly changed
- Who changed it
- When was it changed
- Who approved a change

Currently, we keep the following systems as code:

- link:https://gitlab.com/fluidattacks/integrates/-/commits/master[Integrates]
- link:https://gitlab.com/fluidattacks/asserts/-/commits/master[Asserts]
- link:https://gitlab.com/fluidattacks/web/-/commits/master[Website]
- [inner]#link:../services/continuous-hacking[Continuous Hacking]#
- <<IAC, Infrastructure>>
- General documentation

=== 6.2 Extensive logs

Typical logs are also essential
for a non-repudiation policy to be successful.
Currently, we store logs for:

- *[inner]#link:../products/integrates[Integrates]#'s*
  *logging system:*
  Integrates stores a historic state
  of projects, findings, vulnerabilities
  and other critical components.
  Changes made to these components
  are always tied to a user and a date.
  The historic state never expires.
- *[inner]#link:../products/integrates[Integrates]#'s*
  *error tracking system:*
  It provides real-time logging
  of errors that occur in its production environments.
  It is especially useful for quickly detecting
  new errors and hacking attempts.
  These logs never expire.
- *Cloud logging system:*
  It stores comprehensive logs
  of all our cloud infrastrucutre components.
  Logs here never expire.
- *Forces executions:*
  Every time a CI pipeline runs Forces,
  logs containing information like who ran it,
  vulnerability status and other relevant data
  are uploaded to our cloud storage systems,
  allowing us to always know the current status
  of our client's Forces service.
  Logs here never expire.
- *IAM authentication:*
  Our IAM stores logs of
  login attempts made by users,
  accessed applications
  and possible threats.
  Logs here expire after 7 days.
- *Collaboration systems activity:*
  Our collaboration systems like mail, calendar, etc.
  Store comprehensive logs of employee activity,
  spam mails,
  suspicious login attempts,
  and other possible threats.
  Employee activity logs never expire.
  Other security logs expire after 30 days.
- *CI job logs:*
  All our CI jobs provide full logging
  of who triggerd them, when,
  and console output.
  These logs never expire.

== 7. Integrity

Integrity refers to the ability
of:

- Avoiding data loss or corruption.
- Having clear definitions
  of all technological components
  within the organization
  and making sure
  such definitions are followed.

[IAC]
=== 7.1 Infrastructure as code (IaC)

All our infrastructure is in the cloud.
The only hardware we manage are our employee's laptops.
All our cloud infrastructure is versioned
in a Git repository written as code.
Such code can be deployed anywhere
and has all the properties of any
other source code,
such as auditability, history,
revert capabilities, etc.

==== 7.1.1 Regenerable

It provides us with the ability
to recreate our infrastructure
in a daily basis.
Regenerating our infrastrcture everyday
brings the following advantages:

- Any injected trojans or malicious scripts are removed.
- Having fresh new servers every 24 hours let us avoid
  availability and performance issues generated by
  memory leaks and non-released resources.
- The capability of deploying our infrastructure
  from 0 to production in an automated process.

==== 7.1.2 Immutable

The infrastructure code can be audited
and changes can only be made by
[inner]#link:../rules/265/[changing such code]#.
This provides full transparency on
[inner]#link:../rules/046/[what was changed, when and who did it]#.
Also, no administrative protocols like ssh
or administrative accounts are needed.

=== 7.2 Everything is backed up in the cloud

As data is most likely our most important asset,
we have strong backup policies for everything.
For example:

- Our cloud storage system is full versioned,
  meaning that any file can be recovered
  or returned to a previous version.
- [inner]#link:../products/integrates[Integrates]#'s
  database has weekly, trimestral
  and annual full backup schedules.
- [inner]#link:../products/integrates[Integrates]#'s
  database has point-in-time
  recovery with the capability of recovering
  the database to a state it was during
  the current day. It creates a backup every
  five minutes.
- All Forces exploits are versioned.

== 8. Availability

Availability refers to the capacity
of keeping all our systems up and running.
Avoiding service interruptions is crucial here.

=== 8.1 Distributed applications

[inner]#link:../products/integrates[Integrates]#
is hosted in a Kubernetes cluster with
autoscaling policies and distributed
replicas. This ensures high availability,
as the there is always an instance ready to
recieve user requests in case another stops
working. Every cluster node has at least one
[inner]#link:../products/integrates[Integrates]#
instance running in it.

=== 8.2 Forever-lasting backups

As all our backups are stored in the cloud,
problems like hard drive lifespans
are not a concern to us.
Backups seamlessly exist
for as long as we decide them to exist.
Thus providing us full traceability
and recoverability.

== 9. Resilency

By resilency,
we refer to the organizational capability
of adapting to unexpected circumstances
that would affect the way our team
usually work.

=== 9.1 Redundand roles

Every role within the organization
has a minimum of two different employees
executing its tasks.
This allows us to be able to fill the gap
in case an employee goes on sick leave,
vacations, etc.

=== 9.2 Everything is in the cloud

As all our infrastrucutre is in the cloud,
No hardware maintainance is needed,
making our operation fully descentralized.
No local networks are used,
we only use wifi connections with
[inner]#link:../rules/253/[strong random generated passwords]#
with the sole purpose of accessing the Internet.
Connections are always encrypted
[inner]#link:../rules/252/[using WPA2-AES]#.

=== 9.3 One laptop for every employee

A standard laptop is given to every employee.
Going to the office is the rule,
but employees can always fill out an exception form
to do telework in case they need to.
Also, in case our offices close
(link:https://en.wikipedia.org/wiki/Coronavirus_disease_2019[COVID-19]),
everyone can still to their job seamlessly.
All laptops have a password-secured BIOS,
link:https://docs.microsoft.com/en-us/windows/security/information-protection/tpm/trusted-platform-module-overview[TPM]
hardware and
[inner]#link:../rules/231/[biometric fingerprint reader]#.
By owning the laptops, siezing the computer should the
need arise becomes possible.
BYOD is not allowed.

== 10. Information security culture

This section provides details
regarding all the best practices
we follow in order to have a strong
information security culture.

=== 10.1 We hack ourselves

We have full-time projects focused on hacking our own software.
To us, seting an example of secure software is essential,
that is why today,
our entire technological stack goes through a
[inner]#link:../services/continuous-hacking[Continuous Hacking]#
process.

Aditionally, all our development projects run
link:https://en.wikipedia.org/wiki/Continuous_integration[Continuous Integration]
pipelines,
Including Forces exploits and strict linters
to ensure that
[inner]#link:../rules/155/[no known vulnerabilities]#
are released to production.

=== 10.2 All our hired personnel must accept a NDA

Everyone within our company knows
how important it is to keep our
clients's information secure.
We enforce this by requiring
all our new employees to sign a
Non disclosure agreement.

=== 10.3 Certified hackers

We continuously encourage our hackers
to certify their knowledge.
Usually, hackers start applying for
certificates after spending 6 months
in the company.
[inner]#link:../services/certifications/[Here]#
you can find a comprenhensive list of certifications
our hackers team currently has.

=== 10.4 Extensive hiring process

All job applicans must go through
an extense [inner]#link:../careers[testing process]# in order to prove
their technical capabilities and human values.

The technical part of the testing process
consists of solving programming and hacking challenges,
upload them to a git repository with highly strict linters and compilers,
and ascend in a [inner]#link:../training/[organizational ranking]#

The human values part of the testing process
includes creating a portfolio with the five most
important achievements of the candidate,
going to the office during a training
phase to work alongside the team,
job inverviews, among others.

=== 10.5 Secure policies for enrolled mobile devices

Our collaboration systems also provide security requirements
mobile devices must comply with
before being enrolled with the organization systems.
This is especially useful,
as personal mobile devices
are common targets for malicious hackers.

=== 10.6 No physical keys to our offices

All our offices have digital locks.
Employees have their own password to open the doors.
All successful and failed access attempts are logged.

=== 10.7 We only hire directly

All our employees have indefinite time contracts
directly with the company.
Due to the nature of our business, we never
hire through contractors, freelance or any
other third parties.
