:slug: security/
:description: This page summarizes all the best practices and technology Fluid Attacks implements in order to keep internal products and customer data secure. It goes from philosophies as having open source code, to particular ciphering algorithms used and internal behavioral policies.
:keywords: Fluid Attacks, Security, Data, Policy, Breach, Best practices
:subtitle: How we keep things secure

= Security

As a security company,
Fluid Attacks is aware of the importance of:

. Having honesty, team work and discipline
  as immovable principles.
  Our full manifest can be found
  [inner]#link:../values/[here]#
. Developing products
  that comply with the highest worldwide
  [inner]#link:../products/rules/[security standards]#.
. Aquiring only compliant services and products for internal use.
. Implementing best security practices within our organization.
. Being completely transparent with our clients,
  especially regarding their data: how we use it,
  and what we do to protect it.

This concerns,
concieved since the early days of the company,
have allowed us to implement
a huge number of measures
throughout the years.
In this page we will mention
the ones that provide the highest
value to our customers in
terms of security.

== 1. Open Source

The source code of all our applications
is available to the entire Internet.
There are no backdoors or exposed sensitive data.
The code is transparent and can be reviewed by anyone.
All our source code can be found
link:https://gitlab.com/fluidattacks[here]

== 2. Encryption

We offer both
encryption at rest
and encryption in transit
with cutting-edge industry standards.

=== 2.1 Encryption at rest

All our applications and services have
industry-standard encryption at rest.

- All the sesitive data provided by our clients
  (Repo access keys, vpn credentials, etc)
  is ciphered using our key management system KMS
  symmetric algorithm
  based on Advanced Encryption Standard (AES)
  in Galois Counter Mode (GCM)
  with 256-bit keys.
- All our clients repositories are
  stored in a private, AES256 ciphered
  cloud storage system.
- Forces exploits are stored encrypted using AES256 keys.
- All
  [inner]#link:../products/integrates[Integrates]#
  data is stored in a AES256 encrypted
  non-relational database.
- All our products use our KMS
  for both development and production secrets.
- All our Windows laptops
  have their hard drives encrypted
  using Bitlocker.
  Adherence to this policy is continuously checked
  by a domain controller.
- All our Linux laptos
  have their hard drives encrypted
  from bootloader using LUKS.

=== 2.2 Encryption in transit

All our applications and services have
industry-standard encryption in transit.

- The [inner]#link:../../[Fluid Attacks]# domain
  uses the latest TLSv1.3 cryptographic
  protocol for maximum in transit protection.
- [inner]#link:../products/integrates[Integrates]#'s
  DynamoDB database uses TLSv1.2
  for in transit protection.
- We possess fully dedicated channels with some of our biggest clients,
  allowing us to isolate all unwanted traffic. This is especially useful
  for running secure dynamic application hacking.
- For the rest of our clients, we use fully encrypted VPNs.
- Instead of having long-term development environments like
  staging, we use testing environments that get created
  during a pipeline. We call them ephemeral environments,
  as they only exist in pipeline time. These environments
  get created on demand and always bring a digital certificate,
  validated with ACME protocol and not self-signed.
  Once a change reaches production, its ephemeral environment
  is destroyed forever.

== 3. Authentication

Authentication refers to the process
of validating your identity within a service or platform.
In this context,
we talk about our own services
and other third party services we use.

=== 3.1 For Clients

As
[inner]#link:../products/integrates[Integrates]#
uses SSO with Google and Microsoft Accounts,
we do not store any account passwords.
The only personal information we store of our clients are:

- Full name (Provided by Google or Microsoft).
- Company and cellphone (Only if shared, user can decide).

It is also worth noting that once a user losses her
corporate email, she also loses access to her
[inner]#link:../products/integrates[Integrates]#
account. Allowing clients to easily manage
who has and who does not have access to
their projects.

=== 3.2 Internal

Our IAM is a centralized authentication platform,
allowing us to manage all the applications
we internally use from just one place. Our employees do
not know any of the passwords of the managed applications,
they only know their own IAM passphrase.
Once they log in to IAM,
they can access applications assigned to them.

Some of our IAM specifications and requirements are:

- Passphrases instead of passwords
  (More information [inner]#link:../blog/requiem-password/[here]#).
- Passphrases expire every 90 days.
- Previous passphrases can only be reused after a 24 reset cycle.
- Multi-factor authentication from a mobile device must be
  set. Our MFA uses
  link:https://doubleoctopus.com/security-wiki/authentication/out-of-band-authentication/[OOB],
  which reduces risk in case a comunnication channel becomes compromised.
- In case a mobile phone supports biometric authentication,
  our IAM enforces its usage.
- All successful sessions have a duration of 9 hours.

== 4. Authorization

Authorization refers to the ability of giving
users within an application,
the minimum privileges they need to do
their work. No user should have the ability
to do what she should not.

=== 4.1 For Clients

[inner]#link:../products/integrates[Integrates]#
has a set of roles that are necessary on every hacking project,
providing project managers with the ability
to assign the minimum required permissions
to each team member.
Some of these roles are:
hacker, admin, releaser, escaper,
user, project manager, etc.

=== 4.2 Internal

Every application we use must have user-granular authorization settings
in order to grant minimum-privilege policy at all times.
Some examples are:

- IAM and KMS:
  These two tools are widely used within Fluid Attacks.
  They allow us to ensure
  that hackers can only access source code,
  environments, exploits and secrets
  from projects they have access to.
  Access can be easily removed
  should the need arise,
  with no users/passwords leaked.
  These tools also let us keep application
  production secrets hidden from developers
  (Production-Development secrets separation).
- IAM:
  we can grant application access on a user level.
  Granting us the ability to give employees access
  only to what they need to execute their tasks.
  Giving or removing access to applications
  is simple, and no users/passwords are leaked.


== 5. Client and project pseudonymization

Both clients and projects have a pseudonym within our systems,
briging with it advantages like:

- Employees without direct access to the project do not
  know the client's name or any other information
  that can help them vinculate a project with the client.
- Internal analytics charts and other documents
  never use the clients name, they user their pseudonym.

Generally speaking, only the people who need to know
whose whose client a pseudonym is and
whose client a project is, do actually know it.

== 6. Secure delivery of sensitive data

We use an information sharing system with
link:https://en.wikipedia.org/wiki/Data_loss_prevention_software[DPL]
when sending any sensitive information to our clients.
This includes contracts, portfolios and other sensitive documents.

== 7. Everything is backed up in the cloud

As data is most likely our most important asset,
we have strong backup policies for everything.
For example:

- Our cloud storage system is full versioned,
  meaning that any file can be recovered
  or returned to a previous version.
- Integrates's database has weekly, trimestral
  and annual full backup schedules.
- Integrates's database has point-in-time
  recovery with the capability of recovering
  the database to a state it was during
  the current day. It creates a backup every
  five minutes.
- All Forces exploits are versioned.

== 8. Secret rotation

Key rotation is of the essence when dealing with
sensitive data. The best way to prevent a key leakage is by
regularily changing it. We continuously rotate:

- KMS keys change on a yearly basis or before in case it is needed
- JWT Tokens change on a daily basis
- Digital Certificates change every three months
- IAM passphrases change every three months

== 9. Infrastructure

All our infrastructure is in the cloud.
The only hardware we manage are our employee's laptops.
Having everything in the cloud gives us some advantages.

=== 10.1 Regenerable

It provides us with the ability
to recreate our infrastructure
in a daily basis.
Regenerating our infrastrcture everyday
brings the following advantages:

- Any injected trojans or malicious scripts are removed.
- Having fresh new servers every 24 hours let us avoid
  availability and performance issues generated by
  memory leaks and non-released resources.
- The capability of deploying our infrastructure
  from 0 to production in an automated process.

=== 10.2 Immutable

The infrastructure code can be audited and changes can only be made
by changing such code. This provides full transparency
on what was changed, when and who did it.
Also, no administrative protocols like ssh
or administrative accounts are needed.

=== 10.3 Always available

[inner]#link:../products/integrates[Integrates]#
is hosted in a Kubernetes cluster with
autoscaling policies and distributed
replicas. This ensures high availability,
as the there is always an instance ready to
recieve user requests in case another stops
working. Every cluster node has
[inner]#link:../products/integrates[Integrates]#
running in it.

== 11. We hack ourselves

We have full-time projects focused on hacking our own software.
To us, seting an example of secure software is essential,
that is why today,
our entire technological stack goes through a
[inner]#link:../services/continuous-hacking[Continuous Hacking]#
process.

== 12. Secure Chat

We use a messaging system with
link:https://en.wikipedia.org/wiki/Off-the-Record_Messaging[OTR]
and
link:https://en.wikipedia.org/wiki/End-to-end_encryption[E2EE]
for communication within the organization.
Also, all chat histories reset on a weekly basis as
an extra measure to avoid leaks.

== 13. Transparent cookie usage

Both [inner]#link:../products/integrates[Integrates]#
and [inner]#link:../[Web]#
utilize a GDPR cookie plugin that:

- Informs the user about
  every cookie the page creates
- Lets the user specify
  which ones to allow,
  thus giving the user full control
  over what information we're creating
  and manipulating within her browser

By doing this, we become compliant with
security rules like:

- [inner]#link:../rules/189/[Specify the purpose of data collection]#
- [inner]#link:../rules/314/[Provide processing confirmation]#
- [inner]#link:../rules/315/[Provide processed data information]#

== 14. Information security culture

This section provides details
regarding all the best practices
we follow in order to have a strong
information security culture.

=== 14.1 All our hired personnel must accept a NDA

Everyone within our company knows
how important it is to keep our
clients's information secure.
We enforce this by requiring
all our new employees to sign a
Non disclosure agreement.

=== 14.2 Poligraph tests

We continuously run poligraph checks on all
employees with access to sensitive information.
The test fully focuses on identifying
if an employee disclosed such data
to a third party.

=== 14.3 Extensive hiring process

All job applicans must go through
an extense [inner]#link:../careers[testing process]# in order to prove
their technical capabilities and human values.

=== 14.4 Employee time tracking software

We use a time tracking system that takes periodical
screnshots from laptop screens when
employees are working. Only managers have access to such
screenshots in case an incident happens. Employees
have control over the software, which means once they
stop working, no screen recording occurs.

=== 14.5 Audit reports of every employee

Our collaboration systems,
like mail, document editors, calendar, etc.
Have detailed reports on employees activities,
allowing us to keep full track
of what they do within the collaboration platforms.

=== 14.6 Everyone has a standard laptop

A standard laptop is given to every employee,
allowing us to sieze the computer should the
need arise. All laptops have a password-secured BIOS,
link:https://docs.microsoft.com/en-us/windows/security/information-protection/tpm/trusted-platform-module-overview[TPM]
hardware and biometric fingerprint reader.
BYOD is not allowed.

=== 14.7 No physical keys to our offices

All our offices have digital locks.
Every employee has her own password to open the doors.
All successful and failed access attempts are logged.

=== 14.8 Only Wifi

We only use wifi connections with strong random generated passwords.
Connections are always encrypted using WPA2-AES

=== 14.9 We only hire directly

All our employees have indefinite time contracts
directly with the company.
Due to the nature of our business, we never
hire through contractors, freelance or any
other third parties.

== 15. Data policies

The following policies apply to all the information
provided by a client in a project context.

=== 15.1 Data use policy

We are commited to use our clients data
exclusively for vulnerability seeking
in the context of the service we are providing.
No other activities will be executed
over the provided information.

=== 15.2 Data retention policy

All the data related to a project
can be deleted from
[inner]#link:../products/integrates[Integrates]#
by a user with a project manager role.
Once this action is triggered, a deletion window of 30 days begins.
Any project manager can undo the deletion action.
After the 30 days waiting period, the project,
source code, secrets, metadata and any other project related
data is completely removed from all our infrastructure.

=== 15.3 Data leakeage policy

In case Fluid Attacks detects a breach,
emails notyifing the involved parties will be sent.
Emails will contain information on what data was leaked or compromised,
when and for how long (to the extent this information is available).
For a breach that exposes private data for a large number of users,
the public will also be informed via email.
