:slug: security/
:description: This page summarizes all the best practices and technology Fluid Attacks implements in order to keep internal products and customer data secure. It goes from philosophies as having open source code, to particular ciphering algorithms used and internal behavioral policies.
:keywords: Fluid Attacks, Security, Data, Policy, Breach, Best practices
:subtitle: How we keep things secure

= Security

As a security company,
Fluid Attacks is aware of the importance of:

. Having honesty, team work and discipline
  as immovable principles.
  Our full manifest can be found
  [inner]#link:..values/[here]#
. Developing products
  that comply with the highest worldwide security standards.
. Aquiring only compliant services and products for internal use.
. Implementing best security practices within our organization.
. Being completely transparent with our clients,
  especially regarding their data: how we use it,
  and what we do to protect it.

This concerns,
concieved since the early days of the company,
have allowed us to implement
a huge number of measures
throughout the years.
In this page we will mention
the ones that provide the highest
value to our customers in
terms of security.

== 1. Open Source

The source code of all our applications
is available to the entire Internet.
There are no backdoors or exposed sensitive data.
The code is transparent and can be reviewed by anyone.
All our source code can be found
link:https://gitlab.com/fluidattacks[here]

== 2. Encryption

We offer both
encryption at rest
and encryption in transit
with cutting-edge industry standards.

=== 2.1 Encryption at rest

All our applications and services have
industry-standard encryption at rest.

- All the sesitive data provided by our clients
  (Repo access keys, vpn credentials, etc)
  is ciphered using our key management system KMS
  symmetric algorithm
  based on Advanced Encryption Standard (AES)
  in Galois Counter Mode (GCM)
  with 256-bit keys.
- All our clients repositories are
  stored in private, AES256 ciphered
  cloud storage system.
- Forces exploits are stored encrypted using AES256 keys.
- All
  [inner]#link:../products/integrates[Integrates]#
  data is stored in a AES256 encrypted
  non-relational database.
- All our products use our KMS
  for both development and production secrets.
- All our Windows laptops
  have their hard drives encrypted
  using Bitlocker.
  Adherence to this policy is continuously checked
  by a domain controller.
- All our Linux laptos
  have their hard drives encrypted
  from bootloader using LUKS.

=== 2.2 Encryption in transit

All our applications and services have
industry-standard encryption in transit.

- The link:https://fluidattacks.com[Fluid Attacks] domain
  uses the latest TLSv1.3 cryptographic
  protocol for maximum in transit protection.
- [inner]#link:../products/integrates[Integrates]#'s
  DynamoDB database uses TLSv1.2
  for in transit protection.
- We possess fully dedicated channels with some of our biggest clients,
  allowing us to isolate all unwanted traffic. This is especially useful
  for running secure dynamic application hacking.
- For the rest of our clients, we use fully encrypted VPNs.

== 3. Authentication

=== 3.1 For Clients

As
[inner]#link:../products/integrates[Integrates]#
uses SSO with Google and Microsoft Accounts,
we do not store any account passwords.
The only personal information we store of our clients are:

- Full name (Provided by Google or Microsoft).
- Company and cellphone (Only if shared, user can decide).

It is also worth noting that once a user losses her
corporate email, she also loses access to her
[inner]#link:../products/integrates[Integrates]#
account. Allowing clients to easily manage
who has and who does not have access to
their projects.

=== 3.2 Internal

Our IAM is a centralized authentication platform,
allowing us to manage all the applications
we internally use from just one place. Our employees do
not know any of the passwords of the managed applications,
they only know their own IAM passphrase.
Once they log in to IAM,
they can access applications assigned to them.

Some of our IAM specifications and requirements are:

- Passphrases instead of passwords
  (More information [inner]#link:..blog/requiem-password/[here]#).
- Passphrases expire every 90 days.
- Previous passphrases can only be reused after a 24 reset cycle.
- Multi-factor authentication from a mobile device must be
  set. Our MFA uses
  link:https://doubleoctopus.com/security-wiki/authentication/out-of-band-authentication/[OOB],
  which reduces risk in case a comunnication channel becomes compromised.
- In case a mobile phone supports biometric authentication,
  our IAM enforces its usage.
- All successful sessions have a duration of 9 hours.

== 4. Authorization

=== 4.1 For Clients

[inner]#link:../products/integrates[Integrates]#
has a set of roles that are necessary on every hacking project,
providing project managers with the ability
to assign the minimum required permissions
to each team member.
Some of these roles are:
hacker, admin, releaser, escaper,
user, project manager, etc.

=== 4.2 Internal

Every application we use must have user-granular authorization settings
in order to grant minimum-privilege policy at all times.
Some examples are:

- IAM and KMS:
  These two tools are widely used within Fluid Attacks.
  They allow us to ensure
  that hackers can only access source code,
  environments, exploits and secrets
  from projects they have access to.
  Access can be easily removed
  should the need arise,
  with no users/passwords leaked.
  These tools also let us keep application
  production secrets hidden from developers
  (Production-Development secrets separation).
- IAM:
  we can grant application access on a user level.
  Granting us the ability to give employees access
  only to what they need to execute their tasks.
  Giving or removing access to applications
  is simple, and no users/passwords are leaked.


== 5. Secret rotation

Key rotation is of the essence when dealing with
sensitive data. The best way to prevent a key leakage is by
regularily changing it . We continuously rotate:

- KMS keys
- JWT Tokens
- Digital Certificates
- IAM passphrases.

== 6. Infrastructure

=== 6.1 Regenerable

All our infrastructure is in the cloud.
The only hardware we manage are our employee's laptops.

Having everything in the cloud allows us to keep
the entirety of our infrastructure written as code.
Providing us with the ability to recreate our infrastructure
in a daily basis,
destroying any possible
trojans or malicious injected scripts in the process.

=== 6.2 Immutable

Due to all our infrastructure being completely written as code,
Everything in it can be audited and changes can only be made
by changing such code. This provides full transparency
on what was changed, when and who did it.
Also, no administrative protocols like ssh
or administrative accounts are needed.

== 7. We hack ourselves

We have full-time projects focused on hacking our own software.
To us, seting an example of secure software is essential,
that is why today,
our entire technological stack goes through a
link:../services/continuous-hacking[Continuous Hacking]
process.

== 8. Secure Chat

We use link:https://rocket.chat/[Rocket.chat]
with link:https://en.wikipedia.org/wiki/Off-the-Record_Messaging[OTR]
and
link:https://en.wikipedia.org/wiki/End-to-end_encryption[E2EE]
for messaging within the organization.
Also, all chat histories reset on a weekly basis as
an extra measure to avoid leaks.

== 9. Information security culture

=== 9.1 All our hired personnel must accept a NDA

Everyone within our company knows
how important it is to keep our
clients's information secure.
We enforce this by requiring
all our new employees to sign a
Non disclosure agreement.

=== 9.2 Poligraph tests

We continuously run poligraph checks on all
employees with access to sensitive information.
The test fully focuses on identifying
if an employee disclosed such data
to a third party.

=== 9.3 Extensive hiring process

All job applicans must go through
an extense [inner]#link:../careers[testing process]# in order to prove
their technical capabilities and human values.

=== 9.4 Employee time tracking software

We use a time tracking system that takes periodical
screnshots from laptop screens when
employees are working. Only managers have access to such
screenshots in case an incident happens. Employees
have control over the software, which means once they
stop working, no screen recording occurs.

=== 9.5 Everyone has a standard laptop

A standard laptop is given to every employee,
allowing us to sieze the computer should the
need arise. All laptops have a password-secured BIOS,
link:https://docs.microsoft.com/en-us/windows/security/information-protection/tpm/trusted-platform-module-overview[TPM]
hardware and biometric fingerprint reader.
BYOD is not allowed.

=== 9.6 No physical keys to our offices

All our offices have digital locks.
Every employee has her own password.
All successful and failed access attempts are logged.

=== 9.7 Only Wifi

We only use wifi connections with strong random generated passwords.
Connections are always encrypted using WPA2-AES

=== 9.8 We only hire directly

All our employees have indefinite time contracts
directly with the company.
Due to the nature of our business, we never
hire through contractors, freelance or any
other third parties.

== 10. Data policies

The following policies apply to all the information
provided by a client in a project context.

=== 10.1 Data use policy

We are commited to use our clients data
exclusively for vulnerability seeking
in the context of the service we are providing.
No other activities will be executed
over the provided information.

=== 10.2 Data retention policy

All the data related to a project
can be deleted from
[inner]#link:../products/integrates[Integrates]#
by a user with a project manager role.
Once this action is triggered, a deletion window of 30 days begins.
Any project manager can undo the deletion action.
After the 30 days waiting period, the project,
source code, secrets, metadata and any other project related
data is completely removed from all our infrastructure.

=== 10.3 Data leakeage policy

In case Fluid Attacks detects a breach,
emails notyifing the involved parties will be sent.
Emails will contain information on what data was leaked or compromised,
when and for how long (to the extent this information is available).
For a breach that exposes private data for a large number of users,
the public will also be informed via email.
