:slug: productos/rules/
:category: productos
:description: El propósito de esta página es presentar los productos ofrecidos por Fluid Attacks. Rules es una recopilación de criterios de seguridad desarrollados por Fluid Attacks, basados en diferentes estándares internacionales para garantizar la seguridad de la información en diferentes áreas.
:keywords: Fluid Attacks, Productos, Rules, Criterios, Seguridad, Aplicaciones.

= Rules

[role="tb-product"]
[cols="^.^", frame="none"]
|====

a|+Rules+ es un conjunto de requisitos de seguridad
que permiten parametrizar un hackeo
según el apetito al riesgo de cada organización.
+Rules+ permite determinar qué se prueba y qué no,
qué es una vulnerabilidad y qué no,
adicionalmente es la base para determinar
qué tan riguroso fue un hackeo
basado en los requisitos probados y no probados.
Los requisitos de seguridad son independientes del tipo de tecnología
y son redactados como objetivos concretos y comprensibles.
De alguna forma son los mandamientos
que usted se compromete a cumplir
y por ende en nuestro servicios de hacking determinamos
si estos se cumplen o no.

a|Puedes acceder al producto

a|[button]#link:../../rules/[aquí]#
|====

== Estándares

Rules está basado en diversos estándares
relacionados a la seguridad informática
entre los que se incluyen:

. [button]#link:../../search.html?q=HIPAA[HIPAA]#
Ley de Responsabilidad y Transferibilidad de Seguros Médicos
(link:https://www.hhs.gov/hipaa/for-professionals/security/laws-regulations/index.html[Health Insurance Portability and Accountability Act]).

. [button]#link:../../search.html?q=ASVS[ASVS]#
Estándar de +OWASP+ para la verificación de seguridad en aplicaciones
(link:https://www.owasp.org/index.php/Category:OWASP_Application_Security_Verification_Standard_Project[Application Security Verification Standard]).

. [button]#link:../../search.html?q=CWE[CWE]#
Enumeración de vulnerabilidades comunes
(link:https://cwe.mitre.org/[Common Weakness Enumeration]).

. [button]#link:../../search.html?q=NIST+800-53[NIST]#
link:https://nvd.nist.gov/800-53/Rev4[NIST Special Publication 800-53 (Rev. 4)].

. [button]#link:../../search.html?q=bssim9[BSSIM9]#
link:https://www.bsimm.com/download.html[Building Security In Maturity Model].
