:slug: categories/
:description: Here you can find the different techniques used by Fluid Attacks to detect security vulnerabilities in your applications, infrastructure, and source code.
:keywords: SAST, DAST, MPT, Pentesting, SCA, Reverse Engineering, PTaaS, Ethical Hacking
:phrase: At Fluid Attacks, we are ready to employ diverse techniques that complement each other and constitute an effective package for identifying cybersecurity vulnerabilities.
:template: indexof
:arrow: image:../theme/images/arrow-btn.svg[Young hacker smiling, width=15px, height=15px]

= Categories

== SAST
We offer you the SAST technique for rapid vulnerability detection
at any stage of your Software Development Lifecycle.
SAST is a form of white-box testing working on non-running
software and is compatible with a diversity of programming languages. +
[button]#link:sast/[Go to SAST {arrow}]#

== DAST
We provide you with the DAST technique for the identification
of vulnerabilities in running applications. DAST is a form of
black-box testing in which software weaknesses show a close
connection to data, configuration, and business logic,
no matter the programming language. +
[button]#link:dast/[Go to DAST {arrow}]#

== MPT
We can perform Manual Penetration Testing (MPT) simulating
real attacks to exploit security vulnerabilities that are
difficult to identify by automatic methods. Through MPT,
we can guarantee the reduction of rates of false positives
and negatives achieved by machines. +
[button]#link:mpt/[Go to MPT {arrow}]#

== SCA
We have SCA among our techniques, a method for discovering
cybersecurity risks related to open-source and third-party
components you use in your software and systems.
With SCA, we can inform you about licenses, versions,
and security weaknesses in all these components. +
[button]#link:sca/[Go to SCA {arrow}]#

== RE
We possess certified hackers with the ability to deconstruct
your software through the complex technique of
Reverse Engineering (RE). RE mixes different methods and can
give our hackers a broad understanding of your systems and
applications' security to identify vulnerabilities. +
[button]#link:re/[Go to RE {arrow}]#

== PTaaS
We offer you the PTaaS model that goes beyond traditional Pentesting.
PTaaS joins our Continuous Hacking service and is supported by our
vulnerability management platform. We provide you with constant
comprehensive testing of your software, mixing manual
and automatic operations. +
[button]#link:ptaas/[Go to PTaaS {arrow}]#
