:slug: kb/apache/configurar-soporte-https/
:eth: no
:category: apache
:kb: yes

= Configurar Soporte HTTPS

== Necesidad

Configurar un canal seguro para el envío de información atravesar de formularios 
Web Configurar soporte HTTPS en Apache

== Contexto

A continuación se describen las circunstancias bajo las cuales la siguiente 
solución tiene sentido:

. Se requiere la transmisión de información por un canal seguro a través de una 
página Web.
. Asegurar la confidencialidad de datos cifrando su contenido con SSL.

== Solución

. Instalar el SSL en el sistema operativo y el modulo de soporte para 
servidores Apache
. Debian y derivados
+
[source, bash, linenums]
----
apt-get install mod_ssl openssl
----

. RedHat y derivados
+
[source, bash, linenums]
----
yum install mod_ssl openssl
----

. Generar clave privada (Para el ejemplo se utiliza algoritmo RSA a 1024 bits)
+
[source, bash, linenums]
----
openssl genrsa -out ca.key 1024
----
 
. Generar CSR (Certificate Signing Request)
+
[source, bash, linenums]
----
openssl req -new -key ca.key -out ca.csr 
# Se autofirma el certificado 
openssl x509 -req -days 365 -in ca.csr -signkey ca.key -out ca.crt
----
 
. Mover los ficheros de la firma que acabamos de generar a las rutas
+
[source, bash, linenums]
----
mv ca.crt /etc/pki/tls/certs 
mv ca.key /etc/pki/tls/private/ca.key 
mv ca.csr /etc/pki/tls/private/ca.csr 
----
 
. Editar el archivo /etc/httpd/conf.d/ssl.conf y buscar los parámetros 
SSLCertificateFile y SSLCertificateKeyFile y asignar los valores.
+
[source, shell, linenums]
----
SSLCertificateFile /etc/pki/tls/certs/ca.crt
SSLCertificateKeyFile /etc/pki/tls/private/ca.key
----
 
.  Crear un host virtual donde se le indicara al servidor Apache donde dirigir 
las peticiones dirigidas al puerto 443 (Peticiones HTTPS). Para esta operación 
se edita el archivo /etc/httpd/conf/httpd.conf y se copia al final
+
[source, shell, linenums]
----
<VirtualHost *:443>
 SSLEngine on
 SSLCertificateFile /etc/pki/tls/certs/ca.crt
 SSLCertificateKeyFile /etc/pki/tls/private/ca.key
 AllowOverride All
 DocumentRoot /var/www/httpsdocs
 ServerName dominio.com
</VirtualHost>
----
 
. Reiniciar el servidor Apache
+
[source, bash, linenums]
/etc/init.d/apache restart

== Referencias

. http://www.linuxhispano.net/2011/02/21/configurar-soporte-https-en-apache/[Configurar soporte HTTPS en Apache]
