:slug: defends/scala/registrar-eventos-bitacoras/
:category: scala
:description: Nuestros ethical hackers explican cómo programar adecuadamente en Scala al registrar eventos importantes en bitácoras. Esto facilita la labor de identificar fallas y ataques potenciales, así como realizar un seguimiento detallado de los archivos e información afectada.
:keywords: Scala, Eventos, Bitácora, Registro, Información, Severidad.
:defends: yes

= Registrar Eventos en Bitácoras

== Necesidad

Registrar eventos en las bitácoras de una aplicación +Scala+

== Contexto

A continuación se describen las circunstancias
bajo las cuales la siguiente solución tiene sentido:

. Se esta desarrollando una aplicación
en lenguaje de programación +Scala v2.10.4+.

. Se desea minimizar el número de dependencias externas
de la aplicación (uso de +frameworks+ de +logging+).

== Solución

. Cada evento que desea grabarse en la bitácora tiene un nivel,
que indica la prioridad o urgencia de dicho evento.
Los niveles en orden descendente de urgencia son <<r2, ^[2]^>>:

* +SEVERE+
* +WARNING+
* +INFO+
* +CONFIG+
* +FINE+
* +FINER+
* +FINEST+

. Adicionalmente existen los siguientes niveles,
con significado solo en tiempo de configuración o despliegue,
y que permiten deshabilitar por completo el registro de evento
o por el contrario habilitar el registro de eventos de todos los niveles. <<r2 , ^[2]^>>

* +OFF+
* +ALL+

. El +API+ estándar de bitácoras de +Java+,
se forma principalmente por el concepto de +logger+,
que corresponde a un nombre de estructura jerárquica
similar a la de los paquetes y clases
y que representa una configuración particular para grabar eventos.

. En el código fuente, el objeto +logger+ correspondiente,
es obtenido mediante:
+
[source, scala, linenums]
----
...
val logger = Logger.getLogger(this.getClass().getName())
...
----

. Para grabar eventos asociados al +logger+ existen dos opciones.
La primera, mas corta, involucra el nivel del evento
en el nombre de la función:
+
.logger.scala
[source, scala, linenums]
----
...
  logger.severe("evento")
  logger.warning("evento")
  logger.info("evento")
  logger.config("evento")
  logger.fine("evento")
  logger.finer("evento")
  logger.finest("evento")
...
----

. El segundo involucra el nivel como un parámetro adicional.
+
[source, scala, linenums]
----
...
  logger.log(Level.SEVERE, "evento")
  logger.log(Level.WARNING, "evento")
  logger.log(Level.INFO, "evento")
  logger.log(Level.CONFIG, "evento")
  logger.log(Level.FINE, "evento")
  logger.log(Level.FINER, "evento")
  logger.log(Level.FINEST, "evento")
...
----

. Se recomienda el uso de la primera opción,
por su mantenibilidad y legibilidad.
Adicionalmente, para cualquiera de las dos alternativas,
existen versiones de las funciones
que reciben como parámetro las excepciones
generadas en una clausula +try-catch+.
+
[source, scala, linenums]
----
...
  logger.warning("evento", e)
  logger.log(Level.WARNING, "evento", e)
...
----

. A continuación se presenta un ejemplo
de uso completo del +API+ de bitácoras en cuestión:
+
[source, java, linenums]
----
import java.util.logging.{Logger,Level}

object Main {
    val logger = Logger.getLogger(this.getClass().getName())
    def main(args: Array[String])
    {
        logger.setLevel(Level.WARNING)
        logger.warning("Comenzando el main")
        try {
            println("Hola")
            var i = 0/0;
        } catch {
            case e: Exception => logger.severe("Problemas dentro del main")
        }
        logger.info("No se mostrará por no tener nivel WARNING o superior: Finalizando el main")
    }
}
----

. Se observa la salida:
+
[source, scala, linenums]
----
% scala LogEvents.scala
dic 23, 2015 3:19:34 PM Main$ main
WARNING:: Comenzando el main
Hola
dic 23, 2015 3:19:35 PM Main$ main
SEVERE: Problemas dentro del main
----

. Nótese que sólo los mensajes con nivel de depuración de +INFO+ o superiores,
como es el caso de +SEVERE+, fueron mostrados.

. La configuración de los +loggers+ se define primero
por los valores por defecto que se encuentran en +lib/logging.properties+
en el directorio del +JRE+.
Adicionalmente se pueden definir +loggers+ particulares
mediante la invocación de la máquina virtual con los siguientes parámetros:
+
[source, scala, linenums]
----
...
scala -Djava.util.logging.config.file=mylogging.properties <class>
...
----

. Este archivo de propiedades que determina la configuración
de cada +logger+ permite determinar el nivel de los eventos
que efectivamente se registrarán para cada +logger+ en dicho momento.
El siguiente ejemplo muestra como se define
que se registren todos los eventos para el +logger+ en cuestión:
+
[source, java, linenums]
----
...
com.FLUIDSignal.level = ALL
...
----

. En ambientes de desarrollo la recomendación anterior es ideal,
sin embargo para ambientes de producción se recomienda utilizar niveles
que contengan solo el nivel de detalle necesario
y que no incluyan eventos de depuración.
Esta recomendación ayudará a mantener el rendimiento de la aplicación
y el tamaño de las bitácoras en valores apropiados.

== Referencias

. [[r1]] link:../../../rules/075/[REQ 075: Registrar eventos en bitácoras].

. [[r2]] link:../../../rules/078/[REQ 078: Eventos con severidad deshabilitados].

. [[r3]] link:https://medium.com/el-acordeon-del-programador/logs-en-java-con-java-util-logging-d344ae2ba7bc[Logs en Java con Java.util.logging].
