:slug: rules/186/
:category: system
:description: This requirement establishes the importance of applying the principle of least privilege when accessing systems and assigning permissions.
:keywords: Principle, Least, Privilege, NIST, ASVS, CWE, PCI DSS, Rules, Ethical Hacking, Pentesting
:rules: yes

= R186. Use the principle of least privilege

== Requirement

The principle of least privilege must be applied when creating new objects and
roles, setting access permissions, and accessing other systems.

== Description

Systems should usually have a set of roles with different levels of
privilege for accessing resources.
Users and applications should always have a role with the minimum level of
privilege required to execute their functions.
A violation of this may become a new vulnerability or leverage for causing a
greater impact when exploiting other vulnerabilities.

== Findings

* [inner]#link:/web/findings/031/[F031. Excessive privileges]#

* [inner]#link:/web/findings/101/[F101. Lack of protection against deletion]#

== References

. [[r1]] link:https://cwe.mitre.org/data/definitions/250.html[CWE-250: Execution with Unnecessary Privileges].
The software performs an operation at a privilege level that is higher than the
minimum level required,
which creates new weaknesses or amplifies the consequences of other weaknesses.

. [[r2]] link:https://cwe.mitre.org/data/definitions/269.html[CWE-269: Improper Privilege Management].
The software does not properly assign, modify, track, or check privileges for
an actor,
creating an unintended sphere of control for that actor.

. [[r3]] link:https://cwe.mitre.org/data/definitions/272.html[CWE-272: Least Privilege Violation].
The elevated privilege level required to perform operations such as *chroot()*
should be dropped immediately after the operation is performed.

. [[r4]] link:https://cwe.mitre.org/data/definitions/276.html[CWE-276: Incorrect Default Permissions].
The product, upon installation, sets incorrect permissions for an object that
exposes it to an unintended actor.

. [[r5]] link:https://cwe.mitre.org/data/definitions/285.html[CWE-285: Improper Authorization].
The software does not perform or incorrectly performs an authorization check
when an actor attempts to access a resource or perform an action.

. [[r6]] link:https://cwe.mitre.org/data/definitions/732.html[CWE-732: Incorrect Permission Assignment for Critical Resource].
The product specifies permissions for a security-critical resource in a way
that allows that resource to be read or modified by unintended actors.

. [[r7]] link:https://nvd.nist.gov/800-53/Rev4/control/AC-6[NIST 800-53 AC-6]
The organization employs the principle of least privilege,
allowing only authorized accesses for users
(or processes acting on behalf of users)
which are necessary to accomplish assigned tasks
in accordance with organizational missions and business functions.

. [[r8]] link:https://owasp.org/www-project-top-ten/OWASP_Top_Ten_2017/Top_10-2017_A5-Broken_Access_Control[OWASP Top 10 A5:2017-Broken Access Control].
Restrictions on what authenticated users are allowed to do are often not
properly enforced.
Attackers can exploit these flaws to access unauthorized functionality and/or
data, such as access other users’ accounts, view sensitive files,
modify other users’ data, change access rights, etc.

. [[r9]] link:https://owasp.org/www-project-application-security-verification-standard/[OWASP-ASVS v4.0.1
V1.2 Authentication Architectural Requirements.(1.2.1)]
Verify the use of unique or special low-privilege operating system accounts for
all application components, services, and servers.

. [[r10]] link:https://owasp.org/www-project-application-security-verification-standard/[OWASP-ASVS v4.0.1
V1.4 Access Control Architectural Requirements.(1.4.3)]
Verify enforcement of the principle of least privilege in functions,
data files, **URL**s, controllers, services, and other resources.
This implies protection against spoofing and elevation of privilege.

. [[r11]] link:https://owasp.org/www-project-application-security-verification-standard/[OWASP-ASVS v4.0.1
V4.1 General Access Control Design.(4.1.3)]
Verify that the principle of least privilege exists - users should only be able
to access functions, data files, **URL**s, controllers, services, and other
resources, for which they possess specific authorization.
This implies protection against spoofing and elevation of privilege.

. [[r12]] link:https://owasp.org/www-project-application-security-verification-standard/[OWASP-ASVS v4.0.1
V4.1 General Access Control Design.(4.1.4)]
Verify that the principle of deny by default exists whereby new users/roles
start with minimal or no permissions and users/roles do not receive access to
new features until access is explicitly assigned.

. [[r13]] link:https://owasp.org/www-project-application-security-verification-standard/[OWASP-ASVS v4.0.1
V10.2 Malicious Code Search.(10.2.2)]
Verify that the application does not ask for unnecessary or excessive
permissions to privacy related features or sensors, such as contacts, cameras,
microphones, or location.

. [[r14]] link:https://owasp.org/www-project-application-security-verification-standard/[OWASP-ASVS v4.0.1
V14.2 Dependency.(14.2.6)]
Verify that the attack surface is reduced by sandboxing or encapsulating third
party libraries to expose only the required behavior into the application.

. [[r15]] link:https://www.pcisecuritystandards.org/documents/PCI_DSS_v3-2-1.pdf[PCI DSS v3.2.1 - Requirement 3.4.1]
If disk encryption is used
(rather than file- or column-level database encryption),
logical access must be managed separately and independently of native operating
system authentication and access control mechanisms
(for example, by not using local user account databases or general network
login credentials).

. [[r16]] link:https://www.pcisecuritystandards.org/documents/PCI_DSS_v3-2-1.pdf[PCI DSS v3.2.1 - Requirement 3.5.2]
Restrict access to cryptographic keys to the fewest number of custodians
necessary.
