:slug: careers/technical-challenges/
:category: careers
:description: The main goal of the following page is to inform potential talents and people interested in working with us about our selection process. The technical challenges stage intends to assess the competences of the candidate through programming and hacking exercises.
:keywords: Fluid Attacks, Careers, Selection, Process, Technical Challenges, Training.
//:toc: yes

= Technical Challenges

This stage is parallel to the other stages of the process and
therefore, the more progress you make on it now,
the greater the probability is
of being evaluated before the other participants
once the other stages finish.

It can also be considered as a kind of lifesaver in the process,
because you may not have graduated yet,
have no previous work experience,
or get a low score on your knowledge test,
but if you able to successfully finish this stage,
you will show that you have the most valuable competence of all:
The ability to learn new things on the fly and
apply them to solve real problems.
This, along with human warmth and strong [button]#link:../../values[values]#,
have more weight than everything else.

== 1. Philosophy

In this stage, we want you to evidence your technical skills
through practical exercises and problems
similar to the ones you will face in +Fluid Attacks+.

The technical challenges are divided into
+vbd-hacking+, +ctf-hacking+ and +programming+ challenges.
With the former, you demonstrate your skill to bypass security controls.
With the second one, you demonstrate your adaptation skills
when it comes to solving problems in unknown environments.
With the latter, you show that you are able
to quickly understand source code,
and thus it will be easier for you to audit it.

By solving challenges,
we look forward to:

. Promote the solution of unresolved challenges.

. Encourage self-directed and independent learning

By uploading your solutions to +GitLab+, you will be able to:

. Use the +GitLab+ infrastructure to analyze
your efficiency and work quality as you adapt to the process.

. From early stages,
familiarize with the tools
(+Git+, +AsciiDoc+, +Python+, +Gherkin+, etc) and
concepts (automation, unit tests, continuous integration, +linting+, etc.) that
you will use in your daily work in +Fluid Attacks+.

. Make your results visible to the community and
the team.

== 2. Objectives

. Solve +3+ unique +programming+ challenges.

. Solve +3+ unique +ctf-hacking+ challenges.

. Solve +3+ unique +vbd-hacking+ challenges.

== 3. Recommendations

. When solving +programming+ challenges,
We recommend [button]#link:https://www.codeabbey.com/[Codeabbey]#.
Also, we suggest using a language that is not widely used.

. When solving +ctf-hacking+ challenges,
we recommend [button]#link:https://www.root-me.org/?lang=en[Root Me]#

. Submit your solution immediately after you solve the challenge.
Do not accumulate solutions on your computer without sending them,
because this way,
you will never receive feedback
in order to know what you are doing wrong

== 4. Stage steps

To successfully finish this stage, you must:

. Register on +GitLab+ using your personal email and
a username of your liking.
Your username must not exceed *12* characters in length and
only contain lowercase letters and numbers.

. Join our link:https://join.slack.com/t/autonomicmind/shared_invite/enQtMzU0MDc3NzQwNzI2LTQ1NTZmMDFhZjJmZDQ0ZGRmN2M5MGQ3N2JhYjg0ZTI4OWFkZGJmMjdkYzBjYmU2ZDM1NGI0MmM4OGQxOWVlNDc[Slack channel],
where you can interact with +Fluid Attacks+ personnel and
other candidates who are currently in the same stage
to solve doubts or issues.

. Request developer permissions  to the +Training+ repository through this
[button]#link:https://fluidattacks.com/forms/access[form]#.

. In the +Repo Access Message+ field, paste the following message, replacing
+[username]+ with the +Gitlab+ username created in step 1.
+
[quote]
____________________________________________________________________
I have read and understood all documentation pertaining to technical challenges,
I agree to all of the terms and
therefore request access to the +git+ +training+ repository
with my +GitLab+ username [username].
____________________________________________________________________

. Complete +three (3)+ +programming+ challenges

. Complete +three (3)+ +ctf-hacking+ challenges

. Request developer permissions to the +Writeups+ repository through this
[button]#link:https://fluidattacks.com/forms/access[form]#.
+
This time around, the +Repo Access Message+ field should have the following:
+
[quote]
____________________________________________________________________
I have completed three (3) +programming+ and three (3) +ctf-hacking+ challenges
in the training repo
therefore request access to the +git+ +writeups+ repository
with my +GitLab+ username [username].
____________________________________________________________________

. Complete +three (3)+ +vbd-hacking+ challenges
in the +writeups+ repository

== 5. Conditions

The challenge stage ends under any of the following conditions:

. You have met all link:#objectives[objectives] and
Sent an +email+ with the links to your solutions in the +master+ branch.
. If there is no activity (+push+ to the +git+ repos) in +14+ calendar days.
. If you explicitly manifest your desire to end the process in an +email+.
. If you present someone else’s complete or
partial solutions as your own (plagiarism).
. If you solve a challenge with the help of others.

In all cases, the email address for these steps is: careers@autonomicmind.com

If you were removed from the process due to any of these circumstances,
except for the last two,
You may apply again at any time
and start over the process by clicking
[button]#link:../../../../forms/aplicacion[here]#

== 6. Questions

* Before you send us a question,
please read this document carefully once more and
our link:../faq/[Frequently Asked Questions].

* You can tell us your doubts and
questions in our *#general*
link:https://join.slack.com/t/autonomicmind/shared_invite/enQtMjg4ODI4NjM3MjY3LWUxMTNmMjk3MDdkMDAzYWY0ZjQ3MzNlYjUzZjM3NTM3MDVmYTliN2YyNGViZGUyNzUxOTAzNTdmZDQ5NWNjNGI[Slack channel].

== 7. Property

* The proprietary rights of all content
in the repositories are defined in the files:

** link:https://gitlab.com/fluidattacks/writeups/blob/master/COPYRIGHT.txt[writeups COPYRIGHT].
** link:https://gitlab.com/autonomicmind/training/blob/master/COPYRIGHT.txt[training COPYRIGHT].

* The license and privileges that users of the repositories have
are defined in the files:

** link:https://gitlab.com/fluidattacks/writeups/blob/master/LICENSE.txt[writeups LICENSE].
** link:https://gitlab.com/autonomicmind/training/blob/master/LICENSE.txt[training LICENSE].

* Carrying out a +merge request+ implies the transfer of copyrights.
Therefore, all information contained herein may be used
by +Fluid Attacks+ for any commercial purpose,
always preserving the moral rights of their authors.

== 8. Plagirism

Having the solutions available at everyones disposal
poses an opportunity for plagiarism,
How do we show the solutions to the world and avoid plagiarism?
Plagiarism is not a technical problem,
It is a moral problem of presenting someone else’s work
as your own.

To avoid plagiarism we seek visibility and
an explicit declaration of the authorship of each algorithm
in a centralized place.
This provides clear evidence of the attribution of authorship and
allows for public scrutiny in case of plagiarism.

In other words, the current model avoids plagiarism
through total transparency.

+Fluid Attacks+ actively applies algorithmic similarity detection techniques
on all solutions submitted.
In particular using:

* link:https://theory.stanford.edu/~aiken/moss/[MOSS]
* link:https://en.wikipedia.org/wiki/Plagiarism_detection[Plagiarism Detection Theory]
* link:https://www.plagaware.com/[PlagAware]
* link:https://www.safe-corp.com/products_codematch.htm[Code Match]

== 9. Submission

Now that you know all the rules
and have a general understanding
of why these challenges are important,
you can proceed to the [button]#link:https://gitlab.com/fluidattacks/writeups/wikis/Submission[Submission guide]#
and start posting your solutions. Good luck!

== 10. keywords

. +ToE+: link:https://docs.marklogic.com/6.0/guide/cc/toe[Target Of Evaluation]
. +VBD+: Vulnerable by design
. +CTF+: link:https://ctftime.org/ctf-wtf/[Capture The Flag]
