:slug: kb/aspnet/implementar-esquemas-autorizacion/
:eth: no
:category: aspnet
:kb: yes

= Implementar Esquemas de Autorización

== Necesidad

Implementar esquemas de autorización en ASP.Net

== Contexto

A continuación se describe las circunstancias bajo las cuales la siguiente solución tiene sentido:

. Se está desarrollando una aplicación en ASP.Net.

== Solución

. Cuando se ejecuta la aplicación Web , solicita recursos del servidor Web y , a menudo , de otros procesos , así como una base de datos . El proceso de ASP.NET se ejecuta en un contexto de usuario que determina cómo la aplicación solicitará esos recursos. El proceso de ASP.NET se ejecuta como un usuario local especial denominado ASPNET (por defecto ) en Windows 2000 y Windows XP Professional Edition, o se ejecuta como la identidad del grupo de aplicaciones para la aplicación ASP.NET en Windows 2003 ( por defecto, el cuenta de servicio de red local) . Estas cuentas se ejecutan con permisos limitados. Puede especificar un contexto de usuario diferente para el proceso de ASP.NET, incluyendo la cuenta del sistema local (que se ejecuta la aplicación en el contexto de administrador ) o un usuario cuyas credenciales que proporcione explícitamente , aunque esto no es recomendable .En su aplicación ASP.NET, se puede especificar que los diferentes usuarios han autorizado el acceso a los diferentes recursos . Si la aplicación está utilizando la autenticación de Windows , puede utilizar permisos de Windows para determinar la autorización para acceder a los archivos o carpetas en el servidor.Como alternativa, puede utilizar la autorización basada en URL , en el que la autorización puede ser concedida o denegada según diferentes criterios : 

* Usuarios específicos, o identidades, que se basan en las credenciales proporcionadas por el usuario.

* Roles, que son entidades definidas para permitir que varios usuarios compartir los privilegios sobre la base de un rol o función común.

* Los verbos, que son los procesos de HTTP (como GET y POST) para acceder a partes de la aplicación.

. Por ejemplo, puede especificar que todos los usuarios pueden obtener páginas (realizar GET) de la aplicación, pero que sólo determinados usuarios pueden publicar páginas a la misma. Del mismo modo, es posible especificar que todos los usuarios se les permite OBTENER páginas, pero los roles específicos se les niega el derecho a publicar.

. Puede otorgar autorización de direcciones URL de la aplicación en su conjunto o en forma de directorio por directorio. Un uso típico es permitir que todos los usuarios puedan ver las páginas en un directorio público, pero para mantener las páginas restringidas en un directorio diferente que está autorizado sólo para los usuarios o roles específicos.

. La autorización determina si una identidad que debe darse acceso a un recurso específico. En ASP.NET, hay dos maneras de autorizar el acceso a un recurso dado:   

* La autorización de archivos: La autorización de archivos se realiza por el FileAuthorizationModule. Comprueba la lista de control de acceso (ACL) del archivo de controlador. Aspx o. Asmx para determinar si un usuario debe tener acceso al archivo. Permisos de ACL se verifican para Windows identidad del usuario (si está habilitada la autenticación de Windows) o la identidad de Windows del proceso de ASP.NET. Para obtener más información, vea Suplantación de ASP.NET.

* La autorización de direcciones URL:  La  autorización URL se realiza por el UrlAuthorizationModule, que asigna usuarios y funciones de las direcciones URL de las aplicaciones ASP.NET. Este módulo se puede utilizar para permitir o denegar el acceso a partes arbitrarias de una aplicación (normalmente directorios) para los usuarios o roles específicos de forma selectiva.

. Utilizar la autorización de URL: Con autorización de direcciones URL, puede permitir o denegar el acceso a un directorio en particular por nombre de usuario o rol explícitamente. Para ello, se crea una sección de autorización en el fichero de configuración para ese directorio. Para habilitar la autorización de URL, debe especificar una lista de usuarios o funciones de los elementos de permitir o denegar la autorización de la sección de un archivo de configuración. Los permisos establecidos para un directorio también se aplican a los subdirectorios, a menos que los archivos de configuración en un subdirectorio anulan ellos. A continuación se muestra la sintaxis de la sección de autorización:
+
[source, xml, linenums]
----
<authorization>
  <[allow|deny] users roles verbs />
</authorization>
----

. El permitir o denegar el elemento es requerido. Debe especificar los usuarios o roles del atributo. Ambos se pueden incluir, pero ambos no son obligatorios. El atributo verbos es opcional. Los elementos allow y deny otorgan y revocan el acceso, respectivamente. Cada elemento soporta los atributos mostrados en la tabla siguiente:
+
|===
|*Atributo* | *Descripción*

|users
|Identifica las identidades específicas (cuentas de usuario) para este elemento.Los usuarios anónimos se identifican con un signo de interrogación (?). Puede especificar todos los usuarios autenticados con un asterisco (*).

|roles
|Identifica una función (un objeto RolePrincipal) para la solicitud actual que se permite o deniega el acceso al recurso. 

|verbs
|Define los verbos HTTP a los que se aplica la acción, como GET, HEAD y POST. El valor predeterminado es "*", que especifica todos los verbos.

|===

. El siguiente ejemplo permite el acceso a la identidad Kim y miembros de la función Administradores, y niega el acceso a la identidad de Juan (a menos que la identidad de John está incluido en la función Administradores) y para todos los usuarios anónimos:
+
[source, xml, linenums]
<authorization>
  <allow users="Kim"/>
  <allow roles="Admins"/>
  <deny users="John"/>
  <deny users="?"/>
</authorization>

. El ejemplo siguiente permite que todos los usuarios realizar un HTTP GET para un recurso, pero sólo permite la identidad Kim realizar una operación POST: 
+
[source, xml, linenums]
----
<authorization>
  <allow verbs="GET" users="*"/>
  <allow verbs="POST" users="Kim"/>
  <deny verbs="POST" users="*"/> 
</authorization>
----
+
Las reglas se aplican de la siguiente manera: 

. Reglas que figuran en los archivos de configuración a nivel de aplicación tienen prioridad sobre las reglas heredadas. El sistema determina qué norma prevalece en la construcción de una lista combinada de todas las reglas de una URL, con las normas más recientes (los más cercanos en la jerarquía) a la cabeza de la lista.

. Dado un conjunto de reglas combinadas para una aplicación, ASP.NET se inicia en la cabeza de la lista y comprueba las reglas hasta que se encuentra la primera coincidencia. La configuración predeterminada de ASP.NET contiene un elemento users="*"> <allow, que  autoriza a todos los usuarios. (De forma predeterminada, esta regla se aplica pasada.) Si no hay otra normativa autorización partido, se permite la solicitud. Si se encuentra una coincidencia, y el partido es un elemento deny, la solicitud se devuelve con el código de estado HTTP 401. Si un elemento permiten partidos, el módulo permite que la petición se procesa adicionalmente.
 
== Referencias

. https://msdn.microsoft.com/en-us/library/yfe5dwc2(v=vs.100).aspx[Seguridad en la autenticación ASP.NET]
. https://msdn.microsoft.com/en-us/library/wce3kxhd(v=vs.100).aspx[Autorización ASP.NET]
