:slug: products/rules/list/266/
:category: architecture
:description: This requirement establishes the importance of disabling or controlling system functions that could be harmful to the application.
:keywords: Insecure, Functionality, System, Hardening, ASVS, CAPEC, CWE, OWASP, PCI DSS, Rules, Ethical Hacking, Pentesting
:rules: yes

= R266. Disable insecure functionalities

== Requirement

The organization must disable or carefully control the insecure functions of a
system (system hardening).

== Description

Sometimes platforms include functionalities that are not required or could be
harmful for some applications built on top of or residing in them.
Other times, applications are developed including functionalities that allow
actions that could be considered insecure.
All these functionalities should be disabled or otherwise controlled to prevent
them from compromising the system's security.
Furthermore, the system must enforce those controls on trusted enforcement
points such as access control gateways, severs and serverless functions.

== Findings

* [inner]#link:/products/rules/findings/014/[F014. Insecure functionality]#

* [inner]#link:/products/rules/findings/044/[F044. Insecure HTTP methods enabled]#

* [inner]#link:/products/rules/findings/047/[F047. Automatic information enumeration]#

* [inner]#link:/products/rules/findings/055/[F055. Insecure service configuration]#

* [inner]#link:/products/rules/findings/056/[F056. Anonymous connection]#

* [inner]#link:/products/rules/findings/101/[F101. Lack of protection against deletion]#

* [inner]#link:/products/rules/findings/110/[F110. HTTP request smuggling]#

* [inner]#link:/products/rules/findings/111/[F111. Out-of-bounds Read]#

* [inner]#link:/products/rules/findings/115/[F115. Security controls bypass]#

* [inner]#link:/products/rules/findings/116/[F116. XS-Leaks]#

== References

. [[r1]] link:http://capec.mitre.org/data/definitions/161.html[CAPEC-161: Infrastructure Manipulation].
An attacker exploits characteristics of the infrastructure of a network entity
in order to perpetrate attacks or information gathering on network objects or
effect a change in the ordinary information flow between network objects.

. [[r2]] link:https://cwe.mitre.org/data/definitions/284.html[CWE-284: Improper Access Control]
The software does not restrict or incorrectly restricts access to a resource
from an unauthorized actor.

. [[r3]] link:https://cwe.mitre.org/data/definitions/602.html[CWE-602: Client-Side Enforcement of Server-Side Security]
The software is composed of a server that relies on the client to implement a
mechanism that is intended to protect the server.

. [[r4]] link:https://cwe.mitre.org/data/definitions/749.html[CWE-749: Exposed Dangerous Method or Function]
The software provides an Applications Programming Interface (API) or similar
interface for interaction with external actors,
but the interface includes a dangerous method or function that is not properly
restricted.

. [[r5]] link:https://owasp.org/www-project-top-ten/OWASP_Top_Ten_2017/Top_10-2017_A5-Broken_Access_Control[OWASP Top 10 A5:2017-Broken Access Control].
Restrictions on what authenticated users are allowed to do are often not
properly enforced.
Attackers can exploit these flaws to access unauthorized functionality and/or
data, such as access other users' accounts, view sensitive files,
modify other users' data, change access rights, etc.

. [[r6]] link:https://owasp.org/www-project-top-ten/OWASP_Top_Ten_2017/Top_10-2017_A6-Security_Misconfiguration[OWASP Top 10 A6:2017-Security Misconfiguration].
Security misconfiguration is the most commonly seen issue.
This is commonly a result of insecure default configurations,
incomplete or ad hoc configurations, open cloud storage,
misconfigured *HTTP* headers,
and verbose error messages containing sensitive information.
Not only must all operating systems, frameworks, libraries, and applications be
securely configured, but they must be patched/upgraded in a timely fashion.

. [[r7]] link:https://owasp.org/www-project-application-security-verification-standard/[OWASP-ASVS v4.0.1
Appendix C: Internet of Things Verification Requirements.(C.1)]
Verify that application layer debugging interfaces such *USB*, *UART*,
and other serial variants are disabled or protected by a complex password.

. [[r8]] link:https://owasp.org/www-project-application-security-verification-standard/[OWASP-ASVS v4.0.1
Appendix C: Internet of Things Verification Requirements.(C.4)]
Verify that on-chip debugging interfaces such as *JTAG* or *SWD* are disabled
or that an available protection mechanism is enabled and configured
appropriately.

. [[r9]] link:https://owasp.org/www-project-application-security-verification-standard/[OWASP-ASVS v4.0.1
Appendix C: Internet of Things Verification Requirements.(C.11)]
Verify that any use of banned *C* functions are replaced with the appropriate
safe equivalent functions.

. [[r10]] link:https://owasp.org/www-project-application-security-verification-standard/[OWASP-ASVS v4.0.1
V1.4 Access Control Architectural Requirements.(1.4.1)]
Verify that trusted enforcement points such as at access control gateways,
servers, and serverless functions enforce access controls.
Never enforce access controls on the client.

. [[r11]] link:https://owasp.org/www-project-application-security-verification-standard/[OWASP-ASVS v4.0.1
V4.1 General Access Control Design.(4.1.1)]
Verify that the application enforces access control rules on a trusted service
layer,
especially if client-side access control is present and could be bypassed.

. [[r12]] link:https://owasp.org/www-project-application-security-verification-standard/[OWASP-ASVS v4.0.1
V6.2 Algorithms.(6.2.5)]
Verify that known insecure block modes (i.e. *ECB*, etc.), padding modes
(i.e. **PKCS#1** v1.5, etc.), ciphers with small block sizes
(i.e. **Triple-DES**, *Blowfish*, etc.), and weak hashing algorithms
(i.e. *MD5*, *SHA1*, etc.) are not used unless required for backwards
compatibility.

. [[r13]] link:https://owasp.org/www-project-application-security-verification-standard/[OWASP-ASVS v4.0.1
V9.1 Communications Security Requirements.(9.1.3)]
Verify that old versions of *SSL* and *TLS* protocols, algorithms, ciphers, and
configuration are disabled,
such as *SSLv2*, *SSLv3*, or *TLS* 1.0 and *TLS* 1.1.
The latest version of *TLS* should be the preferred cipher suite.

. [[r14]] link:https://owasp.org/www-project-application-security-verification-standard/[OWASP-ASVS v4.0.1
V14.2 Dependency.(14.2.2)]
Verify that all unneeded features, documentation, samples, configurations are
removed,
such as sample applications, platform documentation, and default or example
users.

. [[r15]] link:https://owasp.org/www-project-application-security-verification-standard/[OWASP-ASVS v4.0.1
V14.5 Validate HTTP Request Header Requirements.(14.5.1)]
Verify that the application server only accepts the *HTTP* methods in use by
the application or *API*, including pre-flight *OPTIONS*.

. [[r16]] link:https://www.pcisecuritystandards.org/documents/PCI_DSS_v3-2-1.pdf[PCI DSS v3.2.1 - Requirement 2.2.2]
Enable only necessary services, protocols, daemons, etc.,
as required for the function of the system.

. [[r17]] link:https://www.pcisecuritystandards.org/documents/PCI_DSS_v3-2-1.pdf[PCI DSS v3.2.1 - Requirement 2.2.5]
Remove all unnecessary functionality, such as scripts, drivers, features,
subsystems, file systems, and unnecessary web servers.

. [[r18]] link:https://www.pcisecuritystandards.org/documents/PCI_DSS_v3-2-1.pdf[PCI DSS v3.2.1 - Requirement 6.5.8]
Address common coding vulnerabilities in software-development processes
including improper access control
(such as insecure direct object references, failure to restrict URL access,
directory traversal, and failure to restrict user access to functions).
