:slug: rules/317/
:category: privacy
:description: This document contains the details of the security requirements related to the management and protection of data privacy in the organization. This requirement establishes the importance of allowing the users to request erasure of data belonging to them.
:keywords: Requirement, Security, Data, GDPR, Erasure, Personal
:rules: yes

= REQ.317 Allow erasure requests

== Requirement

The system must allow users to request erasure of data belonging to them
that it is managing.

== Description

Systems usually request information from the users,
obtain it from third parties or collect it based on their interactions with the
application.
They should have a mechanism that allows users to request the erasure of this
information and guarantees its complete deletion.
Furthermore, the erasure should also occur if the user decides to revoke their
consent.

== Exceptions

. If the system is able to demonstrate that it is not possible to individually
identify the users based on the information collected from them,
this requirement is not applicable.

== References

. [[r1]] link:https://gdpr-info.eu/art-11-gdpr/[GDPR. Art. 11: Processing which does not require identification.(2).]
Where the controller is able to demonstrate that it is not in a position to
identify the data subject,
articles 15 to 20 shall not apply.

. [[r2]] link:https://gdpr-info.eu/art-17-gdpr/[GDPR. Art. 17: Right to erasure (‘right to be forgotten’).(1).]
The data subject shall have the right to obtain from the controller the erasure
of personal data concerning him or her without undue delay and the controller
shall have the obligation to erase personal data without undue delay.
