:slug: values/
:description: This page sets the expectations regarding the behaviour of partners, employees and allies in everyday situations. FLUID is committed to always having an integral and correct behaviour and expects all members to act in accordance with the law and company policies.
:keywords: FLUID, Values, Policies, Ethics, Protection, Information.
:translate: valores/

= Values

== 1. Purpose and Scope

This page sets the expectations
regarding the behaviour of partners, employees and allies in everyday situations.
FLUID is committed to always having an integral and correct behaviour
and expects all members to act in accordance with the law and company policies.
Understanding and compliance is expected from everyone.
The failure to meet the principles hereby stated could imply
penalties and/or criminal sanctions
and could result in the end of all relations with FLUID.

== 2. Principles

FLUID is a Colombian company that firmly believes and stands by their principles,
they are proudly promoted and defended.
Our principles are not negotiable.

Here they are in order of priority:

* *HONESTY*, for FLUID the truth is the greater good and always prevails over everything else.
Everyone´s words and actions must reflect legitimacy,
fraud is considered a very serious fault.
* The *TEAM*, All results in FLUID are achieved through the collaborative work of all the staff. It is a team effort.
Therefore, we promote a dignified and respectful treatment for everyone with equality of opportunities.
* *DISCIPLINE*, understood as the sum of the fulfillment of all commitments, dedication, effort and perseverance.

== 3. Ethics

In our company, the process is more important than the result.
This is why we reject and frown upon any type bribe, monopolies or disloyal competition.
On the contrary,
we favor fair business practices the same way we promote all support to our employees and allies.

Each and everyone of our employees is affiliated to social security for 100% of their salaries.
Our business hours are within the legal boundaries established by Colombian law,
however, in the cases where hours are exceeded, employees may request compensation.
We reject child labor.

== 4. Safekeeping of Information

We are permanently monitoring and managing the risks associated with the information of our clients.

== 5. Problems and Complaints

All matters related to the breach of our values
can be reported through etica@fluidattacks.com

