:slug: rules/160/
:category: source
:description: This requirement establishes the importance of encoding system outputs in the corresponding language.
:keywords: Encoding, Outputs, Escaping, BSIMM9, ASVS, CWE, Rules, Ethical Hacking, Pentesting
:rules: yes

= R160. Encode system outputs

== Requirement

The system output must be encoded in the corresponding language (*escaping*).

== Description

System components use structured messages to communicate with other components.
When this messages include input from untrusted sources and this input is not
properly escaped,
they become prone to the insertion of malicious commands.
For this reason, enconding or escaping must occur before sending the messages.

== References

. [[r1]] link:https://cwe.mitre.org/data/definitions/20.html[CWE-20: Improper Input Validation].
The product does not validate or incorrectly validates input that can affect
the control flow or data flow of a program.

. [[r2]] link:https://cwe.mitre.org/data/definitions/79.html[CWE-79: Cross-site Scripting].
The software does not neutralize or incorrectly neutralizes user-controllable
input before it is placed in output that is used as a web page that is served
to other users.

. [[r3]] link:https://cwe.mitre.org/data/definitions/116.html[CWE-116: Improper Encoding or Escaping of Output].
The product does not validate or incorrectly validates input that can affect
the control flow or data flow of a program.

. [[r4]] link:https://cwe.mitre.org/data/definitions/176.html[CWE-176: Improper Handling of Unicode Encoding].
The product does not validate or incorrectly validates input that can affect
the control flow or data flow of a program.

. [[r5]] link:https://www.bsimm.com/framework/deployment/software-environment.html[BSIMM9 SE3.2 Use code protection].

. [[r6]] link:https://owasp.org/www-project-application-security-verification-standard/[OWASP-ASVS v4.0.1
V1.5 Input and Output Architectural Requirements.(1.5.3)]
Verify that input validation is enforced on a trusted service layer.

. [[r7]] link:https://owasp.org/www-project-application-security-verification-standard/[OWASP-ASVS v4.0.1
V1.5 Input and Output Architectural Requirements.(1.5.4)]
Verify that output encoding occurs close to or by the interpreter for which it
is intended.

. [[r8]] link:https://owasp.org/www-project-application-security-verification-standard/[OWASP-ASVS v4.0.1
V5.3 Output encoding and Injection Prevention Requirements.(5.3.1)]
Verify that output encoding is relevant for the interpreter and context
required.
For example, use encoders specifically for *HTML* values, *HTML* attributes,
JavaScript, URL Parameters, *HTTP* headers, *SMTP*, and others as the context
requires, especially from untrusted inputs
(e.g. names with Unicode or apostrophes, such as ねこ or O'Hara).

. [[r9]] link:https://owasp.org/www-project-application-security-verification-standard/[OWASP-ASVS v4.0.1
V5.3 Output encoding and Injection Prevention Requirements.(5.3.2)]
Verify that output encoding preserves the user's chosen character set and
locale,
such that any Unicode character point is valid and safely handled.

. [[r10]] link:https://owasp.org/www-project-application-security-verification-standard/[OWASP-ASVS v4.0.1
V5.3 Output encoding and Injection Prevention Requirements.(5.3.3)]
Verify that context-aware, preferably automated - or at worst, manual - output
escaping protects against reflected, stored, and *DOM* based *XSS*.

. [[r11]] link:https://owasp.org/www-project-application-security-verification-standard/[OWASP-ASVS v4.0.1
V5.3 Output encoding and Injection Prevention Requirements.(5.3.5)]
Verify that where parameterized or safer mechanisms are not present,
context-specific output encoding is used to protect against injection attacks,
such as the use of *SQL* escaping to protect against *SQL* injection.

. [[r12]] link:https://owasp.org/www-project-application-security-verification-standard/[OWASP-ASVS v4.0.1
V5.3 Output encoding and Injection Prevention Requirements.(5.3.6)]
Verify that the application projects against JavaScript or *JSON* injection
attacks,
including for eval attacks, remote JavaScript includes, *CSP* bypasses,
**DOM XSS**, and JavaScript expression evaluation.

. [[r2]] link:https://owasp.org/www-project-application-security-verification-standard/[OWASP-ASVS v4.0.1
V5.3 Output encoding and Injection Prevention Requirements.(5.3.8)]
Verify that the application protects against *OS* command injection and that
operating system calls use parameterized *OS* queries or use contextual command
line output encoding.
