:slug: products/rules/list/140/
:category: credentials
:description: This requirement establishes the importance of defining a short lifespan for single-use passwords such as access tokens and OTPs.
:keywords: Password, Lifespan, OTP, ASVS, CWE, NIST, OWASP, PCI DSS, Rules, Ethical Hacking, Pentesting
:rules: yes

= R140. Define OTP lifespan

== Requirement

One time passwords (*OTP*) must have a maximum lifespan of *60* seconds.

== Description

*OTP*s are tokens that help hinder phishing (impersonation) attacks.
They should be generated using secure cryptographic algorithms,
be sent over a protected channel and have a short lifespan that considers
network delay and entry time.
Furthermore, it should only be possible to use them once within their validity
period.

== References

. [[r1]] link:https://cwe.mitre.org/data/definitions/287.html[CWE-287: Improper Authentication]
When an actor claims to have a given identity,
the software does not prove or insufficiently proves that the claim is correct.

. [[r2]] link:https://cwe.mitre.org/data/definitions/326.html[CWE-326: Inadequate Encryption Strength]
The software stores or transmits sensitive data using an encryption scheme that
is theoretically sound,
but is not strong enough for the level of protection required.

. [[r3]] link:https://cwe.mitre.org/data/definitions/613.html[CWE-613: Insufficient Session Expiration].
Insufficient Session Expiration is when a web site permits
an attacker to reuse old session credentials or session IDs for authorization.

. [[r4]] link:https://pages.nist.gov/800-63-3/sp800-63b.html[NIST 800-63B 5.1.4.2 Single-Factor OTP Verifiers]
Time-based OTPs SHALL have a defined lifetime that is determined by the
expected clock drift — in either direction — of the authenticator over its
lifetime.

. [[r5]] link:https://pages.nist.gov/800-63-3/sp800-63b.html[NIST 800-63B 5.1.4.2 Single-Factor OTP Verifiers]
The verifier SHALL use approved encryption and an authenticated protected
channel when collecting the OTP in order to provide resistance to eavesdropping
and MitM attacks.

. [[r6]] link:https://pages.nist.gov/800-63-3/sp800-63b.html[NIST 800-63B 5.1.4.2 Single-Factor OTP Verifiers]
In order to provide replay resistance as described in Section 5.2.8,
verifiers SHALL accept a given time-based OTP only once during the validity
period.

. [[r7]] link:https://owasp.org/www-project-top-ten/OWASP_Top_Ten_2017/Top_10-2017_A2-Broken_Authentication[OWASP Top 10 A2:2017-Broken Authentication].
Application functions related to authentication and session management are
often implemented incorrectly,
allowing attackers to compromise passwords, keys, or session tokens,
or to exploit other implementation flaws to assume other users' identities
temporarily or permanently.

. [[r8]] link:https://owasp.org/www-project-application-security-verification-standard/[OWASP-ASVS v4.0.1
V2.8 Single or Multi Factor One Time Verifier Requirements.(2.8.1)]
Verify that time-based *OTP*s have a defined lifetime before expiring.

. [[r9]] link:https://owasp.org/www-project-application-security-verification-standard/[OWASP-ASVS v4.0.1
V2.8 Single or Multi Factor One Time Verifier Requirements.(2.8.3)]
Verify that approved cryptographic algorithms are used in the generation,
seeding, and verification.

. [[r10]] link:https://owasp.org/www-project-application-security-verification-standard/[OWASP-ASVS v4.0.1
V2.8 Single or Multi Factor One Time Verifier Requirements.(2.8.4)]
Verify that time-based *OTP*s can be used only once within the validity period.

. [[r11]] link:https://www.pcisecuritystandards.org/documents/PCI_DSS_v3-2-1.pdf[PCI DSS v3.2.1 - Requirement 6.5.10]
Address common coding vulnerabilities in software-development processes such as
broken authentication and session management.
