:slug: kb/aspnet/configurar-parametro-charset-http/
:eth: no
:category: aspnet
:description: TODO
:keywords: TODO
:kb: yes

= Configurar Parámetro Charset de HTTP

== Necesidad

Establecer Charset en ASP.Net

== Contexto

A continuación se describe las circunstancias 
bajo las cuales la siguiente solución tiene sentido:

. Se está desarrollando en ASP.Net

== Solución

. Las aplicaciones son rara vez probadas 
contra los exploits que usan Unicode,
sin embargo, muchas son vulnerables 
al mismo tipo de problemas 
que permite a un atacante realizar 
un _HTTP Request Smuggling_.

. El _HTTP Request Smuggling_ 
le permite a un atacante 
evadir los controles de un sistema, 
usando codificaciones diferentes, 
para que dos sistemas (usualmente, un WAF y el servidor WEB) 
perciban peticiones HTTP diferentes. 

. La forma normal (_canonical form_) es la representación más simple 
o más estándar de algo. 
El proceso de normalizar las solicitudes 
se encarga de abordar el modo 
en que los sistemas transforman los datos de una forma a otra. 
En sí, normalizar es convertir algo 
desde su estado original 
a una representación más simple. 

. Las aplicaciones Web deben tratar 
con muchos procesos de normalización 
desde la codificación del URL,  
hasta la traducción de las IP. 
Cuando se toman decisiones de seguridad 
basándose en datos normalizados menos que perfectos, 
la aplicación debe ser capaz de manejar 
entradas inesperadas de manera segura. 

. Para evitar los ataques 
que se aprovechan de la normalización, 
se debe seleccionar una forma normal
y modificar todas las entradas de usuario dicha forma 
antes de tomar decisiones de autorización.

. De la misma manera, 
se deben ejecutar pruebas de seguridad 
después de que se ha realizado la decodificación, 
por lo cual se recomienda verificar 
que la codificación usada esté soportada 
para cada símbolo que se presenta. 

. ASP y ASP.Net. _ContentType_ y _Charset_ 
se configuran por separado 
y consisten en métodos del objeto _Response_. 
Para configurar el charset use, por ejemplo:
+
.test.py
[source, html, linenums]
----
<%Response.charset="utf-8"%>
----

. En ASP.Net, la configuración de _Response.ContentEncoding_ 
se hará cargo tanto del parámetro _charset_ del _Content-Type_ de HTTP 
como de la codificación real 
del documento que se envía ,
la cual debe ser, por supuesto, la misma. 
El valor predeterminado puede configurarse 
en el elemento _globalization_ en _Web.config_ 
(o _Machine.config_, que originariamente, se configura en UTF-8). 

. Especificar la codificación: Para configurar la codificación 
en todas las páginas, 
se debe añadir una propiedad globalización 
en el archivo _Web.config_ 
y a continuación, establezca sus atributos _fileEncoding_, 
_requestEncoding_ y _responseEncoding_, 
como se muestra en el siguiente ejemplo:
+
[source,html,linenums]
----
<configuration>
  <system.web>
    <globalization
      fileEncoding="utf-8"
      requestEncoding="utf-8"
      responseEncoding="utf-8"
      culture="en-US"
      uiCulture="de-DE"
    />
  </system.web>
</configuration>
---- 

. Para establecer la codificación de una página individual, 
establezca los atributos _RequestEncoding_ y _ResponseEncoding_ 
de la directiva _@ Page_, como se muestra en el siguiente ejemplo:
+
[source,html,linenums]
----
<%@ Page RequestEncoding="utf-8" ResponseEncoding="utf-8" %>
----

== Referencias

. https://msdn.microsoft.com/en-us/library/39d1w2xf(v=vs.100).aspx[Cómo seleccionar y codificar para la globalización de páginas Web ASP.NET]
