:slug: kb/aspnet/configurar-parametro-charset-http
:eth: no
:category: aspnet
:kb: yes

= Configurar Parámetro Charset de HTTP

== Necesidad

Establecer Charset en ASP.Net

== Contexto

A continuación se describe las circunstancias bajo las cuales la siguiente solución tiene sentido:

. Se está desarrollando en ASP.Net

== Solución

. Las aplicaciones son rara vez probadas contra los exploits que usan Unicode, y sin embargo, muchas son vulnerables al mismo tipo de problemas que permite a un atacante realizar un "HTTP REQUEST SMUGGLING". El "HTTP REQUEST SMUGGLING" le permite a un atacante evadir los controles de un sistema, usando codificaciones diferentes, para que dos sistemas (usualmente, un WAF y el servidor WEB) perciban peticiones HTTP diferentes.

. La forma única significa la forma más simple o más estándar de algo. El proceso de normalizar las solicitudes se encarga de abordar la manera en que los sistemas transforman los datos de una forma a otra. En sí, normalizar es convertir algo desde su representación original a una forma más simple. Las aplicaciones Web deben lidiar con muchos procesos de normalización desde la codificación del URL hasta la traducción de las IP.

. Cuando se toman decisiones de seguridad basándose en datos normalizados menos que perfectos, la aplicación debe ser capaz de lidiar con entradas inesperadas de manera segura. Para evitar los ataques que se aprovechan de la normalización, se debe seleccionar una forma única y todas las entradas de usuario deben ser modificados a esa forma antes de tomar decisiones de autorización. Se debe realizar pruebas de seguridad después de que se ha realizado la decodificación. Se recomienda verificar que la codificación usada esté soportada para cada simbolo que se presenta. 

. ASP y ASP.Net. ContentType y charset se configuran por separado y consisten en métodos del objeto Response. Para configurar el charset use, por ejemplo:

[source, html, linenums]
----
<%Response.charset="utf-8"%>
----

. En ASP.Net, la configuración de Response.ContentEncoding se hará cargo tanto del parámetro charset del Content-Type de HTTP como de la codificación real del documento que se envía (la cual debe, por supuesto, ser la misma). El valor predeterminado puede configurarse en el elemento globalization en Web.config (o Machine.config, que, originariamente, se configura en UTF-8). 

Para especificar la codificación
[start = 1]

. Para configurar la codificación para todas las páginas, añadir una propiedad globalización en el archivo Web.config y, a continuación, establezca su fileEncoding, requestEncoding y responseEncoding atributos, como se muestra en el siguiente ejemplo:

[source,html,linenums]
----
<configuration>
  <system.web>
    <globalization
      fileEncoding="utf-8"
      requestEncoding="utf-8"
      responseEncoding="utf-8"
      culture="en-US"
      uiCulture="de-DE"
    />
  </system.web>
</configuration>
---- 
[start = 2]
. Para establecer la codificación de una página individual, establezca los atributos _RequestEncoding_ y _ResponseEncoding_ de la directiva @ Page, como se muestra en el siguiente ejemplo:

[source,html,linenums]
----
<%@ Page RequestEncoding="utf-8" ResponseEncoding="utf-8" %>
----

== Referencias

. https://msdn.microsoft.com/en-us/library/39d1w2xf(v=vs.100).aspx[Cómo seleccionar y codificar para la globalización de páginas Web ASP.NET]
