:slug: productos/commands/
:category: productos
:description: Commands es un producto de tipo troyano con command & control utilizado para realizar Ethical Hacking ofensivo en equipos críticos. Busca tomar control total de múltiples sistemas críticos para crear una red de nodos infectados que pueda ser controlada desde un centro de mando y control.
:keywords: Fluid Attacks, Productos, Commands, Seguridad, Pentesting, Aplicaciones.

= Commands

Troyano desarrollado completamente por +Fluid Attacks+
para penetrar en profundidad estaciones de trabajo
y servidores críticos durante el Ethical Hacking
en nuestro servicio de [button]#link:../../servicios/hacking-puntual/[Hacking Puntual]#
donde su uso es autorizado.

[role="integrates tb-alt"]
[cols=3, frame="topbot"]
|====
2+a|== Objetivo

En Fluid Attacks no estamos únicamente interesados en encontrar
y reportar una vulnerabilidad, sino también en mostrar a nuestros clientes
los riesgos potenciales que esta implica
y el impacto de negocio que tiene.
Para esto, buscamos tomar el control total de multiples sistemas criticos
y así crear una red de nodos infectados
para obtener información sensible o infectar aún más nodos.
a|image::objetivo.svg[Code spreading throughout several servers]

a|image::metodo.svg[Arrows entering a computer]
2+a|== Como lo hacemos

Para poder usar +FLUIDCommands+
primero necesitamos tener acceso administrativos al sistema vulnerable,
esto lo logramos a través de procesos de hacking manual
que ejecutan nuestros expertos.
Una vez se logre el acceso administrativo
podemos proceder a infectar remotamente la máquina.
Teniendo un nodo comprometido y bajo nuestro control
podemos expandirnos e infectar otros nodos
o concentrarnos en la máquina comprometida
para penetrar en profundidad en busca de información sensible
y vectores de ataque más críticos.

2+a|== Cero Efectos Colaterales

Es importante resaltar que nuestro troyano +FLUIDCommands+
nunca queda instalado en el sistema vulnerable
como un servicio ni como una tarea programada.
Una vez hayan finalizado el Ethical Hacking,
se desinstala remotamente
sin dejar rastro alguno ni efectos colaterales.
a|image::cero-efectos.svg[Skull symbol with a check mark]

a|image::control.svg[Control console]
2+a|== Centro de Mando y Control

+FLUIDCommands+ cuenta con su propio Centro de Mando y Control
desde el cual se pueden enviar órdenes y comandos
a nuestra red de nodos infectados.
El Centro de Mando y Control usa una comunicación cifrada
a través de un proxy reverso ICMP,
dándonos siempre control total sobre nuestro troyano.
Con un solo nodo infectado,
+FLUIDCommands+ puede replicarse en sistemas adjacentes.

2+a|== Función de Captura

* Captura de pantalla: A través del comando +scr+ podemos tomar pantallazos
de la máquina infectada sin alertar la víctima.
* Captura de Audio: Usando el comando +mic+ podemos abrir el micrófono
de la víctima y capturar audio en vivo.
* +Keylogger+: El comando +keylog+ nos permite capturar y +logear+ todas
las teclas presionadas en la máquina de la víctima
para luego extraer información sensible como credenciales
o números de tarjetas de crédito.
a|image::captura.svg[Square focusing on a screen]

a|image::exec.svg[Execution of the psexec command]
2+a|== Función Exec

Esta función nos permite ejecutar de manera remota cualquier comando disponible
a través del +cmd+ en la máquina infectada.


2+a|== Función echo

Este comando se usa para probar la conexión
y garantizar que tengamos control sobre el nodo infectado.
Responde todo lo que se le pase como parametro al comando.
a|image::echo.svg[Execution of the echo command]

a|image::evasion.svg[Skull symbol with a hidden sign]
2+a|== Evasión de Detección

Nuestro troyano siempre evita ser detectado
por todo tipo de controles
+AntiX+ y +SOC+
enmascarando todas sus peticiones y comandos
bajo un protocolo conocido y de confianza.

|====
