:slug: rules/229/
:category: rules
:description: This document contains the details of the security requirements related to the definition and management of access credentials in the organization. This requirement establishes the importance of requesting access credentials in order to validate the authentication process.
:keywords: Requirement, Security, Architecture, Automated, Testing, Deploy.
:rules: yes
:translate: rules/229/

= REQ.229 Request access credentials

== Requirement

The system must request at least one username and password
to every actor that tries to authenticate.

== References

. [[r1]] link:https://www.law.cornell.edu/cfr/text/45/164.312[+HIPAA Security Rules+ 164.312(a)(1):]
Access Control: Implement technical policies and procedures
for electronic information systems
that maintain electronic protected health information
to allow access only to those persons or software programs
that have been granted access rights as specified in link:https://www.law.cornell.edu/cfr/text/45/164.308[164.308(a)(4)]

. [[r2]] link:https://www.law.cornell.edu/cfr/text/45/164.312[+HIPAA Security Rules+ 164.312(d):]
Person or Entity Authentication:
Implement procedures to verify  that a person or entity
seeking access to electronic protected health information
is the one claimed.

. [[r3]] link:https://www.law.cornell.edu/cfr/text/45/164.310[+HIPAA Security Rules+ 164.310(a)(2)(iii):]
Access Control and Validation Procedures: Implement procedures
to control and validate a person's access to facilities
based on their role or function, including visitor control,
and control of access to software programs for testing and revision.
