:slug: rules/099/
:category: rules
:description: En el presente documento se detallan los requerimientos de seguridad relacionados a la gestion segura en cuanto al control de acceso en una organizacion. Por lo tanto, se recomienda que toda organización controle el acceso de vehículos y personas en las zonas de parqueo.
:keywords: Activos, Control, Organización, Acceso, Personas, Vehículos.
:rules: yes

= REQ.099 Controlar acceso vehícular y de personas

== Requisito

La organización debe llevar control de acceso de vehículos
y personas en las zonas de parqueaderos.

== Referencias

. [[r1]] link:https://www.law.cornell.edu/cfr/text/45/164.310[+HIPAA Security Rules+ 164.310(a)(1)]
Controles de acceso a las instalaciones:
Implementar políticas y procedimientos para limitar
el acceso físico a la instalación o instalaciones
donde se almacenan sistemas electrónicos con información sensible,
verificando que todo acceso sea autorizado

. [[r2]] link:https://www.law.cornell.edu/cfr/text/45/164.310[+HIPAA Security Rules+ 164.310(a)(2)(ii):]
Plan de Seguridad en las Instalaciones:
Implementar políticas y procedimientos para salvaguardar
las instalaciones y los equipos
de accesos no autorizados, manipulación y robo.

. [[r3]] link:https://www.law.cornell.edu/cfr/text/45/164.310[+HIPAA Security Rules+ 164.310(a)(2)(iii):]
Procedimientos de control de acceso y validación:
Implementar procedimientos para controlar y validar
el acceso de una persona a las instalaciones basándose
en su rol o función, incluyendo control de visitantes
y control de acceso a software de la compañía
para pruebas o revisión.
