:slug: products/rules/
:category: products
:description: The purpose of this page is to present the products offered by Fluid Attacks. Rules is a recompilation of several security criteria developed by Fluid Attacks. based on different international standards in order to assure information security in different areas of the company.
:keywords: Fluid Attacks, Products, Rules, Criteria, Security, Applications.
:translate: productos/rules/

= Rules

FLUIDRules is a set of security requirements
that allow you to parameterize a pentest
according to the risk appetite of each organization.
FLUIDRules allows you to determine what will be tested and what won't,
what is a vulnerability and what is not.
In addition to this,
it is also the basis to determine how rigorous a pentest was
based on tested and untested requirements.
The security requirements are independent of the type of technology being used
and are written as specific and understandable objectives.
In a way they are the security commandments
that you agree to follow and comply with and therefore,
in our hacking services, we determine if these are met or not.

== Standards

Rules is based on several standards
related to information security, including:

. [button]#link:../../search.html?q=HIPAA[HIPAA]#
link:https://www.hhs.gov/hipaa/for-professionals/security/laws-regulations/index.html[Health Insurance Portability and Accountability Act.]

. [button]#link:../../search.html?q=ASVS[ASVS]#
link:https://www.owasp.org/index.php/Category:OWASP_Application_Security_Verification_Standard_Project[+OWASP+ Application Security Verification Standard].

. [button]#link:../../search.html?q=CWE[CWE]#
link:https://cwe.mitre.org/[Common Weakness Enumeration].

You can access the product [button]#link:../../rules/[here]#
