:slug: rules/139/
:category: credentials
:description: This requirement is related to the importance of defining the minimum length for one-time passwords within the company's system.
:keywords: Length, Password, OTP, ASVS, CWE, NIST, OWASP, PCI DSS, Rules, Ethical Hacking, Pentesting
:rules: yes

= R139. Set minimum OTP length

== Requirement

One-time passwords must be at least 6 characters long.

== Description

One-time passwords (*OTP*) are secrets used during operations that need added
security or as part of user enrollment processes.
Despite their short lifespan, they should have a minimum length of 6 characters
as a protection against brute force attacks.

== Findings

* [inner]#link:/web/findings/035/[F035. Weak credential policy]#

* [inner]#link:/web/findings/050/[F050. Guessed weak credentials]#

== References

. [[r1]] link:https://cwe.mitre.org/data/definitions/330.html[CWE-330: Use of Insufficiently Random Values].
The software uses insufficiently random numbers or values in a security context
that depends on unpredictable numbers.

. [[r2]] link:https://pages.nist.gov/800-63-3/sp800-63b.html[NIST 800-63B 5.1.1.2 Memorized Secret Verifiers]
Memorized secrets that are randomly chosen by the CSP (e.g., at enrollment)
or by the verifier (e.g., when a user requests a new PIN)
SHALL be at least 6 characters in length
and SHALL be generated using an approved random bit generator.

. [[r3]] link:https://owasp.org/www-project-top-ten/OWASP_Top_Ten_2017/Top_10-2017_A2-Broken_Authentication[OWASP Top 10 A2:2017-Broken Authentication].
Application functions related to authentication and session management are
often implemented incorrectly,
allowing attackers to compromise passwords, keys, or session tokens,
or to exploit other implementation flaws to assume other users' identities
temporarily or permanently.

. [[r4]] link:https://owasp.org/www-project-application-security-verification-standard/[OWASP-ASVS v4.0.1
V2.3 Authenticator Lifecycle Requirements.(2.3.1)]
Verify system generated initial passwords or activation codes SHOULD
be securely randomly generated,
SHOULD be at least 6 characters long.

. [[r5]] link:https://www.pcisecuritystandards.org/documents/PCI_DSS_v3-2-1.pdf[PCI DSS v3.2.1 - Requirement 6.5.10]
Address common coding vulnerabilities in software-development processes such as
broken authentication and session management.
