:slug: conferencias/aseguramiento-moviles/
:category: conferencias
:description: La presente página tiene como objetivo informar a los clientes sobre el servicio de conferencias ofrecido por FLUID. La conferencia de Aseguramiento de Dispositivos Móviles, tiene por objetivo socializar los riesgos a la seguridad que trae consigo el uso de smartphones.
:keywords: FLUID, Conferencia, Seguridad, Dispositivos, Móviles, SmartPhone.

= Aseguramiento de Dispositivos Móviles

== 1. Objetivo

La charla genera un espacio de reflexión ante riesgos a los
cuales está expuesta la información y los usuarios de teléfonos inteligentes.

== 2. Contenido

Durante la charla se repasa un conjunto de riesgos a la información relacionados
con el uso de smartphones de manera que cada asistente pueda conocerlo,
saber sus implicaciones y los controles que podría aplicar si desea tratarlo


== 3. Experiencia

Esta conferencia se ha presentado desde hace 5 años en grandes empresas de la región como:
link:https://www.grupobancolombia.com/wps/portal/personas[Bancolombia], link:https://www.negocioleonisa.com/wps/portal/colombia[Leonisa],
link:http://www.tuya.com.co/[Tuya] y link:http://www.celsia.com/[Celsia].

== 4. ¿Dónde?

Podemos dictar la conferencia a domicilio en sus instalaciones.

Las charlas pueden ser en Medellín con un público de mínimo 10 personas.
Para otras ciudades en Colombia, Centroamérica, Ecuador y Perú se debe contar con 20 asistentes

== 5. Duración

La conferencia tiene una duración de dos horas (Es posible variar su duración entre 1½ horas y 2½ horas).

== 6. Público

La conferencia es apta para público con básico o poco conocimiento técnico.
Deben ser usuarios de smartphone.
El límite de asistentes es 30 personas

== 7. Expositor

Licenciado en Educación, con experiencia de 15 años.
Socio fundador de FLUID.
Auditor de Sistemas de Seguridad de la Información
