from enum import (
    Enum,
)


class Source(str, Enum):
    ASM: str = "ASM"
    ESCAPE: str = "ESCAPE"
    MACHINE: str = "MACHINE"


class StateRemovalJustification(str, Enum):
    DUPLICATED: str = "DUPLICATED"
    EXCLUSION: str = "EXCLUSION"
    FALSE_POSITIVE: str = "FALSE_POSITIVE"
    NO_JUSTIFICATION: str = "NO_JUSTIFICATION"
    NOT_REQUIRED: str = "NOT_REQUIRED"
    REPORTING_ERROR: str = "REPORTING_ERROR"


class CredentialType(str, Enum):
    SSH: str = "SSH"
    HTTPS: str = "HTTPS"


class GitCloningStatus(str, Enum):
    CLONING: str = "CLONING"
    FAILED: str = "FAILED"
    OK: str = "OK"
    QUEUED: str = "QUEUED"
    UNKNOWN: str = "UNKNOWN"


class Notification(str, Enum):
    ACCESS_GRANTED: str = "ACCESS_GRANTED"
    AGENT_TOKEN: str = "AGENT_TOKEN"
    CHARTS_REPORT: str = "CHARTS_REPORT"
    DAILY_DIGEST: str = "DAILY_DIGEST"
    EVENT_REPORT: str = "EVENT_REPORT"
    FILE_UPDATE: str = "FILE_UPDATE"
    GROUP_INFORMATION: str = "GROUP_INFORMATION"
    GROUP_REPORT: str = "GROUP_REPORT"
    NEW_COMMENT: str = "NEW_COMMENT"
    NEW_DRAFT: str = "NEW_DRAFT"
    PORTFOLIO_UPDATE: str = "PORTFOLIO_UPDATE"
    REMEDIATE_FINDING: str = "REMEDIATE_FINDING"
    REMINDER_NOTIFICATION: str = "REMINDER_NOTIFICATION"
    ROOT_UPDATE: str = "ROOT_UPDATE"
    SERVICE_UPDATE: str = "SERVICE_UPDATE"
    UNSUBSCRIPTION_ALERT: str = "UNSUBSCRIPTION_ALERT"
    UPDATED_TREATMENT: str = "UPDATED_TREATMENT"
    VULNERABILITY_ASSIGNED: str = "VULNERABILITY_ASSIGNED"
    VULNERABILITY_REPORT: str = "VULNERABILITY_REPORT"


class SolveEventReason(str, Enum):
    AFFECTED_RESOURCE_REMOVED_FROM_SCOPE: str = (
        "AFFECTED_RESOURCE_REMOVED_FROM_SCOPE"
    )
    OTHER: str = "OTHER"
    PERMISSION_DENIED: str = "PERMISSION_DENIED"
    PERMISSION_GRANTED: str = "PERMISSION_GRANTED"
    PROBLEM_SOLVED: str = "PROBLEM_SOLVED"
    SUPPLIES_WERE_GIVEN: str = "SUPPLIES_WERE_GIVEN"
    TOE_CHANGE_APPROVED: str = "TOE_CHANGE_APPROVED"
    TOE_WILL_REMAIN_UNCHANGED: str = "TOE_WILL_REMAIN_UNCHANGED"
