:slug: rules/273/
:category: system
:description: This requirement establishes the importance of installing a fixed and unalterable security suite in all production workstations.
:keywords: CWE, ASVS, Suite, Workstation, Antivirus, Firewall, Rules, Ethical Hacking, Pentesting
:rules: yes

= R273. Define a fixed security suite

== Requirement

All the workstations in production
must count with an unalterable security suite
(Anti-virus, *Antispyware*, *Host Firewall*, *Host-IDS*, *Host-IPS*).

== Findings

* [inner]#link:/web/findings/077/[F077. ARP spoofing]#

* [inner]#link:/web/findings/084/[F084. MDNS spoofing]#

* [inner]#link:/web/findings/104/[F104. USB flash drive attacks]#

* [inner]#link:/web/findings/115/[F115. Security controls bypass]#

== References

. [[r1]] link:https://cwe.mitre.org/data/definitions/923.html[CWE-923: Improper Restriction of Communication Channel to Intended Endpoints]
The software establishes a communication channel to (or from) an endpoint for
privileged or protected operations,
but it does not properly ensure that it is communicating with the correct
endpoint.

. [[r2]] link:https://owasp.org/www-project-application-security-verification-standard/[OWASP-ASVS v4.0.1
V1.14 Configuration Architectural Requirements.(1.14.1)]
Verify the segregation of components of differing trust levels through
well-defined security controls, firewall rules, API gateways, reverse proxies,
cloud-based security groups, or similar mechanisms.

. [[r3]] link:https://owasp.org/www-project-application-security-verification-standard/[OWASP-ASVS v4.0.1
V12.4 File Storage Requirements.(12.4.2)]
Verify that files obtained from untrusted sources are scanned by antivirus
scanners to prevent upload of known malicious content.
