:slug: rules/132/
:category: rules
:description: En el presente documento se detallan los requerimientos de seguridad relacionados a las credenciales de acceso a información sensible de la organización. En este requerimiento se establece la importancia de definir contraseñas tipo frase de al menos 4 palabras de longitud.
:keywords: Contraseña, Contraseña tipo frase, Longitud contraseña, Palabras de longitud, Secuencia de palabras, Seguridad contraseña.
:rules: yes

= REQ.132 Contraseñas con al menos 4 palabras

== Requisito

Las contraseñas (tipo frase) deben tener al menos 4 palabras de longitud.

== Descripción

El presente criterio de seguridad trata sobre
la importancia de establecer al menos cuatro (4) palabras de longitud
para todas las contraseñas tipo frase.
Entendiendo estas últimas, como una secuencia de palabras<<r1,^[1]^>>
cuya longitud es superior pero de mayor seguridad
que otros tipos de contraseñas.

== Soluciones

La presente sección contiene enlaces a artículos
cuyo contenido es propiedad de `Fluid Attacks`.
El objetivo es dar a conocer al público
la implementación del actual requerimiento de seguridad
para diferentes plataformas o lenguajes de programación:

. *`BLOG`* link:../../../en/blog/requiem-password/[Requiem for a p455w0rD].

== Referencias

. [[r1]] link:https://en.wikipedia.org/wiki/Passphrase[Passphrase - Wikipedia].

. [[r2]] link:https://www.owasp.org/index.php/ASVS_V2_Authentication[`OWASP-ASVS v3.1-2.7`]
Verificar que los campos de entrada de las contraseñas permitan
o sugieran sugieran el uso de contraseñas tipo frase,
y que no se impida la entrada de frases largas o de alta complejidad.

. [[r3]] link:https://www.owasp.org/index.php/ASVS_V2_Authentication[`OWASP-ASVS v3.1-2.27`]
Verificar que existan medidas para bloquear el uso
de contraseñas comunes y `passphrases` débiles.
