:slug: defends/aix/activar-rbac-extendido/
:category: aix
:description: Nuestros ethical hackers explican como evitar vulnerabilidades de seguridad mediante la configuracion segura del modo RBAC incluido en los sistemas AIX, donde un atacante puede aprovecharse de una mala configuración de dicho modo, accediendo a funcionalidades criticas dentro del sistema.
:keywords: AIX, Seguridad, RBAC, CLI, Sistema Operativo, Habilitar.
:defends: yes

= Activar RBAC Extendido

== Necesidad

Activar +RBAC+ extendido en +AIX+.

== Contexto

A continuación se describen las circunstancias
bajo las cuales la siguiente solución tiene sentido:

. Se dispone de un sistema operativo +AIX+ versión 6.1 o superior.
. Se dispone de acceso a la interfaz de comandos (+CLI+) del sistema anterior.
. Se dispone de credenciales de +root+.

== Solución

El modo +RBAC (Role Based Access Control)+ extendido de +AIX+
permite establecer un control de acceso granular,
con el fin de otorgar privilegios administrativos
sobre funciones especificas del sistema operativo.
Lo anterior sin requerir otorgar la contraseña de +root+
o establecer permisos +SUID+.
Donde un permiso o privilegio
es un mecanismo utilizado
para otorgar una funcionalidad extra en las llamadas al sistema.

Es importante resaltar la diferencia entre privilegios y autorizaciones.
Ambos se utilizan para controlar
ciertas excepciones permitidas en la política de seguridad dentro del sistema.
La diferencia entre estos radica en que,
los privilegios se asocian con procesos específicos,
mientras que los segundos
se asocian con los usuarios a través de roles.
Las autorizaciones residen con un rol
y el usuario que tiene el rol,
además no dependen del programa que se está ejecutando.
Por su parte, los privilegios residen en el programa
y proporcionan el mecanismo
para ajustar la política de seguridad del sistema.

Dentro del núcleo (+kernel+) de +AIX+<<r1,^[1]^>>,
los privilegios se definen
como +bits+ individuales de una máscara de +bits+
que controlan el acceso a las operaciones con privilegios.
El +kernel+ determina si el proceso
tiene el +bit+ de privilegios asociado requerido,
para luego conceder o denegar la solicitud.

Los privilegios son asignados a invocaciones de comandos
a través de la base de datos de comandos con privilegios
y dichos privilegios son utilizados
para el control de acceso a dispositivos
por medio de la base de datos de dispositivos con privilegios.

Por lo tanto, en el presente artículo,
se habla sobre el modo +RBAC+ extendido de +AIX+.
Explicando cómo comprobar el estado,
habilitar e inhabilitar a dicho modo:

. El modo +RBAC+ extendido está activado por defecto
en sistemas +AIX+ versión 6.1 o superior<<r2,^[2]^>>.
Pero es posible verificar el estado actual del mismo
ejecutando la siguiente la orden:
+
.test.sh
[source, bash, linenums]
----
% lsattr -E -l sys0 -a enhanced_RBAC
true
----
+
En la salida se observa
que el modo de control de acceso +RBAC+ extendido se encuentra habilitado.

. Para deshabilitar dicho modo
debe ejecutar el siguiente comando:
+
[source, bash, linenums]
----
% chdev -l sys0 -a enhanced_RBAC=false
----
. Finalmente para habilitarlo, debe ejecutar el siguiente comando:
+
[source, bash, linenums]
----
% chdev -l sys0 -a enhanced_RBAC=true
----

== Referencias

. [[r1]] link:https://www.ibm.com/support/knowledgecenter/ssw_aix_61/com.ibm.aix.security/rbac_rbac_privs.htm[RBAC privileges].
. [[r2]] link:https://www.ibm.com/support/knowledgecenter/en/ssw_aix_61/com.ibm.aix.security/rbac_config_mode.htm[Configuring the RBAC mode].
