:slug: products/rules/list/130/
:category: credentials
:description: This requirement establishes that the system must not allow its passwords to have a lifespan of more than 30 days.
:keywords: Password, Validity, Security, Expiration, Limit, CAPEC, CWE, NERC, PCI DSS, Rules, Ethical Hacking, Pentesting
:rules: yes

= R130. Limit password lifespan

== Requirement

Passwords must be valid for a maximum of *30* days.

== Findings

* [inner]#link:/findings/035/[F035. Weak credential policy]#

== References

. [[r1]] link:http://capec.mitre.org/data/definitions/49.html[CAPEC-49: Password Brute Forcing].
In this attack, the adversary tries every possible value for a password until
they succeed.
A brute force attack, if feasible computationally, will always be successful
because it will essentially go through all possible passwords given the
alphabet used (lower case letters, upper case letters, numbers, symbols, etc.)
and the maximum length of the password.

. [[r2]] link:https://cwe.mitre.org/data/definitions/263.html[CWE-263: Password Aging with Long Expiration].
Allowing password aging to occur unchecked can result in the possibility of
diminished password integrity.

. [[r3]] link:https://www.nerc.com/pa/Stand/Reliability%20Standards/CIP-007-6.pdf[NERC CIP-007-6. B. Requirements and measures. R5.6]
Where technically feasible,
for password-only authentication for interactive user access,
either technically or procedurally enforce password changes or an obligation to
change the password at least once every 15 calendar months.

. [[r4]] link:https://www.pcisecuritystandards.org/documents/PCI_DSS_v3-2-1.pdf[PCI DSS v3.2.1 - Requirement 8.2.4]
Change user passwords/passphrases at least once every 90 days.
