:slug: kb/aspnet/comprobar-fortaleza-contrasenas/
:category: aspnet
:description: Nuestros ethical hackers explican como evitar vulnerabilidades de seguridad mediante la configuración segura de contraseñas en ASP.NET, probando su resistencia ante ataques de diccionario.
:keywords: ASP.NET, Diccionario.
:kb: yes
:table-caption: Tabla

= Comprobar Fortaleza de Contraseñas con Diccionarios

== Necesidad

Comprobar fortaleza de contraseñas 
por medio de diccionarios en +ASP.NET+

== Contexto

A continuación se describen las circunstancias bajo 
las cuales la siguiente solución tiene sentido:

. Se está desarrollando una aplicación en +ASP.NET+.
. Se requiere comprobar la fortaleza de una contraseña 
por medio de diccionarios <<r1, ^[1]^>>.
. El sistema operativo o el administrador del sistema 
poseen diccionarios con palabras comunes.

== Solución

. El código dará solución a la necesidad 
de comprobar la fortaleza de una contraseña 
al buscarla en diccionarios que contienen palabras comunes. 
Iniciamos el desarrollo de la aplicación 
importando las clases necesarias 
y definiendo el nombre de nuestra clase:
+
.Dictionary.java
[source,java,linenums]
----
using System.IO;
public class Dictionary {
----

. El método +Main+ será el encargado 
de llamar al método +isPasswordInDictionary+ , 
el cual realiza la búsqueda de la contraseña.
+
[source,java,linenums]
----
   public static void Main(string[] args)
   {
      try 
      {
----

. Establecemos la ruta del diccionario 
y se imprime el resultado.
+
[source,java,linenums]
----
       string dic = "passwords.txt";
       System.Console.WriteLine(isPasswordInDictionary(dic, "123"));
       System.Console.WriteLine(isPasswordInDictionary(dic, "hello"));
       System.Console.WriteLine(isPasswordInDictionary(dic, "admin"));
       System.Console.WriteLine(isPasswordInDictionary(dic, "SystEM"));
       System.Console.WriteLine(isPasswordInDictionary(dic, "Str0n6_P4ssw0rd!"));
----

. Capturamos las excepciones posibles:
+
[source,java,linenums]
----
      } 
      catch (FileNotFoundException e) 
      {
          System.Console.WriteLine("Diccionario no encontrado");
          System.Console.Error.WriteLine(e.Message);
      } 
      catch (IOException e) 
      {
          System.Console.WriteLine("Error de entrada/salida de datos");
          System.Console.Error.WriteLine(e.Message);
      }
    }
----

. El método +isPasswordInDictionary+ es el encargado 
de abrir el archivo de diccionario 
y buscar la contraseña. 
Retornará verdadero si la contraseña 
se encuentra en el diccionario 
y falso en el caso contrario. 
Iniciamos definiendo los parámetros: 
+dictionaryFilePath+ que contiene la ruta al diccionario 
y +password+ que es la contraseña.
+
[source,java,linenums]
----
    public static bool isPasswordInDictionary(string dictionaryFilePath, string password)  
    {
----

. Se abre el archivo de diccionario 
con la clase +StreamReader+, 
la cual permite leer archivos de mucho contenido 
con un buen manejo de memoria. 
Se define igualmente la variable 
que contendrá la palabra leída del diccionario.
+
[source,java,linenums]
----
        StreamReader dictionary = new StreamReader(dictionaryFilePath);
        string word = "";
----

. Se itera a través de cada palabra en el archivo, 
si se encuentra la contraseña en el diccionario
entonces se retorna verdadero, 
en otro caso se retorna falso. 
En este caso estamos limitándonos 
a probar palabras del diccionario con más de dos caracteres, 
para evitar problemas con diccionarios 
que puedan tener letras individuales en la lista de palabras.
+
[source,java,linenums]
----
        while ((word = dictionary.ReadLine()) != null) 
        {
            if (word.Length > 2 && (password.IndexOf(word, System.StringComparison.OrdinalIgnoreCase) >= 0)) 
            {
                return true;
            }
        }
        return false;  
     }
----

. Para +GNU/Linux+ se pueden utilizar 
los diccionarios incluidos con el sistema operativo 
que se encuentran en la ruta +/usr/share/dict/+. 
El resultado para la anterior aplicación es el siguiente:
+
.Resultados del ataque con diccionario.
|===
|*Palabra* | *Resultado*

|"123"|+true+

|"hello"|+true+

|"admin"|+true+

|"SystEM"|+true+

|"Str0n6_P4ssw0rd!"|+false+

|===

== Referencias

. [[r1]] REQ.0126 Las contraseñas (tipo palabra) deben tener al menos 8 caracteres de longitud.
. [[r2]] REQ.0127 Las contraseñas (tipo palabra) deben tener al menos 1 letra minúscula.
. [[r3]] REQ.0128 Las contraseñas (tipo palabra) deben tener al menos 1 letra mayúscula.
. [[r4]] REQ.0129 Las contraseñas (tipo palabra) deben tener al menos 1 dígito.
. [[r5]] REQ.0130 Las contraseñas (tipo palabra) deben tener al menos 1 carácter especial.
. [[r6]] link:http://dazzlepod.com/uniqpass/[Uniqpass Password list].
. [[r7]] link:http://www.openwall.com/wordlists/[Openwall worldlist collection].
. [[r8]] link:http://wordlist.aspell.net/[Spell Checker Oriented Word Lists (SCOWL)].
. [[r9]] link:https://packetstormsecurity.com/Crackers/wordlists/[Packetstorm Security Dictionary].
. [[r10]] link:http://www.deer-run.com/~hal/sysadmin/pam_cracklib.html[Deer Dictionary toolbox].