:slug: services/faq/
:category: services
:description: Our Continuous Hacking service aims to detect and report all the vulnerabilities in your application as soon as possible. In this page we present a recompilation of questions and answers that help understand the Continuous Hacking service and how it can benefit an organization.
:keywords: FLUIDAttacks, Services, Continuos Hacking, Ethical Hacking, FAQ, Questions.
:translate: servicios/faq/

= Frequently asked questions

Frequently asked questions about Continuous Hacking.

[qanda]
*What is Continuous Hacking?*::
  Continuous Hacking is a security testing service
  that allows testing to begin at an early stage
  in the software development cycle.
  Its purpose is to guarantee +100%+ testing coverage of the application.


*What are the benefits of Continuous Hacking?*::
  Continuous Hacking:
  . Minimizes the cost of remediation (repair) of a vulnerable security risk
  while the software is in development rather than when it is in production.

  . Reduces application certification time to zero
  because the tests are done during development.

  . Provides clear and detailed information about vulnerable security risks
  and facilitates a coordinated effort between external project personnel
  (+FLUIDAttacks+ experts) identifying security risks,
  and internal project personnel (client company)
  fixing security issues without delays.

*What are the necessary inputs and requirements for Continuous Hacking?*::
  The necessary inputs and requirements are

  . *Phase 1:* Access to the integration branch of the repository
  for the, not-yet deployed, application’s source code.
  Security testing focuses on the source code.

  . *Phase 2:* When the project has a deployed application
  (Integration Environment) the test coverage expands
  to include application security testing.

  . *Phase 3:* This phase applies only if the infrastructure
  supporting the application is defined as code and kept
  in the integration branch of the repository referred to in Phase 1.
  This phase includes infrastructure security testing.

*What tests are included in Continuous Hacking?*::
  Continuous Hacking includes source code analysis,
  application security testing (<<q3,see question 3>>),
  and infrastructure security testing (<<q3,see question 3>>).

*What are the limits of Continuous Hacking?*::
  Continuous Hacking has a limit of +10,000+ deltas per month
  on the source code.

*What is a vulnerability?*::
  A vulnerability is anything that represents a security risk
  (Integrity, Availability, Confidentiality, Non-repudiation)
  to the application.

*If I expect or want to exceed the monthly limit can I increase it?*::
  Yes, the limit can be increased for any particular month or,
  in general, for the duration of the project.

*Does Continuous Hacking use a series of automated tools*::
*or is it the result of a manual (by hand) process?*::
  Automated tools, by themselves,
  are not capable of extracting sensitive business information,
  such as client or employee information.
  Continuous Hacking uses a series of tools
  acquired and developed by +FLUIDAttacks+ and a detailed review process
  performed by our expert technical staff.
  We go the extra mile because automated tools present the following problems:

  . Detection of a minimal percentage
  of existing security risk vulnerabilities.

  . Detected vulnerabilities are primarily false positives.

  . Incapable of combining individual vulnerabilities
  in order to reveal additional vulnerabilities
  which may be an even greater security risk
  than the individual vulnerabilities alone.

*If Continuous Hacking includes a manual review how does FLUIDAttacks*::
*ensure that development cycles are not slowed down?*::
  Continuous Hacking is first performed on the source code.
  This allows for parallel security testing and development simultaneously.
  This minimizes the dependency on functional environments
  and the need for coordination between hackers and developers.
  The client prioritizes detected vulnerabilities.
  The decisions regarding what findings are prioritized for each sprint
  rest solely with the client.
  Unless we are dealing with a company with daily +CI/CD+
  (Continuous Integration/Continuous Deployment)
  not all sprints generate code eligible for release and deployment,
  which improves the remediation (repair) time for detected vulnerabilities.

*If Continuous Hacking is done manually how can a big project move rapidly*::
*and expand as more developers join the team?*::
  Standard Continuous Hacking (at +10,000+ deltas per month)
  covers +95%+ of all business applications being developed.
  If a big project expands, the standard limit of +10,000+ deltas per month
  can be revised upward as needed. (<<q7, see question 7>>).

*If Continuous Hacking is done manually how does it move rapidly*::
*when a client has a big application portfolio that is constantly increasing?*::
  According to +FLUIDAttacks+ historical data,
  recruitment and training capabilities,
  and our ability to innovate internal processes,
  +FLUIDAttacks+ is fully capable of taking on
  between +5+ and +10+ new applications each month.

*Does the cost of Continuous Hacking vary according to the scope*::
*or development phases?*::
  No, there is a fixed cost for Continuous Hacking during the contract period.
  However, if during your contract period the calendar year changes
  from one year to the next there will be an increase in cost
  to reflect rising business costs.
  This increase will be stated in your contract
  and agreed upon before you sign it; there will be no hidden costs.

*Why is it necessary for Continuous Hacking to have access*::
*to the source code stored in the repository?*::
  Continuous Hacking needs access to the source code
  because it is based on continuous security testing
  of the latest version available.

*When does Continuous Hacking begin?*::
  Continuous Hacking begins immediately when +FLUIDAttacks+
  has access to the source code and repository.

*Is it possible to hire On-the-Premises Continuous Hacking?*::
  No. Due to the operational model that supports Continuous Hacking
  it can only be done remotely.

*Is it possible to schedule follow-up meetings?*::
  Yes. All applications covered by the contract for Continuous Hacking
  are assigned to a specific project leader who is available
  to attend all necessary meetings.
  We simply require sufficient notice of an impending meeting
  in order to schedule availability.

*How is a project’s progress determined?*::
  A project’s progress and current state is determined
  using the following metrics:
  . Source code coverage indicator.
  . Percentage of remediated (repaired) security risk vulnerabilities.

*When does Continuous Hacking end?*::
  Continuous Hacking is contracted for a minimum of +12+ months
  and is renewed automatically at the end of the +12+ month time period.
  Continuous Hacking ends when we receive a written request
  through previously defined channels to terminate the contract.

*Can the contract be canceled at any point in time?*::
  You can cancel your contract at any time after the fourth month.
  Cancellation can be requested through any communication channel
  previously defined in the contract.

*When the coverage of my application reaches 100% is Continuous Hacking*::
*suspended until new code is added to the repository?*::
  No. Even if +100%+ of coverage is reached,
  we continue checking already tested source code to identify
  any possible false negatives,
  including components developed by third parties in our tests.

*How is the severity and criticality of the vulnerability calculated?*::
  +FLUIDAttacks+ uses the link:https://www.first.org/cvss/[CVSS]
  (Common Vulnerability Scoring System),
  an international standard using a “standardized framework used
  to rate the severity of security vulnerabilities in software.”
  It gives us a quantitative measure ranging from +0+ to +10+,
  +0+ being the lowest level of risk and +10+ the highest
  and most critical level of risk based on the qualitative characteristics
  of a vulnerability.

*How do I get information about the vulnerabilities found in my application?*::
  Continuous Hacking has an interactive reporting platform
  called link:../../products/integrates/[Integrates].
  Integrates gives all project stakeholders access
  to details concerning vulnerabilities reported by +FLUIDAttacks+.

*What types of reports does Continuous Hacking generate?*::
  Continuous Hacking generates and delivers,
  through link:../../products/integrates/[Integrates],
  a technical report available in +Excel+ and/or +PDF+ format
  during the execution of the project contract.
  Once the project ends, Integrates delivers a presentation
  and an executive report also in +PDF+ format.

*What happens after FLUIDAttacks reports a vulnerability?*::
  Once +FLUIDAttacks+ reports a vulnerability,
  the main objective, for developers, is to eliminate it.
  Through Integrates a client company’s developers can also access
  first-hand detailed information regarding a vulnerability
  in order to plan and execute corrective measures
  to remove it from the application.

*How does FLUIDAttacks know a vulnerability*::
*has been eliminated or remediated?*::
  Through link:../../products/integrates/[Integrates]
  any user with access to the project can request verification
  of a remediated vulnerability.
  A request for verification that a remediated vulnerability
  no longer poses a risk must be accompanied by notification from you
  that the planned remediation has been executed.
  Then +FLUIDAttacks+ performs a closing verification
  to confirm the effectiveness of the remediation.
  Results of the closing verification are then forwarded
  to the project team by email.

*How many closing verifications are included in Continuous Hacking?*::
  Continuous Hacking offers unlimited closing verifications.

*Why do I need to notify FLUIDAttacks that a remediation has been executed*::
*if you already have access to the source code repositories?*::
  One of Continuous Hacking’s objectives
  is to maintain clear and effortless communication
  between all project members.
  This is accomplished when you notify +FLUIDAttacks+
  because the message goes through Integrates and by doing so,
  the entire project team is notified.

*What happens if I do not consider something a vulnerability?*::
  Within link:../../products/integrates/[Integrates] there is a comment section.
  A client company can post its reasons
  for believing a vulnerability finding is not valid.
  Then, +FLUIDAttacks+ experts and all other project members
  can interface and discuss the relative merits of the vulnerability finding
  and the validity of it as a security risk,
  and a final determination can be made.

*Do all reported vulnerabilities have to be remediated?*::
  No. However, this decision is made entirely by the client,
  not by +FLUIDAttacks+, and the client assumes all responsibility
  for possible negative impacts of non-remediation.
  In link:../../products/integrates/[Integrates], under the treatment option,
  a client company indicates whether it will remediate
  or assume responsibility for an identified vulnerability.

*If a client decides not to remediate a vulnerability, thus assuming*::
*responsibility for it, is it excluded from the reports and Integrates?*::
  No. Reports and Integrates include information regarding all vulnerabilities,
  along with whether vulnerabilities were remediated or not.
  Your report and Integrates will include
  all the information with nothing excluded.

*If the application is stored along multiple repositories,*::
*can they all be tested?*::
  Yes, with one condition.
  The code must be stored on the same branch in each repository.
  For example: If it is agreed that all tests
  will be performed on the +QA+ branch,
  then this same branch must be present in all of the repositories
  included for Continuous Hacking.

*If I have code that was developed a long time ago,*::
*is it possible to still hire Continuous Hacking?*::
  Yes, it is still possible to use Continuous Hacking.
  There are two possible options available:

  . A Health Check can be performed testing all existing code.
  Then, Continuous Hacking is executed as usual
  within the defined scope (<<q11,see question 11>>).
  This option is better suited for applications under development.

  . Start with the standard limits (<<q10,see question 10>>)
  increasing the coverage on a monthly basis until +100%+ is reached.
  This option is better suited for applications no longer in development.

*Do the repositories need to be in a specific version control system?*::
  Continuous Hacking is based on using +GIT+ for version control.
  Therefore, +GIT+ is necessary for Continuous Hacking.

*Does FLUIDAttacks keep or store information*::
*regarding the vulnerabilities found?*::
  Information is only kept for the duration of the Continuous Hacking contract.
  Once the contract has ended, information is kept for +7+ business days
  and then deleted from all +FLUIDAttacks+ information systems.

*Does Continuous Hacking require any development methodology?*::
  No. Continuous Hacking is independent
  of the client’s development methodology.
  Continuous Hacking test results become a planning tool
  in future development cycles.
  They do not prevent the continuation of development.

*Will FLUIDAttacks periodically do presentations via teleconferencing?*::
*How do I set one up?*::
  Yes. +FLUIDAttacks+ can schedule periodic presentations via teleconferencing.
  To set up a teleconference presentation you will need to provide us
  with the emails of attendees, and +3+ optional time periods
  of +1+ hour duration for the teleconference.
  We will then notify you of the best time for the teleconference
  based on your availability and ours.
  And, we will send emails to your list of attendees
  inviting their participation.

*Does the development of the test in the continuous model*::
*depends on the type of repository where the code is stored?*::
 No, the client can use the repository he deems appropriate.
 +FLUIDAttacks+ only requires the access to the integration branch
 and its respective environment.

*Are property rights lost if FLUIDAttacks reviews the source code?*::
 No, allowing to review a creation or work as it is a code to a third party
 does not grant any rights over it.

*Does FLUIDAttacks have a tool that allows automation*::
*over the closing tests in the found vulnerabilities?*::
 Yes, +FLUIDAttacks+ has link:../../products/asserts/[Asserts],
 an engine that allows to automate security checks
 once they have been found in an exploratory phase.
 link:../../productos/asserts/[Asserts] operates directly in the +JOB+
 of continuous integration and has the ability to break the +build+
 sent by the programmer in case of breach of security requirements.
 link:../../productos/asserts/[Asserts] runs on any continuous integration platforms
 that support dockers like +JOB+,
 for example: +VSTS+, +GitLab+, +Jenkins+.

*Is Continuous Hacking focused only over source code?*::
*It is possible to include the infrastructure associated with the app?*::
 +FLUIDAttacks+ has evolved the Continuous Hacking model
 and infrastructure now can be included within the Target of Evaluation (+TOE+).
 This include the ports and the inputs of the application.
 In fact, in this evolution,
 you can subscribe a technological infrastructure (ports)
 or an application under the Continuous Hacking model.

*Where does Integrates run?*::
 The platform link:../../products/integrates/[Integrates] runs in the cloud.

*Does FLUIDAttacks manages the access credentials to Integrates?*::
 No, we use the concept of federated authentication,
 that is, both +Google+ and +Azure+ (+Microsoft 360+)
 are the ones who actually validate your credentials.

*Is it possible to activate double authentication token?*
 Yes, it is possible. In fact we recommend to activate
 double token authentication to increase the security level of your credentials
 in order to avoid unauthorised access by third parties over your information.
 This feature is enabled from +Gmail+ or +Azure+ depending on your case.

*What procedure has FLUIDAttacks to catch up with the revision*::
*of the existing code before starting the test?*::
 +FLUIDAttacks+ recommends that both the development of the application
 and the security tests start at the same time.
 However, this does not always happen.
 To do this, we have an activity called link:../continuous-hacking/#healthcheck[+HealthCheck+]
 that allows to catch up the security inspections
 when the development has begun earlier.
