:slug: products/rules/list/273/
:category: system
:description: This requirement establishes the importance of installing a fixed and unalterable security suite in all production workstations.
:keywords: CWE, ASVS, Suite, Workstation, Antivirus, Firewall, CAPEC, NERC, PCI DSS, Rules, Ethical Hacking, Pentesting
:rules: yes

= R273. Define a fixed security suite

== Requirement

All the workstations in production
must count with an unalterable security suite
(Anti-virus, *Antispyware*, *Host Firewall*, *Host-IDS*, *Host-IPS*).

== Findings

* [inner]#link:/products/rules/findings/077/[F077. ARP spoofing]#

* [inner]#link:/products/rules/findings/084/[F084. MDNS spoofing]#

* [inner]#link:/products/rules/findings/104/[F104. USB flash drive attacks]#

* [inner]#link:/products/rules/findings/115/[F115. Security controls bypass]#

== References

. [[r1]] link:https://www.bsimm.com/framework/software-security-development-lifecycle/code-review.html[BSIMM9 CR3.4: 2. Automate malicious code detection].
Automated code review is used to identify dangerous code written by malicious
in-house developers or outsource providers.

. [[r2]] link:http://capec.mitre.org/data/definitions/169.html[CAPEC-169: Footprinting].
An adversary engages in probing and exploration activities to identify
constituents and properties of the target.

. [[r3]] link:http://capec.mitre.org/data/definitions/442.html[CAPEC-442: Infected Software].
An adversary adds malicious logic, often in the form of a computer virus,
to otherwise benign software.
Many times, the malicious logic is inserted into empty space between legitimate
code,
and is then called when the software is executed.

. [[r4]] link:http://capec.mitre.org/data/definitions/549.html[CAPEC-549: Local Execution of Code].
An adversary installs and executes malicious code on the target system in an
effort to achieve a negative technical impact.

. [[r5]] link:https://www.cisecurity.org/controls/[CIS Controls. 8.1 Utilize Centrally Managed Anti-Malware Software].
Utilize centrally managed anti-malware software to continuously monitor and
defend each of the organization’s workstations and servers.

. [[r6]] link:https://www.cisecurity.org/controls/[CIS Controls. 9.4 Apply Host-Based Firewalls or Port-Filtering].
Apply host-based firewalls or port-filtering tools on end systems,
with a default-deny rule that drops all traffic except those services and ports
that are explicitly allowed.

. [[r7]] link:https://www.cisecurity.org/controls/[CIS Controls. 9.5 Implement Application Firewalls].
Place application firewalls in front of any critical servers to verify and
validate the traffic going to the server.
Any unauthorized traffic should be blocked and logged.

. [[r8]] link:https://cwe.mitre.org/data/definitions/923.html[CWE-923: Improper Restriction of Communication Channel to Intended Endpoints]
The software establishes a communication channel to (or from) an endpoint for
privileged or protected operations,
but it does not properly ensure that it is communicating with the correct
endpoint.

. [[r9]] link:https://www.nerc.com/pa/Stand/Reliability%20Standards/CIP-003-8.pdf[NERC CIP-003-8. Attachment 1. Section 5 - 5.1]
Each Responsible Entity shall implement,
except under CIP Exceptional Circumstances,
one or more plan(s) to achieve the objective of mitigating the risk of the
introduction of malicious code to low impact BES Cyber Systems.
The plan(s) shall include antivirus software,
or other method(s) to mitigate the introduction of malicious code.

. [[r10]] link:https://www.nerc.com/pa/Stand/Reliability%20Standards/CIP-005-5.pdf[NERC CIP-005-5. B. Requirements and measures. R1.5]
Have one or more methods for detecting known or suspected malicious
communications for both inbound and outbound communications.

. [[r11]] link:https://owasp.org/www-project-application-security-verification-standard/[OWASP-ASVS v4.0.1
V1.14 Configuration Architectural Requirements.(1.14.1)]
Verify the application does not use unsupported, insecure, or deprecated
client-side technologies such as *NSAPI* plugins, *Flash*, *Shockwave*,
*ActiveX*, *Silverlight*, *NACL*, or client-side *Java* applets.

. [[r12]] link:https://owasp.org/www-project-application-security-verification-standard/[OWASP-ASVS v4.0.1
V12.4 File Storage Requirements.(12.4.2)]
Verify that files obtained from untrusted sources are scanned by antivirus
scanners to prevent upload of known malicious content.

. [[r13]] link:https://www.pcisecuritystandards.org/documents/PCI_DSS_v3-2-1.pdf[PCI DSS v3.2.1 - Requirement 5.1]
Deploy anti-virus software on all systems commonly affected by malicious
software
(particularly personal computers and servers).
