:slug: careers/knowledge-test/
:category: careers
:description: Test your knowledge in different fields before applying to any of our positions.
:keywords: Fluid Attacks, Careers, Knowledge, Test, Selection, Process, Pentesting, Ethical Hacking

= Knowledge Test

To continue in the selection process, complete the knowledge test.
This test contains questions in several areas of knowledge.
Some will apply to your profile, and some will not.
However, you must answer all of them thoroughly
because we will use the test to determine your level of experience.

To access, complete, and submit the test, please do the following:

== Create an account

. Click on this link:https://autonomicgeneralknowledgetest.thinkexam.com/startTest/NjEwNDI=/NA[link].
. Fill out the form with your data.
. Select a group according to the vacancy you are applying for:
.. For Accounting Assistant or similar vacancies,
select the 'Finance General Knowledge Test' group.
.. For Ethical Hacker, QA, Developer, DevOps, or similar vacancies,
select the 'General Knowledge Test' group.

== Important

. *You only have one chance to take the test.*
Make sure you have the time and willingness to take it.
. Enter your full name.
. The test lasts a maximum of *3 hours* and *20 minutes*,
so you should have enough time to take it without interruption.
. Avoid exiting the main screen of the test.
If you do it, the test will be automatically canceled,
and there will not be a second attempt.
. If you have any questions regarding this test,
please contact careers@fluidattacks.com.
. *Send us an email notifying us that you finished the test.*

Have fun! And good luck, although you don't need it.
