:slug: rules/194/
:category: rules
:description: En el presente documento se detallan los requerimientos de seguridad relacionados a la gestión adecuada de dispositivos foráneos de la organización. En este requerimiento, se recomienda que la organización determine los permisos para acceder a recursos internos por parte de dichos dispositivos.
:keywords: Sistema, Organización, Dispositivos, Foráneos, Recursos, Internos.
:rules: yes

= REQ.194 Determinar permiso de dispositivo a recursos

== Requisito

La organización debe determinar
qué tipo de dispositivos foráneos
tienen permiso de consumir recursos internos.

== Referencias

. [[r1]] link:https://www.law.cornell.edu/cfr/text/45/164.310[`HIPAA Security Rules` 164.310(d)(1):]
Control de dispositivos y medios: Implementar políticas y procedimientos
para la recepción y remoción de hardware y medios electrónicos
que contengan información sensible dentro y fuera de las instalaciones,
y el movimiento de dichos objetos dentro de las instalaciones.

. [[r2]] link:https://nvd.nist.gov/800-53/Rev4/control/IA-3[`NIST` 800-53 IA-3]
Identificación y autenticación en dispositivos:
El sistema de información únicamente identifica y autentica
a los dispositivos especificados por la organización
a la hora de establecer una conexión a una red local y/o remota.
