:slug: servicios/
:description: En la siguiente página presentamos los principales servicios ofrecidos por Fluid Attacks. El Ethical Hacking tiene como objetivo encontrar y reportar todas las vulnerabilidades presentes en una aplicación o infraestructura, de forma que el cliente las conozca y pueda decidir cómo afrontarlas.
:keywords: Fluid Attacks, Servicios, Hacking, Hallazgo, Seguridad, Aplicación.
:caption:

= Servicios

[role="tb-alt"]
[cols=3, frame="topbot"]
|====

2+a|== link:hacking-puntual/[Hacking Puntual]

Este servicio busca detectar y reportar todas las vulnerabilidades
y problemas de seguridad en una versión específica de tu aplicación,
sin ningún falso positivo.
a|image::puntual.svg[Computador siendo atacado]

a|image::continuo.svg[Servidor siendo atacado]
2+a|== link:hacking-continuo/[Hacking Continuo]

Este servicio busca detectar y reportar todas las vulnerabilidades
y problemas de seguridad durante todo el ciclo de desarrollo de +software+.
Este método nos permite detectar problemas de seguridad
de manera continua a medida que el +software+ evoluciona.
Esta inspección se realiza sin falsos positivos y asegurando
que los previos problemas fueron resueltos antes de salir a producción.

2+a|== link:diferenciadores/[Diferenciadores]

¿Cuál es la diferencia entre un +pentest+ y un +análisis de vulnerabilidades+
usando herramientas automáticas? +
Estos elementos son los que nos permiten encontrar y reportar
todas las vulnerabilidades de seguridad en tu aplicación.
a|image::diferenciadores.svg[Engranaje de metal]

a|image::comparativo.svg[Balanza de dos platos]
2+a|== link:comparativo/[Comparativo]

¿Cuál es la diferencia entre el servicio +Hacking Puntual+
y el servicio +Hacking Continuo+? +
Estos elementos te ayudarán a decidir cuál de los servicios
se ajusta mejor a tus necesidades.

2+a|== link:certificaciones/[Certificaciones]

Nuestros +hackers+ se encuentran certificados en diferentes áreas
de la Seguridad de la Información, como +OSCP+, +OSWP+,
+CEH+, +CISSP+, entre otras.
Así estás seguro de que estás contratando un equipo capaz de profesionales.
a|image::certificaciones.svg[Diploma de certificación]

a|image::faq.svg[Signo de pregunta]
2+a|== link:faq/[FAQ]

¿Tienes alguna pregunta acerca del serivico de +Hacking Continuo+? +
Lee esta +FAQ+ para solucionar algunas de las dudas más comunes
relacionadas con nuestro servicio.

|====
