:slug: empleos/referencias-inversas/
:category: empleos
:description: La siguiente página tiene como objetivo informar a los interesados en ser parte del equipo de trabajo de FLUIDAttacks sobre el proceso de selección realizado. La etapa de referencias cruzadas consiste en la validación de referencias de los empleos anteriores del candidato a través de dos de sus jefes.
:keywords: FLUIDAttacks, Empleo, Proceso, Selección, Referencias, Inversas.
:translate: careers/reverse-references/

= Referencias Inversas

En esta etapa del proceso, validamos las referencias de sus empleos anteriores de la siguiente manera:
Dos de sus jefes directos (no aplican jefes de sus jefes directos y/o familiares del talento) de los periodos de trabajo ingresados en la aplicación del proceso, deben llamar al celular que damos a continuación.

Se trata de que se realice la gestión necesaria para que dos de sus anteriores jefes nos contacten por medio de una llamada telefónica, para tener una breve conversación con ellos respecto a su trabajo en dicha organización, en donde de forma ágil nos haremos una idea de su paso por el cargo desempeñado.

* Celular: *300 496 3851*

Por medio de un correo por favor confirmarnos los nombres y contactos de los Jefes que nos van a llamar, para saber de parte de quien estan marcando.

Quedamos atentos a cualquier duda al respecto.

El nombre de quien lo contactará es: Santiago Vélez Robledo.
