:slug: empleos/referencias-inversas/
:category: empleos
:description: La siguiente página tiene como objetivo informar a los interesados en ser parte del equipo de trabajo de Fluid Attacks sobre el proceso de selección realizado. La etapa de referencias cruzadas consiste en la validación de referencias de los empleos anteriores a través de dos de sus jefes.
:keywords: Fluid Attacks, Empleo, Proceso, Selección, Referencias, Inversas.
:translate: careers/reverse-references/

= Referencias Inversas

En esta etapa del proceso, validamos las referencias de tus empleos anteriores
de la siguiente manera:

* Dos de tus jefes directos
(no aplican jefes de tus jefes directos y/o familiares tuyos)
de los periodos de trabajo ingresados en la aplicación del proceso,
deben llamar al celular que damos a continuación.

Se trata de que se realices la gestión necesaria
para que dos de tus anteriores jefes nos contacten
por medio de una llamada telefónica,
y así tener una breve conversación con ellos
respecto a tu trabajo en dicha organización,
en donde de forma ágil nos haremos una idea de tu paso por el cargo desempeñado.

* Celular: *300 496 3851*

Por medio de un correo, por favor confirmarnos los nombres y contactos
de los jefes que nos van a llamar, para saber de parte de quién están marcando.

Si tienes alguna duda,
no dudes en escribir a careers@autonomicmind.com

El nombre de la persona a quien contactarán es: Santiago Vélez Robledo.
