:slug: systems/microservices/
:category: systems
:description: APIs and microservices are among the systems that we at Fluid Attacks help you evaluate to detect security vulnerabilities that you can subsequently remediate.
:keywords: Fluid Attacks, API, Microservice, Continuous Hacking, Security, System, Ethical Hacking, Pentesting
:banner: bg-systems
:template: compliance

= APIs and Microservices

[role="fw3 f3"]
APIs and microservices play essential roles in the applications. APIs
(application programming interfaces) define and facilitate data exchange between
different software components and change the way we interact with applications.
On the other hand, microservices, which are smaller, independent units or
containers in the applications with few and closely related jobs, facilitate the
building, functioning and maintenance of the applications. Both APIs and
microservices can be vulnerable to cyberattacks. When either of them are part of
or constitute an application, they represent multiple potential attack vectors
for malicious hackers. Therefore, each of these elements should be evaluated
continuously, considering every line of their code, ideally from the early
development stages.

[role="fw3 f3"]
This is where we come in. Our team of ethical hackers uses diverse techniques,
among which, for these cases, SAST, DAST and Manual Pentesting stand out.
Interactions between microservices, their functions, business logic and the
public exposition of APIs on the networks have to be tracked and attacked to
find vulnerabilities that can be exploited by cybercriminals. The scanning and
testing procedures pay attention to running applications’ behavior, covering
authentication, authorization and encryption functions, among others, always
taking intoaccount more vulnerabilities than those usually publicly highlighted,
for instance by the OWASP Top 10.
