:slug: rules/067/
:category: rules
:description: En el presente documento se detallan los requerimientos de seguridad relacionados a la gestion segura de los componentes definidos para un determinado sistema. Por lo tanto, dichos componentes a ser probados deben estar definidos al realizar pruebas de caja blanca.
:keywords: Componente, Sistema, Probar, Caja Blanca, Definir, Seguridad.
:rules: yes

= REQ.067 Definir componentes a ser probados

== Requisito

Los componentes del sistema que serán probados
(pruebas de caja blanca) deben estar definidos.

== Descripción

Dentro de la documentación del plan de pruebas
se debe identificar los componentes que serán probados,
dependiendo del tipo de prueba se debe entregar la mayor información
sobre el objeto a probar de forma que la prueba
pueda revisar todas las características del componente.

== Implementación

. El listado de componentes del sistema se entrega
y se realiza el plan de pruebas,
para cada prueba se establece el alcance,
en lo posible en la sumatoria de pruebas
se debería dar cobertura a todo el listado de componentes entregado.
La documentación de la prueba debe contener el alcance planeado para la misma.

== Ataques

. Un componente se queda sin probar
debido a que no fue identificado en etapa de pruebas,
y es vulnerado estando en producción.

== Atributos

* Capa: Negocio
* Activo: Arquitectura de seguridad
* Alcance: Adherencia
* Fase: Pruebas
* Tipo de Control: Recomendación
