:slug: careers/terms/
:category: careers
:description: This page is meant to inform everyone interested in being part of the Fluid Attacks team about the selection process. Here we present information about our company and the terms and conditions that need to be accepted if you wish to be part of the team.
:keywords: Fluid Attacks, Careers, Process, Selection, Terms, Company.

= Careers Terms

== Fluid Attacks Overview

=== Who We Are, Who We Are Looking For, and How to Apply

Please read every item below carefully.

If you have any questions about any item,
do not hesitate to email us at careers@autonomicmind.com.

To take part in the process,
fill out the following [inner]#link:https://fluidattacks.com/forms/seleccion[form]#.

== The Company

For more information about +Fluid Attacks+,
please read our [inner]#link:../../about-us/[About us]# section


=== Context

* At +Fluid Attacks+, all systems are constantly monitored
through link:https://www.timedoctor.com/[automatic time and activity control systems].
We do this to:

** Assure the security of our clients' information

** Be objective, precise, and fair in the performance evaluation

* At +Fluid Attacks+, we follow an ethics code
which you can read by clicking [inner]#link:../../values/[here]#

== The Selection Process

. Our selection process is set up to identify,
assess, and ultimately hire candidates from the top +10%+
of the +IT+ population for each available position.

. We select only the best to join the +Fluid Attacks+ team.
A team that is:

** Elite.
** Enduring.
** Disciplined.
** Responsible.
** Ethical.

. We have automated many stages of the selection process
so that you can optimize your time and
become part of our team faster and easier.

. Because most of the process is done online,
the duration of the process is +90%+ in your hands.

. Our selection process is very detailed
and may be different from what you see in other companies.
Please read the process detailed link:../[here],
carefully.

. Continuing with your application
implies you understand who we are and what we stand for,
and are genuinely interested in becoming part of our team.

=== End of the Process

. After completing the application process,
if you are no longer interested in being considered
for a position with +Fluid Attacks+,
please notify us and we will remove you from our candidate database.
However, if we are not interested in your application, we will notify you.
If we do not notify you, your application will remain active,
and therefore, will be considered for any current or future opening.

== The Hiring Process

. By accepting these terms and conditions
you are stating that your current or previous contracts
do not have any clauses (or that these have expired)
that forbid you to work in any role in an information security company.

. By accepting these terms and conditions
you understand that if you sign a contract with us,
it will have the following clauses:

* Exclusivity.
* Non-compete.
* No solicitation.
* Confidentiality.
+
The previous clauses will remain valid
throughout your work contract with +Fluid Attacks+.

. Once you accept our job offer
you must provide the following link:../hiring/[information]..

. When we make a salary proposal it may be lower than your expectations.
This may be because we take the following factors into consideration:

** Salary equity among our team members.
**  The correlation between pay
and our perception of an employee's potential performance of required duties.

. By participating in our hiring process
you also agree to being recommended for openings,
not only with +Fluid Attacks+,
but also for openings with some of our business associates.

. By default, your records will stay in our database
so you may be considered for future open positions.
** If you wish to have your data deleted from our database
you must send us an email indicating so at careers@autonomicmind.com.
