:slug: rules/337/
:category: source
:description: This requirement establishes the importance of safely managing threads to avoid race conditions, especially in critical business logic flows.
:keywords: Thread, Safe, Race, Condition, ASVS, CWE, Rules, Ethical Hacking, Pentesting
:rules: yes

= R337. Make critical logic flows thread safe

== Requirement

Critical and high-value business logic flows must be thread safe and resistant
to time-of-check and time-of-use (*TOCTOU*) **race conditions**.

== Description

A **race condition** occurs when a code sequence requires exclusive access to a
resource but another code sequence can modify the same resource before the
first one has released it.
This can have security implications if it occurs during high-value business
logic flows such as authentication, authorization and session management.
Therefore, threads and concurrent processes must be managed carefully in order
to prevent **race conditions** from arising.

== References

. [[r1]] link:https://cwe.mitre.org/data/definitions/362.html[CWE-362: Concurrent Execution using Shared Resource with
Improper Synchronization ('Race Condition').]
The program contains a code sequence that can run concurrently with other code,
and the code sequence requires temporary, exclusive access to a shared
resource,
but a timing window exists in which the shared resource can be modified by
another code sequence that is operating concurrently.

. [[r2]] link:https://cwe.mitre.org/data/definitions/367.html[CWE-367: Time-of-check Time-of-use (TOCTOU) Race Condition.]
The software checks the state of a resource before using that resource,
but the resource's state can change between the check and the use in a way that
invalidates the results of the check.
This can cause the software to perform invalid actions when the resource is in
an unexpected state.

. [[r3]] link:https://owasp.org/www-project-application-security-verification-standard/[OWASP-ASVS v4.0.1
Appendix C: Internet of Things Verification Requirements.(C.20)]
Verify that the firmware update process is not vulnerable to time-of-check vs
time-of-use attacks.

. [[r4]] link:https://owasp.org/www-project-application-security-verification-standard/[OWASP-ASVS v4.0.1
V1.11 Business Logic Architectural Requirements.(1.11.2)]
Verify that all high-value business logic flows,
including authentication, session management and access control,
do not share unsynchronized state.

. [[r5]] link:https://owasp.org/www-project-application-security-verification-standard/[OWASP-ASVS v4.0.1
V1.11 Business Logic Architectural Requirements.(1.11.3)]
Verify that all high-value business logic flows,
including authentication, session management and access control,
are thread safe and resistant to time-of-check and time-of-use race conditions.

. [[r6]] link:https://owasp.org/www-project-application-security-verification-standard/[OWASP-ASVS v4.0.1
V11.1 Business Logic Security Requirements.(11.1.6)]
Verify the application does not suffer from "time of check to time of use"
(*TOCTOU*) issues or other race conditions for sensitive operations.
