:slug: kb/java/definir-rol-seguridad-tomcat/
:category: java
:description: TODO
:keywords: TODO
:kb: yes

= Definir Roles de Seguridad en Tomcat

== Necesidad

Definir roles de seguridad en Tomcat.

== Contexto

A continuación se describen las circunstancias bajo las cuales la siguiente 
solución tiene sentido:

. Se dispone de un servidor de aplicaciones Tomcat 5.5. o superior

== Solución

. Mediante repositorio interno de usuarios en el servidor de aplicaciones:
. En el archivo conf\tomcat-users.xml añadir los roles y usuarios requeridos, 
estos últimos asociados a su respectiva contraseña y roles:
+
.test.py
[source, xml, linenums]
----
<?xml version='1.0' encoding='utf-8'?>
  <tomcat-users>
    <role rolename="rol1"/>
    <role rolename="rol2"/>
    <user username="usuario1" password="clave1" roles="rol1"/>
    <user username="usuario2" password="clave2" roles="rol1,rol2"/>
  </tomcat-users>
----

. El servidor de aplicaciones, tiene habilitado por defecto este tipo de 
repositorio de usuarios en el archivo conf/server.xml:
+
[source, xml, linenums]
----
<Realm className="org.apache.catalina.realm.UserDatabaseRealm" 
   resourceName="UserDatabase"/>
----

. Para otro tipo de repositorios (base de datos, directorios, JAAS o memoria), remitirse a [1]

== Referencias

. Apache Tomcat - Realm How To
