:slug: services/continuous-hacking/
:category: services
:description: In this page we describe our Continuous Hacking service, which aims to detect and report all the vulnerabilities in your application as soon as possible. Our participation in the development life cycle allow us to continuously detect security findings in a development environment.
:keywords: Fluid Attacks, Services, Continuous Hacking, Ethical Hacking, Pentesting, Security.
:translate: servicios/hacking-continuo/

= Continuous Hacking

The Continuous Hacking service aims to detect and report all vulnerabilities
and security issues during the entire software development cycle.
Our participation during the entire development period
allows us to detect security issues continuously
as the software evolves during development.
The rigorous inspection carried out by our team
allows us to detect all security issues with no false positives
and to check if issues were properly repaired
before the system goes into the production phase.

[role="tb-alt"]
[cols=3, frame="topbot"]
|====

2+a|== Ethical hacking can start before there is a working environment

Ethical Hacking can start along with code development,
even before a first application version is released.
There's no need to have a working environment to start hacking,
since we are able to analyse source code
published on project's +GIT+ repository.


a|image::hacking-before-env.svg[alt="Application blueprint"]

a|image::hacking-techniques.svg[alt="Source code symbol"]

2+a|== Hacking techniques

* Integral continuous hacking is achieved through application
and infrastructure ethical hacking as well as source code analysis.
In order to perform integral continuous hacking,
access to both +GIT+ repository and integration environment are required.

* In limited continuous ethical hacking
the customer can choose between application ethical hacking
or source code analysis.
In order to perform limited continuous hacking,
access to the +GIT+ repository or the integration environment is required.

2+a|== Healthcheck

When a new continuous ethical hacking subscription starts,
if there were any previous issues
it is necessary to perform a healthcheck.
This means we will attack all versions of the existing code
up to the subscription start point in addition to the monthly test limit
to catch up with the development team
within the first +3+ subscription months.
Then we’ll continue hacking simultaneously as development continues
(healthcheck will have additional fees).

a|image::healthchecks.svg[alt="Source code with successful checks"]

a|image::severity.svg[alt="Checklist"]

2+a|== Severity

Customers are able to decide which security requirements will be tested
on each Ethical Hacking (Profiling) through our
[button]#link:../../products/rules/[Rules]# product.

Customers will know the exact severity for each hacking
(for inspected and non-inspected profiled requirements).

2+a|== Duration

Minimum subscription time for continuous ethical hacking is one year.

a|image::duration.svg[alt="Calendar"]

a|image::attack-cycles.svg[alt="Metal Gear"]

2+a|== Attack Cycles

During the subscription period the selected system
will be attacked multiple times
to test all versions generated during the development phase.
The hacking team will constantly attack the system
even though its functionalities
may have already been attacked in a previous version.

2+a|== Direct and agile communication

All project communication is done through
[button]#link:../../products/integrates/[Integrates]#,
customers can use chat and comments for any project or finding question.

a|image::agile-communication.svg[alt="Two persons having a conversation"]

a|image::hacking-envs.svg[alt="Source code inside a scope target"]

2+a|== Hacking environments

Basic service allows customers to choose a single environment from production,
testing or integration environment,
customers can also add additional testing environments
for finding validation with an additional charge.

2+a|== Highly trained hacking team

Our hackers have practical certifications and academic backgrounds
related to security testing.
They perform manual testing and use tools
to guarantee that our reporting includes insecure programming practices,
standard alignment and security regulation compliance,
and findings with specific business impacts.
This enables us to detect Zero Day findings
with no false positive reports.

a|image::trained-team.svg[alt="Team"]

a|image::exploitation.svg[alt="Computer with an open lock symbol"]

2+a|== Exploitation

As long as we have access to deployed applications
and customer authorization,
using our own exploitation engine [button]#link:../../products/asserts/[Asserts]#

2+a|== Critical information extraction

Whenever findings make it possible to get information,
all compromised records are extracted
to maximize finding impact and compromise sensible information.
[button]#link:../../products/integrates/#compromised-records[Example]#.

a|image::critical-info.svg[alt="Arrows flowing out of a lock"]

a|image::follow-up.svg[alt="Bar graph with a continuous line on top"]

2+a|== Follow up using Integrates

During project execution customers can check out finding information,
visualize real time project statistics,
check on finding remediation status,
classify findings according age,
and other functionalities using our
[button]#link:../../products/integrates/[Integrates]# product.

2+a|== Remediation validation

Multiple finding validation cycles are performed during subscription time
to assure findings have been properly repaired,
we can check if any finding is closed as many times as customer needs us to.
In order to perform remediation validation
customers must define a finding treatment
and then request for finding validation through our
[button]#link:../../products/integrates/[Integrates]# platform.

a|image::validate-remediation.svg[alt="Checklist"]

a|image::remediation-support.svg[alt="Question and answer symbol"]

2+a|== Remediation support

During the project customers can request clarifications directly to our hackers
via [button]#link:../../products/integrates/[Integrates]#.

Customers can use our detailed remediation guides
via [button]#link:../../products/defends/[Defends]#.

2+a|== Generate technical and executive reports from Integrates

Technical report provides detailed information of each vulnerability.
It is of great use to all technical personnel
when it comes to remediating the reported security flaws.
Executive report provides summarized and organized information.
Thus, it may be useful for all the project’s stakeholders.

a|image::reports.svg[alt="Bar graph in a presentation"]

a|image::secure-deletion.svg[alt="Trash can with a cloud behind"]

2+a|== Information gets deleted securely

+7+ days after customer's final report approval
all information gathered during Ethical Hacking
is deleted securely from all our systems.

|====

* To check on differences between our services
and other providers take a look at our differentiators
[button]#link:../differentiators/[here]#.

* To check on differences between our One-shot hacking
and Continuous hacking take a look at our comparative
[button]#link:../comparative/[here]#.
