:slug: rules/142/
:category: credentials
:description: This document contains the details of the security requirements related to the definition and management of access credentials in the organization. This requirement establishes the importance of modifying all default credentials in the system in order to avoid brute force attacks.
:keywords: Change, Credentials, Default, Password, System, ASVS
:rules: yes

= R142. Change system default credentials

== Requirement

The organization must modify
all default access credentials of embedded systems.

== Description

Organizations usually keep default configurations
of third-party products
since these may adapt to most environments where they are installed
and facilitate the deployment to production.
However, this practice may leave a default open gate for products
and, in most cases, credentials found in provider documentation,
which can be found easily on the Internet.
For this reason it is important to check all configurations
before deployment and remove all default credentials.

== Implementation

. Remove all default credentials.

. Implement a mechanism to ensure only users
with administrator privileges can access
product consoles.

. Create a robust credential policy
to improve the security of all credentials in the organization.

. The passwords must be changed every so often
in case they are compromised.

. Perform audits periodically
to detect improper configurations or missing patches.


== Attacks

. Brute force attack.
. Information leakage: Technical.

== Attributes

. Layer: Business layer
. Asset: Access credentials
. Scope: Confidentiality
. Phase: Deployment
. Type of Control: Recommendation

== Findings

* [inner]#link:/web/findings/041/[F041. Enabled default credentials]#

* [inner]#link:/web/findings/056/[F056. Anonymous connection]#

== References

. [[r1]] link:http://capec.mitre.org/data/definitions/70.html[CAPEC-70 - Try Common Usernames and Passwords]
An adversary may try certain common or default usernames and passwords to gain
access into the system and perform unauthorized actions.

. [[r2]] link:https://owasp.org/www-project-application-security-verification-standard/[OWASP-ASVS v4.0.1
V2.5 Credential Recovery Requirements.(2.5.4)]
Verify shared or default accounts are not present
(e.g. "root", "admin", or "sa").

. [[r3]] link:https://www.pcisecuritystandards.org/documents/PCI_DSS_v3-2es-LA.pdf[PCI DSS - Requirement 2.2.d]
