:slug: products/rules/list/169/
:category: source
:description: This requirement establishes the importance of using parameterized queries in order to avoid injection attacks such as SQLi.
:keywords: Parameterized, Queries, SQLi, Injection, ASVS, CAPEC, CWE, PCI DSS, Rules, Ethical Hacking, Pentesting
:rules: yes

= R169. Use parameterized queries

== Requirement

The system must use parameterized queries or stored procedures
to create dynamic sentences (e.g., *java.sql.PreparedStatement*).

== Findings

* [inner]#link:/products/rules/findings/001/[F001. SQL injection]#

* [inner]#link:/products/rules/findings/105/[F105. Apache Lucene query injection]#

== References

. [[r1]] link:http://capec.mitre.org/data/definitions/7.html[CAPEC-7: Blind SQL Injection].
Blind *SQL* Injection results from an insufficient mitigation for *SQL*
Injection.
Blind *SQL* Injection is a form of *SQL* Injection that overcomes the lack of
error messages.

. [[r2]] link:https://cwe.mitre.org/data/definitions/89.html[CWE-89: SQL Injection].
The software constructs all or part of an SQL command using
externally-influenced input from an upstream component,
but it does not neutralize or incorrectly neutralizes special elements that
could modify the intended SQL command.

. [[r3]] link:https://owasp.org/www-project-top-ten/OWASP_Top_Ten_2017/Top_10-2017_A1-Injection[OWASP Top 10 A1:2017-Injection].
Injection flaws, such as **SQL**, **NoSQL**, **OS**, and *LDAP* injection,
occur when untrusted data is sent to an interpreter as part of a command or
query.
The attacker's hostile data can trick the interpreter into executing unintended
commands or accessing data without proper authorization.

. [[r4]] link:https://owasp.org/www-project-application-security-verification-standard/[OWASP-ASVS v4.0.1
V5.3 Output encoding and Injection Prevention Requirements.(5.3.4)]
Verify that data selection or database queries
(e.g. *SQL*, *HQL*, *ORM*, *NoSQL*) use parameterized queries, *ORMs*,
entity frameworks, or are otherwise protected from database injection attacks.

. [[r5]] link:https://www.pcisecuritystandards.org/documents/PCI_DSS_v3-2-1.pdf[PCI DSS v3.2.1 - Requirement 6.5.1]
Address common coding vulnerabilities in software-development processes such as
injection flaws, particularly *SQL* injection.
Also consider *OS* Command Injection, *LDAP* and *XPath* injection flaws as
well as other injection flaws.
