:slug: products/rules/list/311/
:category: privacy
:description: This requirement focuses on the importance of establishing a mechanism to demonstrate that the user has granted consent for the collection of data.
:keywords: Requirement, Security, Data, GDPR, Consent Demonstration, Regulation, Rules, Ethical Hacking, Pentesting
:rules: yes

= R311. Demonstrate user consent

== Requirement

The system must establish a mechanism which can be used to demonstrate
that users have granted their consent to collection of their data.

== Description

Systems usually request information from their users or collect it based
on their interactions with the application.
Regulations demand that none of these collections occur without the user's
consent and that this consent be demonstrable afterwards.
Therefore, the system must have a mechanism
that can be used to demonstrate the grant of the consent.

== Findings

* [inner]#link:/products/rules/findings/088/[F088. Privacy violation]#

== References

. [[r1]] link:https://gdpr-info.eu/art-7-gdpr/[GDPR. Art. 7: Conditions for consent.(1).]
Where processing is based on consent, the controller shall be able to
demonstrate that the data subject has consented to processing of his or her
personal data.

. [[r2]] link:https://www.iso.org/obp/ui/#iso:std:54534:en[ISO 27001:2013. Annex A - 18.1.4]
When applicable, guarantee the privacy and security of personal information,
as required by the relevant legislation and regulations.
