:slug: empleos/inmersion/
:category: empleos
:description: La siguiente página tiene como objetivo informar a los interesados en ser parte del equipo de trabajo de FLUID sobre el proceso de selección realizado. La etapa de inmersión consiste en un entrenamiento remunerado cuya finalidad es adquirir los conocimientos necesarios para desempeñar tu cargo.
:keywords: FLUID, Empleo, Proceso, Selección, Inmersión, Entrenamiento.
:toc: yes
// :translate: careers/immersion/

= Inmersión

A esta altura del proceso estamos a pocos pasos de culminar. 
Este nuevo paso, para el cual usted ha sido seleccionado entre más de 100 candidatos, 
busca que usted haga parte en un auto-entrenamiento intensivo en retos de programación y 
hacking financiado por FLUID llamado “Inmersión”. 

El objetivo de esta etapa es que usted alcance los más altos niveles de fortaleza técnica. 
Esto previo a efectuar pruebas reales de seguridad sobre sistemas financieros y de telecomunicaciones, 
así como validar sus competencias humanas y de trabajo en equipo cerca a otros hackers que 
ya se encuentran en nuestra organización.

Por lo extenso del proceso, FLUID, para esta etapa, 
busca independiente del avance en puntos y ranking, 
que usted reciba una remuneración por el tiempo invertido en el proceso.

Los términos del contrato de entrenamiento para esta etapa de Inmersión son los siguientes:

== Inicio

Esta etapa comienza cuando usted:

. Haya finalizado la etapa de link:../retos-tecnicos[retos técnicos]
. Se registre como tercero en el siguiente [button]#link:../../../../forms/tercero[formulario >>]# con el RUT anexo,
. Entregue en PDF escaneado la copia de la Tarjeta Profesional o el recibo de comienzo de trámite de la misma 
(aplica si usted ya tiene título de pregrado).
. Lea y acepte las condiciones de almacenamiento de resultados de entrenamiento que se encuentran link:../retos-tecnicos/#propiedad-intelectual[aquí].

Otros detalles procedimentales de cómo se llevará a cabo el entrenamiento, 
que se hace cada día, los lenguajes de programación, 
la forma de documentación y las herramientas requeridas entre otros, 
serán revelados el primer día de Inmersión y 
cuando haya finalizado todos los ítems mencionados en esta sección.

En caso de aceptar esta propuesta sólo requerimos que nos indique:

* La fecha en la que enviará el 100% de los requerimientos mencionados,
* La fecha en la cual puede comenzar la etapa de Inmersión en nuestras instalaciones.

== Entrenamientos

. El entrenamiento es auto-dirigido (usted investiga por su propia cuenta sin instrucción alguna),
. Debe entrenarse de forma independiente (sin ayuda de otro),
. Los días pares se trabajarán retos de hacking.
. Los días impares se trabajarán retos de programación.
. El entrenamiento debe iniciar a las 7:00 am en las instalaciones de FLUID,
. Debe finalizar el entrenamiento antes de las 6:00PM del día en cuestión,
. Si por algún motivo excepcional no puede realizar el entrenamiento de forma presencial, 
se deberá definir un horario de entrenamiento semanal para realizarlo de forma remota,
. El entrenamiento se realizará desde un portátil de su propiedad,
. Su dedicación diaria se evaluará sobre un tiempo de referencia de 48 horas/semanales,
. Se espera que usted pueda dedicarse todos los días hábiles de la semana de manera presencial 
en las instalaciones de la compañía,
. Si por algún motivo de salud o personal no es posible ir a la oficina a realizar los retos de forma presencial, 
ese día no se hacen retos ni se reporta tiempo de entrenamiento con la herramienta asignada.
. El tercer día hábil de cada semana, 
usted deberá entrenar la máxima dedicación posible,

=== Intentos fallidos

Al igual que en la etapa de link:../retos-tecnicos[retos técnicos], 
aplicará el tope de 10 MR fallidos, 
incluyendo los acumulados en dicha etapa.

Puede ver más detalles [button]#link:../retos-tecnicos/#intentos-fallidos[aquí >>]#

== Reportes

. Debe reportar todo el tiempo dedicado mediante la herramienta asignada en modo automático,
. Debe diligenciar el [button]#link:../../../../forms/training[reporte de entrenamiento]# antes de finalizar la jornada.
. El fraude deparará en la finalización inmediata del proceso de selección

== Pagos

. Se pagará el tiempo reportado a formación con un valor hora de $6.468 COP,
. Se espera que usted logre una dedicación mínima del 80% (Relación al tiempo de referencia),
. Si la dedicación total es mayor o menor a lo anterior se pagará proporcional
. Las primeras 96 horas de entrenamiento reportadas no serán remuneradas y 
de continuar en la etapa de inmersión luego de estas primeras 96 horas, 
se garantiza el pago mínimo de las siguientes 96 horas de entrenamiento reportadas,
. El contrato es un contrato por servicios con pago mensual,
. Debe pagar la seguridad social correspondiente a estos servicios (como trabajador independiente),
. Debe presentar el 1er día hábil calendario del mes siguiente los documentos que permiten consignar el dinero a su cuenta:
.. Cuenta de cobro por las horas del mes anterior,
.. Recibo de pago de la seguridad social por el periodo anterior

== Ciclos

. El entrenamiento se realizará en ciclos o iteraciones de semana calendario,
. Inicialmente se le ofrece un primer ciclo de entrenamiento,
. Al final de cada ciclo puede ocurrir lo siguiente:
.. No indicar nada, con lo cual puede asumir que el ciclo de formación se renueva una semana más.
.. Notificar que no deseamos continuar con otro ciclo y por ende suspender el proceso,
.. Formalizar que no deseamos continuar con otro ciclo, 
debido a que queremos adelantar la etapa siguiente,
. Lo usual es que se requiera entre 8 y 12 ciclos antes de comenzar la última etapa,

== Fin

Esta etapa termina cuando:

. Se acepten en el repositorio 100 nuevas soluciones de hacking

. Se acepten en el repositorio 100 nuevas soluciones de programación

*IMPORTANTE:* Todas las soluciones que usted envíe deben cumplir con 
las [button]#link:../retos-tecnicos/#envio[reglas de envío >>]#.,

. Participe en dos proyectos de entrenamiento sorpresa, 
con indicaciones variables que midan su capacidad 
de seguir instrucciones y desarrollar actividades bajo presión. 

. Se acepten en el repositorio 10 artículos publicables en el blog que cumplan la link:../../estilo/[línea editorial].

. Para la elaboración de artículos deberá tener en cuenta lo siguiente:

=== Artículos

La elaboración de artículos tiene como objetivo familiarizar a futuros talentos con contenido
relevante para la audiencia de FLUID. Por tal motivo estos deben adherirse
a la línea editorial definida link:../../estilo/[aquí].

Para la generación de documentos y artículos para el blog (carpeta
articles) el lenguaje que debe utilizarse es AsciiDoc.
Estos archivos deben finalizar siempre con la extensión .adoc
Un ejemplo más detallado de uso de AsciiDoc se encuentra
link:https://github.com/opendevise/asciidoc-samples/blob/master/demo.adoc[aquí].

Tenga especial atención con los requisitos de numero de palabras y de índice
de legibilidad LIX. Estos requisitos son verificados estrictamente por el
integrador continuo. Si quiere calcular usted mismo estas métricas puede
utilizar las herramientas wc y diction (comando style).

En función de la calidad de los artículos, FLUID puede decidir publicarlos
inmediata o posteriormente en nuestro blog y anunciar su publicación a los
clientes suscritos al mismo. 
Una medida de la calidad del contenido generado
por usted es el número de artículos que resultan publicados.

* *Artículos cón código*: Si en algún momento le es solicitado explícitamente
realizar la solución de un reto de programación como parte de un artículo de
blog (estilo programación literal), este debe hacerse también en AsciiDoc
(asc), presentar en la versión documento el código fuente sin comentarios, 
de forma secuencial, manteniendo la indentación original y utilizando el
resaltado de código (syntax highlighting) propio de GitLab y AsciiDoc:

.test.py
[source,python]
----
print('Hola mundo')
----

Este es un link:../../blog/que-ruta-mas-insegura/[ejemplo] de un
artículo que cumple totalmente con estas indicaciones.

Los artículos deben subirse al repositorio que le indicaremos al entrar en esta etapa.

Si tienes alguna duda no dudes en escribir a careers@autonomicmind.co