:slug: careers/faq/
:category: careers
:description: The main goal of the following page is to inform potential talents and people interested in working with us about our selection process. Here we present a Frequently Asked Questions (FAQ) section which intends to guide our candidates through the selection process.
:keywords: Fluid Attacks, Careers, Selection, Process, FAQ, Questions.

= Frequently Asked Questions (FAQ)

{description}

== Before Entering

[qanda]

*I already applied in a job portal, why I am not invited to the process?*::
  Once you apply to one of our vacancies
  on any of the job portals we are registered in,
  it takes from +1+ to +2+ days identifying potential candidates,
  classifying and sending invitations via email.
  If for any reason you have not been invited
  after +2+ days of your application (excluding weekends)
  and you consider that your profile fits
  the vacancy, you can write us to careers@autonomicmind.com.

*The test application doesn't allow me to exit Moodle, what can I do?*::
  If you already finished the exam,
  click the button located on the lower right side of the screen to exit.
  If this doesn't work,
  try restarting your machine,
  don't worry, you have already sent the test
  and there won't be any data loss.

*I don't have a RUT, how can I complete the third party form?*::
  In the link:http://www.dian.gov.co/contenidos/servicios/rut.html[+DIAN+ webpage]
  you can find out how to obtain your +RUT+ for the first time,
  or how to update it in case you already have one.

*I don't know what vacancy I applied for, how can I find out?*::
  You can write any doubt or observation
  regarding the selection process to careers@autonomicmind.com

*If I already applied for a vacancy, can I do it again for other profiles*::
*or the same profile?*::
  Yes, you can do it.
  If it has been more than six months
  since your last application
  you must do the process again from the beginning.
  Otherwise, you can write us to career@autonomicmind.com
  informing us you want to apply to a different profile.

*Can I apply for two different vacancies?*::
  Yes, you follow the selection process once
  and tell us the vacancies you want to apply
  writing an email to careers@autonomicmind.com

*What experience do I need to apply to the vacancies?*::
  You don't need any experience.
  What is essential is the ability to research,
  solve issues, and self-learning.

*What previous knowledge do I need to apply to the vacancies*::
  We look for talented people with high learning abilities.
  It doesn't matter your career or if you haven't graduated yet,
  what matters is to adapt to our philosophy and values.
  It is desirable to have experience with programming languages,
  but it is not mandatory.
  We value the ability to address a problem more than your professional degrees.
  Our selection process is designed to encourage the candidate
  to self-acquire the knowledge necessary
  to fulfill the charge.

*Does the company train me to fulfill my charge?*::
  In +Fluid Attacks+ we do not demand any laboral experience,
  nor certify your knowledge with degrees;
  however, we do not train our candidates at any moment.
  It is up to you to acquire the knowledge you may need
  and have the correct attitude to overcome
  the technical challenges and immersion stages.
  We value your abilities and attitude during the selection process
  since both are necessary for any role in the organization.

*The application test doesn't work, what can I do?*::
  Try executing the test as administrator.
  If the problem persists, you can try from a different computer.

*I didn't receive the attached file for data analysis, how do I get it?*::
  Try downloading the file from [button]#link:../non-technical-challenges/hallazgos-open-data.tar.bz2[here]#

*I ran out of time for the test, what can I do?*::
  If you have a valid reason
  (application lockouts, unexpected restarts, connection issues),
  you can write an email to careers@autonomicmind.com
  explaining to us what happened
  and we will indicate you how to proceed.

*I couldn't send my data analysis, what can I do?*::
  If you have a valid reason,
  write an email to careers@autonomicmind.com
  explaining why you did not send the data
  in the established deadline
  and asking for a new delivery date.

*What should I put on my portfolio?*::
  You can find the instructions and bits of advice
  for the portfolio creation [button]#link:../portfolio/[here]#

*I do not have a +VISA+, What should I put on that field?*::
  This field is not mandatory,
  do not fill if you don't have a +VISA+.

*What should I do after finishing the character test?*::
  When you finish this test,
  you can proceed with the next stage (knowledge test).
  We will send your result via email moments after.

*Do I have to present the polygraph test?*::
  In most cases, this test is not mandatory
  during the selection process.
  However, since our main business is the information security,
  it may be necessary to complete this test
  depending on your selection process.

*Do I have to present the Gallup test?*::
  This test only is required in some cases,
  therefore, please notify us via email
  when you reach this stage,
  and we will indicate you how to proceed.

*Does this process perform any risk analysis with my data?*::
  Yes, in the stage previous to the hiring,
  a confirmation is made on the risk central
  about the candidate data, among other references.

*I haven't notified my company about my current selection process,*::
*is the reverse references stage mandatory?*::
  Yes, it is mandatory and since it's an advanced stage
  in the selection process
  it is necessary for all the parties
  to have clear expectations.

*I'm very shy to present in public,*::
*is it mandatory to perform the audition?*::
  This stage is optional during the selection process.
  However, you must consider that in +Fluid Attacks+
  keeping good communication is essential,
  no matter the role to fulfill.

*Is it mandatory to complete all the stages of the process?*::
  Depending on the vacancy you applied for,
  and your selection process,
  we will indicate you how to proceed.

*What does offer validity time mean?*::
  It is the time during which +Fluid Attacks+ can hold up the offer.
  If during this time, we don't receive
  the explicit and written acceptance of the talent,
  the offer will become invalid.
  The purpose of this measure is to give other candidates
  in the selection process the possibility to be hired
  as soon as possible.

*If I do not accept the offer, what happens with my immersion process?*::
  The immersion ends immediately.
  +Fluid Attacks+ will remove the access to the training systems
  and will send you the time report of the hours
  pending to be charged in your billing statement.

== After Entering

+Fluid Attacks+ is a company focused and specialized in +Red Team+ testing.
We aim information security concepts towards an offensive approach,
looking for all the vulnerabilities and reporting them
as soon as possible.
Below we list some Frequently Asked Questions (+FAQ+)
presented when the talent is hired
and is part of our work team:

[qanda]

*What are the responsibilities of my role?*::
  +Fluid Attacks+ seeks to be agile and flexible,
  capable of adapting to changes at high speed.
  To accomplish this goal, we have decided to keep
  a work team below +50+ persons.
  In addition to that,
  we require generic roles and a lot of team work,
  which allows co-workers to complement each other's weaknesses.
  Because of this, each profile is grouped
  in any of these +2+ kind of roles: technical and non-technical.
  +
  * In technical roles, the responsibilities typically are:
  hacking systems, audit source code, develop attack exploits,
  develop tools for hackers, document found vulnerabilities,
  configure infrastructure as code, perform peer review,
  present reports to the customers,
  spread knowledge among customers and co-workers,
  migration of obsolete information and creation of new information,
  among others.
  +
  +
  * Non-technical roles comprise responsibilities of:
  customer management, technical pre-sales, marketing,
  +Fluid Attacks+ representation in other companies,
  speakers for conferences or seminars,
  crisis management, among others.
  +
  In short, the responsibilities defined for each role
  are unknown, and we expect you to contribute
  to any aspect of the previous kind of roles,
  depending on the needs of the company.
  We truly appreciate high technical talents that,
  after fulfilling technical roles,
  gradually migrate to non-technical roles.

*What kind of contract does Fluid Attacks offer?*::
  In +Fluid Attacks+ we offer just one type of contract:
  Labour contract for an indefinite period,
  with all the benefits required by law
  and parafiscal contributions
  (healthcare, retirement fund, allowances, layoffs)
  all paid on the +100%+ of the salary.
  All the talents have the same type of contract no matter their role,
  the only change is the salary amount.

*Does the salary offer correspond to the amount deposited into my account?*::
  No, the salary offer corresponds to the gross salary.
  The net salary will depend on personal variables
  that the employer cannot define
  (such as contribution to retirement funds, housing interests,
  number of dependents, among others ).
  However, in the following [button]#link:http://www.elempleo.com/co/calculadora-salarial/[link]#
  you can simulate an approximated value for your net salary.
  Enter the proposed salary in the first field (+Salario+).
  And then press +Calcular+.
  In the monthly net compensation field,
  you will find an approximated value of the the money
  that you will receive monthly in your payroll account.

*Why is there a difference between the gross salary and the net salary?*::
  There are law deductions that the government makes to the employees.
  These values are fixed and can be modified
  neither by the talent nor by +Fluid Attacks+.
  The only value to agree is the amount of the gross salary.

*Must the talent pay his/her own social security?*::
  No, the talent must not pay anything on his/her own.
  It is +Fluid Attacks+ who directly performs the deductions
  and makes the payment to the corresponding entities.
  (+EPS+, retirement funds, compensation funds, among others).
  +Fluid Attacks+ pays on the +100%+ of the salary
  all the benefits demanded by law,
  ensuring that the talent must not perform additional payments
  to the deductions previously indicated.
