:slug: rules/300/
:category: data
:description: This requirement establishes the importance of masking sensitive personal and business data to avoid information leakages.
:keywords: Requirement, Security, Data, Information, Business, Mask, GDPR, ISO, OWASP, PCI DSS, Rules, Ethical Hacking, Pentesting
:rules: yes

= R300. Mask sensitive data

== Requirement

Bussiness sensitive data
(passwords, credit card numbers, *CVV*, etc) must be masked.

== Description

Applications usually handle personal information such as credit card numbers,
*CVV*, personal identifications, social security numbers, etc.
The exposure of this data could severely affect their owners and so it must
be considered sensitive and specifically protected.
Masking is a mechanism that contributes to this protection.

== Findings

* [inner]#link:/findings/038/[F038. Business information leak]#

== References

. [[r1]] link:https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:02002L0058-20091219[Directive 2002/58/EC (amended by E-privacy Directive 2009/136/EC).
Art. 4: Security of processing.(1a)]
The measures referred to in paragraph 1 shall at least protect personal data
stored or transmitted against accidental or unlawful destruction,
accidental loss or alteration,
and unauthorized or unlawful storage, processing, access or disclosure.

. [[r2]] link:https://gdpr-info.eu/recitals/no-51/[GDPR. Recital 51: Protecting sensitive personal data]
Personal data which are, by their nature, particularly sensitive in relation
to fundamental rights and freedoms merit specific protection as the context of
their processing could create significant risks to the fundamental rights
and freedoms.

. [[r3]] link:https://www.iso.org/obp/ui/#iso:std:54534:en[ISO 27001:2013. Annex A - 18.1.3]
Protect records against loss, destruction, forgery, unauthorized access and
unauthorized release,
in accordance with legal, regulatory, contractual and business requirements.

. [[r4]] link:https://owasp.org/www-project-top-ten/OWASP_Top_Ten_2017/Top_10-2017_A3-Sensitive_Data_Exposure[OWASP Top 10 A3:2017-Sensitive Data Exposure].
Many web applications and **API**s do not properly protect sensitive data,
such as financial, healthcare, and *PII*.
Attackers may steal or modify such weakly protected data to conduct credit card
fraud, identity theft, or other crimes.
Sensitive data may be compromised without extra protection,
such as encryption at rest or in transit, and requires special precautions when
exchanged with the browser.

. [[r5]] link:https://www.pcisecuritystandards.org/documents/PCI_DSS_v3-2-1.pdf[PCI DSS v3.2.1 - Requirement 3.3]
Mask *PAN* (Primary Account Number) when displayed
(the first sixand last four digits are the maximum number of digits to be
displayed),
such that only personnel with a legitimate business need can see more than the
first six/last four digits of the *PAN*.
