:slug: systems/
:description: Here you can find the multiple information systems that we are capable of testing for your company to detect any cybersecurity vulnerability.
:keywords: Application, Web, Mobile, Thick Client, API, Microservice, Cloud, Network, IoT; OT, Pentesting, Ethical Hacking
:phrase: At Fluid Attacks, we have a broad collection of information systems to use as targets in security testing aimed at detecting vulnerabilities at risk of being exploited.
:template: indexof
:arrow: image:../theme/images/arrow-btn.svg[Young hacker smiling, width=15px, height=15px]

= Systems

== Web Applications
We can help you test your web applications' features, functions, and components
that may possess security vulnerabilities putting your company's and users'
information assets at risk. Our security testing goes beyond the OWASP top
ten web application security risks. +
[button]#link:web-apps/[Go to Web Applications {arrow}]#

== Mobile Applications
We keep up to date with attack vectors on mobile applications and provide you
with security testing to identify vulnerabilities in this kind of system.
We work with iOS, Android, and Windows UI and go beyond the OWASP top 10
mobile vulnerabilities and other popular lists. +
[button]#link:mobile-apps/[Go to Mobile Applications {arrow}]#

== Thick Clients
We recognize the value of assessing not only thin clients but also
thick client applications, which mainly operate on the client-side with or without
connection to a network. Testing configurations and interactions,
we look for vulnerabilities that affect both client and server-side. +
[button]#link:thick-clients/[Go to Thick Clients {arrow}]#

== APIs and Microservices
We are aware of the essential functions of APIs and microservices in the applications
and how both can be vulnerable to cyberattacks. We evaluate
microservices' interactions and operations and the exposition of APIs
for discovering vulnerabilities that criminals could exploit. +
[button]#link:apis/[Go to APIs and Microservices {arrow}]#

== Cloud Infrastructure
We can help you test the cloud infrastructure your company has acquired
for monetary and optimization benefits. We work on Azure, AWS, GCP, or any other
cloud to identify configuration, application, or network weaknesses
representing potential attack vectors. +
[button]#link:cloud-infrastructure/[Go to Cloud Infrastructure {arrow}]#

== Networks and Hosts
We are able to perform assessments of hosts, devices, and services
of your company's internal and external networks. We can help you detect
misconfigurations and outdated components, among other flaws, going from
general structure analysis to specific elements inspection. +
[button]#link:networks-and-hosts/[Go to Networks and Hosts {arrow}]#

== Internet of Things
We understand that IoT devices are often implemented in some companies'
infrastructures without the appropriate security measures. We provide
you with security testing for each connected element and every new
incorporation to find vulnerabilities that may affect other devices or servers. +
[button]#link:iot/[Go to Internet of Things {arrow}]#

== SCADA and OT
We also work on Operational Technology that serves for the monitoring of industrial
elements and processes. We implement security assessments in the
industrial control system SCADA, considering the cybersecurity risks
your company may face when OT networks are connected to the Internet. +
[button]#link:ot/[Go to SCADA and OT {arrow}]#
