:slug: kb/aspnet/establecer-content-type-charset/
:eth: no
:category: aspnet
:description: TODO
:keywords: TODO
:kb: yes

= Establecer Content-Type y Charset

== Necesidad

Establecer Content-Type y Charset en ASP.Net

== Contexto

A continuación se describe las circunstancias 
bajo las cuales la siguiente solución tiene sentido:

. Se está desarrollando en ASP.Net

== Solución

. Las aplicaciones son rara vez probadas 
contra los exploits que usan Unicode,
sin embargo, muchas son vulnerables 
al mismo tipo de problemas 
que permite a un atacante realizar 
un _HTTP Request Smuggling_.
 
. El _HTTP Request Smuggling_ 
le permite a un atacante 
evadir los controles de un sistema, 
usando codificaciones diferentes, 
para que dos sistemas (usualmente, un WAF y el servidor WEB) 
perciban peticiones HTTP diferentes. 
+
La forma normal (_canonical form_) es la representación más simple 
o más estándar de algo. 
El proceso de normalizar las solicitudes 
se encarga de abordar el modo 
en que los sistemas transforman los datos de una forma a otra. 
En sí, normalizar es convertir algo 
desde su estado original 
a una representación más simple. 
+
Las aplicaciones Web deben tratar 
con muchos procesos de normalización 
desde la codificación del URL,  
hasta la traducción de las IP. 
Cuando se toman decisiones de seguridad 
basándose en datos normalizados menos que perfectos, 
la aplicación debe ser capaz de manejar 
entradas inesperadas de manera segura. 
+
Para evitar los ataques 
que se aprovechan de la normalización, 
se debe seleccionar una forma normal
y modificar todas las entradas de usuario dicha forma 
antes de tomar decisiones de autorización.

. De la misma manera, 
se deben ejecutar pruebas de seguridad 
después de que se ha realizado la decodificación, 
por lo cual se recomienda verificar 
que la codificación usada esté soportada 
para cada símbolo que se presenta. 

. Para definir una forma normal, 
en HTTP se define el Content-Type. 
En C# tenemos la propiedad _HttpResponse.ContentType_, 
que permite establecer u obtener 
el tipo _MIME_ del flujo de salida , 
el cual se encuentra alojado 
en el espacio de nombres _System.Web_ 
en el ensamblado _System.Web_ de _System.Web.dll_. 
A continuación se presenta un ejemplo de uso del _ContentType_:
+

[source, java, linenums]
----
// Establece el contet type.
Response.ContentType = "image/jpeg";
----

. De modo similar al _ContentType_, 
es necesario definir el _Character-Set_ usado. 
En C# se cuenta con _HttpResponse.Charset_ 
que permite establecer u obtener 
el tipo _MIME_ del flujo de salida. 
El código mostrado a continuación, 
ejemplifica el uso del _Charset_:
+

[source,java,linenums]
----
if (Response.Charset == "utf-8") 
 {
   // ...
 }
----

== Referencias

. https://msdn.microsoft.com/en-us/library/system.web.httpresponse.contenttype.aspx[Microsoft, HttpResponse.ContentType]

. REQ.0039: Los archivos generados de forma dinámica por el sistema deben tener definido un Content-Type explícito.

. REQ.0040: Los archivos generados de forma dinámica por el sistema deben tener definido un Character-Set explícito.