:slug: kb/aspnet/cifrar-contrasenas-con-salt/
:eth: no
:category: aspnet
:kb: yes

= Cifrar Contraseñas con Salt

== Necesidad

Cifrado de contraseñas con salt en ASP.Net.

== Contexto

A continuación se describen las circunstancias 
bajo las cuales la siguiente solución tiene sentido:

. Se desarrolla una aplicación en ASP.Net.
. Se requiere el uso de funciones de resumen (hash) 
para cifrado de contraseñas.
. Se requiere implementar salt al momento de cifrar las contraseñas.

== Solución

. El proveedor de pertenencia de SQL Server 
admite los formatos de contraseña _Clear_, _Encrypted_ y _Hashed_. 
Las contraseñas _Clear_ se guardan en texto sin formato, 
lo cual mejora el rendimiento de almacenamiento 
y recuperación de contraseñas 
pero es menos seguro, 
ya que las contraseñas se leen con facilidad 
si la base de datos de SQL Server se ve comprometida. 
Las contraseñas _Encrypted_ se cifran cuando se almacenan 
y se pueden descifrar 
para su comparación o recuperación. 
Esto requiere un procesamiento adicional 
para el almacenamiento y la recuperación de contraseñas, 
pero es más seguro 
ya que las contraseñas 
no pueden determinarse con facilidad 
si se ve comprometida la base de datos SQL Server. 
Las contraseñas _Hashed_ se fragmentan 
utilizando un algoritmo _hash_ unidireccional 
y un valor _salt_ que se genera aleatoriamente 
cuando se almacenan en la base de datos. 
Cuando se valida una contraseña, 
se fragmenta con el valor salt 
en la base de datos para su comprobación. 
Las contraseñas fragmentadas no se pueden recuperar.

. El valor de PasswordFormat se especifica 
en la sección providers del archivo _Web.config_ 
de la aplicación ASP.NET.

. De manera predeterminada, las contraseñas _Encrypted_ se cifran 
y a las contraseñas _Hashed_ se les aplica un algoritmo _hash_ 
según la información proporcionada 
en el elemento _machineKey_ de la configuración. 
Tenga en cuenta que si se especifica un valor de 3DES 
para el atributo _validation_ 
o si no se especifica ningún valor, 
se aplicará el algoritmo hash _SHA1_ 
a las contraseñas correspondientes.

. Se puede definir un algoritmo _hash_ personalizado 
mediante el atributo _hashAlgorithmType_ 
del elemento de configuración _membership_ , 
presente en el esquema de configuración de ASP.NET. 
Si elige el cifrado, el cifrado de contraseña predeterminado utiliza AES. 
Puede cambiar el algoritmo de cifrado 
estableciendo el atributo _decryption_ 
del elemento de configuración _machineKey_. 
Si cifra las contraseñas, debe proporcionar un valor explícito 
para el atributo _decryptionKey_ 
en el elemento _machineKey_. 
No se admite el valor predeterminado de _AutoGenerate_ 
para el atributo _decryptionKey_ 
al utilizar las contraseñas cifradas con Pertenencia de ASP.NET. 

. En el siguiente ejemplo, 
se muestra el elemento _membership_ 
en la sección _system.web_ 
del archivo _Web.config_ de una aplicación ASP.NET. 
A continuación, se especifica la instancia _SqlMembershipProvider_ 
de la aplicación y se establece el formato de contraseña en _Hashed_.

[source, xml, linenums]
<membership defaultProvider="SqlProvider" userIsOnlineTimeWindow="20">
  <providers>
    <add name="SqlProvider"
      type="System.Web.Security.SqlMembershipProvider"
      connectionStringName="SqlServices"
      enablePasswordRetrieval="false"
      enablePasswordReset="true"
      requiresQuestionAndAnswer="true"
      passwordFormat="Hashed"
      applicationName="MyApplication" />
  </providers>
</membership>

== Referencias

. https://msdn.microsoft.com/en-us/library/system.security.cryptography.hashalgorithm.aspx[HashAlgorithm Class]
. https://msdn.microsoft.com/es-es/library/system.security.cryptography.randomnumbergenerator.aspx[RandomNumberGenerator Class]
. REQ.0132: El sistema debe almacenar las contraseñas con diferentes derivaciones de clave (Salt).
. REQ.0133: Las derivaciones de clave (Salt), deben ser aleatorias y de mínimo 48 bits.
. REQ.0142: Las funciones de criptografía del sistema deben ser implementadas con mecanismos criptográficos pre-existentes.
. REQ.0145: Debe utilizarse funciones resumen con un tamaño mínimo de 256 bits.
. https://stackoverflow.com/questions/949271/storing-hashed-passwords-base64-or-hex-string-or-something-else[Storing Hashed Passwords]
. https://msdn.microsoft.com/es-es/library/system.web.security.sqlmembershipprovider.passwordformat(v=vs.110).aspx[Password Format]
